using System;
using System.Collections.Generic;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using Godot;
using WorldV2;

namespace GameplayV3.Work;

public readonly struct WorkResourceSelfCheckResultV3{public WorkResourceSelfCheckResultV3(bool passed,string summary){Passed=passed;Summary=summary;}public bool Passed{get;}public string Summary{get;}}
public static class WorkResourceSelfCheckV3
{
    public static WorkResourceSelfCheckResultV3 Run()
    {List<string> failures=new();Rect2I bounds=new(0,0,32,32);string id=ResourceNodeIdFactoryV3.Create();Require(ResourceNodeIdFactoryV3.IsValid(id),"resource id",failures);Require(!ResourceNodeIdFactoryV3.IsValid("node_"+Guid.NewGuid().ToString("N")),"resource prefix",failures);ResourceNodeStateV3.TryCreate(id,ResourceNodeTypeV3.Tree,new(new Vector2I(4,4)),7,7,5,bounds,DateTime.UtcNow,out ResourceNodeStateV3? node,out string reason);Require(node!=null,reason,failures);Require(node!.TryHarvest(out int first,out _)&&first==5&&node.RemainingAmount==2,"first harvest",failures);Require(node.TryHarvest(out int last,out _)&&last==2&&node.IsDepleted,"last harvest",failures);Require(!node.TryHarvest(out _,out _),"depleted harvest",failures);ResourceNodeRegistryV3 nodes=new();ResourceNodeStateV3.TryCreate(ResourceNodeIdFactoryV3.Create(),ResourceNodeTypeV3.Tree,new(new Vector2I(5,5)),15,15,5,bounds,DateTime.UtcNow,out ResourceNodeStateV3? a,out _);ResourceNodeStateV3.TryCreate(ResourceNodeIdFactoryV3.Create(),ResourceNodeTypeV3.StoneOutcrop,new(new Vector2I(5,5)),20,20,5,bounds,DateTime.UtcNow,out ResourceNodeStateV3? b,out _);Require(nodes.TryRegister(a,out _),"node register",failures);Require(!nodes.TryRegister(b,out _),"duplicate cell",failures);GroundResourceStackRegistryV3 stacks=new();Require(stacks.TryAddStack(ResourceTypeV3.Wood,5,new(new Vector2I(1,1)),out GroundResourceStackV3? wood,out bool mergedA,out _)&&!mergedA,"stack create",failures);Require(stacks.TryAddStack(ResourceTypeV3.Wood,5,new(new Vector2I(1,1)),out GroundResourceStackV3? merged,out bool mergedB,out _)&&mergedB&&merged!.Amount==10&&merged.ResourceStackId==wood!.ResourceStackId,"stack merge",failures);Require(stacks.TryAddStack(ResourceTypeV3.Stone,5,new(new Vector2I(1,1)),out _,out bool mixed,out _)&&!mixed&&stacks.Count==2,"different stack type",failures);ResourceReservationRegistryV3 reservations=new();ResourceReservationV3 reservation=new("node","work","merc","company",1,DateTime.UtcNow);Require(reservations.TryReserve(reservation,out _),"reserve",failures);Require(reservations.TryReserve(reservation,out _),"idempotent reserve",failures);Require(!reservations.TryReserve(new("node","other","otherMerc","company",2,DateTime.UtcNow),out _),"duplicate reserve",failures);Require(reservations.ReleaseByMercenary("merc")==1&&reservations.Count==0,"release reservation",failures);TestQuery query=new(bounds);IReadOnlyList<GlobalCellCoord> candidates=GatheringApproachCellServiceV3.GetCandidates(new(new Vector2I(0,4)),new(new Vector2I(4,4)),query);Require(candidates.Count==8,"approach count",failures);Require(candidates[0].Value==new Vector2I(3,4),"cardinal approach priority",failures);return new(failures.Count==0,failures.Count==0?"PASS":"FAIL: "+string.Join(" | ",failures));}
    private static void Require(bool value,string reason,List<string> failures){if(!value)failures.Add(reason);}
    private sealed class TestQuery:IMercenaryNavigationWorldQueryV3{private readonly Rect2I _bounds;public TestQuery(Rect2I bounds){_bounds=bounds;}public bool IsInsideWorld(Vector2I cell)=>_bounds.HasPoint(cell);public MercenaryNavigationCellInfoV3 GetCellInfo(Vector2I cell)=>new(IsInsideWorld(cell),IsInsideWorld(cell),1,TileType.Grass,BiomeKindV3.Plains);public bool IsWalkable(Vector2I cell)=>IsInsideWorld(cell);public float GetTraversalMultiplier(Vector2I cell)=>1;}
}
