using System;
using System.Collections.Generic;
using GameplayV3.Mercenary;
using GameplayV3.Resources;
using GameplayV3.Work;
using Godot;
using WorldV2;

namespace GameplayV3.Stockpile;

public readonly struct StockpileHaulingSelfCheckResultV3{public StockpileHaulingSelfCheckResultV3(bool passed,string summary){Passed=passed;Summary=summary;}public bool Passed{get;}public string Summary{get;}}
public static class StockpileHaulingSelfCheckV3
{
    public static StockpileHaulingSelfCheckResultV3 Run()
    {
        List<string> failures=new();Rect2I bounds=new(0,0,32,32);StockpileSessionV3 session=new();GlobalCellCoord a=new(new Vector2I(4,4)),b=new(new Vector2I(5,4));Require(StockpileZoneIdFactoryV3.IsValid(StockpileZoneIdFactoryV3.Create()),"zone id",failures);Require(session.Zones.TryCreateZone("company",new[]{a,b},bounds,out StockpileZoneStateV3? zone,out _)&&zone?.CellCount==2,"zone create",failures);Require(!session.Zones.TryCreateZone("other",new[]{a},bounds,out _,out _),"zone overlap",failures);Require(session.Zones.TryGetZoneAtCell(a,out StockpileZoneStateV3? at)&&at?.StockpileZoneId==zone?.StockpileZoneId,"cell index",failures);
        StockpileCellReservationV3 destination=new(zone!.StockpileZoneId,a,"work","merc",ResourceTypeV3.Wood,1,DateTime.UtcNow);Require(session.CellReservations.TryReserve(destination,out _),"destination reserve",failures);Require(!session.CellReservations.TryReserve(new(zone.StockpileZoneId,a,"other","other",ResourceTypeV3.Wood,2,DateTime.UtcNow),out _),"destination duplicate",failures);Require(!session.Zones.TryRemoveCells(zone.StockpileZoneId,"company",new[]{a},out _,out _),"reserved cell removal",failures);session.CellReservations.ReleaseByWorkRequest("work");Require(session.Zones.TryRemoveCells(zone.StockpileZoneId,"company",new[]{a},out _,out _)&&zone.CellCount==1,"cell remove",failures);Require(session.Zones.TryRemoveCells(zone.StockpileZoneId,"company",new[]{b},out bool removed,out _)&&removed&&session.Zones.Count==0,"empty zone removal",failures);
        ResourceSessionV3 reservationResources=new();reservationResources.GroundStacks.TryAddStack(ResourceTypeV3.Wood,20,new(new Vector2I(2,2)),out GroundResourceStackV3? reservedStack,out _,out _);GroundStackReservationRegistryV3 sources=new(reservationResources.AmountReservations,reservationResources.GroundStacks);GroundStackReservationV3 sourceReservation=new(reservedStack!.ResourceStackId,"work","merc","company",20,1,DateTime.UtcNow);Require(sources.TryReserve(sourceReservation,out _)&&sources.TryReserve(sourceReservation,out _),"source idempotent",failures);Require(!sources.TryReserve(new(reservedStack.ResourceStackId,"other","merc2","company",20,2,DateTime.UtcNow),out _),"source duplicate",failures);Require(sources.ReleaseByMercenary("merc")==1,"source release",failures);
        MercenaryAttributeSetV3.TryCreate(15,7,13,7,12,out MercenaryAttributeSetV3? attributes,out _);MercenaryWorkSkillSetV3.TryCreate(12,6,11,5,6,3,9,out MercenaryWorkSkillSetV3? skills,out _);MercenaryProfileV3.TryCreate(MercenaryIdFactoryV3.CreateMercenaryId(),"Recruit C","placeholder_c",attributes,skills,DateTime.UtcNow,out MercenaryProfileV3? profile,out _);HaulingWorkCalculationV3 calculation=HaulingWorkCalculatorV3.Calculate(profile!);Require(calculation.MaxCarryUnits==16,"capacity floor",failures);Require(Math.Abs(calculation.HaulingScore-12.5f)<0.001f,"hauling score",failures);
        GroundResourceStackRegistryV3 stacks=new();MercenaryCarryRegistryV3 carries=new();GlobalCellCoord sourceCell=new(new Vector2I(1,1)),destinationCell=new(new Vector2I(4,4));stacks.TryAddStack(ResourceTypeV3.Wood,15,sourceCell,out GroundResourceStackV3? wood,out _,out _);Require(stacks.TryTakeAmount(wood!.ResourceStackId,16,out int woodTaken,out _,out bool woodRemoved,out _)&&woodTaken==15&&woodRemoved,"wood take",failures);Require(carries.TryBeginCarry("merc","woodWork",ResourceTypeV3.Wood,woodTaken,wood.ResourceStackId,1,16,out _,out _),"wood carry",failures);Require(carries.TryDropCarryAtCell("merc","woodWork",destinationCell,stacks,out GroundResourceStackV3? storedWood,out _)&&storedWood?.Amount==15&&carries.Count==0,"wood one trip",failures);Require(stacks.GetTotalAmount(ResourceTypeV3.Wood)==15,"wood conservation",failures);
        stacks.TryAddStack(ResourceTypeV3.Stone,20,sourceCell,out GroundResourceStackV3? stone,out _,out _);int initialStone=stacks.GetTotalAmount(ResourceTypeV3.Stone);Require(stacks.TryTakeAmount(stone!.ResourceStackId,16,out int first,out _,out _,out _)&&first==16,"stone first take",failures);carries.TryBeginCarry("merc","stoneWork",ResourceTypeV3.Stone,first,stone.ResourceStackId,2,16,out _,out _);carries.TryDropCarryAtCell("merc","stoneWork",destinationCell,stacks,out _,out _);Require(stacks.TryTakeAmount(stone.ResourceStackId,16,out int second,out _,out _,out _)&&second==4,"stone second take",failures);carries.TryBeginCarry("merc","stoneWork",ResourceTypeV3.Stone,second,stone.ResourceStackId,2,16,out _,out _);carries.TryDropCarryAtCell("merc","stoneWork",destinationCell,stacks,out GroundResourceStackV3? storedStone,out _);Require(storedStone?.Amount==20&&stacks.GetTotalAmount(ResourceTypeV3.Stone)==initialStone,"stone two trips conservation",failures);
        stacks.TryAddStack(ResourceTypeV3.Potato,3,sourceCell,out GroundResourceStackV3? potato,out _,out _);Require(stacks.TryTakeAmount(potato!.ResourceStackId,16,out int potatoTaken,out _,out bool potatoRemoved,out _)&&potatoTaken==3&&potatoRemoved,"potato take",failures);Require(carries.TryBeginCarry("merc","potatoWork",ResourceTypeV3.Potato,potatoTaken,potato.ResourceStackId,3,16,out _,out _),"potato carry",failures);Require(carries.TryDropCarryAtCell("merc","potatoWork",destinationCell,stacks,out GroundResourceStackV3? storedPotato,out _)&&storedPotato?.Amount==3&&stacks.GetTotalAmount(ResourceTypeV3.Potato)==3,"potato hauling conservation",failures);
        stacks.TryAddStack(ResourceTypeV3.Wood,20,sourceCell,out GroundResourceStackV3? snapshot,out _,out _);Require(stacks.TryTakeAmount(snapshot!.ResourceStackId,15,out int snapshotTaken,out GroundResourceStackV3? remainder,out _,out _)&&snapshotTaken==15&&remainder?.Amount==5,"amount snapshot leaves additions",failures);
        stacks.TryAddStack(ResourceTypeV3.Stone,8,sourceCell,out GroundResourceStackV3? emergency,out _,out _);stacks.TryTakeAmount(emergency!.ResourceStackId,8,out int emergencyTaken,out _,out _,out _);carries.TryBeginCarry("merc","cancel",ResourceTypeV3.Stone,emergencyTaken,emergency.ResourceStackId,3,16,out _,out _);int beforeEmergency=stacks.GetTotalAmount(ResourceTypeV3.Stone)+carries.GetTotalAmount(ResourceTypeV3.Stone);Require(carries.TryDropCarryAtCell("merc","cancel",new(new Vector2I(2,2)),stacks,out _,out _)&&beforeEmergency==stacks.GetTotalAmount(ResourceTypeV3.Stone),"emergency conservation",failures);
        session.Clear();Require(session.Zones.Count==0&&session.CellReservations.Count==0,"session clear",failures);return new(failures.Count==0,failures.Count==0?"PASS":"FAIL: "+string.Join(" | ",failures));
    }
    private static void Require(bool value,string reason,List<string> failures){if(!value)failures.Add(reason);}
}
