using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Godot;
using GameplayV3.Bases;
using GameplayV3.Company;
using GameplayV3.Mercenary;
using GameplayV3.Needs;
using WorldV2;

namespace GameplayV3.Jobs;

public static class JobActivityRangeSelfCheckV3
{
    public static string LastValidationSummary{get;private set;}="not run";public static string LastPerformanceSummary{get;private set;}="not run";public static string LastScaleSummary{get;private set;}="not run";
    public static bool TryValidate(out string reason)
    {
        try
        {
            using Fixture f=new(301,2);string a=f.Companies[0],b=f.Companies[1];MercenaryStateV3 worker=f.AddMercenary(a,new(0,0));f.Affiliations.ProcessUntilIdle();JobManagerV3 manager=new(301);
            JobRecordV3 noBase=AddJob(manager,a,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,"initial",new(5,0));Require(f.Policy.Evaluate(noBase,worker.MercenaryId).Reason==JobActivityRangeReasonV3.NoCompanyBaseFallback,"A: pre-base fallback failed.");
            Add(f.Bases,"bed_a",a,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new(0,0));Add(f.Bases,"wall_a",a,BaseSpatialSourceKindV3.Wall,BaseSpatialSourceRoleV3.Connector,new(2,0));Add(f.Bases,"stock_a",a,BaseSpatialSourceKindV3.StockpileZone,BaseSpatialSourceRoleV3.Attachment,new(3,0));Add(f.Bases,"bed_b",a,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new(140,0));Add(f.Bases,"wall_b",a,BaseSpatialSourceKindV3.Wall,BaseSpatialSourceRoleV3.Connector,new(142,0));Add(f.Bases,"stock_b",a,BaseSpatialSourceKindV3.StockpileZone,BaseSpatialSourceRoleV3.Attachment,new(143,0));f.Rebuild(a);f.Affiliations.RequestReevaluation(worker.MercenaryId,"PolicySetup");f.Affiliations.ProcessUntilIdle();if(!f.Affiliations.TryGetMercenaryBase(worker.MercenaryId,out var affiliation)||affiliation?.BaseAreaId==null)throw new InvalidOperationException("Policy setup affiliation failed.");string baseA=affiliation.BaseAreaId;
            JobRecordV3 same=AddJob(manager,a,JobTypeV3.Demolition,JobSourceKindV3.Structure,"wall_a",new(2,0));JobRecordV3 other=AddJob(manager,a,JobTypeV3.Demolition,JobSourceKindV3.Structure,"wall_b",new(142,0));Require(f.Policy.Evaluate(same,worker.MercenaryId).Reason==JobActivityRangeReasonV3.SameBaseFacility,"B: same-base facility was not allowed.");Require(!f.Policy.Evaluate(other,worker.MercenaryId).Allowed&&f.Policy.Diagnostics.LastReason==JobActivityRangeReasonV3.OtherBaseFacility,"C: other-base facility was not rejected.");
            JobRecordV3 fieldIn=AddJob(manager,a,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,"field_in",new(40,0));JobRecordV3 fieldOut=AddJob(manager,a,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,"field_out",new(70,0));Require(f.Policy.Evaluate(fieldIn,worker.MercenaryId).Reason==JobActivityRangeReasonV3.InsideActivityRange,"D: in-range field job failed.");Require(f.Policy.Evaluate(fieldOut,worker.MercenaryId).Reason==JobActivityRangeReasonV3.OutsideActivityRange,"D: out-of-range field job was allowed.");string beforeDirect=baseA;Require(f.Policy.Evaluate(a,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,"field_out",new(new Vector2I(70,0)),worker.MercenaryId,JobCommandSourceV3.DirectOrder).Reason==JobActivityRangeReasonV3.DirectOrderOverride&&f.Affiliations.IsMercenaryAssignedToBase(worker.MercenaryId,beforeDirect),"E: direct override changed affiliation or was rejected.");
            JobRecordV3 haulIn=AddJob(manager,a,JobTypeV3.Hauling,JobSourceKindV3.GroundResourceStack,"stack_in",new(40,0));JobRecordV3 haulCross=AddJob(manager,a,JobTypeV3.Hauling,JobSourceKindV3.GroundResourceStack,"stack_b",new(140,0));Require(f.Policy.Evaluate(haulIn,worker.MercenaryId).Allowed,"F: own-base/range hauling failed.");Require(f.Policy.Evaluate(haulCross,worker.MercenaryId).Reason==JobActivityRangeReasonV3.CrossBaseHauling,"F: cross-base hauling was allowed.");Require(f.Policy.Evaluate(a,JobTypeV3.Hauling,JobSourceKindV3.GroundResourceStack,"stack_b",new(new Vector2I(140,0)),worker.MercenaryId,JobCommandSourceV3.DirectOrder).Allowed,"F: direct hauling override failed.");Require(f.Policy.Evaluate(a,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,"need",new(new Vector2I(500,0)),worker.MercenaryId,JobCommandSourceV3.NeedAutomatic).Reason==JobActivityRangeReasonV3.NeedsOverride,"G: Needs override failed.");
            manager.QueueIdleMercenary(worker.MercenaryId);int dispatch=0;manager.TickAssignments(0,_=>worker.CurrentCell.Value,_=>a,_=>true,(job,id)=>f.Policy.Evaluate(job,id).Allowed,(_,_)=>1,(job,id)=>{dispatch++;return JobDispatchResultV3.Success("work_policy");});Require(dispatch==1,"Automatic policy did not retain an eligible job.");string assignedId=manager.TryGetAssignedJob(worker.MercenaryId,out var running)&&running!=null?running.JobId:string.Empty;
            string[] bridge=Enumerable.Range(1,17).Select(i=>$"bridge_{i}").ToArray();for(int i=0;i<bridge.Length;i++)Add(f.Bases,bridge[i],a,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new((i+1)*8,0));f.Rebuild(a);foreach(string id in bridge)f.Bases.RemoveSource(id);f.Rebuild(a);Require(manager.TryGetAssignedJob(worker.MercenaryId,out var afterSplit)&&afterSplit?.JobId==assignedId,"H/I: merge/split cancelled a running job instead of waiting for a safe boundary.");
            f.Bases.RemoveSource("bed_a");f.Bases.RemoveSource("bed_b");f.Rebuild(a);Require(f.Affiliations.TryGetMercenaryBase(worker.MercenaryId,out var removed)&&removed?.State==MercenaryBaseAffiliationStateV3.Unassigned&&f.Policy.Evaluate(fieldOut,worker.MercenaryId).Allowed,"J: base removal did not restore Unassigned fallback.");
            Add(f.Bases,"conflict_a",a,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new(300,0));Add(f.Bases,"conflict_b",b,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new(300,0));f.Bases.RebuildCompanyNow(a);f.Bases.RebuildCompanyNow(b);f.Bases.UpdateRoomSnapshot(new[]{new GameplayV3.Rooms.RoomTopologyStateV3("room_conflict",1,new[]{new GlobalCellCoord(300,0)},Array.Empty<string>(),Array.Empty<string>(),1,GameplayV3.Rooms.RoomRebuildReasonV3.InitialScan)});f.Bases.RebuildCompanyNow(a);f.Bases.RebuildCompanyNow(b);f.Facilities.ProcessUntilIdle();worker.TrySetCurrentCell(new(new Vector2I(300,0)),out _);f.Affiliations.RequestReevaluation(worker.MercenaryId,"AmbiguousFixture");f.Affiliations.ProcessUntilIdle();JobRecordV3 ambiguous=AddJob(manager,a,JobTypeV3.Demolition,JobSourceKindV3.Structure,"room_conflict",new(300,0));Require(f.Policy.Evaluate(ambiguous,worker.MercenaryId).Reason==JobActivityRangeReasonV3.FacilityAffiliationAmbiguous,"K: ambiguous facility policy failed.");JobRecordV3 otherCompany=AddJob(manager,b,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,"other_company",new(300,0));Require(f.Policy.Evaluate(otherCompany,worker.MercenaryId).Reason is JobActivityRangeReasonV3.UnassignedFallback or JobActivityRangeReasonV3.NoCompanyBaseFallback,"L setup failed; JobManager company gate remains authoritative.");
            Require(f.Policy.Diagnostics.MercenaryJobCartesianScanCount==0&&f.Policy.Diagnostics.MercenaryBaseCartesianScanCount==0&&f.Policy.Diagnostics.FullJobAffiliationRebuildCount==0,"Forbidden activity-range scans were used.");var d=f.Policy.Diagnostics;LastValidationSummary=$"allow same/range/fallback/direct/needs={d.AllowedSameBaseCount}/{d.AllowedRangeCount}/{d.FallbackCount}/{d.DirectOverrideCount}/{d.NeedsOverrideCount} reject other/outside/cross/pending/ambiguous={d.RejectedOtherBaseCount}/{d.RejectedOutsideRangeCount}/{d.RejectedCrossBaseHaulingCount}/{d.RejectedPendingCount}/{d.RejectedAmbiguousCount} runningPreserved={(assignedId.Length>0)}";reason=string.Empty;return true;
        }
        catch(Exception exception){reason=exception.Message;return false;}
    }

    public static string RunPerformanceFixture()
    {
        Stopwatch watch=Stopwatch.StartNew();using Fixture f=new(401,4);const int baseCount=200,mercenaryCount=1000,jobCount=100000;List<(string Company,Vector2I Cell)> anchors=new();for(int i=0;i<baseCount;i++){int companyIndex=i%4,j=i/4;string company=f.Companies[companyIndex];Vector2I cell=new((j/2)*256+(j%2)*80,companyIndex*4096);Add(f.Bases,$"perf_bed_{i}",company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,cell);anchors.Add((company,cell));}foreach(string company in f.Companies)f.Bases.RebuildCompanyNow(company);f.Facilities.ProcessUntilIdle();List<MercenaryStateV3> workers=new();for(int i=0;i<mercenaryCount;i++){var anchor=anchors[i%baseCount];workers.Add(f.AddMercenary(anchor.Company,anchor.Cell));}f.Affiliations.ProcessUntilIdle();for(int cycle=0;cycle<20;cycle++){int companyIndex=cycle%4,pair=cycle/4,leftIndex=companyIndex+pair*8;var left=anchors[leftIndex];string[] bridges=Enumerable.Range(1,9).Select(n=>$"perf_bridge_{cycle}_{n}").ToArray();for(int n=0;n<bridges.Length;n++)Add(f.Bases,bridges[n],left.Company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,left.Cell+new Vector2I((n+1)*8,0));f.Rebuild(left.Company);foreach(string id in bridges)f.Bases.RemoveSource(id);f.Rebuild(left.Company);}JobManagerV3 jobs=new(401);for(int i=0;i<jobCount;i++){var anchor=anchors[i%baseCount];jobs.TryUpsertSource(new(anchor.Company,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,$"perf_job_{i}"),anchor.Cell+new Vector2I(i%17-8,(i/17)%17-8),1,out _,out _,out _);}foreach(var worker in workers)jobs.QueueIdleMercenary(worker.MercenaryId);int ticks=0;while(jobs.ActiveAssignmentCount<mercenaryCount&&ticks++<1000)jobs.TickAssignments(ticks,id=>f.Mercenaries.Registry.TryGetState(id,out var state)&&state!=null?state.CurrentCell.Value:null,id=>f.Mercenaries.Registry.TryGetState(id,out var state)&&state!=null?state.CompanyId:string.Empty,_=>true,(job,id)=>f.Policy.Evaluate(job,id).Allowed,(_,_)=>1,(job,id)=>JobDispatchResultV3.Success($"perf_work_{id}"));Require(jobs.ActiveAssignmentCount==mercenaryCount,"Performance fixture did not assign all workers.");long limit=(long)mercenaryCount*Enum.GetValues<JobTypeV3>().Length*jobs.Settings.CandidateLimitPerType;Require(jobs.Diagnostics.CandidateEvaluations<=limit&&jobs.Diagnostics.CartesianScanCount==0&&f.Policy.Diagnostics.MercenaryJobCartesianScanCount==0&&f.Policy.Diagnostics.MercenaryBaseCartesianScanCount==0,"Performance candidate bounds failed.");watch.Stop();LastPerformanceSummary=$"companies=4 bases={baseCount} mercenaries={mercenaryCount} jobs={jobCount} overlapPairs=100 churn=20 candidates={jobs.Diagnostics.CandidateEvaluations}/{limit} policyEval={f.Policy.Diagnostics.EvaluatedCount} assignments={jobs.Diagnostics.AssignmentsSucceeded} ticks={ticks} elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms";return LastPerformanceSummary;
    }

    public static string RunScaleFixtures()
    {
        List<string> summaries=new();Stopwatch total=Stopwatch.StartNew();
        using(Fixture a=new(501,4))
        {
            Stopwatch watch=Stopwatch.StartNew();const int bases=1000,facilities=20000,mercenaries=10000,jobs=100000;List<(string Company,Vector2I Cell)> anchors=new(bases);
            for(int i=0;i<bases;i++){string company=a.Companies[i%4];Vector2I cell=new((i/4%50)*160,(i/200)*160+(i%4)*8192);Add(a.Bases,$"scale_a_bed_{i}",company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,cell);anchors.Add((company,cell));}
            for(int i=bases;i<facilities;i++){var owner=anchors[(i-bases)%bases];Vector2I cell=owner.Cell+new Vector2I(i%5-2,(i/5)%5-2);Add(a.Bases,$"scale_a_floor_{i}",owner.Company,BaseSpatialSourceKindV3.Floor,BaseSpatialSourceRoleV3.Connector,cell);}
            foreach(string company in a.Companies)a.Bases.RebuildCompanyNow(company);int peakFacilityDirty=a.Facilities.DirtyFacilityCount+a.Facilities.DirtyBaseAreaCount;a.Facilities.ProcessUntilIdle();for(int i=0;i<mercenaries;i++){var owner=anchors[i%bases];a.AddMercenary(owner.Company,owner.Cell);}int peakMercDirty=a.Affiliations.DirtyMercenaryCount;a.Affiliations.ProcessUntilIdle();JobManagerV3 manager=new(501);for(int i=0;i<jobs;i++){var owner=anchors[i%bases];manager.TryUpsertSource(new(owner.Company,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,$"scale_a_job_{i}"),owner.Cell+new Vector2I(i%11-5,(i/11)%11-5),1,out _,out _,out _);}Require(a.Facilities.Count==facilities&&a.Affiliations.Count==mercenaries&&manager.Count==jobs,"Fixture A counts failed.");Require(peakFacilityDirty>=facilities&&peakMercDirty==mercenaries,"Fixture A dirty queues did not expose bounded backlog.");watch.Stop();summaries.Add($"A 4c/{a.Bases.Areas.Count}b/{a.Facilities.Count}f/{a.Affiliations.Count}m/{manager.Count}j dirtyPeak={peakFacilityDirty}/{peakMercDirty} elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms");
        }
        using(Fixture b=new(502,1))
        {
            Stopwatch watch=Stopwatch.StartNew();const int facilities=55000,mercenaries=5000,jobs=200000;string company=b.Companies[0];Vector2I anchor=new(0,0);Add(b.Bases,"scale_b_bed",company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,anchor);for(int i=1;i<facilities;i++)Add(b.Bases,$"scale_b_floor_{i}",company,BaseSpatialSourceKindV3.Floor,BaseSpatialSourceRoleV3.Connector,new(i%512-256,i/512-54));b.Bases.RebuildCompanyNow(company);b.Facilities.ProcessUntilIdle();for(int i=0;i<mercenaries;i++)b.AddMercenary(company,new(i%41-20,(i/41)%41-20));b.Affiliations.ProcessUntilIdle();JobManagerV3 manager=new(502);for(int i=0;i<jobs;i++)manager.TryUpsertSource(new(company,JobTypeV3.Gathering,JobSourceKindV3.ResourceNode,$"scale_b_job_{i}"),new(i%701-350,(i/701)%701-350),1,out _,out _,out _);Require(b.Bases.Areas.Count==1&&b.Facilities.Count==facilities&&b.Affiliations.Count==mercenaries&&manager.Count==jobs,"Fixture B counts failed.");watch.Stop();summaries.Add($"B 1c/1b/{b.Facilities.Count}f/{b.Affiliations.Count}m/{manager.Count}j elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms");
        }
        using(Fixture c=new(503,1))
        {
            Stopwatch watch=Stopwatch.StartNew();string company=c.Companies[0];for(int i=0;i<100;i++){Vector2I cell=new((i/2)*128,(i%2)*16);Add(c.Bases,$"scale_c_bed_{i}",company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,cell);c.AddMercenary(company,cell);}c.Rebuild(company);long startRemaps=c.Affiliations.Diagnostics.RemappedCount;for(int i=0;i<1000;i++){int pair=i%50;string bridge=$"scale_c_bridge_{i}";Add(c.Bases,bridge,company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new(pair*128,8));c.Rebuild(company);c.Bases.RemoveSource(bridge);c.Rebuild(company);}foreach(string id in c.Bases.RetiredBaseAreaIds)Require(!c.Bases.Areas.TryGet(id,out _),"Fixture C retained retired ID.");Require(c.Affiliations.Count==100,"Fixture C lost mercenary affiliation.");watch.Stop();summaries.Add($"C bases=100 churn=1000 remaps={c.Affiliations.Diagnostics.RemappedCount-startRemaps} retired={c.Bases.RetiredBaseAreaIds.Count} elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms");
        }
        using(Fixture d=new(504,1))
        {
            Stopwatch watch=Stopwatch.StartNew();string company=d.Companies[0];Add(d.Bases,"scale_d_left",company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new(0,0));Add(d.Bases,"scale_d_right",company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new(120,0));d.Rebuild(company);List<MercenaryStateV3> values=new();for(int i=0;i<1000;i++)values.Add(d.AddMercenary(company,new(47,i%3)));d.Affiliations.ProcessUntilIdle();long changes=d.Affiliations.Diagnostics.ChangedCount,stable=d.Affiliations.Diagnostics.StabilityKeepCount;for(int cycle=0;cycle<20;cycle++){int x=cycle%2==0?49:47;foreach(var state in values){state.TrySetCurrentCell(new(new Vector2I(x,state.CurrentCell.Value.Y)),out _);d.Affiliations.RequestReevaluation(state.MercenaryId,"ScaleBoundary");}Require(d.Affiliations.DirtyMercenaryCount==values.Count,"Fixture D dirty coalescing failed.");d.Affiliations.ProcessUntilIdle();}long churn=d.Affiliations.Diagnostics.ChangedCount-changes,keeps=d.Affiliations.Diagnostics.StabilityKeepCount-stable;Require(churn==0&&keeps>=20000,"Fixture D caused affiliation churn.");watch.Stop();summaries.Add($"D events=20000 churn={churn} stabilityKeeps={keeps} budget={MercenaryBaseAffiliationSettingsV3.MaxMercenaryReevaluationsPerTick} elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms");
        }
        total.Stop();LastScaleSummary=string.Join("; ",summaries)+$"; total={total.Elapsed.TotalMilliseconds:0.0}ms";return LastScaleSummary;
    }

    private sealed class Fixture:IDisposable
    {
        public Fixture(long revision,int companyCount){CompaniesSession=new();Require(CompaniesSession.TryInitializeLocalSinglePlayer(out _,out string reason),reason);Companies.Add(CompaniesSession.LocalContext.LocalCompanyId!);for(int i=1;i<companyCount;i++){Require(CompaniesSession.CompanyRegistry.TryCreateCompany(CompanyIdFactoryV3.CreatePlayerId(),$"Company {i}",out var company,out reason),reason);Companies.Add(company!.CompanyId);}Mercenaries=new(CompaniesSession.CompanyRegistry);Needs=new(revision);Bases=new(revision);Bases.SetWorldBounds(new(-1000,-1000,100000,100000));Facilities=new(revision,Bases);Affiliations=new(revision,Mercenaries,Needs,Bases,Facilities);Policy=new(Bases,Facilities,Affiliations);}
        public CompanySessionV3 CompaniesSession{get;}public List<string> Companies{get;}=new();public MercenarySessionV3 Mercenaries{get;}public MercenaryNeedsSessionV3 Needs{get;}public BaseAreaSessionV3 Bases{get;}public FacilityAffiliationSessionV3 Facilities{get;}public MercenaryBaseAffiliationSessionV3 Affiliations{get;}public JobActivityRangePolicyV3 Policy{get;}
        public MercenaryStateV3 AddMercenary(string company,Vector2I cell){string id=MercenaryIdFactoryV3.CreateMercenaryId();DateTime now=DateTime.UtcNow;MercenaryAttributeSetV3.TryCreate(10,10,10,10,10,out var attributes,out _);MercenaryWorkSkillSetV3.TryCreate(8,8,8,8,8,8,8,out var skills,out _);MercenaryProfileV3.TryCreate(id,"Policy Worker","placeholder",attributes,skills,now,out var profile,out _);MercenaryStateV3.TryCreate(id,company,new(cell),MercenaryActivityStateV3.Idle,now,out var state,out _);Require(Mercenaries.Registry.TryRegisterMercenary(profile,state,out string reason),reason);return state!;}
        public void Rebuild(string company){Bases.RebuildCompanyNow(company);Facilities.ProcessUntilIdle();Affiliations.ProcessUntilIdle();}
        public void Dispose(){Affiliations.Dispose();Facilities.Dispose();}
    }
    private static JobRecordV3 AddJob(JobManagerV3 manager,string company,JobTypeV3 type,JobSourceKindV3 kind,string id,Vector2I cell){Require(manager.TryUpsertSource(new(company,type,kind,id),cell,1,out var job,out _,out string reason),reason);return job!;}
    private static void Add(BaseAreaSessionV3 bases,string id,string company,BaseSpatialSourceKindV3 kind,BaseSpatialSourceRoleV3 role,Vector2I cell)=>bases.UpsertSource(new(id,company,kind,role,new[]{new GlobalCellCoord(cell)},role==BaseSpatialSourceRoleV3.Anchor?4:0,bases.NextSourceCreationOrder(),1));
    private static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}
}
