using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Company;
using GameplayV3.Construction.Runtime;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Stockpile;
using GameplayV3.Work;
using Godot;
using WorldV2;

namespace GameplayV3.Construction;

public sealed record ConstructionRuntimeSelfCheckResultV3(bool Passed,string Summary,int SingleStackTrips,int SplitStackTrips,string SupplyWorker,string ConstructionWorker);
public sealed record ConstructionPresetSmokeResultV3(bool Passed,string Summary,IReadOnlyDictionary<WorldMapSizePresetV2,string> PresetResults);
public static class ConstructionRuntimeSelfCheckV3
{
    public static ConstructionRuntimeSelfCheckResultV3 Run()
    {
        List<string> failures=new();Scenario single=CreateScenario(new[]{(new Vector2I(2,2),20)});RunSupply(single,20);Check(single.Blueprint.MaterialBuffer.IsComplete,"single stack ready");Check(single.Coordinator.LastSupplyTripCount==2,"single stack 16+4 trips");Check(Clean(single),"single stack cleanup");int singleTrips=single.Coordinator.LastSupplyTripCount;
        Scenario split=CreateScenario(new[]{(new Vector2I(2,2),12),(new Vector2I(3,2),8)});RunSupply(split,20);Check(split.Blueprint.MaterialBuffer.IsComplete,"split stack ready");Check(split.Coordinator.LastSupplyTripCount==2,"split stack 12+8 trips");Check(Clean(split),"split stack cleanup");int splitTrips=split.Coordinator.LastSupplyTripCount;
        int totalBefore=Total(split);Check(split.Coordinator.TryCancelBlueprint(split.Blueprint.BlueprintId,out _),"ready blueprint cancel");Check(Total(split)==totalBefore,"ready cancel conservation");Check(split.Construction.Blueprints.Count==0&&split.Construction.Reservations.Count==0,"ready cancel cleanup");
        Scenario active=CreateScenario(new[]{(new Vector2I(2,2),20)});Check(active.Coordinator.TryIssue(active.Blueprint.BlueprintId,active.Selected,out _),"active supply issue");AdvanceOne(active);int activeTotal=Total(active);Check(active.Work.Carries.Count==1,"carry after pickup");Check(active.Coordinator.TryCancelBlueprint(active.Blueprint.BlueprintId,out _),"active supply cancel");Check(Total(active)==activeTotal&&active.Work.Carries.Count==0&&Clean(active),"active supply conservation");
        Scenario beforePickup=CreateScenario(new[]{(new Vector2I(2,2),20)});int beforeTotal=Total(beforePickup);Check(beforePickup.Coordinator.TryIssue(beforePickup.Blueprint.BlueprintId,beforePickup.Selected,out _),"before-pickup issue");Check(beforePickup.Coordinator.TryCancelBlueprint(beforePickup.Blueprint.BlueprintId,out _)&&Total(beforePickup)==beforeTotal&&Clean(beforePickup),"before-pickup cancel conservation");
        Scenario afterDelivery=CreateScenario(new[]{(new Vector2I(2,2),20)});Check(afterDelivery.Coordinator.TryIssue(afterDelivery.Blueprint.BlueprintId,afterDelivery.Selected,out _),"after-delivery issue");AdvanceOne(afterDelivery);AdvanceOne(afterDelivery);int afterDeliveryTotal=Total(afterDelivery);Check(afterDelivery.Blueprint.MaterialBuffer.GetDeliveredAmount(ResourceTypeV3.Wood)==16,"first buffer delivery");Check(afterDelivery.Coordinator.TryCancelBlueprint(afterDelivery.Blueprint.BlueprintId,out _)&&Total(afterDelivery)==afterDeliveryTotal&&Clean(afterDelivery),"after-delivery cancel conservation");
        Scenario secondPickup=CreateScenario(new[]{(new Vector2I(2,2),20)});Check(secondPickup.Coordinator.TryIssue(secondPickup.Blueprint.BlueprintId,secondPickup.Selected,out _),"second-pickup issue");AdvanceOne(secondPickup);AdvanceOne(secondPickup);AdvanceOne(secondPickup);int secondPickupTotal=Total(secondPickup);Check(secondPickup.Work.Carries.GetTotalAmount(ResourceTypeV3.Wood)==4,"second pickup carry");Check(secondPickup.Coordinator.TryCancelBlueprint(secondPickup.Blueprint.BlueprintId,out _)&&Total(secondPickup)==secondPickupTotal&&Clean(secondPickup),"second-pickup cancel conservation");
        Scenario build=CreateScenario(new[]{(new Vector2I(2,2),20)},5);RunSupply(build,5);Check(build.Coordinator.TryIssue(build.Blueprint.BlueprintId,build.Selected,out _),"construction issue");AdvanceOne(build);Check(build.Coordinator.LastConstructionWorkerId==build.B,"Recruit B construction selection");build.Coordinator.Tick(100);Check(build.Construction.Blueprints.Count==0&&build.Construction.Structures.Count==1,"construction completion");StructureStateV3 built=build.Construction.Structures.GetStructuresByCompany(build.CompanyId)[0];Check(built.EmbeddedMaterials.Sum(x=>x.RequiredAmount)==5&&build.Construction.Structures.IsMovementBlocked(build.Blueprint.AnchorCell),"embedded material and blocking");Check(Clean(build),"construction cleanup");
        Scenario waiting=CreateScenario(new[]{(new Vector2I(2,2),20)},5);RunSupply(waiting,5);Check(waiting.Coordinator.TryIssue(waiting.Blueprint.BlueprintId,waiting.Selected,out _),"waiting construction issue");AdvanceOne(waiting);waiting.Mercenaries.Registry.TryGetState(waiting.A,out MercenaryStateV3? blocker);GlobalCellCoord old=blocker!.CurrentCell;blocker.TrySetCurrentCell(waiting.Blueprint.AnchorCell,out _);waiting.Coordinator.Tick(100);Check(waiting.Blueprint.Status==ConstructionBlueprintStatusV3.WaitingForFootprintClear&&waiting.Construction.Structures.Count==0,"footprint current-cell wait");float progress=waiting.Blueprint.ConstructionProgressSeconds;blocker.TrySetCurrentCell(old,out _);waiting.Coordinator.Tick(.1f);Check(waiting.Construction.Structures.Count==1&&progress==waiting.Blueprint.ConstructionProgressSeconds,"footprint clear resumes");
        Scenario movingBlock=CreateScenario(new[]{(new Vector2I(2,2),20)},5);RunSupply(movingBlock,5);Check(movingBlock.Coordinator.TryIssue(movingBlock.Blueprint.BlueprintId,movingBlock.Selected,out _),"moving-footprint construction issue");AdvanceOne(movingBlock);movingBlock.Mercenaries.Registry.TryGetState(movingBlock.A,out MercenaryStateV3? movingState);MercenaryMovementStateV3 movement=new(movingBlock.A,"test",MovementRequestSourceTypeV3.DirectCommand,1,1,movingBlock.Blueprint.AnchorCell,new[]{movingBlock.Blueprint.AnchorCell},1){FromCell=movingState!.CurrentCell,ToCell=movingBlock.Blueprint.AnchorCell,NextPathIndex=1};movingBlock.Control.Movements.Set(movement);movingBlock.Coordinator.Tick(100);Check(movingBlock.Blueprint.Status==ConstructionBlueprintStatusV3.WaitingForFootprintClear&&movingBlock.Construction.Structures.Count==0,"footprint ToCell wait");movingBlock.Control.Movements.Remove(movingBlock.A);movingBlock.Coordinator.Tick(.1f);Check(movingBlock.Construction.Structures.Count==1,"ToCell clear resumes");
        Scenario constructionCancel=CreateScenario(new[]{(new Vector2I(2,2),20)},5);RunSupply(constructionCancel,5);Check(constructionCancel.Coordinator.TryIssue(constructionCancel.Blueprint.BlueprintId,constructionCancel.Selected,out _),"construction-cancel issue");AdvanceOne(constructionCancel);constructionCancel.Coordinator.Tick(1);int constructionTotal=Total(constructionCancel);Check(constructionCancel.Coordinator.TryCancelBlueprint(constructionCancel.Blueprint.BlueprintId,out _)&&Total(constructionCancel)==constructionTotal&&Clean(constructionCancel),"construction-progress cancel conservation");
        Scenario directBefore=CreateScenario(new[]{(new Vector2I(2,2),20)});int directBeforeTotal=Total(directBefore);Check(directBefore.Coordinator.TryIssue(directBefore.Blueprint.BlueprintId,directBefore.Selected,out _),"direct before-pickup issue");directBefore.Coordinator.CancelForDirectMove(directBefore.Coordinator.LastSupplyWorkerId);Check(Total(directBefore)==directBeforeTotal&&directBefore.Construction.Blueprints.Count==1&&Clean(directBefore),"direct before-pickup conservation");
        Scenario directCarry=CreateScenario(new[]{(new Vector2I(2,2),20)});Check(directCarry.Coordinator.TryIssue(directCarry.Blueprint.BlueprintId,directCarry.Selected,out _),"direct carry issue");AdvanceOne(directCarry);int directCarryTotal=Total(directCarry);directCarry.Coordinator.CancelForDirectMove(directCarry.Coordinator.LastSupplyWorkerId);Check(Total(directCarry)==directCarryTotal&&directCarry.Work.Carries.Count==0&&directCarry.Construction.Blueprints.Count==1&&Clean(directCarry),"direct carry emergency drop");
        Scenario directDelivered=CreateScenario(new[]{(new Vector2I(2,2),20)});Check(directDelivered.Coordinator.TryIssue(directDelivered.Blueprint.BlueprintId,directDelivered.Selected,out _),"direct delivered issue");AdvanceOne(directDelivered);AdvanceOne(directDelivered);int directDeliveredTotal=Total(directDelivered);directDelivered.Coordinator.CancelForDirectMove(directDelivered.Coordinator.LastSupplyWorkerId);Check(Total(directDelivered)==directDeliveredTotal&&directDelivered.Blueprint.MaterialBuffer.GetDeliveredAmount(ResourceTypeV3.Wood)==16&&Clean(directDelivered),"direct delivered buffer preserved");
        Scenario directSecondCarry=CreateScenario(new[]{(new Vector2I(2,2),20)});Check(directSecondCarry.Coordinator.TryIssue(directSecondCarry.Blueprint.BlueprintId,directSecondCarry.Selected,out _),"direct second-carry issue");AdvanceOne(directSecondCarry);AdvanceOne(directSecondCarry);AdvanceOne(directSecondCarry);int directSecondTotal=Total(directSecondCarry);directSecondCarry.Coordinator.CancelForDirectMove(directSecondCarry.Coordinator.LastSupplyWorkerId);Check(Total(directSecondCarry)==directSecondTotal&&directSecondCarry.Blueprint.MaterialBuffer.GetDeliveredAmount(ResourceTypeV3.Wood)==16&&directSecondCarry.Work.Carries.Count==0&&Clean(directSecondCarry),"direct second-carry conservation");
        Scenario directBuild=CreateScenario(new[]{(new Vector2I(2,2),20)},5);RunSupply(directBuild,5);Check(directBuild.Coordinator.TryIssue(directBuild.Blueprint.BlueprintId,directBuild.Selected,out _),"direct construction issue");AdvanceOne(directBuild);directBuild.Coordinator.Tick(1);float directProgress=directBuild.Blueprint.ConstructionProgressSeconds;int directBuildTotal=Total(directBuild);directBuild.Coordinator.CancelForDirectMove(directBuild.Coordinator.LastConstructionWorkerId);Check(directProgress>0&&directBuild.Blueprint.ConstructionProgressSeconds==directProgress&&Total(directBuild)==directBuildTotal&&directBuild.Construction.Blueprints.Count==1&&Clean(directBuild),"direct construction progress preserved");
        Scenario doorBuild=CreateScenario(new[]{(new Vector2I(2,2),2)},2,null,StructureDefinitionCatalogV3.WoodenDoorId);RunSupply(doorBuild,2);Check(doorBuild.Blueprint.MaterialBuffer.IsComplete,"door supply through common material buffer");Check(doorBuild.Coordinator.TryIssue(doorBuild.Blueprint.BlueprintId,doorBuild.Selected,out _),"door common construction issue");AdvanceOne(doorBuild);doorBuild.Coordinator.Tick(100);StructureStateV3? completedDoor=doorBuild.Construction.Structures.GetStructuresByCompany(doorBuild.CompanyId).SingleOrDefault();Check(completedDoor?.MovementKind==StructureMovementKindV3.PassableDoor&&completedDoor.RoomBoundaryKind==StructureRoomBoundaryKindV3.Door&&completedDoor.EmbeddedMaterials.Sum(x=>x.RequiredAmount)==2&&doorBuild.Construction.DoorPassages.Count==1&&!doorBuild.Construction.Structures.IsMovementBlocked(doorBuild.Blueprint.AnchorCell)&&Clean(doorBuild),"door common supply/construction completion");
        return new(failures.Count==0,failures.Count==0?"PASS":"FAIL: "+string.Join(" | ",failures),singleTrips,splitTrips,single.Coordinator.LastSupplyWorkerId,build.Coordinator.LastConstructionWorkerId);
        void Check(bool ok,string name){if(!ok)failures.Add(name);}
    }

    public static ConstructionPresetSmokeResultV3 RunPresetSmoke()
    {
        Dictionary<WorldMapSizePresetV2,string> results=new();
        List<string> failures=new();
        foreach(WorldMapSizePresetV2 preset in Enum.GetValues<WorldMapSizePresetV2>())
        {
            Rect2I bounds=WorldMapSizeDefinitionV2.FromPreset(preset).CellBounds;
            Scenario scenario=CreateScenario(new[]{(new Vector2I(2,2),5)},5,bounds);
            RunSupply(scenario,5);
            bool supplyReady=scenario.Blueprint.MaterialBuffer.IsComplete;
            bool issued=scenario.Coordinator.TryIssue(scenario.Blueprint.BlueprintId,scenario.Selected,out string reason);
            if(issued)
            {
                AdvanceOne(scenario);
                scenario.Coordinator.Tick(100);
            }

            bool passed=scenario.Mercenaries.Registry.CountByCompany(scenario.CompanyId)==3
                && supplyReady
                && issued
                && scenario.Construction.Blueprints.Count==0
                && scenario.Construction.Structures.Count==1
                && scenario.Construction.Structures.GetStructuresByCompany(scenario.CompanyId)[0].EmbeddedMaterials.Sum(x=>x.RequiredAmount)==5
                && scenario.Work.Carries.Count==0
                && scenario.Work.SourceStackReservations.Count==0
                && scenario.Construction.Reservations.Count==0
                && scenario.Coordinator.ActiveJobCount==0
                && scenario.Construction.Structures.IsMovementBlocked(scenario.Blueprint.AnchorCell);
            results[preset]=passed?"PASS":$"FAIL ({reason})";
            if(!passed)failures.Add($"{preset}:{reason}");
        }
        return new(failures.Count==0,failures.Count==0?"PASS":"FAIL: "+string.Join(" | ",failures),results);
    }

    private static void RunSupply(Scenario s,int expected){CheckIssue();int guard=0;while(s.Coordinator.ActiveJobCount>0&&guard++<20)AdvanceOne(s);if(guard>=20)throw new InvalidOperationException("Supply self-check exceeded bounded steps.");void CheckIssue(){if(!s.Coordinator.TryIssue(s.Blueprint.BlueprintId,s.Selected,out string reason))throw new InvalidOperationException(reason);}}
    private static void AdvanceOne(Scenario s){string worker=s.Control.ExternalMovements.GetActive().Single().MercenaryId;s.Mercenaries.Registry.TryGetState(worker,out MercenaryStateV3? state);s.Control.ExternalMovements.TryGetActive(worker,out MercenaryMovementRequestV3? request);state!.TrySetCurrentCell(request!.DestinationCell,out _);s.Control.ExternalMovements.Complete(request,true,string.Empty);if(!s.Control.ExternalMovements.TryDequeueResult(out MercenaryMovementResultV3? result)||result==null||!s.Coordinator.TryHandleMovementResult(result))throw new InvalidOperationException("Construction movement result was not handled.");}
    private static bool Clean(Scenario s)=>s.Work.Carries.Count==0&&s.Work.SourceStackReservations.Count==0&&s.Construction.Reservations.Count==0&&s.Coordinator.ActiveJobCount==0;
    private static int Total(Scenario s)=>s.Resources.GroundStacks.GetTotalAmount(ResourceTypeV3.Wood)+s.Work.Carries.GetTotalAmount(ResourceTypeV3.Wood)+s.Construction.Blueprints.GetBlueprintsByCompany(s.CompanyId).Sum(x=>x.MaterialBuffer.GetDeliveredAmount(ResourceTypeV3.Wood))+s.Construction.Structures.GetStructuresByCompany(s.CompanyId).Sum(x=>x.EmbeddedMaterials.Where(m=>m.ResourceType==ResourceTypeV3.Wood).Sum(m=>m.RequiredAmount));

    private static Scenario CreateScenario((Vector2I Cell,int Amount)[] stacks,int required=20,Rect2I? scenarioBounds=null,string? catalogDefinitionId=null)
    {
        Rect2I bounds=scenarioBounds??new Rect2I(0,0,40,40);CompanySessionV3 companies=new();companies.TryInitializeLocalSinglePlayer(out _,out _);string player=companies.LocalPlayer!.PlayerId,company=companies.LocalContext.LocalCompanyId!;MercenarySessionV3 mercenaries=new(companies.CompanyRegistry);string a=AddMerc(mercenaries,company,"A",10,10,10,10,10,8,8,new(1,1)),b=AddMerc(mercenaries,company,"B",7,14,9,12,9,6,11,new(1,2)),c=AddMerc(mercenaries,company,"C",15,7,13,7,12,12,6,new(1,3));MercenaryControlSessionV3 control=new(1,companies,mercenaries);ResourceSessionV3 resources=new();StockpileSessionV3 stockpiles=new();stockpiles.Zones.TryCreateZone(company,stacks.Select(x=>new GlobalCellCoord(x.Cell)).ToArray(),bounds,out _,out _);foreach(var stack in stacks)resources.GroundStacks.TryAddStack(ResourceTypeV3.Wood,stack.Amount,new(stack.Cell),out _,out _,out _);MercenaryWorkSessionV3 work=new(1,companies,mercenaries,resources,stockpiles,control);control.AttachWorkSession(work);ConstructionSessionV3 construction=new();StructureDefinitionV3 definition;if(!string.IsNullOrEmpty(catalogDefinitionId))construction.Definitions.TryGetDefinition(catalogDefinitionId,out definition!);else if(required==5)construction.Definitions.TryGetDefinition(StructureDefinitionCatalogV3.WoodenWallId,out definition!);else definition=new("runtime_test","Runtime Test",new[]{new StructureFootprintOffsetV3(0,0)},Enum.GetValues<StructureOrientationV3>(),new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,required)},6,true,StructurePlacementModeV3.Single);GlobalCellCoord anchor=new(new Vector2I(10,10));ResolvedStructureFootprintV3 footprint=StructureFootprintResolverV3.Resolve(definition,anchor,StructureOrientationV3.Deg0);ConstructionBlueprintStateV3 blueprint=new(ConstructionBlueprintIdFactoryV3.Create(),company,definition.DefinitionId,anchor,StructureOrientationV3.Deg0,footprint.Cells,new(definition.RequiredMaterials),DateTime.UtcNow);construction.Blueprints.TryRegister(blueprint,construction.Structures,bounds,out _);TestQuery query=new(bounds,construction.Structures);ConstructionWorkCoordinatorV3 coordinator=new(construction,resources,stockpiles,work,control,mercenaries,query,player,company,bounds);return new(companies,mercenaries,control,resources,stockpiles,work,construction,coordinator,blueprint,player,company,a,b,c,new[]{a,b,c});
    }
    private static string AddMerc(MercenarySessionV3 session,string company,string name,int str,int agi,int end,int intel,int mental,int hauling,int construction,Vector2I cell){MercenaryAttributeSetV3.TryCreate(str,agi,end,intel,mental,out var attributes,out _);MercenaryWorkSkillSetV3.TryCreate(hauling,construction,8,8,8,8,8,out var skills,out _);string id=MercenaryIdFactoryV3.CreateMercenaryId();DateTime now=DateTime.UtcNow;MercenaryProfileV3.TryCreate(id,name,"placeholder",attributes,skills,now,out var profile,out _);MercenaryStateV3.TryCreate(id,company,new(cell),MercenaryActivityStateV3.Idle,now,out var state,out _);session.Registry.TryRegisterMercenary(profile,state,out _);return id;}
    private sealed record Scenario(CompanySessionV3 Companies,MercenarySessionV3 Mercenaries,MercenaryControlSessionV3 Control,ResourceSessionV3 Resources,StockpileSessionV3 Stockpiles,MercenaryWorkSessionV3 Work,ConstructionSessionV3 Construction,ConstructionWorkCoordinatorV3 Coordinator,ConstructionBlueprintStateV3 Blueprint,string PlayerId,string CompanyId,string A,string B,string C,IReadOnlyList<string> Selected);
    private sealed class TestQuery:IMercenaryNavigationWorldQueryV3,INavigationOccupancyRevisionV3{private readonly Rect2I _bounds;private readonly StructureRegistryV3 _structures;public TestQuery(Rect2I bounds,StructureRegistryV3 structures){_bounds=bounds;_structures=structures;}public long OccupancyRevision=>_structures.OccupancyRevision;public bool IsInsideWorld(Vector2I c)=>_bounds.HasPoint(c);public MercenaryNavigationCellInfoV3 GetCellInfo(Vector2I c)=>new(IsInsideWorld(c),IsWalkable(c),1,TileType.Grass,BiomeKindV3.Plains);public bool IsWalkable(Vector2I c)=>IsInsideWorld(c)&&!_structures.IsMovementBlocked(new(c));public float GetTraversalMultiplier(Vector2I c)=>1;}
}
