using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Resources;
using GameplayV3.Navigation;
using GameplayV3.Construction.Runtime;
using Godot;
using WorldV2;

namespace GameplayV3.Construction;

public sealed record ConstructionSelfCheckResultV3(bool Succeeded,string Summary);
public static class ConstructionSelfCheckV3
{
    public static ConstructionSelfCheckResultV3 Run()
    {
        List<string> failures=new();Rect2I bounds=new(0,0,32,32);ConstructionSessionV3 session=new();session.Definitions.TryGetDefinition(StructureDefinitionCatalogV3.WoodenWallId,out var wall);Check(wall!=null,"wooden wall definition");
        Check(ConstructionPlacementServiceV3.BuildLine(new(new Vector2I(2,2)),new(new Vector2I(2,2))).Count==1,"single blueprint placement line");var horizontal=ConstructionPlacementServiceV3.BuildLine(new(new Vector2I(2,2)),new(new Vector2I(4,2)));Check(horizontal.Count==3&&horizontal.Select(x=>x.Value).SequenceEqual(new[]{new Vector2I(2,2),new Vector2I(3,2),new Vector2I(4,2)}),"horizontal three-cell blueprint batch");
        if(wall!=null){var resolved=StructureFootprintResolverV3.Resolve(wall,new(new Vector2I(3,4)),StructureOrientationV3.Deg90);Check(resolved.Cells.Count==1&&resolved.Cells[0].Value==new Vector2I(3,4),"wall footprint");}
        foreach((string Name,StructureFootprintOffsetV3[] Shape,int W,int H) t in new[]{("2x2",new[]{new StructureFootprintOffsetV3(0,0),new(1,0),new(0,1),new(1,1)},2,2),("2x3",new[]{new StructureFootprintOffsetV3(0,0),new(1,0),new(0,1),new(1,1),new(0,2),new(1,2)},2,3),("L",new[]{new StructureFootprintOffsetV3(0,0),new(0,1),new(1,1)},2,2)})
        {var d=new StructureDefinitionV3(t.Name,t.Name,t.Shape,Enum.GetValues<StructureOrientationV3>(),new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,1)},1,true,StructurePlacementModeV3.Single);foreach(var o in Enum.GetValues<StructureOrientationV3>()){var r=StructureFootprintResolverV3.Resolve(d,new(new Vector2I(5,6)),o);Check(r.Cells.Count==t.Shape.Length&&r.Cells.Distinct().Count()==r.Cells.Count,$"{t.Name} {o}");Check(r.Cells.SequenceEqual(r.Cells.OrderBy(x=>x.Value.Y).ThenBy(x=>x.Value.X)),$"{t.Name} deterministic");}if(t.Name=="2x3"){var r=StructureFootprintResolverV3.Resolve(d,new(new Vector2I(0,0)),StructureOrientationV3.Deg90);Check(r.Width==3&&r.Height==2,"2x3 rotation dimensions");}}
        ConstructionMaterialBufferV3 buffer=new(new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,5)});Check(buffer.TryDeliver(ResourceTypeV3.Wood,3,out _)&&buffer.TryDeliver(ResourceTypeV3.Wood,2,out _)&&buffer.IsComplete,"material delivery");Check(!buffer.TryDeliver(ResourceTypeV3.Wood,1,out _)&&!buffer.TryDeliver(ResourceTypeV3.Stone,1,out _),"material rejection");
        if(wall!=null){var r=StructureFootprintResolverV3.Resolve(wall,new(new Vector2I(1,1)),StructureOrientationV3.Deg0);var bp=new ConstructionBlueprintStateV3(ConstructionBlueprintIdFactoryV3.Create(),"company",wall.DefinitionId,new(new Vector2I(1,1)),StructureOrientationV3.Deg0,r.Cells,new(wall.RequiredMaterials),DateTime.UtcNow);Check(session.Blueprints.TryRegister(bp,session.Structures,bounds,out _),"blueprint register");Check(!session.Blueprints.TryRegister(new(ConstructionBlueprintIdFactoryV3.Create(),"company",wall.DefinitionId,bp.AnchorCell,bp.Orientation,r.Cells,new(wall.RequiredMaterials),DateTime.UtcNow),session.Structures,bounds,out _),"blueprint overlap");Check(session.Blueprints.TryGetBlueprintAtCell(bp.AnchorCell,out var indexed)&&indexed?.BlueprintId==bp.BlueprintId,"blueprint cell index");bp.MaterialBuffer.TryDeliver(ResourceTypeV3.Wood,5,out _);bp.RefreshMaterialStatus();var structure=new StructureStateV3(StructureIdFactoryV3.Create(),bp.CompanyId,bp.DefinitionId,bp.AnchorCell,bp.Orientation,bp.OccupiedCells,bp.MaterialBuffer.GetDeliveredMaterialsSnapshot(),true,DateTime.UtcNow);Check(session.Structures.TryRegister(structure,session.Blueprints,bounds,out _,bp.BlueprintId),"structure completion register");session.Blueprints.TryRemove(bp.BlueprintId,out _);Check(session.Structures.IsMovementBlocked(bp.AnchorCell),"structure blocks movement");}
        ConstructionSessionV3 revisionSession=new();DynamicStructureNavigationQueryV3 dynamicQuery=new(new FlatQuery(bounds),revisionSession.Structures);MercenaryPathRequestV3 oldRequest=new("path","merc",new(new Vector2I(0,0)),new(new Vector2I(2,0)),1,1){NavigationOccupancyRevision=dynamicQuery.OccupancyRevision};StructureStateV3 blocker=new(StructureIdFactoryV3.Create(),"company","test",new(new Vector2I(1,0)),StructureOrientationV3.Deg0,new[]{new GlobalCellCoord(new Vector2I(1,0))},new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,1)},true,DateTime.UtcNow);Check(revisionSession.Structures.TryRegister(blocker,revisionSession.Blueprints,bounds,out _),"occupancy revision structure");Check(!MercenaryNavigationRevisionPolicyV3.IsCurrent(oldRequest,dynamicQuery),"stale occupancy path rejected");MercenaryPathRequestV3 reroute=new("reroute","merc",new(new Vector2I(0,0)),new(new Vector2I(2,0)),1,2){NavigationOccupancyRevision=dynamicQuery.OccupancyRevision};MercenaryPathfindingSchedulerV3 scheduler=new(new());scheduler.Enqueue(reroute);MercenaryPathResultV3? rerouteResult=null;for(int i=0;i<16&&rerouteResult==null;i++){var results=scheduler.Tick(dynamicQuery,_=>true,out _);if(results.Count>0)rerouteResult=results[0];}Check(rerouteResult?.Success==true&&rerouteResult.Path.All(x=>x.Value!=new Vector2I(1,0)),"completed wall path reroutes");
        return new(failures.Count==0,failures.Count==0?"PASS":"FAIL: "+string.Join(" | ",failures));void Check(bool ok,string name){if(!ok)failures.Add(name);}
    }
    private sealed class FlatQuery:IMercenaryNavigationWorldQueryV3{private readonly Rect2I _bounds;public FlatQuery(Rect2I bounds){_bounds=bounds;}public bool IsInsideWorld(Vector2I c)=>_bounds.HasPoint(c);public MercenaryNavigationCellInfoV3 GetCellInfo(Vector2I c)=>new(IsInsideWorld(c),IsInsideWorld(c),1,TileType.Grass,BiomeKindV3.Plains);public bool IsWalkable(Vector2I c)=>IsInsideWorld(c);public float GetTraversalMultiplier(Vector2I c)=>1;}
}
