using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Company;
using GameplayV3.Construction.Runtime;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Stockpile;
using GameplayV3.Work;
using Godot;
using WorldV2;

namespace GameplayV3.Construction;

public sealed record DemolitionSelfCheckResultV3(bool Passed,string Summary,float RecruitAScore,float RecruitBScore,float RecruitCScore,float RecruitASeconds,float RecruitBSeconds,float RecruitCSeconds,string SelectedWorker,int SalvagedWood,long OccupancyBefore,long OccupancyAfter);
public sealed record DemolitionPresetSmokeResultV3(bool Passed,IReadOnlyDictionary<WorldMapSizePresetV2,string> Results);
public static class DemolitionSelfCheckV3
{
    public static DemolitionPresetSmokeResultV3 RunPresetSmoke(){Dictionary<WorldMapSizePresetV2,string> results=new();foreach(WorldMapSizePresetV2 preset in Enum.GetValues<WorldMapSizePresetV2>()){Rect2I bounds=WorldMapSizeDefinitionV2.FromPreset(preset).CellBounds;ConstructionSessionV3 construction=new();ResourceSessionV3 resources=new();construction.Definitions.TryGetDefinition(StructureDefinitionCatalogV3.WoodenWallId,out var wall);StructureStateV3 structure=new(StructureIdFactoryV3.Create(),"company",wall!.DefinitionId,new(new Vector2I(10,10)),StructureOrientationV3.Deg0,new[]{new GlobalCellCoord(new Vector2I(10,10))},new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,5)},true,DateTime.UtcNow);bool ok=construction.Structures.TryRegister(structure,construction.Blueprints,bounds,out _)&&construction.Demolitions.TryDesignate(structure,wall,"company",out _,out _,out _);string work=WorkRequestIdFactoryV3.Create();ok=ok&&construction.DemolitionReservations.TryReserve(new(structure.StructureId,work,"merc","company",DateTime.UtcNow,1),out _)&&construction.Demolitions.TryBeginDemolition(structure.StructureId,out _)&&construction.Demolitions.TryAddProgress(structure.StructureId,4,out _);DemolitionCompletionResultV3 completion=ok?DemolitionCompletionServiceV3.TryComplete(construction,resources,structure.StructureId,work,bounds,4):new(false,"SetupFailed",structure.StructureId,Array.Empty<string>(),0,0,0);ok=ok&&completion.Succeeded&&construction.Structures.Count==0&&construction.Demolitions.Count==0&&construction.DemolitionReservations.Count==0&&resources.GroundStacks.GetTotalAmount(ResourceTypeV3.Wood)==5;results[preset]=ok?"PASS":"FAIL";}return new(results.Values.All(x=>x=="PASS"),results);}
    public static DemolitionSelfCheckResultV3 Run()
    {
        List<string> failures=new();void Check(bool ok,string name){if(!ok)failures.Add(name);}Rect2I bounds=new(0,0,64,64);ConstructionSessionV3 construction=new();construction.Definitions.TryGetDefinition(StructureDefinitionCatalogV3.WoodenWallId,out var wall);Check(wall?.CanBeDemolished==true&&Mathf.IsEqualApprox(wall.BaseDemolitionDurationSeconds,4f),"wooden wall demolition definition");bool invalidDuration=false;try{_ = new StructureDefinitionV3("bad","Bad",new[]{new StructureFootprintOffsetV3(0,0)},Enum.GetValues<StructureOrientationV3>(),new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,1)},1,true,StructurePlacementModeV3.Single,true,0);}catch(ArgumentOutOfRangeException){invalidDuration=true;}Check(invalidDuration,"invalid demolition duration rejected");
        CompanySessionV3 companies=new();companies.TryInitializeLocalSinglePlayer(out _,out _);string player=companies.LocalPlayer!.PlayerId,company=companies.LocalContext.LocalCompanyId!;MercenarySessionV3 mercenaries=new(companies.CompanyRegistry);string a=AddMerc(mercenaries,company,"A",10,10,10,10,10,8,new(1,1)),b=AddMerc(mercenaries,company,"B",7,14,9,12,9,11,new(1,2)),c=AddMerc(mercenaries,company,"C",15,7,13,7,12,6,new(1,3));mercenaries.Registry.TryGetProfile(a,out var pa);mercenaries.Registry.TryGetProfile(b,out var pb);mercenaries.Registry.TryGetProfile(c,out var pc);DemolitionWorkCalculationV3 ca=DemolitionWorkCalculatorV3.Calculate(pa!,4),cb=DemolitionWorkCalculatorV3.Calculate(pb!,4),cc=DemolitionWorkCalculatorV3.Calculate(pc!,4);Check(ca.DemolitionScore<cb.DemolitionScore&&cb.DemolitionScore<cc.DemolitionScore,"demolition score ordering");
        StructureDefinitionV3 multiDefinition=new("multi_test","Multi",new[]{new StructureFootprintOffsetV3(0,0),new(1,0),new(0,1),new(1,1),new(0,2),new(1,2)},Enum.GetValues<StructureOrientationV3>(),new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,5),new StructureMaterialRequirementV3(ResourceTypeV3.Stone,3)},1,true,StructurePlacementModeV3.Single,true,4);var footprint=StructureFootprintResolverV3.Resolve(multiDefinition,new(new Vector2I(10,10)),StructureOrientationV3.Deg0);StructureStateV3 multi=new(StructureIdFactoryV3.Create(),company,multiDefinition.DefinitionId,new(new Vector2I(10,10)),StructureOrientationV3.Deg0,footprint.Cells,new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,5),new StructureMaterialRequirementV3(ResourceTypeV3.Stone,3)},true,DateTime.UtcNow);Check(construction.Structures.TryRegister(multi,construction.Blueprints,bounds,out _),"multi structure register");Check(construction.Demolitions.TryDesignate(multi,multiDefinition,company,out var designation,out bool reused,out _)&&!reused&&designation!=null&&construction.Demolitions.Count==1,"multi structure designate once");Check(construction.Demolitions.TryDesignate(multi,multiDefinition,company,out _,out reused,out _)&&reused&&construction.Demolitions.Count==1,"designation idempotent");Check(!construction.Demolitions.TryDesignate(multi,multiDefinition,"other",out _,out _,out _),"designation ownership");string workId=WorkRequestIdFactoryV3.Create();Check(construction.DemolitionReservations.TryReserve(new(multi.StructureId,workId,"merc",company,DateTime.UtcNow,1),out _),"demolition reserve");Check(!construction.DemolitionReservations.TryReserve(new(multi.StructureId,WorkRequestIdFactoryV3.Create(),"other",company,DateTime.UtcNow,2),out _),"duplicate demolition reserve rejected");construction.Demolitions.TryBeginDemolition(multi.StructureId,out _);construction.Demolitions.TryAddProgress(multi.StructureId,4,out _);ResourceSessionV3 coreResources=new();long coreBefore=construction.Structures.OccupancyRevision;DemolitionCompletionResultV3 completion=DemolitionCompletionServiceV3.TryComplete(construction,coreResources,multi.StructureId,workId,bounds,4);Check(completion.Succeeded&&construction.Structures.Count==0&&footprint.Cells.All(x=>!construction.Structures.IsStructureCell(x)),"multi footprint atomic removal");Check(coreResources.GroundStacks.GetTotalAmount(ResourceTypeV3.Wood)==5&&coreResources.GroundStacks.GetTotalAmount(ResourceTypeV3.Stone)==3,"embedded multi-resource salvage");Check(completion.OccupancyRevisionAfter>coreBefore&&construction.Demolitions.Count==0&&construction.DemolitionReservations.Count==0,"occupancy and terminal cleanup");
        ConstructionSessionV3 rollbackConstruction=new();ResourceSessionV3 rollbackResources=new();StructureStateV3 rollbackStructure=new(StructureIdFactoryV3.Create(),company,StructureDefinitionCatalogV3.WoodenWallId,new(new Vector2I(20,20)),StructureOrientationV3.Deg0,new[]{new GlobalCellCoord(new Vector2I(20,20))},new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,1)},true,DateTime.UtcNow);rollbackConstruction.Structures.TryRegister(rollbackStructure,rollbackConstruction.Blueprints,bounds,out _);rollbackConstruction.Demolitions.TryDesignate(rollbackStructure,wall!,company,out _,out _,out _);string rollbackWork=WorkRequestIdFactoryV3.Create();rollbackConstruction.DemolitionReservations.TryReserve(new(rollbackStructure.StructureId,rollbackWork,"merc",company,DateTime.UtcNow,1),out _);rollbackConstruction.Demolitions.TryBeginDemolition(rollbackStructure.StructureId,out _);rollbackConstruction.Demolitions.TryAddProgress(rollbackStructure.StructureId,4,out _);rollbackResources.GroundStacks.TryAddStack(ResourceTypeV3.Wood,int.MaxValue,rollbackStructure.AnchorCell,out _,out _,out _);DemolitionCompletionResultV3 rollback=DemolitionCompletionServiceV3.TryComplete(rollbackConstruction,rollbackResources,rollbackStructure.StructureId,rollbackWork,bounds,4);Check(!rollback.Succeeded&&rollbackConstruction.Structures.Contains(rollbackStructure.StructureId)&&rollbackResources.GroundStacks.GetTotalAmount(ResourceTypeV3.Wood)==int.MaxValue,"salvage rollback preserves structure and resources");
        ConstructionSessionV3 runtimeConstruction=new();ResourceSessionV3 resources=new();StockpileSessionV3 stockpiles=new();MercenaryControlSessionV3 control=new(1,companies,mercenaries);MercenaryWorkSessionV3 work=new(1,companies,mercenaries,resources,stockpiles,control);control.AttachWorkSession(work);StructureStateV3 wallState=new(StructureIdFactoryV3.Create(),company,wall!.DefinitionId,new(new Vector2I(30,30)),StructureOrientationV3.Deg0,new[]{new GlobalCellCoord(new Vector2I(30,30))},new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,5)},true,DateTime.UtcNow);runtimeConstruction.Structures.TryRegister(wallState,runtimeConstruction.Blueprints,bounds,out _);runtimeConstruction.Demolitions.TryDesignate(wallState,wall,company,out _,out _,out _);TestQuery query=new(bounds,runtimeConstruction.Structures);DemolitionWorkCoordinatorV3 coordinator=new(runtimeConstruction,resources,work,control,mercenaries,query,player,company,bounds);Check(coordinator.TryIssue(wallState.StructureId,new[]{a,b,c},out _),"runtime demolition issue");string selected=runtimeConstruction.DemolitionDiagnostics.LastWorkerId;Check(selected==c,"deterministic demolition worker");Advance(coordinator,control,mercenaries,selected);coordinator.Tick(cc.RequiredSeconds*.5f);runtimeConstruction.Demolitions.TryGet(wallState.StructureId,out var half);float saved=half?.ProgressSeconds??0;coordinator.CancelForDirectMove(selected);runtimeConstruction.Demolitions.TryGet(wallState.StructureId,out var afterCancel);Check(saved>0&&Mathf.IsEqualApprox(afterCancel?.ProgressSeconds??0,saved)&&runtimeConstruction.Structures.Contains(wallState.StructureId)&&runtimeConstruction.DemolitionReservations.Count==0,"direct move preserves progress and designation");Check(coordinator.TryIssue(wallState.StructureId,new[]{a,b,c},out _),"runtime demolition resume");Advance(coordinator,control,mercenaries,selected);long runtimeBefore=runtimeConstruction.Structures.OccupancyRevision;MercenaryPathRequestV3 stale=new("stale","merc",new(new Vector2I(29,30)),new(new Vector2I(30,30)),1,1){NavigationOccupancyRevision=runtimeBefore};coordinator.Tick(100);Check(runtimeConstruction.Structures.Count==0&&resources.GroundStacks.GetTotalAmount(ResourceTypeV3.Wood)==5&&coordinator.ActiveJobCount==0&&runtimeConstruction.Demolitions.Count==0&&runtimeConstruction.DemolitionReservations.Count==0,"runtime demolition completion and salvage");Check(!query.IsWalkable(new Vector2I(30,30))==false&&runtimeConstruction.Structures.OccupancyRevision>runtimeBefore&&!MercenaryNavigationRevisionPolicyV3.IsCurrent(stale,query),"dynamic occupancy release and stale revision");
        ConstructionSessionV3 removeDesignation=new();StructureStateV3 removeState=new(StructureIdFactoryV3.Create(),company,wall.DefinitionId,new(new Vector2I(40,40)),StructureOrientationV3.Deg0,new[]{new GlobalCellCoord(new Vector2I(40,40))},new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,5)},true,DateTime.UtcNow);removeDesignation.Structures.TryRegister(removeState,removeDesignation.Blueprints,bounds,out _);removeDesignation.Demolitions.TryDesignate(removeState,wall,company,out _,out _,out _);removeDesignation.Demolitions.TryBeginDemolition(removeState.StructureId,out _);removeDesignation.Demolitions.TryAddProgress(removeState.StructureId,2,out _);Check(removeDesignation.Demolitions.TryRemoveDesignation(removeState.StructureId,out _)&&!removeDesignation.Demolitions.Contains(removeState.StructureId)&&removeDesignation.Structures.Contains(removeState.StructureId),"designation removal clears progress only");
        return new(failures.Count==0,failures.Count==0?"PASS":"FAIL: "+string.Join(" | ",failures),ca.DemolitionScore,cb.DemolitionScore,cc.DemolitionScore,ca.RequiredSeconds,cb.RequiredSeconds,cc.RequiredSeconds,selected,resources.GroundStacks.GetTotalAmount(ResourceTypeV3.Wood),runtimeBefore,runtimeConstruction.Structures.OccupancyRevision);
    }
    private static void Advance(DemolitionWorkCoordinatorV3 coordinator,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,string worker){control.ExternalMovements.TryGetActive(worker,out var request);if(request==null)throw new InvalidOperationException("Missing demolition movement.");mercenaries.Registry.TryGetState(worker,out var state);state!.TrySetCurrentCell(request.DestinationCell,out _);control.ExternalMovements.Complete(request,true,string.Empty);while(control.ExternalMovements.TryDequeueResult(out var result))if(result!=null&&coordinator.TryHandleMovementResult(result))return;throw new InvalidOperationException("Demolition movement result was not handled.");}
    private static string AddMerc(MercenarySessionV3 session,string company,string name,int str,int agi,int end,int intel,int mental,int construction,Vector2I cell){MercenaryAttributeSetV3.TryCreate(str,agi,end,intel,mental,out var attributes,out _);MercenaryWorkSkillSetV3.TryCreate(8,construction,8,8,8,8,8,out var skills,out _);string id=MercenaryIdFactoryV3.CreateMercenaryId();DateTime now=DateTime.UtcNow;MercenaryProfileV3.TryCreate(id,name,"placeholder",attributes,skills,now,out var profile,out _);MercenaryStateV3.TryCreate(id,company,new(cell),MercenaryActivityStateV3.Idle,now,out var state,out _);session.Registry.TryRegisterMercenary(profile,state,out _);return id;}
    private sealed class TestQuery:IMercenaryNavigationWorldQueryV3,INavigationOccupancyRevisionV3{private readonly Rect2I _bounds;private readonly StructureRegistryV3 _structures;public TestQuery(Rect2I bounds,StructureRegistryV3 structures){_bounds=bounds;_structures=structures;}public long OccupancyRevision=>_structures.OccupancyRevision;public bool IsInsideWorld(Vector2I c)=>_bounds.HasPoint(c);public MercenaryNavigationCellInfoV3 GetCellInfo(Vector2I c)=>new(IsInsideWorld(c),IsWalkable(c),1,TileType.Grass,BiomeKindV3.Plains);public bool IsWalkable(Vector2I c)=>IsInsideWorld(c)&&!_structures.IsMovementBlocked(new(c));public float GetTraversalMultiplier(Vector2I c)=>1;}
}
