using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using Godot;
using WorldV2;

namespace GameplayV3.Construction;

public enum FloorVisualKindV3 { WoodenPlanks }
public sealed record FloorDefinitionV3(string FloorTypeId,string DisplayName,ResourceTypeV3 ResourceType,int ResourceCost,float BaseConstructionDurationSeconds,float BaseDemolitionDurationSeconds,float MovementSpeedMultiplier,int RoomQualityValue,FloorVisualKindV3 VisualKind,bool IsPassable);
public sealed class FloorDefinitionCatalogV3
{
    public const string WoodenFloorId="wooden_floor";private readonly Dictionary<string,FloorDefinitionV3> _definitions=new(StringComparer.Ordinal);
    public FloorDefinitionCatalogV3()=>_definitions.Add(WoodenFloorId,new(WoodenFloorId,"나무 바닥",ResourceTypeV3.Wood,1,2f,1.5f,1.10f,1,FloorVisualKindV3.WoodenPlanks,true));
    public bool TryGet(string id,out FloorDefinitionV3? definition)=>_definitions.TryGetValue(id,out definition);
}
public sealed class FloorCellStateV3
{
    internal FloorCellStateV3(string company,GlobalCellCoord cell,string type,long sequence){CompanyId=company;Cell=cell;FloorTypeId=type;CompletedSequence=sequence;Revision=1;}
    public string CompanyId{get;}public GlobalCellCoord Cell{get;}public string FloorTypeId{get;}public int Revision{get;internal set;}public long CompletedSequence{get;}
}
public sealed class FloorBlueprintV3
{
    internal FloorBlueprintV3(string id,string company,GlobalCellCoord cell,string type,FloorDefinitionV3 definition,DateTime created){BlueprintId=id;CompanyId=company;Cell=cell;FloorTypeId=type;MaterialBuffer=new(new[]{new StructureMaterialRequirementV3(definition.ResourceType,definition.ResourceCost)});CreatedUtc=created.ToUniversalTime();}
    public string BlueprintId{get;}public string CompanyId{get;}public GlobalCellCoord Cell{get;}public string FloorTypeId{get;}public ConstructionMaterialBufferV3 MaterialBuffer{get;}public ConstructionBlueprintStatusV3 Status{get;private set;}=ConstructionBlueprintStatusV3.AwaitingMaterials;public float ProgressSeconds{get;private set;}public int Revision{get;private set;}public DateTime CreatedUtc{get;}
    public void RefreshMaterialStatus(){if(Status is ConstructionBlueprintStatusV3.Completed or ConstructionBlueprintStatusV3.Cancelled)return;Status=MaterialBuffer.IsComplete?ConstructionBlueprintStatusV3.ReadyToBuild:ConstructionBlueprintStatusV3.AwaitingMaterials;Revision++;}
    public bool TryBegin(out string reason){if(!MaterialBuffer.IsComplete){reason="MaterialsMissing";return false;}if(Status is ConstructionBlueprintStatusV3.Completed or ConstructionBlueprintStatusV3.Cancelled){reason="InvalidBlueprintState";return false;}Status=ConstructionBlueprintStatusV3.UnderConstruction;Revision++;reason="";return true;}
    public void AddProgress(float delta){if(Status==ConstructionBlueprintStatusV3.UnderConstruction&&delta>0){ProgressSeconds+=delta;Revision++;}}
    internal void MarkCompleted(){Status=ConstructionBlueprintStatusV3.Completed;Revision++;}internal void MarkCancelled(){Status=ConstructionBlueprintStatusV3.Cancelled;Revision++;}
}
public enum FloorDemolitionStatusV3 { Designated, UnderDemolition, Completed, Cancelled }
public sealed class FloorDemolitionMarkV3
{
    internal FloorDemolitionMarkV3(string id,string company,GlobalCellCoord cell,int floorRevision){MarkId=id;CompanyId=company;Cell=cell;FloorRevision=floorRevision;Revision=1;}
    public string MarkId{get;}public string CompanyId{get;}public GlobalCellCoord Cell{get;}public int FloorRevision{get;}public int Revision{get;private set;}public float ProgressSeconds{get;private set;}public FloorDemolitionStatusV3 Status{get;private set;}=FloorDemolitionStatusV3.Designated;
    public bool TryBegin(){if(Status is FloorDemolitionStatusV3.Completed or FloorDemolitionStatusV3.Cancelled)return false;Status=FloorDemolitionStatusV3.UnderDemolition;Revision++;return true;}public bool TryAddProgress(float value){if(Status!=FloorDemolitionStatusV3.UnderDemolition||value<0||!float.IsFinite(value))return false;ProgressSeconds+=value;Revision++;return true;}public void Reset(){if(Status!=FloorDemolitionStatusV3.Completed){Status=FloorDemolitionStatusV3.Designated;Revision++;}}internal void Complete(){Status=FloorDemolitionStatusV3.Completed;Revision++;}
}
public sealed class FloorChunkDataV3
{
    private readonly HashSet<Vector2I> _floorCells=new(),_blueprintCells=new(),_markCells=new();internal FloorChunkDataV3(Vector2I coord)=>ChunkCoord=coord;
    public Vector2I ChunkCoord{get;}public long Revision{get;internal set;}public long VisualRevision{get;internal set;}public long MovementCostRevision{get;internal set;}public int FloorCount=>_floorCells.Count;public int BlueprintCount=>_blueprintCells.Count;public int MarkCount=>_markCells.Count;public bool IsEmpty=>FloorCount+BlueprintCount+MarkCount==0;
    internal void AddFloor(Vector2I c){_floorCells.Add(c);Touch(true);}internal void RemoveFloor(Vector2I c){_floorCells.Remove(c);Touch(true);}internal void AddBlueprint(Vector2I c){_blueprintCells.Add(c);Touch(false);}internal void RemoveBlueprint(Vector2I c){_blueprintCells.Remove(c);Touch(false);}internal void AddMark(Vector2I c){_markCells.Add(c);Touch(false);}internal void RemoveMark(Vector2I c){_markCells.Remove(c);Touch(false);}private void Touch(bool movement){Revision++;VisualRevision++;if(movement)MovementCostRevision++;}
    public IReadOnlyCollection<Vector2I> FloorCells=>_floorCells;public IReadOnlyCollection<Vector2I> BlueprintCells=>_blueprintCells;public IReadOnlyCollection<Vector2I> MarkCells=>_markCells;
}
public enum FloorSourceChangeKindV3{Blueprint,Demolition}
public readonly record struct FloorSourceChangeV3(FloorSourceChangeKindV3 Kind,string SourceId,string CompanyId,GlobalCellCoord Cell,long Revision,bool IsValid);
public sealed class FloorDiagnosticsV3
{
    public int BlueprintCreatesThisTick{get;internal set;}public int CompletionsThisTick{get;internal set;}public int RemovalsThisTick{get;internal set;}public int SourceUpdatesThisTick{get;internal set;}public int EventsEmittedThisTick{get;internal set;}public int VisualChunksUpdatedThisFrame{get;internal set;}public int PerCellNodeCount=>0;public int PerCellProcessCount=>0;public int FullFloorRegistryScanCount{get;internal set;}public int FullFloorBlueprintScanCount{get;internal set;}public int FloorVisualFullMapRebuildCount{get;internal set;}public int FloorPathRequestsThisTick{get;internal set;}public string LastFailure{get;internal set;}="";public double RuntimeTickMs{get;internal set;}public double MaxRuntimeTickMs{get;internal set;}
}
public sealed class FloorRegistryV3
{
    private readonly Dictionary<Vector2I,FloorCellStateV3> _floors=new();private readonly Dictionary<string,FloorBlueprintV3> _blueprints=new(StringComparer.Ordinal);private readonly Dictionary<Vector2I,string> _blueprintByCell=new();private readonly Dictionary<string,FloorDemolitionMarkV3> _marks=new(StringComparer.Ordinal);private readonly Dictionary<Vector2I,string> _markByCell=new();private readonly Dictionary<Vector2I,FloorChunkDataV3> _chunks=new();private readonly Queue<FloorSourceChangeV3> _sourceChanges=new();private readonly HashSet<Vector2I> _dirtyChunks=new();private long _sequence;
    public event Action<Vector2I,int,long>? ChunkChanged;public FloorDiagnosticsV3 Diagnostics{get;}=new();public int Count=>_floors.Count;public int BlueprintCount=>_blueprints.Count;public int DemolitionMarkCount=>_marks.Count;public int ChunkCount=>_chunks.Count;public int DirtyChunkCount=>_dirtyChunks.Count;public int PendingSourceChangeCount=>_sourceChanges.Count;public long Revision{get;private set;}public long MovementCostRevision{get;private set;}
    public static Vector2I ChunkOf(Vector2I cell)=>WorldV2CoordinateUtility.GlobalCellToGlobalChunkCoord(cell);private FloorChunkDataV3 Chunk(Vector2I cell){Vector2I c=ChunkOf(cell);if(!_chunks.TryGetValue(c,out var chunk)){chunk=new(c);_chunks.Add(c,chunk);}return chunk;}private void Changed(Vector2I cell,int count=1){Vector2I c=ChunkOf(cell);_dirtyChunks.Add(c);Revision++;Diagnostics.EventsEmittedThisTick++;ChunkChanged?.Invoke(c,count,Revision);}private void CleanupChunk(Vector2I cell){Vector2I c=ChunkOf(cell);if(_chunks.TryGetValue(c,out var chunk)&&chunk.IsEmpty)_chunks.Remove(c);}
    public bool TryGetFloor(GlobalCellCoord cell,out FloorCellStateV3? floor)=>_floors.TryGetValue(cell.Value,out floor);public bool HasFloor(GlobalCellCoord cell)=>_floors.ContainsKey(cell.Value);public bool TryGetBlueprint(string id,out FloorBlueprintV3? bp)=>_blueprints.TryGetValue(id,out bp);public bool TryGetBlueprint(GlobalCellCoord cell,out FloorBlueprintV3? bp){bp=null;return _blueprintByCell.TryGetValue(cell.Value,out string? id)&&_blueprints.TryGetValue(id,out bp);}public bool TryGetMark(string id,out FloorDemolitionMarkV3? mark)=>_marks.TryGetValue(id,out mark);public bool TryGetMark(GlobalCellCoord cell,out FloorDemolitionMarkV3? mark){mark=null;return _markByCell.TryGetValue(cell.Value,out string? id)&&_marks.TryGetValue(id,out mark);}public bool ContainsTarget(string id)=>_blueprints.ContainsKey(id)||_marks.ContainsKey(id);
    public FloorChunkDataV3? GetChunk(Vector2I chunk)=>_chunks.GetValueOrDefault(chunk);public IEnumerable<Vector2I> GetChunkCoords()=>_chunks.Keys;public IEnumerable<FloorCellStateV3> EnumerateFloorsInChunk(Vector2I chunk){if(!_chunks.TryGetValue(chunk,out var data))yield break;foreach(Vector2I cell in data.FloorCells)if(_floors.TryGetValue(cell,out var floor))yield return floor;}public IEnumerable<FloorBlueprintV3> EnumerateBlueprintsInChunk(Vector2I chunk){if(!_chunks.TryGetValue(chunk,out var data))yield break;foreach(Vector2I cell in data.BlueprintCells)if(_blueprintByCell.TryGetValue(cell,out var id)&&_blueprints.TryGetValue(id,out var bp))yield return bp;}public IEnumerable<FloorDemolitionMarkV3> EnumerateMarksInChunk(Vector2I chunk){if(!_chunks.TryGetValue(chunk,out var data))yield break;foreach(Vector2I cell in data.MarkCells)if(_markByCell.TryGetValue(cell,out var id)&&_marks.TryGetValue(id,out var mark))yield return mark;}
    public bool TryCreateBlueprint(string company,GlobalCellCoord cell,FloorDefinitionV3 definition,Rect2I bounds,out FloorBlueprintV3? bp,out string reason){bp=null;if(!bounds.HasPoint(cell.Value)){reason="OutOfBounds";return false;}if(_floors.ContainsKey(cell.Value)||_blueprintByCell.ContainsKey(cell.Value)||_markByCell.ContainsKey(cell.Value)){reason="FloorCellOccupied";return false;}bp=new(ConstructionBlueprintIdFactoryV3.Create(),company,cell,definition.FloorTypeId,definition,DateTime.UtcNow);_blueprints.Add(bp.BlueprintId,bp);_blueprintByCell.Add(cell.Value,bp.BlueprintId);Chunk(cell.Value).AddBlueprint(cell.Value);_sourceChanges.Enqueue(new(FloorSourceChangeKindV3.Blueprint,bp.BlueprintId,company,cell,bp.Revision,true));Diagnostics.BlueprintCreatesThisTick++;Changed(cell.Value);reason="";return true;}
    public bool TryCancelBlueprint(string id,out FloorBlueprintV3? bp){if(!_blueprints.Remove(id,out bp)||bp==null)return false;_blueprintByCell.Remove(bp.Cell.Value);Chunk(bp.Cell.Value).RemoveBlueprint(bp.Cell.Value);bp.MarkCancelled();_sourceChanges.Enqueue(new(FloorSourceChangeKindV3.Blueprint,id,bp.CompanyId,bp.Cell,bp.Revision,false));Changed(bp.Cell.Value);CleanupChunk(bp.Cell.Value);return true;}
    public bool TryCompleteBlueprint(string id,out FloorCellStateV3? floor,out string reason){floor=null;if(!_blueprints.TryGetValue(id,out var bp)||!bp.MaterialBuffer.IsComplete){reason="InvalidFloorBlueprint";return false;}if(_floors.ContainsKey(bp.Cell.Value)){reason="FloorAlreadyExists";return false;}_blueprints.Remove(id);_blueprintByCell.Remove(bp.Cell.Value);FloorChunkDataV3 chunk=Chunk(bp.Cell.Value);chunk.RemoveBlueprint(bp.Cell.Value);floor=new(bp.CompanyId,bp.Cell,bp.FloorTypeId,++_sequence);_floors.Add(bp.Cell.Value,floor);chunk.AddFloor(bp.Cell.Value);bp.MarkCompleted();MovementCostRevision++;Diagnostics.CompletionsThisTick++;_sourceChanges.Enqueue(new(FloorSourceChangeKindV3.Blueprint,id,bp.CompanyId,bp.Cell,bp.Revision,false));Changed(bp.Cell.Value);reason="";return true;}
    internal bool TryRegisterCompletedFloorForFixture(string company,GlobalCellCoord cell,string floorTypeId){if(_floors.ContainsKey(cell.Value)||_blueprintByCell.ContainsKey(cell.Value)||_markByCell.ContainsKey(cell.Value))return false;var floor=new FloorCellStateV3(company,cell,floorTypeId,++_sequence);_floors.Add(cell.Value,floor);Chunk(cell.Value).AddFloor(cell.Value);MovementCostRevision++;Changed(cell.Value);return true;}
    public bool TryMarkDemolition(string company,GlobalCellCoord cell,out FloorDemolitionMarkV3? mark,out bool reused,out string reason){mark=null;reused=false;if(!_floors.TryGetValue(cell.Value,out var floor)){reason="FloorMissing";return false;}if(floor.CompanyId!=company){reason="OwnershipDenied";return false;}if(_blueprintByCell.ContainsKey(cell.Value)){reason="FloorBlueprintConflict";return false;}if(TryGetMark(cell,out mark)){reused=true;reason="";return true;}string id=$"floor:{cell.Value.X}:{cell.Value.Y}";mark=new(id,company,cell,floor.Revision);_marks.Add(id,mark);_markByCell.Add(cell.Value,id);Chunk(cell.Value).AddMark(cell.Value);_sourceChanges.Enqueue(new(FloorSourceChangeKindV3.Demolition,id,company,cell,mark.Revision,true));Changed(cell.Value);reason="";return true;}
    public bool TryBeginDemolition(string id)=>_marks.TryGetValue(id,out var mark)&&mark.TryBegin();public bool TryAddDemolitionProgress(string id,float delta)=>_marks.TryGetValue(id,out var mark)&&mark.TryAddProgress(delta);public bool TryResetDemolition(string id){if(!_marks.TryGetValue(id,out var mark))return false;mark.Reset();_sourceChanges.Enqueue(new(FloorSourceChangeKindV3.Demolition,id,mark.CompanyId,mark.Cell,mark.Revision,true));return true;}
    public bool TryRemoveMark(string id,out FloorDemolitionMarkV3? mark){if(!_marks.Remove(id,out mark)||mark==null)return false;_markByCell.Remove(mark.Cell.Value);Chunk(mark.Cell.Value).RemoveMark(mark.Cell.Value);_sourceChanges.Enqueue(new(FloorSourceChangeKindV3.Demolition,id,mark.CompanyId,mark.Cell,mark.Revision,false));Changed(mark.Cell.Value);CleanupChunk(mark.Cell.Value);return true;}
    public bool TryCompleteDemolition(string id,out FloorCellStateV3? floor,out string reason){floor=null;if(!_marks.TryGetValue(id,out var mark)||mark.Status!=FloorDemolitionStatusV3.UnderDemolition||!_floors.TryGetValue(mark.Cell.Value,out floor)||floor.Revision!=mark.FloorRevision){reason="InvalidFloorDemolition";return false;}_floors.Remove(mark.Cell.Value);FloorChunkDataV3 chunk=Chunk(mark.Cell.Value);chunk.RemoveFloor(mark.Cell.Value);mark.Complete();TryRemoveMark(id,out _);MovementCostRevision++;Diagnostics.RemovalsThisTick++;Changed(mark.Cell.Value);CleanupChunk(mark.Cell.Value);reason="";return true;}
    public int DrainSourceChanges(int budget,List<FloorSourceChangeV3> output){int count=0;while(count<budget&&_sourceChanges.Count>0){output.Add(_sourceChanges.Dequeue());count++;}Diagnostics.SourceUpdatesThisTick=count;return count;}public IReadOnlyList<Vector2I> ConsumeDirtyChunks(int budget){List<Vector2I> result=new(Math.Min(budget,_dirtyChunks.Count));foreach(Vector2I c in _dirtyChunks){result.Add(c);if(result.Count>=budget)break;}foreach(var c in result)_dirtyChunks.Remove(c);return result.AsReadOnly();}
    public void ResetTickDiagnostics(){Diagnostics.BlueprintCreatesThisTick=Diagnostics.CompletionsThisTick=Diagnostics.RemovalsThisTick=Diagnostics.SourceUpdatesThisTick=Diagnostics.EventsEmittedThisTick=Diagnostics.VisualChunksUpdatedThisFrame=Diagnostics.FloorPathRequestsThisTick=0;}
    public void Clear(){_floors.Clear();_blueprints.Clear();_blueprintByCell.Clear();_marks.Clear();_markByCell.Clear();_chunks.Clear();_sourceChanges.Clear();_dirtyChunks.Clear();Revision++;MovementCostRevision++;}
}
public sealed class FloorNavigationQueryV3:IMercenaryNavigationWorldQueryV3,INavigationOccupancyRevisionV3
{
    private readonly IMercenaryNavigationWorldQueryV3 _base;private readonly FloorRegistryV3 _floors;private readonly FloorDefinitionCatalogV3 _definitions;public FloorNavigationQueryV3(IMercenaryNavigationWorldQueryV3 query,FloorRegistryV3 floors,FloorDefinitionCatalogV3 definitions){_base=query;_floors=floors;_definitions=definitions;}public long OccupancyRevision=>MercenaryNavigationRevisionPolicyV3.GetRevision(_base);public bool IsInsideWorld(Vector2I c)=>_base.IsInsideWorld(c);public bool IsWalkable(Vector2I c)=>_base.IsWalkable(c);public MercenaryNavigationCellInfoV3 GetCellInfo(Vector2I c){var info=_base.GetCellInfo(c);return new(info.IsInsideWorld,info.IsWalkable,ApplyFloor(c,info.TraversalMultiplier),info.TileType,info.BiomeKind);}public float GetTraversalMultiplier(Vector2I c)=>ApplyFloor(c,_base.GetTraversalMultiplier(c));private float ApplyFloor(Vector2I c,float value){if(_floors.TryGetFloor(new(c),out var floor)&&floor!=null&&_definitions.TryGet(floor.FloorTypeId,out var definition)&&definition!=null)value/=definition.MovementSpeedMultiplier;return value;}
}
