using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using GameplayV3.Construction;
using GameplayV3.Needs;
using GameplayV3.Session;
using GameplayV3.Stockpile;
using Godot;
using WorldV2;

namespace GameplayV3.Rooms.Runtime;

internal sealed class RoomFloodBatchV3
{
    public required RoomRebuildReasonV3 Reason;public readonly Queue<Vector2I> Seeds=new();public readonly HashSet<Vector2I> SeedSet=new();public readonly List<HashSet<Vector2I>> IndoorComponents=new();public readonly HashSet<Vector2I> CompletedCells=new();public Queue<Vector2I>? Frontier;public HashSet<Vector2I>? Visited;public bool ReachedExterior;public bool ExceededLimit;public int Processed;
}

public partial class RoomRuntimeV3:Node
{
    public const int MaxDetectedRoomCells=4096,MaxRoomFloodCellsPerTick=2048,MaxTopologyJobsAdvancedPerTick=4,MaxTopologyCommitsPerTick=4,MaxMetadataRoomsPerTick=16;
    private static readonly Vector2I[] Four={Vector2I.Up,Vector2I.Right,Vector2I.Down,Vector2I.Left};
    private RoomSessionV3? _session;private ConstructionSessionV3? _construction;private StockpileSessionV3? _stockpiles;private MercenaryNeedsSessionV3? _needs;private Rect2I _bounds;private readonly Queue<RoomTopologyChangeV3> _changes=new();private readonly HashSet<Vector2I> _dirtySeeds=new();private readonly Queue<RoomFloodBatchV3> _jobs=new();private readonly HashSet<string> _dirtyMetadata=new(StringComparer.Ordinal);private long _sequence,_lastFloorRevision,_lastStockpileRevision,_lastAssignmentRevision,_lastStructureRevision;private bool _initialized;
    public int DirtyTopologyCellCount=>_dirtySeeds.Count;public int PendingFloodJobCount=>_jobs.Count;public int DirtyMetadataRoomCount=>_dirtyMetadata.Count;public RoomSessionV3? Session=>_session;
    public void Initialize(RoomSessionV3 session,ConstructionSessionV3 construction,StockpileSessionV3 stockpiles,MercenaryNeedsSessionV3? needs,Rect2I bounds)
    {if(_initialized)return;_initialized=true;_session=session;_construction=construction;_stockpiles=stockpiles;_needs=needs;_bounds=bounds;construction.Structures.StructureRegistered+=OnStructureAdded;construction.Structures.StructureRemoved+=OnStructureRemoved;construction.Floors.ChunkChanged+=OnFloorChanged;if(needs!=null)needs.Assignments.Changed+=OnAssignmentChanged;_lastFloorRevision=construction.Floors.Revision;_lastStockpileRevision=stockpiles.Zones.Revision;_lastAssignmentRevision=needs?.Assignments.Revision??0;foreach(string id in construction.Structures.GetAllStructureIds())if(construction.Structures.TryGet(id,out var s)&&s!=null&&s.RoomBoundaryKind!=StructureRoomBoundaryKindV3.None)EnqueueBoundary(s,RoomTopologyChangeKindV3.BoundaryAdded,StructureRoomBoundaryKindV3.None,s.RoomBoundaryKind);}
    public void AttachStockpileEvents(){if(_stockpiles!=null)_stockpiles.Zones.CellsChanged+=OnStockpileCellsChanged;}
    private void OnStockpileCellsChanged(IReadOnlyList<GlobalCellCoord> cells){foreach(var cell in cells)MarkMetadataAt(cell);}
    public override void _ExitTree(){if(_stockpiles!=null)_stockpiles.Zones.CellsChanged-=OnStockpileCellsChanged;if(_construction!=null){_construction.Structures.StructureRegistered-=OnStructureAdded;_construction.Structures.StructureRemoved-=OnStructureRemoved;_construction.Floors.ChunkChanged-=OnFloorChanged;}if(_needs!=null)_needs.Assignments.Changed-=OnAssignmentChanged;if(!IsInsideTree())Free();}
    private void OnStructureAdded(StructureStateV3 s){if(s.RoomBoundaryKind!=StructureRoomBoundaryKindV3.None)EnqueueBoundary(s,RoomTopologyChangeKindV3.BoundaryAdded,StructureRoomBoundaryKindV3.None,s.RoomBoundaryKind);else MarkMetadataAt(s.AnchorCell);}
    private void OnStructureRemoved(StructureStateV3 s){if(s.RoomBoundaryKind!=StructureRoomBoundaryKindV3.None)EnqueueBoundary(s,RoomTopologyChangeKindV3.BoundaryRemoved,s.RoomBoundaryKind,StructureRoomBoundaryKindV3.None);else MarkMetadataAt(s.AnchorCell);}
    private void EnqueueBoundary(StructureStateV3 s,RoomTopologyChangeKindV3 kind,StructureRoomBoundaryKindV3 oldKind,StructureRoomBoundaryKindV3 newKind){foreach(var c in s.OccupiedCells){_changes.Enqueue(new($"roomchg_{++_sequence}",c,kind,oldKind,newKind,s.StructureId,_sequence));AddSeed(c.Value);foreach(var d in Four)AddSeed(c.Value+d);}}
    private void AddSeed(Vector2I c){if(_bounds.HasPoint(c))_dirtySeeds.Add(c);}
    private void OnFloorChanged(Vector2I chunk,int count,long revision){if(_session==null)return;foreach(var room in _session.Registry.EnumerateRoomsInChunk(chunk))_dirtyMetadata.Add(room.RoomId);_lastFloorRevision=revision;}
    private void OnAssignmentChanged(){if(_session==null)return;foreach(string id in BedRoomIds())_dirtyMetadata.Add(id);_lastAssignmentRevision=_needs?.Assignments.Revision??0;}
    private IEnumerable<string> BedRoomIds(){if(_construction==null||_session==null)yield break;foreach(string id in _construction.Structures.GetAllStructureIds())if(_construction.Structures.TryGet(id,out var s)&&s!=null&&_construction.Definitions.TryGetDefinition(s.DefinitionId,out var d)&&d?.RestFacility!=null&&_session.Registry.TryGetRoom(s.AnchorCell,out var room)&&room!=null)yield return room.RoomId;}
    private void MarkMetadataAt(GlobalCellCoord cell){if(_session?.Registry.TryGetRoom(cell,out var room)==true&&room!=null)_dirtyMetadata.Add(room.RoomId);}
    public override void _PhysicsProcess(double delta)
    {if(_session==null||!GameplaySessionV3.IsCurrentRoomSession(_session))return;var sw=Stopwatch.StartNew();var diag=_session.Registry.Diagnostics;diag.FloodCellsProcessedThisTick=diag.TopologyCommitsThisTick=diag.MetadataCommitsThisTick=0;if(_stockpiles!=null&&_stockpiles.Zones.Revision!=_lastStockpileRevision){_lastStockpileRevision=_stockpiles.Zones.Revision;MarkAllRoomsMetadataDirty();}if(_construction!=null&&_construction.Floors.Revision!=_lastFloorRevision)_lastFloorRevision=_construction.Floors.Revision;if(_needs!=null&&_needs.Assignments.Revision!=_lastAssignmentRevision)OnAssignmentChanged();CreateFloodBatch();AdvanceFloodJobs();ProcessMetadata();sw.Stop();diag.RuntimeTickMs=sw.Elapsed.TotalMilliseconds;diag.MaxRoomRuntimeTickMs=Math.Max(diag.MaxRoomRuntimeTickMs,diag.RuntimeTickMs);}
    private void MarkAllRoomsMetadataDirty(){if(_session==null)return;HashSet<string> seen=new(StringComparer.Ordinal);foreach(Vector2I chunk in _session.Registry.DirtyVisualChunks)foreach(var room in _session.Registry.EnumerateRoomsInChunk(chunk))if(seen.Add(room.RoomId))_dirtyMetadata.Add(room.RoomId);if(seen.Count==0){foreach(string id in _construction!.Structures.GetAllStructureIds())if(_construction.Structures.TryGet(id,out var s)&&s!=null&&_session.Registry.TryGetRoom(s.AnchorCell,out var room)&&room!=null)_dirtyMetadata.Add(room.RoomId);}}
    private void CreateFloodBatch(){if(_dirtySeeds.Count==0||_jobs.Count>=MaxTopologyJobsAdvancedPerTick)return;var batch=new RoomFloodBatchV3{Reason=_changes.Count>0&&_changes.Peek().Kind==RoomTopologyChangeKindV3.BoundaryRemoved?RoomRebuildReasonV3.BoundaryRemoved:RoomRebuildReasonV3.BoundaryAdded};foreach(Vector2I seed in _dirtySeeds.OrderBy(c=>c.Y).ThenBy(c=>c.X)){batch.Seeds.Enqueue(seed);batch.SeedSet.Add(seed);}_dirtySeeds.Clear();_changes.Clear();_jobs.Enqueue(batch);}
    private void AdvanceFloodJobs(){if(_session==null||_construction==null)return;int budget=MaxRoomFloodCellsPerTick,jobs=0;while(budget>0&&jobs++<MaxTopologyJobsAdvancedPerTick&&_jobs.Count>0){RoomFloodBatchV3 job=_jobs.Peek();while(budget>0){if(job.Frontier==null){while(job.Seeds.Count>0&&job.CompletedCells.Contains(job.Seeds.Peek()))job.Seeds.Dequeue();if(job.Seeds.Count==0){Commit(job);_jobs.Dequeue();break;}Vector2I seed=job.Seeds.Dequeue();if(IsBoundary(seed)||!_bounds.HasPoint(seed)){job.CompletedCells.Add(seed);continue;}job.Frontier=new();job.Visited=new();job.Frontier.Enqueue(seed);job.Visited.Add(seed);job.ReachedExterior=false;job.ExceededLimit=false;}if(job.Frontier.Count==0){FinishComponent(job);continue;}Vector2I cell=job.Frontier.Dequeue();job.Processed++;budget--;_session.Registry.Diagnostics.FloodCellsProcessedThisTick++;if(IsWorldEdge(cell))job.ReachedExterior=true;foreach(Vector2I d in Four){Vector2I next=cell+d;if(!_bounds.HasPoint(next)){job.ReachedExterior=true;continue;}if(IsBoundary(next)||job.Visited!.Contains(next))continue;job.Visited.Add(next);job.Frontier.Enqueue(next);if(job.Visited.Count>MaxDetectedRoomCells){job.ExceededLimit=true;job.Frontier.Clear();break;}}}if(_jobs.Count>0&&ReferenceEquals(_jobs.Peek(),job))break;}_session.Registry.Diagnostics.MaxFloodCellsProcessedInTick=Math.Max(_session.Registry.Diagnostics.MaxFloodCellsProcessedInTick,_session.Registry.Diagnostics.FloodCellsProcessedThisTick);}
    private void FinishComponent(RoomFloodBatchV3 job){var cells=job.Visited!;foreach(var c in cells)job.CompletedCells.Add(c);if(job.ExceededLimit){_session!.Registry.Diagnostics.TooLargeCandidateCount++;_session.Registry.Diagnostics.FloodLimitHitCount++;}else if(job.ReachedExterior)_session!.Registry.Diagnostics.OutdoorCandidateCount++;else if(cells.Count>0)job.IndoorComponents.Add(cells);job.Frontier=null;job.Visited=null;}
    private bool IsBoundary(Vector2I cell)=>_construction!.Structures.TryGetStructureAtCell(new(cell),out var s)&&s?.RoomBoundaryKind is StructureRoomBoundaryKindV3.Solid or StructureRoomBoundaryKindV3.Door;
    private bool IsWorldEdge(Vector2I c)=>c.X==_bounds.Position.X||c.Y==_bounds.Position.Y||c.X==_bounds.End.X-1||c.Y==_bounds.End.Y-1;
    private void Commit(RoomFloodBatchV3 job){if(_session==null||_construction==null)return;var registry=_session.Registry;HashSet<Vector2I> all=new();foreach(var c in job.IndoorComponents)all.UnionWith(c);var old=registry.GetOverlapping(job.CompletedCells);HashSet<string> remove=old.Select(r=>r.RoomId).ToHashSet(StringComparer.Ordinal);List<RoomTopologyStateV3> rooms=new();HashSet<string> used=new(StringComparer.Ordinal);foreach(var component in job.IndoorComponents.OrderByDescending(c=>c.Count).ThenBy(c=>c.Min(v=>v.Y)).ThenBy(c=>c.Min(v=>v.X))){var overlap=old.Select(r=>(Room:r,Count:r.Cells.Count(c=>component.Contains(c.Value)))).Where(x=>x.Count>0&&!used.Contains(x.Room.RoomId)).OrderByDescending(x=>x.Count).ThenBy(x=>x.Room.CreatedSequence).ThenBy(x=>x.Room.RoomId,StringComparer.Ordinal).FirstOrDefault();string id=overlap.Room?.RoomId??RoomIdFactoryV3.Create();long created=overlap.Room?.CreatedSequence??++_sequence;used.Add(id);rooms.Add(new(id,created,component.Select(c=>new GlobalCellCoord(c)),Array.Empty<string>(),Array.Empty<string>(),(overlap.Room?.TopologyRevision??0)+1,job.Reason));}registry.Commit(rooms,remove,Array.Empty<RoomPortalStateV3>(),job.Reason);RebuildPortals();foreach(var room in rooms)_dirtyMetadata.Add(room.RoomId);registry.Diagnostics.TopologyCommitsThisTick++;}
    private void RebuildPortals(){if(_session==null||_construction==null)return;List<RoomPortalStateV3> portals=new();foreach(string id in _construction.Structures.GetAllStructureIds()){if(!_construction.Structures.TryGet(id,out var door)||door?.RoomBoundaryKind!=StructureRoomBoundaryKindV3.Door)continue;Vector2I a,b;if(door.Orientation is StructureOrientationV3.Deg0 or StructureOrientationV3.Deg180){a=door.AnchorCell.Value+Vector2I.Left;b=door.AnchorCell.Value+Vector2I.Right;}else{a=door.AnchorCell.Value+Vector2I.Up;b=door.AnchorCell.Value+Vector2I.Down;}_session.Registry.TryGetRoomId(new(a),out string roomA);_session.Registry.TryGetRoomId(new(b),out string roomB);string portalId=$"portal_{door.StructureId}";portals.Add(new(portalId,door.StructureId,door.AnchorCell,string.IsNullOrEmpty(roomA)?null:roomA,string.IsNullOrEmpty(roomB)?null:roomB,string.IsNullOrEmpty(roomA),string.IsNullOrEmpty(roomB),_session.Registry.Revision+1));}_session.Registry.ReplacePortals(portals);}
    private void ProcessMetadata(){if(_session==null||_construction==null||_stockpiles==null)return;int budget=MaxMetadataRoomsPerTick;foreach(string id in _dirtyMetadata.OrderBy(x=>x,StringComparer.Ordinal).Take(budget).ToList()){_dirtyMetadata.Remove(id);if(!_session.Registry.TryGetRoomById(id,out var room)||room==null)continue;int beds=0,assigned=0,stock=0,floors=0,wood=0,doors=room.DoorStructureIds.Count;Dictionary<string,int> companies=new(StringComparer.Ordinal);HashSet<string> countedStructures=new(StringComparer.Ordinal);foreach(var cell in room.Cells){if(_construction.Floors.TryGetFloor(cell,out var floor)&&floor!=null){floors++;if(floor.FloorTypeId==FloorDefinitionCatalogV3.WoodenFloorId)wood++;Add(floor.CompanyId);}if(_stockpiles.Zones.TryGetZoneAtCell(cell,out var zone)&&zone!=null){stock++;Add(zone.CompanyId);}if(_construction.Structures.TryGetStructureAtCell(cell,out var s)&&s!=null&&countedStructures.Add(s.StructureId)){Add(s.CompanyId);if(_construction.Definitions.TryGetDefinition(s.DefinitionId,out var d)&&d?.RestFacility!=null){beds+=d.RestFacility.Slots.Count;foreach(var slot in RestFacilitySlotResolverV3.Resolve(s,d))if(_needs?.Assignments.IsSlotAssigned(slot.RestSlotId)==true)assigned++;}}}var snapshot=new RoomFeatureSnapshotV3(beds,assigned,stock,floors,wood,doors,countedStructures.Count,new ReadOnlyDictionary<string,int>(companies));var role=RoomRoleClassifierV3.Classify(snapshot);var quality=RoomQualityEvaluatorV3.Evaluate(room.CellCount,snapshot);var ordered=companies.OrderByDescending(x=>x.Value).ThenBy(x=>x.Key,StringComparer.Ordinal).ToList();RoomAffiliationKindV3 kind=ordered.Count==0?RoomAffiliationKindV3.Unowned:ordered.Count==1?RoomAffiliationKindV3.SingleCompany:RoomAffiliationKindV3.Mixed;var affiliation=new RoomAffiliationSnapshotV3(kind,ordered.FirstOrDefault().Key??string.Empty,new ReadOnlyDictionary<string,int>(companies),_session.Registry.MetadataRevision+1);_session.Registry.SetMetadata(new(id,snapshot,role,quality,affiliation,_session.Registry.MetadataRevision+1));_session.Registry.Diagnostics.MetadataCommitsThisTick++;void Add(string company){if(!string.IsNullOrWhiteSpace(company))companies[company]=companies.GetValueOrDefault(company)+1;}}}
}
