using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Godot;
using WorldV2;

namespace GameplayV3.Bases;

public static class BaseAreaSelfCheckV3
{
    public static string LastPerformanceSummary{get;private set;}=string.Empty;
    public static bool TryValidate(out string reason)
    {
        try
        {
            Rect2I bounds=new(-256,-256,1024,1024);
            BaseAreaSessionV3 session=new(1);session.SetWorldBounds(bounds);
            AddBed(session,"bed_a","company_a",new(0,0));session.RebuildCompanyNow("company_a");
            Require(session.Areas.Count==1,"Completed bed did not create one base.");BaseAreaV3 first=session.Areas.GetForCompany("company_a")[0];Require(BaseAreaIdFactoryV3.IsValid(first.BaseAreaId),"BaseAreaId format invalid.");Require(first.Contains(new(0,0))&&first.CenterCell.Value==new Vector2I(0,0),"Bed footprint or center missing.");string firstId=first.BaseAreaId;

            AddAttachment(session,"wall_near","company_a",BaseSpatialSourceKindV3.Wall,new(3,0));AddAttachment(session,"door_near","company_a",BaseSpatialSourceKindV3.Door,new(2,1));AddAttachment(session,"floor_near","company_a",BaseSpatialSourceKindV3.Floor,new(1,2));AddAttachment(session,"wall_far","company_a",BaseSpatialSourceKindV3.Wall,new(80,80));session.RebuildCompanyNow("company_a");BaseAreaV3 expanded=session.Areas.GetForCompany("company_a")[0];Require(expanded.BaseAreaId==firstId&&expanded.AnchorCount==1&&expanded.MemberSourceIds.Contains("wall_near")&&!expanded.MemberSourceIds.Contains("wall_far"),"Attachment affiliation or ID continuity failed.");

            BaseAreaSessionV3 thresholds=new(2);thresholds.SetWorldBounds(bounds);AddAreaSource(thresholds,"stock_1","company_a",BaseSpatialSourceKindV3.StockpileZone,Line(0,0,1),4);AddAreaSource(thresholds,"stock_3","company_a",BaseSpatialSourceKindV3.StockpileZone,Line(20,0,3),4);AddAreaSource(thresholds,"stock_4","company_a",BaseSpatialSourceKindV3.StockpileZone,Line(40,0,4),4);AddAreaSource(thresholds,"stock_disconnected","company_a",BaseSpatialSourceKindV3.StockpileZone,new[]{Cell(60,0),Cell(62,0),Cell(64,0),Cell(66,0)},4);thresholds.RebuildCompanyNow("company_a");Require(thresholds.Areas.Count==1&&thresholds.Sources.TryGet("stock_4",out var stock4)&&stock4?.IsAnchor==true,"Stockpile threshold or connectivity failed.");
            BaseAreaSessionV3 farms=new(3);farms.SetWorldBounds(bounds);AddAreaSource(farms,"farm_8","company_a",BaseSpatialSourceKindV3.FarmPlot,RectCells(0,20,4,2),3);AddAreaSource(farms,"farm_9","company_a",BaseSpatialSourceKindV3.FarmPlot,RectCells(20,20,3,3),3);AddAreaSource(farms,"farm_disconnected","company_a",BaseSpatialSourceKindV3.FarmPlot,Enumerable.Range(0,9).Select(i=>Cell(50+i*2,20)).ToArray(),3);farms.RebuildCompanyNow("company_a");Require(farms.Areas.Count==1&&farms.Sources.TryGet("farm_9",out var farm9)&&farm9?.IsAnchor==true,"Farm threshold or connectivity failed.");

            BaseAreaSessionV3 topology=new(4);topology.SetWorldBounds(bounds);AddBed(topology,"bed_left","company_a",new(0,0));AddBed(topology,"bed_right","company_a",new(16,0));topology.RebuildCompanyNow("company_a");Require(topology.Areas.Count==2,"Distant anchors did not create two bases.");string survivor=topology.Areas.GetForCompany("company_a")[0].BaseAreaId;AddAttachment(topology,"connector_only","company_a",BaseSpatialSourceKindV3.Floor,new(8,0));topology.RebuildCompanyNow("company_a");Require(topology.Areas.Count==2,"Attachment incorrectly merged bases.");AddBed(topology,"bed_bridge","company_a",new(8,0));topology.RebuildCompanyNow("company_a");Require(topology.Areas.Count==1&&topology.Areas.GetForCompany("company_a")[0].BaseAreaId==survivor,"Anchor merge or survivor policy failed.");topology.RemoveSource("bed_bridge");topology.RebuildCompanyNow("company_a");Require(topology.Areas.Count==2&&topology.Areas.GetForCompany("company_a").Any(a=>a.BaseAreaId==survivor),"Anchor removal split or ID continuity failed.");

            BaseAreaSessionV3 companies=new(5);companies.SetWorldBounds(bounds);AddBed(companies,"a_bed","company_a",new(5,5));AddBed(companies,"b_bed","company_b",new(5,5));companies.RebuildCompanyNow("company_a");companies.RebuildCompanyNow("company_b");Require(companies.Areas.Count==2&&companies.Areas.GetAtCell(Cell(5,5)).Count==2&&companies.Areas.TryGetAtCell("company_a",Cell(5,5),out _)&&companies.Areas.TryGetAtCell("company_b",Cell(5,5),out _),"Company isolation or overlapping cell query failed.");

            var room=new GameplayV3.Rooms.RoomTopologyStateV3("room_base",1,RectCells(-1,-1,12,4),Array.Empty<string>(),Array.Empty<string>(),1,GameplayV3.Rooms.RoomRebuildReasonV3.InitialScan);session.UpdateRoomSnapshot(new[]{room});session.RebuildCompanyNow("company_a");Require(session.Areas.GetForCompany("company_a")[0].RoomIds.Contains("room_base")&&session.Areas.GetForCompany("company_a")[0].Contains(new(10,2)),"Room metadata or room-cell influence failed.");long doorNeutralRevision=session.Areas.GetForCompany("company_a")[0].Revision;Require(session.Areas.GetForCompany("company_a")[0].Revision==doorNeutralRevision,"Door state changed base revision.");
            var conflictRoom=new GameplayV3.Rooms.RoomTopologyStateV3("room_conflict",2,RectCells(4,4,3,3),Array.Empty<string>(),Array.Empty<string>(),1,GameplayV3.Rooms.RoomRebuildReasonV3.InitialScan);companies.UpdateRoomSnapshot(new[]{conflictRoom});companies.RebuildCompanyNow("company_a");companies.RebuildCompanyNow("company_b");Require(companies.Areas.GetForCompany("company_a")[0].RoomCount==0&&companies.Areas.GetForCompany("company_b")[0].RoomCount==0&&companies.Diagnostics.ConflictRoomCount>0,"Conflicting room was assigned to a base.");

            topology.RemoveSource("bed_left");topology.RemoveSource("bed_right");topology.RebuildCompanyNow("company_a");Require(topology.Areas.Count==0&&topology.RetiredBaseAreaIds.Count>=2,"Last-anchor removal did not remove and retire bases.");Require(topology.Diagnostics.FullWorldBaseScanCount==0&&topology.Diagnostics.FullCompanySourceScanCount==0&&topology.Diagnostics.AnchorCartesianPairCount==0&&topology.Diagnostics.PerBaseNodeCount==0&&topology.Diagnostics.PerBaseProcessCount==0,"Forbidden architecture counters changed.");

            BaseAreaSessionV3 staged=new(6);staged.SetWorldBounds(bounds);AddBed(staged,"staged_bed","company_a",new(0,0));for(int i=0;i<3000;i++)AddAttachment(staged,$"staged_floor_{i}","company_a",BaseSpatialSourceKindV3.Floor,new(i%100,i/100));staged.RebuildDirtyCompanies(1);Require(staged.Areas.Count==0&&staged.ActiveRebuildCount==1,"Staged rebuild exposed a partial snapshot.");AddAttachment(staged,"staged_newer","company_a",BaseSpatialSourceKindV3.Floor,new(1,1));staged.RebuildCompanyNow("company_a");Require(staged.Areas.Count==1&&staged.Diagnostics.StaleRebuildCount>0,"Stale staged rebuild was not superseded.");

            RunBoundedPerformanceFixture();reason=string.Empty;return true;
        }
        catch(Exception exception){reason=exception.Message;return false;}
    }

    private static void RunBoundedPerformanceFixture()
    {
        Stopwatch watch=Stopwatch.StartNew();BaseAreaSessionV3 fixture=new(99);fixture.SetWorldBounds(new(0,0,5000,5000));const int anchors=1000,attachments=20000;for(int i=0;i<anchors;i++){Vector2I cell=new((i%50)*20,(i/50)*20);AddBed(fixture,$"bed_{i}","company_perf",cell);}for(int i=0;i<attachments;i++){int owner=i%anchors;Vector2I anchor=new((owner%50)*20,(owner/50)*20);AddAttachment(fixture,$"floor_{i}","company_perf",BaseSpatialSourceKindV3.Floor,anchor+new Vector2I(i%3-1,(i/3)%3-1));}fixture.RebuildCompanyNow("company_perf");watch.Stop();Require(fixture.Sources.Count==21000,"Performance fixture source count mismatch.");Require(fixture.Diagnostics.AnchorCartesianPairCount==0&&fixture.Diagnostics.FullWorldBaseScanCount==0&&fixture.Diagnostics.FullCompanySourceScanCount==0,"Performance fixture used a forbidden scan.");LastPerformanceSummary=$"sources={fixture.Sources.Count} bases={fixture.Areas.Count} chunks={fixture.Sources.ChunkCount} pairChecks={fixture.Diagnostics.AnchorPairChecksThisTick} attachmentChecks={fixture.Diagnostics.AttachmentChecksThisTick} cellWrites={fixture.Diagnostics.CellIndexWritesThisTick} elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms";
    }

    public static string RunLargePerformanceFixtures()
    {
        Stopwatch watch=Stopwatch.StartNew();BaseAreaSessionV3 large=new(100);large.SetWorldBounds(new(0,0,10000,10000));const int anchors=5000,attachments=50000;for(int i=0;i<anchors;i++){Vector2I cell=new((i%100)*20,(i/100)*20);AddBed(large,$"large_bed_{i}","company_large",cell);}for(int i=0;i<attachments;i++){int owner=i%anchors;Vector2I anchor=new((owner%100)*20,(owner/100)*20);AddAttachment(large,$"large_floor_{i}","company_large",BaseSpatialSourceKindV3.Floor,anchor+new Vector2I(i%3-1,(i/3)%3-1));}large.RebuildCompanyNow("company_large");Require(large.Sources.Count==55000&&large.Areas.Count==5000,"Large 5k/50k fixture count mismatch.");Require(large.Diagnostics.FullWorldBaseScanCount==0&&large.Diagnostics.AnchorCartesianPairCount==0&&large.Diagnostics.PerBaseNodeCount==0,"Large fixture used forbidden architecture.");
        BaseAreaSessionV3 churn=new(101);churn.SetWorldBounds(new(-100,-100,500,500));HashSet<string> issued=new(StringComparer.Ordinal);for(int i=0;i<1000;i++){AddBed(churn,"left","company",new(0,0));AddBed(churn,"right","company",new(16,0));churn.RebuildCompanyNow("company");AddBed(churn,$"bridge_{i}","company",new(8,0));churn.RebuildCompanyNow("company");foreach(var area in churn.Areas.GetAll())Require(issued.Add(area.BaseAreaId)||area.AnchorCount==3,"Duplicate live BaseAreaId issued during churn.");churn.RemoveSource($"bridge_{i}");churn.RebuildCompanyNow("company");churn.RemoveSource("left");churn.RemoveSource("right");churn.RebuildCompanyNow("company");}Require(churn.Areas.Count==0&&churn.RetiredBaseAreaIds.Count>=2000,"Merge/split churn leaked live areas or reused retired ids.");watch.Stop();return $"large sources={large.Sources.Count} bases={large.Areas.Count} chunks={large.Sources.ChunkCount} slices={large.Diagnostics.RebuildSliceCount} pairChecks={large.Diagnostics.AnchorPairChecksThisTick} attachmentChecks={large.Diagnostics.AttachmentChecksThisTick} cellWrites={large.Diagnostics.CellIndexWritesThisTick}; churn=1000 retired={churn.RetiredBaseAreaIds.Count}; elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms";
    }

    private static void AddBed(BaseAreaSessionV3 session,string id,string company,Vector2I cell)=>session.UpsertSource(new(id,company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,new[]{new GlobalCellCoord(cell)},4,session.NextSourceCreationOrder(),1));
    private static void AddAttachment(BaseAreaSessionV3 session,string id,string company,BaseSpatialSourceKindV3 kind,Vector2I cell)=>session.UpsertSource(new(id,company,kind,BaseSpatialSourceRoleV3.Attachment,new[]{new GlobalCellCoord(cell)},0,session.NextSourceCreationOrder(),1));
    private static void AddAreaSource(BaseAreaSessionV3 session,string id,string company,BaseSpatialSourceKindV3 kind,IReadOnlyCollection<GlobalCellCoord> cells,int weight){BaseSpatialSourceRoleV3 role=kind==BaseSpatialSourceKindV3.StockpileZone?BaseSpatialSourceCatalogV3.ClassifyStockpile(cells):BaseSpatialSourceCatalogV3.ClassifyFarm(cells);session.UpsertSource(new(id,company,kind,role,cells,role==BaseSpatialSourceRoleV3.Anchor?weight:0,session.NextSourceCreationOrder(),1));}
    private static GlobalCellCoord Cell(int x,int y)=>new(new Vector2I(x,y));private static GlobalCellCoord[] Line(int x,int y,int count)=>Enumerable.Range(0,count).Select(i=>Cell(x+i,y)).ToArray();private static GlobalCellCoord[] RectCells(int x,int y,int width,int height)=>Enumerable.Range(0,height).SelectMany(dy=>Enumerable.Range(0,width).Select(dx=>Cell(x+dx,y+dy))).ToArray();
    private static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}
}
