using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Godot;
using GameplayV3.Rooms;
using WorldV2;

namespace GameplayV3.Bases;

public static class FacilityAffiliationSelfCheckV3
{
    public static string LastPerformanceSummary{get;private set;}="not run";
    public static bool TryValidate(out string reason)
    {
        try
        {
            Rect2I bounds=new(-256,-256,1024,1024);BaseAreaSessionV3 bases=new(10);bases.SetWorldBounds(bounds);using FacilityAffiliationSessionV3 facilities=new(10,bases);
            AddBed(bases,"bed_a","company_a",new(0,0));AddSource(bases,"wall_near","company_a",BaseSpatialSourceKindV3.Wall,BaseSpatialSourceRoleV3.Connector,new(2,0));AddSource(bases,"door_near","company_a",BaseSpatialSourceKindV3.Door,BaseSpatialSourceRoleV3.Connector,new(3,0));AddSource(bases,"floor_near","company_a",BaseSpatialSourceKindV3.Floor,BaseSpatialSourceRoleV3.Connector,new(1,2));AddSource(bases,"wall_far","company_a",BaseSpatialSourceKindV3.Wall,BaseSpatialSourceRoleV3.Connector,new(100,0));facilities.ProcessUntilIdle();Require(facilities.TryGetFacility("bed_a",out var pending)&&pending?.AffiliationState==FacilityAffiliationStateV3.PendingBaseRebuild,"Dirty source did not expose PendingBaseRebuild.");bases.RebuildCompanyNow("company_a");facilities.ProcessUntilIdle();Require(Affiliated(facilities,"bed_a")&&Affiliated(facilities,"wall_near")&&Affiliated(facilities,"door_near")&&Affiliated(facilities,"floor_near"),"Bed or nearby attachment affiliation failed.");Require(facilities.TryGetFacility("wall_far",out var far)&&far?.AffiliationState==FacilityAffiliationStateV3.Unaffiliated,"Distant wall was not unaffiliated.");BaseAreaV3 first=bases.Areas.GetForCompany("company_a").Single();Require(facilities.IsCellInsideBaseCore(first.BaseAreaId,new(0,0))&&facilities.IsCellInsideActivityRange(first.BaseAreaId,new(48,0))&&!facilities.IsCellInsideActivityRange(first.BaseAreaId,new(60,0)),"Core or activity range query failed.");

            AddArea(bases,"stock_small","company_a",BaseSpatialSourceKindV3.StockpileZone,Line(4,2,3),3);AddArea(bases,"stock_anchor","company_a",BaseSpatialSourceKindV3.StockpileZone,Line(20,0,4),3);AddArea(bases,"farm_small","company_a",BaseSpatialSourceKindV3.FarmPlot,Rect(4,4,4,2),2);AddArea(bases,"farm_anchor","company_a",BaseSpatialSourceKindV3.FarmPlot,Rect(40,0,3,3),2);bases.RebuildCompanyNow("company_a");facilities.ProcessUntilIdle();Require(Affiliated(facilities,"stock_small")&&Affiliated(facilities,"farm_small")&&Affiliated(facilities,"stock_anchor")&&Affiliated(facilities,"farm_anchor"),"Stockpile/farm membership and affiliation diverged.");

            BaseAreaSessionV3 topology=new(11);topology.SetWorldBounds(bounds);using FacilityAffiliationSessionV3 derived=new(11,topology);AddBed(topology,"left","company_a",new(0,0));AddBed(topology,"right","company_a",new(80,0));AddSource(topology,"left_wall","company_a",BaseSpatialSourceKindV3.Wall,BaseSpatialSourceRoleV3.Connector,new(1,0));AddSource(topology,"right_wall","company_a",BaseSpatialSourceKindV3.Wall,BaseSpatialSourceRoleV3.Connector,new(79,0));topology.RebuildCompanyNow("company_a");derived.ProcessUntilIdle();Require(topology.Areas.Count==2,"Two-base setup failed.");Require(derived.GetBaseAreasWhoseActivityRangeContains("company_a",new(40,0)).Count==2,"Overlapping activity query did not return both bases.");Require(derived.TryGetNearestBaseAreaInActivityRange("company_a",new(40,0),out var deterministic)&&deterministic==topology.Areas.GetForCompany("company_a")[0],"Overlapping activity range order was not deterministic.");

            string[] bridgeIds=Enumerable.Range(1,9).Select(i=>$"mid_{i}").ToArray();for(int i=0;i<bridgeIds.Length;i++)AddBed(topology,bridgeIds[i],"company_a",new((i+1)*8,0));string survivor=topology.Areas.GetForCompany("company_a")[0].BaseAreaId;int rightEvents=0;derived.FacilityAffiliationChanged+=e=>{if(e.FacilityKey=="right_wall")rightEvents++;};topology.RebuildCompanyNow("company_a");derived.ProcessUntilIdle();Require(topology.Areas.Count==1&&topology.Areas.GetForCompany("company_a")[0].BaseAreaId==survivor,"Merge survivor setup failed.");Require(derived.TryGetFacility("right_wall",out var merged)&&merged?.BaseAreaId==survivor&&rightEvents==1,"Merge remap or event coalescing failed.");

            foreach(string id in bridgeIds)topology.RemoveSource(id);topology.RebuildCompanyNow("company_a");derived.ProcessUntilIdle();Require(topology.Areas.Count==2,"Split did not restore two bases.");Require(derived.TryGetFacility("left_wall",out var splitLeft)&&derived.TryGetFacility("right_wall",out var splitRight)&&splitLeft?.BaseAreaId!=splitRight?.BaseAreaId,"Split affiliation ignored source membership.");topology.RemoveSource("left");topology.RemoveSource("right");topology.RebuildCompanyNow("company_a");derived.ProcessUntilIdle();Require(topology.Areas.Count==0&&derived.TryGetFacility("left_wall",out var removedLeft)&&removedLeft?.AffiliationState==FacilityAffiliationStateV3.Unaffiliated&&!derived.TryGetActivityRange(splitLeft!.BaseAreaId!,out _),"Base removal left stale affiliation or range.");

            BaseAreaSessionV3 isolation=new(12);isolation.SetWorldBounds(bounds);using FacilityAffiliationSessionV3 isolated=new(12,isolation);AddBed(isolation,"a_bed","company_a",new(10,10));AddBed(isolation,"b_bed","company_b",new(10,10));isolation.RebuildCompanyNow("company_a");isolation.RebuildCompanyNow("company_b");isolated.ProcessUntilIdle();Require(isolated.GetBaseAreasWhoseActivityRangeContains("company_a",new(10,10)).Count==1&&isolated.GetBaseAreasWhoseActivityRangeContains("company_b",new(10,10)).Count==1,"Company activity range isolation failed.");RoomTopologyStateV3 conflictRoom=new("room_conflict",1,new[]{new GlobalCellCoord(10,10)},Array.Empty<string>(),Array.Empty<string>(),1,RoomRebuildReasonV3.InitialScan);isolation.UpdateRoomSnapshot(new[]{conflictRoom});isolation.RebuildCompanyNow("company_a");isolation.RebuildCompanyNow("company_b");isolated.ProcessUntilIdle();Require(isolated.TryGetFacility("room_conflict",out var room)&&room?.AffiliationState==FacilityAffiliationStateV3.Ambiguous,"Room conflict was not ambiguous.");

            isolated.Dispose();BaseAreaSessionV3 emptyBases=new(13);using FacilityAffiliationSessionV3 replacement=new(13,emptyBases);Require(replacement.Count==0&&replacement.ActivityRangeCount==0&&replacement.DirtyFacilityCount==0,"New-session affiliation state was not empty.");AddSource(emptyBases,"orphan_wall","company_z",BaseSpatialSourceKindV3.Wall,BaseSpatialSourceRoleV3.Connector,new(0,0));replacement.ProcessUntilIdle();Require(replacement.TryGetFacility("orphan_wall",out var orphanPending)&&orphanPending?.AffiliationState==FacilityAffiliationStateV3.PendingBaseRebuild,"Orphan source did not enter pending state.");emptyBases.RebuildCompanyNow("company_z");replacement.ProcessUntilIdle();Require(replacement.TryGetFacility("orphan_wall",out var orphan)&&orphan?.AffiliationState==FacilityAffiliationStateV3.Unaffiliated,"Empty rebuild did not resolve pending affiliation.");reason=string.Empty;return true;
        }
        catch(Exception exception){reason=exception.Message;return false;}
    }

    public static string RunPerformanceFixture()
    {
        Stopwatch watch=Stopwatch.StartNew();BaseAreaSessionV3 bases=new(20);bases.SetWorldBounds(new(0,0,40000,40000));using FacilityAffiliationSessionV3 facilities=new(20,bases);const int companies=4,baseCount=1000,facilityCount=20000;for(int i=0;i<baseCount;i++){string company=$"company_{i%companies}";Vector2I cell=new((i/companies%50)*128,(i/companies/50)*128+(i%companies)*8192);AddBed(bases,$"perf_bed_{i}",company,cell);}for(int i=baseCount;i<facilityCount;i++){int owner=(i-baseCount)%baseCount;string company=$"company_{owner%companies}";Vector2I anchor=new((owner/companies%50)*128,(owner/companies/50)*128+(owner%companies)*8192);AddSource(bases,$"perf_facility_{i}",company,BaseSpatialSourceKindV3.Floor,BaseSpatialSourceRoleV3.Attachment,anchor+new Vector2I(i%3-1,(i/3)%3-1));}for(int c=0;c<companies;c++)bases.RebuildCompanyNow($"company_{c}");facilities.ProcessUntilIdle();Require(bases.Areas.Count==baseCount&&facilities.Count==facilityCount&&facilities.ActivityRangeCount==baseCount,"Performance fixture counts mismatch.");int hits=0;for(int i=0;i<100000;i++){int owner=i%baseCount;string company=$"company_{owner%companies}";Vector2I cell=new((owner/companies%50)*128,(owner/companies/50)*128+(owner%companies)*8192);if(facilities.TryGetNearestBaseAreaInActivityRange(company,new(cell),out _))hits++;}Require(hits==100000,"Performance activity queries missed indexed bases.");var d=facilities.Diagnostics;Require(d.FullWorldFacilityScanCount==0&&d.FullWorldActivityCellBuildCount==0&&d.PerFacilityNodeCount==0&&d.PerBaseActivityNodeCount==0&&d.ActivityRangeTriggeredChunkGenerationCount==0,"Performance fixture used forbidden architecture.");watch.Stop();LastPerformanceSummary=$"companies={companies} bases={baseCount} facilities={facilityCount} queries=100000 candidates={d.ActivityChunkCandidateCount} chunksIndexed={bases.Areas.ChunkIndexCount} elapsed={watch.Elapsed.TotalMilliseconds:0.0}ms";return LastPerformanceSummary;
    }

    private static bool Affiliated(FacilityAffiliationSessionV3 session,string id)=>session.TryGetFacility(id,out var value)&&value?.AffiliationState==FacilityAffiliationStateV3.Affiliated&&!string.IsNullOrEmpty(value.BaseAreaId);
    private static void AddBed(BaseAreaSessionV3 bases,string id,string company,Vector2I cell)=>AddSource(bases,id,company,BaseSpatialSourceKindV3.Bed,BaseSpatialSourceRoleV3.Anchor,cell,4);
    private static void AddSource(BaseAreaSessionV3 bases,string id,string company,BaseSpatialSourceKindV3 kind,BaseSpatialSourceRoleV3 role,Vector2I cell,int weight=0)=>bases.UpsertSource(new(id,company,kind,role,new[]{new GlobalCellCoord(cell)},weight,bases.NextSourceCreationOrder(),1));
    private static void AddArea(BaseAreaSessionV3 bases,string id,string company,BaseSpatialSourceKindV3 kind,IReadOnlyCollection<GlobalCellCoord> cells,int weight){BaseSpatialSourceRoleV3 role=kind==BaseSpatialSourceKindV3.StockpileZone?BaseSpatialSourceCatalogV3.ClassifyStockpile(cells):BaseSpatialSourceCatalogV3.ClassifyFarm(cells);bases.UpsertSource(new(id,company,kind,role,cells,role==BaseSpatialSourceRoleV3.Anchor?weight:0,bases.NextSourceCreationOrder(),1));}
    private static GlobalCellCoord[] Line(int x,int y,int count)=>Enumerable.Range(0,count).Select(i=>new GlobalCellCoord(x+i,y)).ToArray();private static GlobalCellCoord[] Rect(int x,int y,int width,int height)=>Enumerable.Range(0,height).SelectMany(dy=>Enumerable.Range(0,width).Select(dx=>new GlobalCellCoord(x+dx,y+dy))).ToArray();
    private static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}
}
