using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using Godot;
using GameplayV3.Rooms;
using WorldV2;

namespace GameplayV3.Bases;

public enum FacilityKindV3 { Structure, Bed, Door, Wall, Floor, StockpileZone, FarmPlot, RoomMetadata, Other }
public enum FacilityAffiliationStateV3 { Affiliated, Unaffiliated, Ambiguous, PendingBaseRebuild, Invalid }

public sealed class FacilityAffiliationSnapshotV3
{
    internal FacilityAffiliationSnapshotV3(string key,FacilityKindV3 kind,string company,string? baseId,FacilityAffiliationStateV3 state,string sourceId,long sourceRevision,long baseRevision,Rect2I bounds,string reason,long revision)
    {FacilityKey=key;FacilityKind=kind;CompanyId=company;BaseAreaId=baseId;AffiliationState=state;SourceId=sourceId;SourceRevision=sourceRevision;BaseAreaRevision=baseRevision;Bounds=bounds;ChangedReason=reason;Revision=revision;}
    public string FacilityKey{get;}public FacilityKindV3 FacilityKind{get;}public string CompanyId{get;}public string? BaseAreaId{get;}public FacilityAffiliationStateV3 AffiliationState{get;}public string SourceId{get;}public long SourceRevision{get;}public long BaseAreaRevision{get;}public Rect2I Bounds{get;}public string ChangedReason{get;}public long Revision{get;}
}

public sealed class BaseActivityRangeV3
{
    private readonly ReadOnlyCollection<Vector2I> _chunks;
    internal BaseActivityRangeV3(BaseAreaV3 area,long revision)
    {BaseAreaId=area.BaseAreaId;CompanyId=area.CompanyId;BaseAreaRevision=area.Revision;Bounds=area.Bounds;ActivityPaddingCells=FacilityAffiliationSettingsV3.BaseActivityPaddingCells;ExpandedBounds=Bounds.Grow(ActivityPaddingCells);Revision=revision;List<Vector2I> chunks=new();Vector2I min=BaseSpatialSourceV3.ChunkOf(ExpandedBounds.Position),max=BaseSpatialSourceV3.ChunkOf(ExpandedBounds.End-Vector2I.One);for(int y=min.Y;y<=max.Y;y++)for(int x=min.X;x<=max.X;x++)chunks.Add(new(x,y));_chunks=chunks.AsReadOnly();}
    public string BaseAreaId{get;}public string CompanyId{get;}public long BaseAreaRevision{get;}public Rect2I Bounds{get;}public Rect2I ExpandedBounds{get;}public int ActivityPaddingCells{get;}public IReadOnlyList<Vector2I> ChunkCoords=>_chunks;public long Revision{get;}
    public bool Contains(GlobalCellCoord cell)=>ExpandedBounds.HasPoint(cell.Value);
    public int DistanceToCoreBounds(GlobalCellCoord cell)=>FacilityAffiliationSessionV3.ChebyshevDistance(Bounds,cell.Value);
}

public sealed record FacilityAffiliationChangedV3(string FacilityKey,string CompanyId,string? OldBaseAreaId,string? NewBaseAreaId,FacilityAffiliationStateV3 OldState,FacilityAffiliationStateV3 NewState,long Revision,string Reason);
public sealed record BaseActivityRangeChangedV3(string BaseAreaId,string CompanyId,bool Removed,long BaseAreaRevision,long Revision,string Reason);

public static class FacilityAffiliationSettingsV3
{
    public const int BaseActivityPaddingCells=48;
    public const int MaxDirtyFacilitiesPerTick=128;
    public const int MaxDirtyBaseAreasPerTick=32;
    public const int MaxRecentEvents=32;
}

public sealed class FacilityAffiliationDiagnosticsV3
{
    public int DirtyFacilityCount{get;internal set;}public int DirtyBaseAreaCount{get;internal set;}public int FacilitiesProcessedThisTick{get;internal set;}public int ActivityRangesProcessedThisTick{get;internal set;}public long FacilityChangedCount{get;internal set;}public long ActivityRangeChangedCount{get;internal set;}public long ActivityQueryCount{get;internal set;}public long ActivityChunkCandidateCount{get;internal set;}public long AmbiguousFacilityCount{get;internal set;}public long StaleBaseReferenceDiscardCount{get;internal set;}public double LastTickMilliseconds{get;internal set;}public double MaxTickMilliseconds{get;internal set;}
    public int FullWorldFacilityScanCount=>0;public int FullWorldActivityCellBuildCount=>0;public int PerFacilityNodeCount=>0;public int PerBaseActivityNodeCount=>0;public int ActivityRangeTriggeredChunkGenerationCount=>0;
    internal void ResetTick(){FacilitiesProcessedThisTick=ActivityRangesProcessedThisTick=0;LastTickMilliseconds=0;}
}

public sealed class FacilityAffiliationSessionV3:IDisposable
{
    private readonly BaseAreaSessionV3 _bases;
    private readonly Dictionary<string,FacilityAffiliationSnapshotV3> _facilities=new(StringComparer.Ordinal);
    private readonly Dictionary<string,HashSet<string>> _facilitiesByBase=new(StringComparer.Ordinal);
    private readonly Dictionary<Vector2I,HashSet<string>> _facilitiesByChunk=new();
    private readonly Dictionary<FacilityAffiliationStateV3,int> _stateCounts=new();
    private readonly Dictionary<string,HashSet<string>> _pendingByCompany=new(StringComparer.Ordinal);
    private readonly Dictionary<string,BaseActivityRangeV3> _ranges=new(StringComparer.Ordinal);
    private readonly Dictionary<(string Company,Vector2I Chunk),HashSet<string>> _rangeChunks=new();
    private readonly Dictionary<string,Rect2I> _companyChunkBounds=new(StringComparer.Ordinal);
    private readonly Queue<string> _facilityOrder=new();private readonly HashSet<string> _dirtyFacilities=new(StringComparer.Ordinal);
    private readonly Queue<string> _baseOrder=new();private readonly HashSet<string> _dirtyBases=new(StringComparer.Ordinal);
    private readonly Queue<string> _roomOrder=new();private readonly HashSet<string> _dirtyRooms=new(StringComparer.Ordinal);private readonly HashSet<string> _knownRooms=new(StringComparer.Ordinal);
    private readonly Queue<FacilityAffiliationChangedV3> _recentFacility=new();private readonly Queue<BaseActivityRangeChangedV3> _recentRanges=new();
    private long _revision;private bool _disposed;
    public FacilityAffiliationSessionV3(long sessionRevision,BaseAreaSessionV3 bases){SessionRevision=sessionRevision;_bases=bases;bases.Changed+=OnBaseChanged;bases.SourceChanged+=OnSourceChanged;bases.RoomSnapshotChanged+=OnRoomSnapshotChanged;bases.RebuildCompleted+=OnRebuildCompleted;foreach(var source in bases.Sources.GetAll())QueueFacility(source.SourceId);foreach(var area in bases.Areas.GetAll())QueueBase(area.BaseAreaId);QueueRooms();}
    public long SessionRevision{get;}public int Count=>_facilities.Count;public int ActivityRangeCount=>_ranges.Count;public int DirtyFacilityCount=>_dirtyFacilities.Count+_dirtyRooms.Count;public int DirtyBaseAreaCount=>_dirtyBases.Count;public FacilityAffiliationDiagnosticsV3 Diagnostics{get;}=new();
    public event Action<FacilityAffiliationChangedV3>? FacilityAffiliationChanged;public event Action<BaseActivityRangeChangedV3>? BaseActivityRangeChanged;
    public bool TryGetFacility(string key,out FacilityAffiliationSnapshotV3? snapshot)=>_facilities.TryGetValue(key,out snapshot);
    public bool TryGetActivityRange(string baseAreaId,out BaseActivityRangeV3? range)=>_ranges.TryGetValue(baseAreaId,out range);
    public int GetFacilityStateCount(FacilityAffiliationStateV3 state)=>_stateCounts.GetValueOrDefault(state);
    public IReadOnlyList<FacilityAffiliationSnapshotV3> GetFacilitiesInChunk(Vector2I chunk)
    {if(!_facilitiesByChunk.TryGetValue(chunk,out var ids))return Array.Empty<FacilityAffiliationSnapshotV3>();List<FacilityAffiliationSnapshotV3> result=new(ids.Count);foreach(string id in ids)if(_facilities.TryGetValue(id,out var value))result.Add(value);result.Sort((a,b)=>StringComparer.Ordinal.Compare(a.FacilityKey,b.FacilityKey));return result.AsReadOnly();}
    public IReadOnlyList<FacilityAffiliationSnapshotV3> GetFacilitiesForBase(string baseAreaId)=>_facilitiesByBase.TryGetValue(baseAreaId,out var ids)?ids.Select(id=>_facilities[id]).OrderBy(x=>x.FacilityKey,StringComparer.Ordinal).ToList().AsReadOnly():Array.Empty<FacilityAffiliationSnapshotV3>();
    public bool HasFacilityKindForBase(string baseAreaId,FacilityKindV3 kind){if(!_facilitiesByBase.TryGetValue(baseAreaId,out var ids))return false;foreach(string id in ids)if(_facilities.TryGetValue(id,out var facility)&&facility.FacilityKind==kind&&facility.AffiliationState==FacilityAffiliationStateV3.Affiliated)return true;return false;}
    public IReadOnlyList<FacilityAffiliationChangedV3> GetRecentFacilityEvents()=>_recentFacility.ToList().AsReadOnly();public IReadOnlyList<BaseActivityRangeChangedV3> GetRecentRangeEvents()=>_recentRanges.ToList().AsReadOnly();
    public bool IsCellInsideBaseCore(string baseAreaId,GlobalCellCoord cell)=>_bases.Areas.TryGet(baseAreaId,out var area)&&area!=null&&area.Contains(cell.Value);
    public bool IsCellInsideActivityRange(string baseAreaId,GlobalCellCoord cell)=>_ranges.TryGetValue(baseAreaId,out var range)&&range.Contains(cell);
    public IReadOnlyList<string> GetActivityRangeChunkCandidates(string company,Vector2I chunk)=>_rangeChunks.TryGetValue((company,chunk),out var ids)?ids.OrderBy(x=>x,StringComparer.Ordinal).ToList().AsReadOnly():Array.Empty<string>();
    public IReadOnlyList<BaseAreaV3> GetBaseAreasWhoseActivityRangeContains(string company,GlobalCellCoord cell)
    {Diagnostics.ActivityQueryCount++;Vector2I chunk=BaseSpatialSourceV3.ChunkOf(cell.Value);if(!_rangeChunks.TryGetValue((company,chunk),out var ids))return Array.Empty<BaseAreaV3>();List<BaseAreaV3> result=new();foreach(string id in ids){Diagnostics.ActivityChunkCandidateCount++;if(_ranges.TryGetValue(id,out var range)&&range.Contains(cell)&&_bases.Areas.TryGet(id,out var area)&&area!=null)result.Add(area);}return OrderCandidates(result,cell,null).AsReadOnly();}
    public bool TryGetNearestBaseAreaInActivityRange(string company,GlobalCellCoord cell,out BaseAreaV3? area,string? continuityBaseAreaId=null){area=GetOrderedCandidates(company,cell,continuityBaseAreaId).FirstOrDefault();return area!=null;}
    public bool TryGetNearestCompanyBase(string company,GlobalCellCoord cell,out BaseAreaV3? area)
    {area=null;Diagnostics.ActivityQueryCount++;if(!_companyChunkBounds.TryGetValue(company,out Rect2I chunkBounds))return false;Vector2I origin=BaseSpatialSourceV3.ChunkOf(cell.Value);int maxRing=Math.Max(Math.Max(Math.Abs(origin.X-chunkBounds.Position.X),Math.Abs(origin.X-(chunkBounds.End.X-1))),Math.Max(Math.Abs(origin.Y-chunkBounds.Position.Y),Math.Abs(origin.Y-(chunkBounds.End.Y-1))));HashSet<string> seen=new(StringComparer.Ordinal);int bestDistance=int.MaxValue;for(int ring=0;ring<=maxRing;ring++){foreach(Vector2I chunk in EnumerateRing(origin,ring)){if(!_rangeChunks.TryGetValue((company,chunk),out var ids))continue;foreach(string id in ids)if(seen.Add(id)&&_bases.Areas.TryGet(id,out var candidate)&&candidate!=null){Diagnostics.ActivityChunkCandidateCount++;int distance=ChebyshevDistance(candidate.Bounds,cell.Value);if(area==null||distance<bestDistance||distance==bestDistance&&(candidate.CreationOrder<area.CreationOrder||candidate.CreationOrder==area.CreationOrder&&string.CompareOrdinal(candidate.BaseAreaId,area.BaseAreaId)<0)){area=candidate;bestDistance=distance;}}}if(area!=null&&ring*WorldV2CoordinateUtility.ChunkSizeCells-(WorldV2CoordinateUtility.ChunkSizeCells-1)-FacilityAffiliationSettingsV3.BaseActivityPaddingCells>bestDistance)break;}return area!=null;}
    private List<BaseAreaV3> GetOrderedCandidates(string company,GlobalCellCoord cell,string? continuity){Diagnostics.ActivityQueryCount++;Vector2I chunk=BaseSpatialSourceV3.ChunkOf(cell.Value);if(!_rangeChunks.TryGetValue((company,chunk),out var ids))return new();List<BaseAreaV3> candidates=new();foreach(string id in ids){Diagnostics.ActivityChunkCandidateCount++;if(_ranges.TryGetValue(id,out var range)&&range.Contains(cell)&&_bases.Areas.TryGet(id,out var area)&&area!=null)candidates.Add(area);}return OrderCandidates(candidates,cell,continuity);}
    private List<BaseAreaV3> OrderCandidates(IEnumerable<BaseAreaV3> values,GlobalCellCoord cell,string? continuity)=>values.OrderByDescending(a=>a.Contains(cell.Value)).ThenBy(a=>ChebyshevDistance(a.Bounds,cell.Value)).ThenByDescending(a=>a.BaseAreaId==continuity).ThenBy(a=>a.CreationOrder).ThenBy(a=>a.BaseAreaId,StringComparer.Ordinal).ToList();
    public int ProcessDirty(int facilityBudget=FacilityAffiliationSettingsV3.MaxDirtyFacilitiesPerTick,int baseBudget=FacilityAffiliationSettingsV3.MaxDirtyBaseAreasPerTick)
    {if(_disposed)return 0;Stopwatch watch=Stopwatch.StartNew();Diagnostics.ResetTick();int processed=0;while(Diagnostics.ActivityRangesProcessedThisTick<baseBudget&&_baseOrder.Count>0){string id=_baseOrder.Dequeue();if(!_dirtyBases.Remove(id))continue;RefreshRange(id);Diagnostics.ActivityRangesProcessedThisTick++;processed++;}while(Diagnostics.FacilitiesProcessedThisTick<facilityBudget&&_facilityOrder.Count>0){string id=_facilityOrder.Dequeue();if(!_dirtyFacilities.Remove(id))continue;RefreshSourceFacility(id);Diagnostics.FacilitiesProcessedThisTick++;processed++;}while(Diagnostics.FacilitiesProcessedThisTick<facilityBudget&&_roomOrder.Count>0){string id=_roomOrder.Dequeue();if(!_dirtyRooms.Remove(id))continue;RefreshRoomFacility(id);Diagnostics.FacilitiesProcessedThisTick++;processed++;}Diagnostics.DirtyFacilityCount=DirtyFacilityCount;Diagnostics.DirtyBaseAreaCount=DirtyBaseAreaCount;watch.Stop();Diagnostics.LastTickMilliseconds=watch.Elapsed.TotalMilliseconds;Diagnostics.MaxTickMilliseconds=Math.Max(Diagnostics.MaxTickMilliseconds,Diagnostics.LastTickMilliseconds);return processed;}
    public void ProcessUntilIdle(int maxTicks=100000){int guard=0;while((DirtyFacilityCount>0||DirtyBaseAreaCount>0)&&guard++<maxTicks)ProcessDirty();if(guard>=maxTicks)throw new InvalidOperationException("Facility affiliation dirty queues did not converge.");}
    private void OnSourceChanged(BaseSpatialSourceChangeEventV3 value)=>QueueFacility(value.SourceId);
    private void OnRebuildCompleted(string company){if(_pendingByCompany.TryGetValue(company,out var pending))foreach(string facility in pending.ToList())QueueFacility(facility);}
    private void OnBaseChanged(BaseAreaChangeEventV3 value){foreach(string id in value.OldBaseAreaIds){QueueBase(id);if(_facilitiesByBase.TryGetValue(id,out var facilities))foreach(string facility in facilities.ToList())QueueFacility(facility);}foreach(string id in value.NewBaseAreaIds){QueueBase(id);if(_bases.Areas.TryGet(id,out var area)&&area!=null)foreach(string source in area.MemberSourceIds)QueueFacility(source);}if(_pendingByCompany.TryGetValue(value.CompanyId,out var pending))foreach(string facility in pending.ToList())QueueFacility(facility);QueueRooms();}
    private void OnRoomSnapshotChanged()=>QueueRooms();
    private void QueueFacility(string id){if(_dirtyFacilities.Add(id))_facilityOrder.Enqueue(id);}
    private void QueueBase(string id){if(!string.IsNullOrWhiteSpace(id)&&_dirtyBases.Add(id))_baseOrder.Enqueue(id);}
    private void QueueRoom(string id){if(_dirtyRooms.Add(id))_roomOrder.Enqueue(id);}
    private void QueueRooms(){HashSet<string> current=new(_bases.GetRoomSnapshot().Select(r=>r.RoomId),StringComparer.Ordinal);foreach(string id in _knownRooms)if(!current.Contains(id))QueueRoom(id);foreach(string id in current)QueueRoom(id);_knownRooms.Clear();_knownRooms.UnionWith(current);}
    private void RefreshSourceFacility(string id)
    {if(!_bases.Sources.TryGet(id,out var source)||source==null){RemoveFacility(id,"SourceRemoved");return;}FacilityAffiliationStateV3 state;string? baseId=null;long baseRevision=0;string reason;if(_bases.Areas.TryGetForSource(id,out var area)&&area!=null){state=FacilityAffiliationStateV3.Affiliated;baseId=area.BaseAreaId;baseRevision=area.Revision;reason="SourceMembership";}else if(_bases.IsCompanyDirty(source.CompanyId)){state=FacilityAffiliationStateV3.PendingBaseRebuild;reason="PendingBaseRebuild";}else{state=source.IsCompleted&&source.IsEligible?FacilityAffiliationStateV3.Unaffiliated:FacilityAffiliationStateV3.Invalid;reason=state.ToString();}ApplyFacility(new(id,KindOf(source.SourceKind),source.CompanyId,baseId,state,id,source.SourceRevision,baseRevision,source.Bounds,reason,++_revision));}
    private void RefreshRoomFacility(string roomId)
    {RoomTopologyStateV3? room=_bases.GetRoomSnapshot().FirstOrDefault(r=>r.RoomId==roomId);if(room==null){RemoveFacility(roomId,"RoomRemoved");return;}HashSet<Vector2I> cells=new(room.Cells.Select(c=>c.Value));HashSet<string> owners=new(StringComparer.Ordinal);HashSet<string> companies=new(StringComparer.Ordinal);HashSet<string> seenSources=new(StringComparer.Ordinal);foreach(Vector2I chunk in room.Cells.Select(c=>BaseSpatialSourceV3.ChunkOf(c.Value)).Distinct())foreach(var source in _bases.Sources.EnumerateChunk(chunk))if(source.IsAnchor&&seenSources.Add(source.SourceId)&&source.FootprintCells.Any(c=>cells.Contains(c.Value))&&_bases.Areas.TryGetForSource(source.SourceId,out var area)&&area!=null){owners.Add(area.BaseAreaId);companies.Add(area.CompanyId);}FacilityAffiliationStateV3 state=owners.Count==1&&companies.Count==1?FacilityAffiliationStateV3.Affiliated:owners.Count>1||companies.Count>1?FacilityAffiliationStateV3.Ambiguous:FacilityAffiliationStateV3.Unaffiliated;string? baseId=state==FacilityAffiliationStateV3.Affiliated?owners.First():null;long baseRevision=baseId!=null&&_bases.Areas.TryGet(baseId,out var owner)&&owner!=null?owner.Revision:0;string company=state==FacilityAffiliationStateV3.Affiliated?companies.First():string.Empty;Rect2I bounds=BoundsOf(room.Cells);if(state==FacilityAffiliationStateV3.Ambiguous)Diagnostics.AmbiguousFacilityCount++;ApplyFacility(new(roomId,FacilityKindV3.RoomMetadata,company,baseId,state,roomId,room.TopologyRevision,baseRevision,bounds,state==FacilityAffiliationStateV3.Ambiguous?"RoomConflict":"RoomMetadata",++_revision));}
    private void RefreshRange(string id){if(!_bases.Areas.TryGet(id,out var area)||area==null){RemoveRange(id,"BaseRemoved");return;}BaseActivityRangeV3 next=new(area,++_revision);if(_ranges.TryGetValue(id,out var old)&&old.BaseAreaRevision==next.BaseAreaRevision&&old.ExpandedBounds==next.ExpandedBounds)return;if(old!=null)RemoveRangeIndexes(old);_ranges[id]=next;AddRangeIndexes(next);EmitRange(new(id,area.CompanyId,false,area.Revision,next.Revision,old==null?"Created":"BaseChanged"));}
    private void ApplyFacility(FacilityAffiliationSnapshotV3 next){_facilities.TryGetValue(next.FacilityKey,out var old);if(old!=null&&Equivalent(old,next))return;if(old!=null)RemoveFacilityIndexes(old);_facilities[next.FacilityKey]=next;AddFacilityIndexes(next);EmitFacility(new(next.FacilityKey,next.CompanyId,old?.BaseAreaId,next.BaseAreaId,old?.AffiliationState??FacilityAffiliationStateV3.Invalid,next.AffiliationState,next.Revision,next.ChangedReason));}
    private void RemoveFacility(string id,string reason){if(!_facilities.Remove(id,out var old)||old==null)return;RemoveFacilityIndexes(old);EmitFacility(new(id,old.CompanyId,old.BaseAreaId,null,old.AffiliationState,FacilityAffiliationStateV3.Invalid,++_revision,reason));}
    private void AddFacilityIndexes(FacilityAffiliationSnapshotV3 value){_stateCounts[value.AffiliationState]=_stateCounts.GetValueOrDefault(value.AffiliationState)+1;if(value.BaseAreaId!=null){if(!_facilitiesByBase.TryGetValue(value.BaseAreaId,out var ids)){ids=new(StringComparer.Ordinal);_facilitiesByBase.Add(value.BaseAreaId,ids);}ids.Add(value.FacilityKey);}if(value.AffiliationState==FacilityAffiliationStateV3.PendingBaseRebuild){if(!_pendingByCompany.TryGetValue(value.CompanyId,out var pending)){pending=new(StringComparer.Ordinal);_pendingByCompany.Add(value.CompanyId,pending);}pending.Add(value.FacilityKey);}foreach(Vector2I chunk in ChunksOf(value.Bounds)){if(!_facilitiesByChunk.TryGetValue(chunk,out var ids)){ids=new(StringComparer.Ordinal);_facilitiesByChunk.Add(chunk,ids);}ids.Add(value.FacilityKey);}}
    private void RemoveFacilityIndexes(FacilityAffiliationSnapshotV3 value){int count=_stateCounts.GetValueOrDefault(value.AffiliationState)-1;if(count<=0)_stateCounts.Remove(value.AffiliationState);else _stateCounts[value.AffiliationState]=count;if(value.BaseAreaId!=null&&_facilitiesByBase.TryGetValue(value.BaseAreaId,out var ids)){ids.Remove(value.FacilityKey);if(ids.Count==0)_facilitiesByBase.Remove(value.BaseAreaId);}if(value.AffiliationState==FacilityAffiliationStateV3.PendingBaseRebuild)RemovePending(value.CompanyId,value.FacilityKey);foreach(Vector2I chunk in ChunksOf(value.Bounds))if(_facilitiesByChunk.TryGetValue(chunk,out var chunkIds)){chunkIds.Remove(value.FacilityKey);if(chunkIds.Count==0)_facilitiesByChunk.Remove(chunk);}}
    private static IEnumerable<Vector2I> ChunksOf(Rect2I bounds){if(bounds.Size.X<=0||bounds.Size.Y<=0)yield break;Vector2I min=BaseSpatialSourceV3.ChunkOf(bounds.Position),max=BaseSpatialSourceV3.ChunkOf(bounds.End-Vector2I.One);for(int y=min.Y;y<=max.Y;y++)for(int x=min.X;x<=max.X;x++)yield return new(x,y);}
    private void RemovePending(string company,string id){if(_pendingByCompany.TryGetValue(company,out var ids)){ids.Remove(id);if(ids.Count==0)_pendingByCompany.Remove(company);}}
    private void RemoveRange(string id,string reason){if(!_ranges.Remove(id,out var old)||old==null)return;RemoveRangeIndexes(old);Diagnostics.StaleBaseReferenceDiscardCount++;EmitRange(new(id,old.CompanyId,true,old.BaseAreaRevision,++_revision,reason));}
    private void AddRangeIndexes(BaseActivityRangeV3 range){foreach(Vector2I chunk in range.ChunkCoords){var key=(range.CompanyId,chunk);if(!_rangeChunks.TryGetValue(key,out var ids)){ids=new(StringComparer.Ordinal);_rangeChunks.Add(key,ids);}ids.Add(range.BaseAreaId);}ExpandCompanyChunkBounds(range.CompanyId,range.ChunkCoords);}
    private void RemoveRangeIndexes(BaseActivityRangeV3 range){foreach(Vector2I chunk in range.ChunkCoords){var key=(range.CompanyId,chunk);if(_rangeChunks.TryGetValue(key,out var ids)){ids.Remove(range.BaseAreaId);if(ids.Count==0)_rangeChunks.Remove(key);}}RecomputeCompanyChunkBounds(range.CompanyId);}
    private void EmitFacility(FacilityAffiliationChangedV3 value){Diagnostics.FacilityChangedCount++;_recentFacility.Enqueue(value);while(_recentFacility.Count>FacilityAffiliationSettingsV3.MaxRecentEvents)_recentFacility.Dequeue();FacilityAffiliationChanged?.Invoke(value);}
    private void EmitRange(BaseActivityRangeChangedV3 value){Diagnostics.ActivityRangeChangedCount++;_recentRanges.Enqueue(value);while(_recentRanges.Count>FacilityAffiliationSettingsV3.MaxRecentEvents)_recentRanges.Dequeue();BaseActivityRangeChanged?.Invoke(value);}
    public void Dispose(){if(_disposed)return;_disposed=true;_bases.Changed-=OnBaseChanged;_bases.SourceChanged-=OnSourceChanged;_bases.RoomSnapshotChanged-=OnRoomSnapshotChanged;_bases.RebuildCompleted-=OnRebuildCompleted;_facilityOrder.Clear();_baseOrder.Clear();_roomOrder.Clear();_dirtyFacilities.Clear();_dirtyBases.Clear();_dirtyRooms.Clear();}
    public static int ChebyshevDistance(Rect2I bounds,Vector2I cell){int dx=cell.X<bounds.Position.X?bounds.Position.X-cell.X:cell.X>=bounds.End.X?cell.X-bounds.End.X+1:0;int dy=cell.Y<bounds.Position.Y?bounds.Position.Y-cell.Y:cell.Y>=bounds.End.Y?cell.Y-bounds.End.Y+1:0;return Math.Max(dx,dy);}
    private static IEnumerable<Vector2I> EnumerateRing(Vector2I center,int radius){if(radius==0){yield return center;yield break;}int minX=center.X-radius,maxX=center.X+radius,minY=center.Y-radius,maxY=center.Y+radius;for(int x=minX;x<=maxX;x++){yield return new(x,minY);yield return new(x,maxY);}for(int y=minY+1;y<maxY;y++){yield return new(minX,y);yield return new(maxX,y);}}
    private void ExpandCompanyChunkBounds(string company,IReadOnlyList<Vector2I> chunks){if(chunks.Count==0)return;int minX=chunks.Min(c=>c.X),minY=chunks.Min(c=>c.Y),maxX=chunks.Max(c=>c.X),maxY=chunks.Max(c=>c.Y);if(_companyChunkBounds.TryGetValue(company,out var old)){minX=Math.Min(minX,old.Position.X);minY=Math.Min(minY,old.Position.Y);maxX=Math.Max(maxX,old.End.X-1);maxY=Math.Max(maxY,old.End.Y-1);}_companyChunkBounds[company]=new(minX,minY,maxX-minX+1,maxY-minY+1);}
    private void RecomputeCompanyChunkBounds(string company){List<Vector2I> chunks=_rangeChunks.Keys.Where(k=>k.Company==company).Select(k=>k.Chunk).ToList();if(chunks.Count==0){_companyChunkBounds.Remove(company);return;}_companyChunkBounds[company]=new(chunks.Min(c=>c.X),chunks.Min(c=>c.Y),chunks.Max(c=>c.X)-chunks.Min(c=>c.X)+1,chunks.Max(c=>c.Y)-chunks.Min(c=>c.Y)+1);}
    private static Rect2I BoundsOf(IReadOnlyList<GlobalCellCoord> cells){if(cells.Count==0)return new();int minX=cells.Min(c=>c.Value.X),minY=cells.Min(c=>c.Value.Y),maxX=cells.Max(c=>c.Value.X),maxY=cells.Max(c=>c.Value.Y);return new(minX,minY,maxX-minX+1,maxY-minY+1);}
    private static FacilityKindV3 KindOf(BaseSpatialSourceKindV3 kind)=>kind switch{BaseSpatialSourceKindV3.Bed=>FacilityKindV3.Bed,BaseSpatialSourceKindV3.Door=>FacilityKindV3.Door,BaseSpatialSourceKindV3.Wall=>FacilityKindV3.Wall,BaseSpatialSourceKindV3.Floor=>FacilityKindV3.Floor,BaseSpatialSourceKindV3.StockpileZone=>FacilityKindV3.StockpileZone,BaseSpatialSourceKindV3.FarmPlot=>FacilityKindV3.FarmPlot,BaseSpatialSourceKindV3.Structure or BaseSpatialSourceKindV3.FutureFacility=>FacilityKindV3.Structure,_=>FacilityKindV3.Other};
    private static bool Equivalent(FacilityAffiliationSnapshotV3 a,FacilityAffiliationSnapshotV3 b)=>a.FacilityKind==b.FacilityKind&&a.CompanyId==b.CompanyId&&a.BaseAreaId==b.BaseAreaId&&a.AffiliationState==b.AffiliationState&&a.SourceRevision==b.SourceRevision&&a.BaseAreaRevision==b.BaseAreaRevision&&a.Bounds==b.Bounds;
}
