using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Mercenary;
using GameplayV3.Needs;
using WorldV2;

namespace GameplayV3.Bases;

public enum MercenaryBaseAffiliationStateV3 { Assigned, Unassigned, PendingReassignment, BaseRemoved, Ambiguous }
public enum MercenaryBaseAssignmentSourceV3 { AssignedBed, InsideBaseCore, InsideActivityRange, NearestCompanyBase, MergeRemap, SplitReassignment, SessionDeployment, None }

public sealed class MercenaryBaseAffiliationV3
{
    internal MercenaryBaseAffiliationV3(string mercenaryId,string companyId,string? baseAreaId,MercenaryBaseAffiliationStateV3 state,MercenaryBaseAssignmentSourceV3 source,long assignedAtRevision,long baseAreaRevision,long positionRevision,bool pinned,long revision,string reason)
    {MercenaryId=mercenaryId;CompanyId=companyId;BaseAreaId=baseAreaId;State=state;AssignmentSource=source;AssignedAtRevision=assignedAtRevision;BaseAreaRevision=baseAreaRevision;MercenaryPositionRevision=positionRevision;IsPinned=pinned;Revision=revision;LastChangedReason=reason;}
    public string MercenaryId{get;}public string CompanyId{get;}public string? BaseAreaId{get;}public MercenaryBaseAffiliationStateV3 State{get;}public MercenaryBaseAssignmentSourceV3 AssignmentSource{get;}public long AssignedAtRevision{get;}public long BaseAreaRevision{get;}public long MercenaryPositionRevision{get;}public bool IsPinned{get;}public long Revision{get;}public string LastChangedReason{get;}
}

public sealed record MercenaryBaseAffiliationChangedV3(string MercenaryId,string CompanyId,string? OldBaseAreaId,string? NewBaseAreaId,MercenaryBaseAffiliationStateV3 OldState,MercenaryBaseAffiliationStateV3 NewState,MercenaryBaseAssignmentSourceV3 Source,long Revision,string Reason);
public sealed record MercenaryBecameUnassignedV3(string MercenaryId,string CompanyId,string? PreviousBaseAreaId,long Revision,string Reason);
public sealed record MercenaryBaseRemappedV3(string MercenaryId,string CompanyId,string OldBaseAreaId,string NewBaseAreaId,long Revision,string Reason);

public static class MercenaryBaseAffiliationSettingsV3
{
    public const int MaxMercenaryEventsPerTick=128;public const int MaxMercenaryReevaluationsPerTick=64;public const int MaxBaseRemapsPerTick=256;public const int MaxRecentEvents=64;
}

public sealed class MercenaryBaseAffiliationDiagnosticsV3
{
    public int DirtyMercenaryCount{get;internal set;}public int ReevaluationsThisTick{get;internal set;}public long ChangedCount{get;internal set;}public long UnassignedCount{get;internal set;}public long RemappedCount{get;internal set;}public long StabilityKeepCount{get;internal set;}public long BedAssignmentCount{get;internal set;}public long CoreAssignmentCount{get;internal set;}public long RangeAssignmentCount{get;internal set;}public long NearestAssignmentCount{get;internal set;}public long MissingMercenaryCount{get;internal set;}public long RetiredBaseReferenceDiscardCount{get;internal set;}public int MercenaryBaseCartesianComparisonCount=>0;public int PerMercenaryBaseNodeCount=>0;public int PerMercenaryBaseProcessCount=>0;public int MercenaryBaseTriggeredChunkGenerationCount=>0;
    internal void ResetTick(){ReevaluationsThisTick=0;}
}

public sealed class MercenaryBaseAffiliationSessionV3:IDisposable
{
    private readonly MercenarySessionV3 _mercenaries;private readonly MercenaryNeedsSessionV3 _needs;private readonly BaseAreaSessionV3 _bases;private readonly FacilityAffiliationSessionV3 _facilities;
    private readonly Dictionary<string,MercenaryBaseAffiliationV3> _values=new(StringComparer.Ordinal);private readonly Dictionary<string,HashSet<string>> _byBase=new(StringComparer.Ordinal);private readonly Dictionary<string,HashSet<string>> _unassignedByCompany=new(StringComparer.Ordinal);private readonly Dictionary<string,GlobalCellCoord> _observedCells=new(StringComparer.Ordinal);private readonly Dictionary<string,long> _positionRevisions=new(StringComparer.Ordinal);
    private readonly Dictionary<MercenaryBaseAffiliationStateV3,int> _stateCounts=new();
    private readonly Queue<string> _dirtyOrder=new();private readonly Dictionary<string,string> _dirtyReasons=new(StringComparer.Ordinal);private readonly Queue<MercenaryBaseAffiliationChangedV3> _recent=new();private long _revision;private bool _disposed;
    public MercenaryBaseAffiliationSessionV3(long sessionRevision,MercenarySessionV3 mercenaries,MercenaryNeedsSessionV3 needs,BaseAreaSessionV3 bases,FacilityAffiliationSessionV3 facilities)
    {SessionRevision=sessionRevision;_mercenaries=mercenaries;_needs=needs;_bases=bases;_facilities=facilities;mercenaries.Registry.MercenaryRegistered+=OnMercenaryRegistered;mercenaries.Registry.MercenaryRemoved+=OnMercenaryRemoved;needs.Assignments.AssignmentChanged+=OnBedAssignmentChanged;bases.Changed+=OnBaseChanged;facilities.FacilityAffiliationChanged+=OnFacilityChanged;facilities.BaseActivityRangeChanged+=OnRangeChanged;foreach(string id in mercenaries.Registry.GetAllMercenaryIds())RequestReevaluation(id,"InitialSync");}
    public long SessionRevision{get;}public int Count=>_values.Count;public int DirtyMercenaryCount=>_dirtyReasons.Count;public MercenaryBaseAffiliationDiagnosticsV3 Diagnostics{get;}=new();public event Action<MercenaryBaseAffiliationChangedV3>? MercenaryBaseAffiliationChanged;public event Action<MercenaryBecameUnassignedV3>? MercenaryBecameUnassigned;public event Action<MercenaryBaseRemappedV3>? MercenaryBaseRemapped;
    public bool TryGetMercenaryBase(string mercenaryId,out MercenaryBaseAffiliationV3? value)=>_values.TryGetValue(mercenaryId,out value);
    public int GetStateCount(MercenaryBaseAffiliationStateV3 state)=>_stateCounts.GetValueOrDefault(state);
    public IReadOnlyList<string> GetMercenariesForBase(string baseAreaId)=>_byBase.TryGetValue(baseAreaId,out var ids)?ids.OrderBy(x=>x,StringComparer.Ordinal).ToList().AsReadOnly():Array.Empty<string>();
    public IReadOnlyList<string> GetUnassignedMercenaries(string companyId)=>_unassignedByCompany.TryGetValue(companyId,out var ids)?ids.OrderBy(x=>x,StringComparer.Ordinal).ToList().AsReadOnly():Array.Empty<string>();
    public bool IsMercenaryAssignedToBase(string mercenaryId,string baseAreaId)=>_values.TryGetValue(mercenaryId,out var value)&&value.State==MercenaryBaseAffiliationStateV3.Assigned&&value.BaseAreaId==baseAreaId;
    public void RequestReevaluation(string mercenaryId,string reason){if(string.IsNullOrWhiteSpace(mercenaryId))return;string next=string.IsNullOrWhiteSpace(reason)?"ExplicitReevaluation":reason;if(!_dirtyReasons.TryGetValue(mercenaryId,out string? current)){_dirtyOrder.Enqueue(mercenaryId);_dirtyReasons[mercenaryId]=next;}else if(ReasonPriority(next)>=ReasonPriority(current))_dirtyReasons[mercenaryId]=next;Diagnostics.DirtyMercenaryCount=_dirtyReasons.Count;}
    public void RequestCompanyReevaluation(string companyId,string reason){foreach(string id in _mercenaries.Registry.GetMercenariesByCompany(companyId))RequestReevaluation(id,reason);}
    public int ProcessDirty(int budget=MercenaryBaseAffiliationSettingsV3.MaxMercenaryReevaluationsPerTick){if(_disposed)return 0;Diagnostics.ResetTick();while(Diagnostics.ReevaluationsThisTick<budget&&_dirtyOrder.Count>0){string id=_dirtyOrder.Dequeue();if(!_dirtyReasons.Remove(id,out string? reason))continue;Reevaluate(id,reason);Diagnostics.ReevaluationsThisTick++;}Diagnostics.DirtyMercenaryCount=_dirtyReasons.Count;return Diagnostics.ReevaluationsThisTick;}
    public void ProcessUntilIdle(int maxTicks=100000){int guard=0;while(_dirtyReasons.Count>0&&guard++<maxTicks)ProcessDirty();if(guard>=maxTicks)throw new InvalidOperationException("Mercenary base affiliation queue did not converge.");}
    private void Reevaluate(string id,string reason)
    {if(!_mercenaries.Registry.TryGetState(id,out var state)||state==null){Remove(id,"MercenaryRemoved");Diagnostics.MissingMercenaryCount++;return;}long positionRevision=ObservePosition(state);_values.TryGetValue(id,out var old);if(_needs.Assignments.TryGetByMercenary(id,out var bed)&&bed!=null&&_facilities.TryGetFacility(bed.StructureId,out var bedFacility)&&bedFacility!=null){if(bedFacility.AffiliationState==FacilityAffiliationStateV3.Affiliated&&bedFacility.CompanyId==state.CompanyId&&bedFacility.BaseAreaId!=null&&_bases.Areas.TryGet(bedFacility.BaseAreaId,out var bedBase)&&bedBase!=null){Diagnostics.BedAssignmentCount++;Apply(Build(state,bedBase,MercenaryBaseAssignmentSourceV3.AssignedBed,positionRevision,reason));return;}if(bedFacility.AffiliationState is FacilityAffiliationStateV3.PendingBaseRebuild){Apply(BuildPending(state,old,positionRevision,"BedPendingBaseRebuild"));return;}if(bedFacility.AffiliationState==FacilityAffiliationStateV3.Ambiguous){Apply(BuildAmbiguous(state,positionRevision,"BedAffiliationAmbiguous"));return;}}
        IReadOnlyList<BaseAreaV3> ranges=_facilities.GetBaseAreasWhoseActivityRangeContains(state.CompanyId,state.CurrentCell);List<BaseAreaV3> cores=ranges.Where(a=>a.Contains(state.CurrentCell.Value)).ToList();if(old?.BaseAreaId!=null&&_bases.Areas.TryGet(old.BaseAreaId,out var current)&&current!=null&&current.CompanyId==state.CompanyId){BaseAreaV3? currentCore=cores.FirstOrDefault(a=>a.BaseAreaId==current.BaseAreaId);if(currentCore!=null){Diagnostics.CoreAssignmentCount++;Apply(Build(state,currentCore,MercenaryBaseAssignmentSourceV3.InsideBaseCore,positionRevision,"InsideExistingBaseCore"));return;}BaseAreaV3? otherCore=cores.FirstOrDefault(a=>a.BaseAreaId!=current.BaseAreaId);if(otherCore==null){Diagnostics.StabilityKeepCount++;Apply(Build(state,current,old.AssignmentSource,positionRevision,"StableExistingBase"));return;}Diagnostics.CoreAssignmentCount++;Apply(Build(state,otherCore,MercenaryBaseAssignmentSourceV3.InsideBaseCore,positionRevision,"EnteredOtherBaseCore"));return;}
        if(old?.BaseAreaId!=null)Diagnostics.RetiredBaseReferenceDiscardCount++;if(cores.Count>0){Diagnostics.CoreAssignmentCount++;Apply(Build(state,cores[0],TransitionSource(old,cores[0],MercenaryBaseAssignmentSourceV3.InsideBaseCore,reason),positionRevision,reason));return;}if(_facilities.TryGetNearestBaseAreaInActivityRange(state.CompanyId,state.CurrentCell,out var inRange)&&inRange!=null){Diagnostics.RangeAssignmentCount++;Apply(Build(state,inRange,TransitionSource(old,inRange,MercenaryBaseAssignmentSourceV3.InsideActivityRange,reason),positionRevision,reason));return;}if(_facilities.TryGetNearestCompanyBase(state.CompanyId,state.CurrentCell,out var nearest)&&nearest!=null){Diagnostics.NearestAssignmentCount++;Apply(Build(state,nearest,TransitionSource(old,nearest,MercenaryBaseAssignmentSourceV3.NearestCompanyBase,reason),positionRevision,reason));return;}Apply(BuildUnassigned(state,positionRevision,reason));}
    private MercenaryBaseAffiliationV3 Build(MercenaryStateV3 state,BaseAreaV3 area,MercenaryBaseAssignmentSourceV3 source,long positionRevision,string reason){long revision=++_revision;long assignedAt=_values.TryGetValue(state.MercenaryId,out var old)&&old.State==MercenaryBaseAffiliationStateV3.Assigned&&old.BaseAreaId==area.BaseAreaId?old.AssignedAtRevision:revision;return new(state.MercenaryId,state.CompanyId,area.BaseAreaId,MercenaryBaseAffiliationStateV3.Assigned,source,assignedAt,area.Revision,positionRevision,false,revision,reason);}
    private MercenaryBaseAffiliationV3 BuildUnassigned(MercenaryStateV3 state,long positionRevision,string reason)=>new(state.MercenaryId,state.CompanyId,null,MercenaryBaseAffiliationStateV3.Unassigned,MercenaryBaseAssignmentSourceV3.None,0,0,positionRevision,false,++_revision,reason);
    private MercenaryBaseAffiliationV3 BuildPending(MercenaryStateV3 state,MercenaryBaseAffiliationV3? old,long positionRevision,string reason)=>new(state.MercenaryId,state.CompanyId,old?.BaseAreaId,MercenaryBaseAffiliationStateV3.PendingReassignment,old?.AssignmentSource??MercenaryBaseAssignmentSourceV3.None,old?.AssignedAtRevision??0,old?.BaseAreaRevision??0,positionRevision,false,++_revision,reason);
    private MercenaryBaseAffiliationV3 BuildAmbiguous(MercenaryStateV3 state,long positionRevision,string reason)=>new(state.MercenaryId,state.CompanyId,null,MercenaryBaseAffiliationStateV3.Ambiguous,MercenaryBaseAssignmentSourceV3.None,0,0,positionRevision,false,++_revision,reason);
    private void Apply(MercenaryBaseAffiliationV3 next){_values.TryGetValue(next.MercenaryId,out var old);if(old!=null&&EquivalentAffiliation(old,next)){if(old.MercenaryPositionRevision!=next.MercenaryPositionRevision)_values[next.MercenaryId]=new(old.MercenaryId,old.CompanyId,old.BaseAreaId,old.State,old.AssignmentSource,old.AssignedAtRevision,old.BaseAreaRevision,next.MercenaryPositionRevision,old.IsPinned,old.Revision,old.LastChangedReason);return;}RemoveIndexes(old);_values[next.MercenaryId]=next;AddIndexes(next);MercenaryBaseAffiliationChangedV3 changed=new(next.MercenaryId,next.CompanyId,old?.BaseAreaId,next.BaseAreaId,old?.State??MercenaryBaseAffiliationStateV3.Unassigned,next.State,next.AssignmentSource,next.Revision,next.LastChangedReason);Diagnostics.ChangedCount++;_recent.Enqueue(changed);while(_recent.Count>MercenaryBaseAffiliationSettingsV3.MaxRecentEvents)_recent.Dequeue();MercenaryBaseAffiliationChanged?.Invoke(changed);if(next.State==MercenaryBaseAffiliationStateV3.Unassigned){Diagnostics.UnassignedCount++;MercenaryBecameUnassigned?.Invoke(new(next.MercenaryId,next.CompanyId,old?.BaseAreaId,next.Revision,next.LastChangedReason));}if(old?.BaseAreaId!=null&&next.BaseAreaId!=null&&old.BaseAreaId!=next.BaseAreaId){Diagnostics.RemappedCount++;MercenaryBaseRemapped?.Invoke(new(next.MercenaryId,next.CompanyId,old.BaseAreaId,next.BaseAreaId,next.Revision,next.LastChangedReason));}}
    private void Remove(string id,string reason){if(!_values.Remove(id,out var old)||old==null)return;RemoveIndexes(old);_observedCells.Remove(id);_positionRevisions.Remove(id);}
    private void AddIndexes(MercenaryBaseAffiliationV3 value){_stateCounts[value.State]=_stateCounts.GetValueOrDefault(value.State)+1;if(value.BaseAreaId!=null){if(!_byBase.TryGetValue(value.BaseAreaId,out var ids)){ids=new(StringComparer.Ordinal);_byBase.Add(value.BaseAreaId,ids);}ids.Add(value.MercenaryId);}if(value.State==MercenaryBaseAffiliationStateV3.Unassigned){if(!_unassignedByCompany.TryGetValue(value.CompanyId,out var ids)){ids=new(StringComparer.Ordinal);_unassignedByCompany.Add(value.CompanyId,ids);}ids.Add(value.MercenaryId);}}
    private void RemoveIndexes(MercenaryBaseAffiliationV3? value){if(value==null)return;int count=_stateCounts.GetValueOrDefault(value.State)-1;if(count<=0)_stateCounts.Remove(value.State);else _stateCounts[value.State]=count;if(value.BaseAreaId!=null&&_byBase.TryGetValue(value.BaseAreaId,out var assigned)){assigned.Remove(value.MercenaryId);if(assigned.Count==0)_byBase.Remove(value.BaseAreaId);}if(_unassignedByCompany.TryGetValue(value.CompanyId,out var unassigned)){unassigned.Remove(value.MercenaryId);if(unassigned.Count==0)_unassignedByCompany.Remove(value.CompanyId);}}
    private long ObservePosition(MercenaryStateV3 state){if(!_observedCells.TryGetValue(state.MercenaryId,out var old)||old.Value!=state.CurrentCell.Value){_observedCells[state.MercenaryId]=state.CurrentCell;_positionRevisions[state.MercenaryId]=_positionRevisions.GetValueOrDefault(state.MercenaryId)+1;}return _positionRevisions.GetValueOrDefault(state.MercenaryId);}
    private void OnMercenaryRegistered(MercenaryStateV3 state)=>RequestReevaluation(state.MercenaryId,"MercenaryRegistered");private void OnMercenaryRemoved(string id,string company)=>Remove(id,"MercenaryRemoved");private void OnBedAssignmentChanged(string id)=>RequestReevaluation(id,"BedAssignmentChanged");
    private void OnBaseChanged(BaseAreaChangeEventV3 value){string reason=value.Kind switch{BaseAreaChangeKindV3.Merged=>"MergeRemap",BaseAreaChangeKindV3.Split=>"SplitReassignment",BaseAreaChangeKindV3.Removed=>"BaseRemoved",_=>"CompanyBaseChanged"};if(value.Kind==BaseAreaChangeKindV3.Merged||value.Kind==BaseAreaChangeKindV3.Split||value.Kind==BaseAreaChangeKindV3.Removed){foreach(string oldId in value.OldBaseAreaIds)if(_byBase.TryGetValue(oldId,out var ids))foreach(string id in ids.ToList())RequestReevaluation(id,reason);}if(value.Kind==BaseAreaChangeKindV3.Created&&_unassignedByCompany.TryGetValue(value.CompanyId,out var unassigned))foreach(string id in unassigned.ToList())RequestReevaluation(id,reason);}
    private void OnFacilityChanged(FacilityAffiliationChangedV3 value){if(_facilities.TryGetFacility(value.FacilityKey,out var facility)&&facility?.FacilityKind!=FacilityKindV3.Bed)return;foreach(var assignment in _needs.Assignments.GetByStructure(value.FacilityKey))RequestReevaluation(assignment.MercenaryId,"AssignedBedAffiliationChanged");}
    private void OnRangeChanged(BaseActivityRangeChangedV3 value){if(value.Removed&&_byBase.TryGetValue(value.BaseAreaId,out var assigned))foreach(string id in assigned.ToList()){MarkBaseRemoved(id,value.BaseAreaId);RequestReevaluation(id,"BaseRemoved");}if(_unassignedByCompany.TryGetValue(value.CompanyId,out var unassigned))foreach(string id in unassigned.ToList())RequestReevaluation(id,"CompanyBaseChanged");}
    private void MarkBaseRemoved(string id,string baseId){if(!_values.TryGetValue(id,out var old)||old.BaseAreaId!=baseId||!_mercenaries.Registry.TryGetState(id,out var state)||state==null)return;MercenaryBaseAffiliationV3 removed=new(id,state.CompanyId,baseId,MercenaryBaseAffiliationStateV3.BaseRemoved,old.AssignmentSource,++_revision,0,old.MercenaryPositionRevision,false,_revision,"BaseRemoved");Apply(removed);}
    public IReadOnlyList<MercenaryBaseAffiliationChangedV3> GetRecentEvents()=>_recent.ToList().AsReadOnly();
    public void Dispose(){if(_disposed)return;_disposed=true;_mercenaries.Registry.MercenaryRegistered-=OnMercenaryRegistered;_mercenaries.Registry.MercenaryRemoved-=OnMercenaryRemoved;_needs.Assignments.AssignmentChanged-=OnBedAssignmentChanged;_bases.Changed-=OnBaseChanged;_facilities.FacilityAffiliationChanged-=OnFacilityChanged;_facilities.BaseActivityRangeChanged-=OnRangeChanged;_dirtyOrder.Clear();_dirtyReasons.Clear();}
    private static MercenaryBaseAssignmentSourceV3 TransitionSource(MercenaryBaseAffiliationV3? old,BaseAreaV3 next,MercenaryBaseAssignmentSourceV3 fallback,string reason){if(old?.BaseAreaId==null||old.BaseAreaId==next.BaseAreaId)return fallback;if(reason.Contains("Merge",StringComparison.Ordinal))return MercenaryBaseAssignmentSourceV3.MergeRemap;if(reason.Contains("Split",StringComparison.Ordinal))return MercenaryBaseAssignmentSourceV3.SplitReassignment;return fallback;}
    private static int ReasonPriority(string reason)=>reason.Contains("Merge",StringComparison.Ordinal)||reason.Contains("Split",StringComparison.Ordinal)?4:reason.Contains("BaseRemoved",StringComparison.Ordinal)?3:reason.Contains("Bed",StringComparison.Ordinal)?2:1;
    private static bool EquivalentAffiliation(MercenaryBaseAffiliationV3 a,MercenaryBaseAffiliationV3 b)=>a.CompanyId==b.CompanyId&&a.BaseAreaId==b.BaseAreaId&&a.State==b.State&&a.AssignmentSource==b.AssignmentSource&&a.BaseAreaRevision==b.BaseAreaRevision&&a.IsPinned==b.IsPinned;
}
