using System;
using System.Collections.Generic;
using GameplayV3.Construction;
using GameplayV3.Production;
using GameplayV3.Resources;
using GameplayV3.Work;
using GameplayV3.Equipment;
using Godot;
using WorldV2;

namespace GameplayV3.Selection;

public enum SelectionTargetKindV3 { Mercenary,ResourceNode,GroundResourceStack,ConstructionBlueprint,CompletedStructure,StockpileZone,FarmPlot,Equipment }
public readonly record struct SelectionTargetRefV3(SelectionTargetKindV3 TargetKind,string StableTargetId,long BoundSessionRevision,GlobalCellCoord? Cell=null,string? CompanyId=null);
public sealed record SelectionInspectRowV3(string Label,string Value);
public sealed record SelectionInspectSnapshotV3(SelectionTargetRefV3 Target,string DisplayName,string KindLabel,string Status,IReadOnlyList<SelectionInspectRowV3> Rows,long SourceRevision);
public sealed class SelectionDiagnosticsV3{public long SelectionTargetChangeCount{get;internal set;}public long SelectionSnapshotBuildCount{get;internal set;}public long SelectionFullRegistryScanCount{get;internal set;}public long SelectionStaleTargetDropCount{get;internal set;}public long HoverTargetChangeCount{get;internal set;}public long HoverSnapshotBuildCount{get;internal set;}public long HoverFullRegistryScanCount{get;internal set;}public long HoverTextAssignmentCount{get;internal set;}public long HiddenSelectionUiQueryCount{get;internal set;}}

public sealed class SelectionInspectSnapshotBuilderV3
{
    private readonly ResourceSessionV3 _resources;private readonly ConstructionSessionV3 _construction;private readonly MercenaryWorkSessionV3 _work;private readonly ProductionSessionV3? _production;private readonly Func<string,string>? _productionBlockReason;private readonly EquipmentRuntimeV3? _equipment;
    public SelectionInspectSnapshotBuilderV3(ResourceSessionV3 resources,ConstructionSessionV3 construction,MercenaryWorkSessionV3 work,ProductionSessionV3? production=null,Func<string,string>? productionBlockReason=null,EquipmentRuntimeV3? equipment=null){_resources=resources;_construction=construction;_work=work;_production=production;_productionBlockReason=productionBlockReason;_equipment=equipment;}
    public bool TryHit(GlobalCellCoord cell,long revision,out SelectionTargetRefV3 target){if(_construction.Blueprints.TryGetBlueprintAtCell(cell,out var blueprint)&&blueprint!=null){target=new(SelectionTargetKindV3.ConstructionBlueprint,blueprint.BlueprintId,revision,cell,blueprint.CompanyId);return true;}if(_construction.Structures.TryGetStructureAtCell(cell,out var structure)&&structure!=null){target=new(SelectionTargetKindV3.CompletedStructure,structure.StructureId,revision,cell,structure.CompanyId);return true;}IReadOnlyList<string> equipment=_equipment?.GetGroundEquipmentAtCell(cell.Value)??Array.Empty<string>();if(equipment.Count==0)equipment=_equipment?.GetStoredEquipmentAtCell(cell.Value)??Array.Empty<string>();if(equipment.Count>0&&_equipment!.TryGetInstance(equipment[0],out var item)&&item!=null){target=new(SelectionTargetKindV3.Equipment,item.EquipmentInstanceId,revision,cell,item.OwnerCompanyId);return true;}IReadOnlyList<GroundResourceStackV3> stacks=_resources.GroundStacks.GetStacksAtCell(cell);if(stacks.Count>0){target=new(SelectionTargetKindV3.GroundResourceStack,stacks[0].ResourceStackId,revision,cell);return true;}if(_resources.Nodes.TryGetAtCell(cell.Value,out var node)&&node!=null){target=new(SelectionTargetKindV3.ResourceNode,node.ResourceNodeId,revision,cell);return true;}target=default;return false;}
    public bool TryBuild(SelectionTargetRefV3 target,long revision,out SelectionInspectSnapshotV3? snapshot)
    {
        snapshot=null;if(target.BoundSessionRevision!=revision)return false;List<SelectionInspectRowV3> rows=new();
        switch(target.TargetKind)
        {
            case SelectionTargetKindV3.ResourceNode:
                if(!_resources.Nodes.TryGet(target.StableTargetId,out var node)||node==null)return false;NaturalResourceDefinitionCatalogV3.TryGet(node.NodeType,out var definition);_work.Reservations.TryGetReservation(node.ResourceNodeId,out var reservation);rows.Add(new("\uB0A8\uC740 \uC591",$"{node.RemainingAmount} / {node.MaxAmount}"));rows.Add(new("\uC0B0\uCD9C\uBB3C",$"{StarterProcessingContentV3.GetResourceDisplayName(node.ProducedResourceType)} \u00D7{node.YieldPerCycle}"));rows.Add(new("\uC608\uC57D",reservation==null?"\uC5C6\uC74C":reservation.MercenaryId));snapshot=new(target,definition?.NodeDisplayName??node.NodeType.ToString(),"\uC790\uC5F0 \uC790\uC6D0",node.IsDepleted?"\uACE0\uAC08\uB428":reservation==null?"\uCC44\uC9D1 \uBA85\uB839 \uBBF8\uC9C0\uC815":"\uCC44\uC9D1 \uC911",rows.AsReadOnly(),_resources.Nodes.Revision);return true;
            case SelectionTargetKindV3.GroundResourceStack:
                if(!_resources.GroundStacks.TryGet(target.StableTargetId,out var stack)||stack==null)return false;int reserved=_resources.AmountReservations.GetReservedAmount(stack.ResourceStackId);rows.Add(new("\uC218\uB7C9",stack.Amount.ToString()));rows.Add(new("\uC608\uC57D",reserved==0?"\uC5C6\uC74C":$"{reserved}\uAC1C"));snapshot=new(target,$"{StarterProcessingContentV3.GetResourceDisplayName(stack.ResourceType)} \u00D7{stack.Amount}","\uBC14\uB2E5 \uC790\uC6D0",reserved>0?"\uC6B4\uBC18 \uB610\uB294 \uC0AC\uC6A9 \uC911":"\uC6B4\uBC18 \uB300\uAE30",rows.AsReadOnly(),_resources.GroundStacks.Revision+_resources.AmountReservations.Revision);return true;
            case SelectionTargetKindV3.Equipment:
                if(_equipment==null||!_equipment.TryGetInstance(target.StableTargetId,out var equipmentInstance)||equipmentInstance==null||!_equipment.Definitions.TryGetDefinition(equipmentInstance.EquipmentDefinitionId,out var equipmentDefinition)||equipmentDefinition==null)return false;
                rows.Add(new("\uC7A5\uCC29 \uBD80\uC704",EquipmentDisplayNamesV3.GetSlotDisplayName(equipmentDefinition.Slot)));rows.Add(new("\uD488\uC9C8",EquipmentDisplayNamesV3.GetQualityDisplayName(equipmentInstance.Quality)));foreach(var modifier in equipmentDefinition.Modifiers)if(EquipmentQualityResolverV3.TryEvaluateModifier(equipmentDefinition,equipmentInstance.Quality,modifier.ModifierKind,out double value))rows.Add(new("\uD575\uC2EC \uBCF4\uC815",$"{modifier.ModifierKind} {value:+0.##;-0.##;0}"));rows.Add(new("\uC81C\uC791\uC790",equipmentInstance.CrafterMercenaryId));rows.Add(new("\uC81C\uC791 \uB2A5\uB825",equipmentInstance.CrafterProductionSkillSnapshot.ToString()));rows.Add(new("\uD604\uC7AC \uC704\uCE58",equipmentInstance.LocationKind==EquipmentLocationKindV3.Storage?"\uBE44\uCD95":equipmentInstance.LocationKind==EquipmentLocationKindV3.Ground?"\uBC14\uB2E5":equipmentInstance.LocationKind.ToString()));string equipmentName=$"{EquipmentDisplayNamesV3.GetQualityDisplayName(equipmentInstance.Quality)} {equipmentDefinition.DisplayName}";snapshot=new(target,equipmentName,"\uC7A5\uBE44",_equipment.TryGetReservation(equipmentInstance.EquipmentInstanceId,out _)?"\uC608\uC57D \uC911":"\uC0AC\uC6A9 \uAC00\uB2A5",rows.AsReadOnly(),HashCode.Combine(equipmentInstance.LocationKind,equipmentInstance.GroundCell,equipmentInstance.StorageId,equipmentInstance.StorageCell));return true;
            case SelectionTargetKindV3.ConstructionBlueprint:
                if(!_construction.Blueprints.TryGet(target.StableTargetId,out var blueprint)||blueprint==null||!_construction.Definitions.TryGetDefinition(blueprint.DefinitionId,out var blueprintDefinition)||blueprintDefinition==null)return false;foreach(var requirement in blueprint.MaterialBuffer.GetRequiredMaterialsSnapshot()){int delivered=blueprint.MaterialBuffer.GetDeliveredAmount(requirement.ResourceType),missing=Math.Max(0,requirement.RequiredAmount-delivered);rows.Add(new(StarterProcessingContentV3.GetResourceDisplayName(requirement.ResourceType),$"{delivered} / {requirement.RequiredAmount}"+(missing>0?$" \u00B7 {missing}\uAC1C \uBD80\uC871":" \u00B7 \uC644\uB8CC")));}float work=blueprint.RequiredWorkSeconds>0?blueprint.RequiredWorkSeconds:blueprintDefinition.BaseConstructionDurationSeconds;rows.Add(new("\uC791\uC5C5 \uC9C4\uD589",$"{Mathf.Clamp(blueprint.ConstructionProgressSeconds/work*100,0,100):0}%"));if(blueprint.MaterialResourceType!=null)rows.Add(new("\uC7AC\uC9C8",StarterProcessingContentV3.GetResourceDisplayName(blueprint.MaterialResourceType.Value)));snapshot=new(target,ConstructionMaterialContentV3.GetStructureDisplayName(blueprintDefinition,blueprint.MaterialResourceType)+" \uAC74\uC124 \uC608\uC815\uC9C0","\uAC74\uC124 \uC791\uC5C5",BlueprintStatus(blueprint),rows.AsReadOnly(),blueprint.Revision);return true;
            case SelectionTargetKindV3.CompletedStructure:
                if(!_construction.Structures.TryGet(target.StableTargetId,out var structure)||structure==null||!_construction.Definitions.TryGetDefinition(structure.DefinitionId,out var structureDefinition)||structureDefinition==null)return false;rows.Add(new("\uB0B4\uAD6C\uB3C4",$"{structure.CurrentHealth:0} / {structure.MaxHealth:0}"));if(structure.MaterialResourceType!=null)rows.Add(new("\uC7AC\uC9C8",StarterProcessingContentV3.GetResourceDisplayName(structure.MaterialResourceType.Value)));string kind="\uC644\uC131 \uAC74\uCD95\uBB3C",status=_construction.Demolitions.Contains(structure.StructureId)?"\uCCA0\uAC70 \uB300\uAE30":"\uC815\uC0C1";long sourceRevision=_construction.Structures.OccupancyRevision;if(_production!=null&&_production.TryGetFacility(structure.StructureId,out var facility)&&facility!=null){kind="\uC0DD\uC0B0 \uC2DC\uC124";sourceRevision+=facility.Revision;string blockReason=_productionBlockReason?.Invoke(facility.FacilityId)??string.Empty;if(blockReason.Length>0){status=blockReason;sourceRevision=HashCode.Combine(sourceRevision,blockReason);}rows.Add(new("\uB300\uAE30 \uBA85\uB839",$"{facility.Queue.Count}\uAC74"));if(facility.Queue.Count>0){ProductionOrderSnapshotV3 order=facility.Queue[0];_production.TryGetRecipe(order.RecipeId,out var recipe);rows.Add(new("\uD604\uC7AC \uBA85\uB839",$"{recipe?.DisplayName??order.RecipeId} {order.CompletedBatches}/{order.RequestedBatches}\uD68C"));rows.Add(new("\uC791\uC5C5\uC790",order.AssignedMercenaryId??"\uC5C6\uC74C"));float progress=recipe==null||recipe.BaseWorkSeconds<=0?0:Mathf.Clamp(order.WorkProgressSeconds/recipe.BaseWorkSeconds*100,0,100);rows.Add(new("\uC9C4\uD589\uB3C4",$"{progress:0}%"));if(blockReason.Length==0)status=ProductionState(order.State);}if(_equipment!=null){IReadOnlyList<string> outputs=_equipment.GetEquipmentOutputInstanceIds(facility.FacilityId);rows.Add(new("\uC7A5\uBE44 \uCD9C\uB825",$"{outputs.Count} / {facility.EquipmentOutputCapacity}"));for(int i=0;i<outputs.Count&&i<4;i++)if(_equipment.TryGetInstance(outputs[i],out var output)&&output!=null&&_equipment.Definitions.TryGetDefinition(output.EquipmentDefinitionId,out var outputDefinition)&&outputDefinition!=null)rows.Add(new($"\uC644\uC131 \uC7A5\uBE44 {i+1}",$"{EquipmentDisplayNamesV3.GetQualityDisplayName(output.Quality)} {outputDefinition.DisplayName}"));if(outputs.Count>0&&_construction.Demolitions.Contains(structure.StructureId))status="\uC644\uC131\uB41C \uC7A5\uBE44\uB97C \uBA3C\uC800 \uAEBC\uB0B4\uC57C \uCCA0\uAC70\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.";}}snapshot=new(target,ConstructionMaterialContentV3.GetStructureDisplayName(structureDefinition,structure.MaterialResourceType),kind,status,rows.AsReadOnly(),sourceRevision);return true;
            default:return false;
        }
    }
    private static string BlueprintStatus(ConstructionBlueprintStateV3 blueprint)=>blueprint.Status switch{ConstructionBlueprintStatusV3.AwaitingMaterials=>blueprint.MaterialBuffer.GetTotalMissingAmount()>0?"\uC7AC\uB8CC \uC6B4\uBC18 \uB300\uAE30":"\uC791\uC5C5\uC790 \uBC30\uC815 \uB300\uAE30",ConstructionBlueprintStatusV3.ReadyToBuild=>"\uC791\uC5C5\uC790 \uBC30\uC815 \uB300\uAE30",ConstructionBlueprintStatusV3.UnderConstruction=>"\uAC74\uC124 \uC911",ConstructionBlueprintStatusV3.WaitingForFootprintClear=>"\uC644\uC131 \uACF5\uAC04 \uBE44\uC6B0\uAE30 \uB300\uAE30",_=>blueprint.Status.ToString()};
    private static string ProductionState(ProductionOrderStateV3 state)=>state switch{ProductionOrderStateV3.WaitingMaterials=>"\uC7AC\uB8CC \uC6B4\uBC18 \uC911",ProductionOrderStateV3.Ready=>"\uC791\uC5C5\uC790 \uBC30\uC815 \uB300\uAE30",ProductionOrderStateV3.Producing=>"\uC81C\uC791 \uC911",ProductionOrderStateV3.OutputBlocked=>"\uACB0\uACFC\uBB3C \uBC30\uCD9C \uB300\uAE30",_=>"\uB300\uAE30"};
}

public static class SelectionInspectSelfCheckV3
{
    public static bool TryValidate(out string reason){var resources=new ResourceSessionV3();var construction=new ConstructionSessionV3();var companies=new GameplayV3.Company.CompanySessionV3();var mercenaries=new GameplayV3.Mercenary.MercenarySessionV3(companies.CompanyRegistry);var stockpiles=new GameplayV3.Stockpile.StockpileSessionV3();var control=new GameplayV3.Control.MercenaryControlSessionV3(1,companies,mercenaries);var work=new MercenaryWorkSessionV3(1,companies,mercenaries,resources,stockpiles,control);var builder=new SelectionInspectSnapshotBuilderV3(resources,construction,work);if(builder.TryHit(new(new Vector2I(0,0)),1,out _)){reason="Empty cell unexpectedly hit.";return false;}reason="";return true;}
}
