using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Construction;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Needs;
using GameplayV3.Resources;
using GameplayV3.Stockpile;
using GameplayV3.Work;
using Godot;
using WorldV2;

namespace GameplayV3.Farming.Runtime;

public partial class FarmWorldOverlayV3:Node2D
{
    private FarmSessionV3? _farm;private WorldV2GridRenderer? _grid;private IReadOnlyList<(GlobalCellCoord Cell,bool Valid,bool Removing)> _preview=Array.Empty<(GlobalCellCoord,bool,bool)>();public int LastDrawnCellCount{get;private set;}public int LastPreviewCellCount{get;private set;}
    public void Initialize(FarmSessionV3 farm,WorldV2GridRenderer grid){_farm=farm;_grid=grid;ZIndex=2;farm.Plots.Changed+=Refresh;Refresh();}public override void _ExitTree(){if(_farm!=null)_farm.Plots.Changed-=Refresh;}public void Refresh()=>QueueRedraw();public void SetPreview(IReadOnlyList<(GlobalCellCoord Cell,bool Valid,bool Removing)> cells){_preview=cells;QueueRedraw();}public void ClearPreview(){if(_preview.Count==0)return;_preview=Array.Empty<(GlobalCellCoord,bool,bool)>();QueueRedraw();}
    public override void _Draw(){LastDrawnCellCount=0;LastPreviewCellCount=0;if(_farm==null||_grid==null)return;foreach(var crop in _farm.Plots.GetAllCrops()){DrawCrop(crop);LastDrawnCellCount++;}foreach(var item in _preview){Color c=!item.Valid?new(.9f,.18f,.18f,.35f):item.Removing?new(.92f,.75f,.18f,.28f):new(.52f,.78f,.25f,.28f);Rect2 rect=CellRect(item.Cell.Value);DrawRect(rect,c);DrawRect(rect,c.Lightened(.18f),false,1);LastPreviewCellCount++;}}
    private void DrawCrop(CropCellStateV3 crop){Rect2 rect=CellRect(crop.Cell);DrawRect(rect,new Color(.33f,.22f,.12f,.42f));DrawRect(rect,new Color(.55f,.40f,.20f,.64f),false,.8f);Vector2 center=rect.GetCenter();if(crop.Stage==CropStageV3.Empty)return;float size=crop.Stage==CropStageV3.Mature?7:3+crop.GrowthNormalized*4;Color leaf=crop.Stage==CropStageV3.Mature?new(.13f,.48f,.16f):new(.28f,.68f,.25f);DrawCircle(center+new Vector2(-3,0),size,leaf);DrawCircle(center+new Vector2(3,1),size*.82f,leaf.Darkened(.08f));if(crop.Stage==CropStageV3.Mature)DrawCircle(center+new Vector2(7,-7),2,new Color(1f,.9f,.32f));}
    private Rect2 CellRect(Vector2I cell)=>new(cell.X*_grid!.TileSize,cell.Y*_grid.TileSize,_grid.TileSize,_grid.TileSize);
}

public partial class FarmDesignationControllerV3:Node
{
    public const int MaxCellsPerDesignation=256;private FarmSessionV3? _farm;private ConstructionSessionV3? _construction;private ResourceSessionV3? _resources;private StockpileSessionV3? _stockpiles;private IMercenaryNavigationWorldQueryV3? _query;private WorldV2GridRenderer? _grid;private WorldManagerV2? _manager;private FarmWorldOverlayV3? _overlay;private bool _dragging;private Vector2 _start;public bool Active{get;private set;}public event Action<bool>? ActiveChanged;
    public void Initialize(FarmSessionV3 farm,ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,IMercenaryNavigationWorldQueryV3 query,WorldV2GridRenderer grid,WorldManagerV2 manager,FarmWorldOverlayV3 overlay){_farm=farm;_construction=construction;_resources=resources;_stockpiles=stockpiles;_query=query;_grid=grid;_manager=manager;_overlay=overlay;}
    public void SetActive(bool active){if(Active==active)return;Active=active;_dragging=false;_overlay?.ClearPreview();ActiveChanged?.Invoke(active);_manager?.UpdateDebugHud(active?"감자밭 지정":"감자밭 지정 종료");}
    public bool TryHandleInput(InputEvent e){if(!Active)return false;if(e is InputEventKey key&&key.Pressed&&!key.Echo&&key.Keycode==Key.Escape){SetActive(false);return true;}if(e is InputEventMouseButton b){if(b.ButtonIndex==MouseButton.Right&&b.Pressed){SetActive(false);return true;}if(b.ButtonIndex==MouseButton.Left){if(b.Pressed){_dragging=true;_start=b.Position;UpdatePreview(b.Position,b.ShiftPressed);return true;}if(_dragging){Commit(b.Position,b.ShiftPressed);_dragging=false;return true;}}}if(e is InputEventMouseMotion m&&_dragging){UpdatePreview(m.Position,Input.IsKeyPressed(Key.Shift));return true;}return false;}
    private void UpdatePreview(Vector2 end,bool remove)=>_overlay?.SetPreview(Build(end,remove));
    private IReadOnlyList<(GlobalCellCoord Cell,bool Valid,bool Removing)> Build(Vector2 end,bool remove){List<(GlobalCellCoord,bool,bool)> result=new();Vector2 a=GetViewport().GetCanvasTransform().AffineInverse()*_start,b=GetViewport().GetCanvasTransform().AffineInverse()*end;Vector2I ca=_grid!.WorldToCell(a),cb=_grid.WorldToCell(b);for(int y=Math.Min(ca.Y,cb.Y);y<=Math.Max(ca.Y,cb.Y)&&result.Count<MaxCellsPerDesignation;y++)for(int x=Math.Min(ca.X,cb.X);x<=Math.Max(ca.X,cb.X)&&result.Count<MaxCellsPerDesignation;x++){GlobalCellCoord cell=new(new(x,y));bool valid=remove?CanRemove(cell):FarmDesignationValidationV3.CanAdd(cell,_manager!.LocalCompanyId,_farm!,_construction!,_resources!,_stockpiles!,_query!,out _);result.Add((cell,valid,remove));}return result.AsReadOnly();}
    private bool CanRemove(GlobalCellCoord cell)=>_farm!.Plots.TryGetCrop(cell,out var crop)&&crop?.CompanyId==_manager!.LocalCompanyId&&crop.Stage==CropStageV3.Empty&&!_farm.Reservations.IsReserved(cell);
    private void Commit(Vector2 end,bool remove){var preview=Build(end,remove);var valid=preview.Where(x=>x.Valid).Select(x=>x.Cell).ToList();_overlay?.ClearPreview();if(valid.Count==0){_manager?.UpdateDebugHud("InvalidFarmCell");return;}if(remove){int removed=0;foreach(var cell in valid)if(_farm!.Plots.TryRemoveEmpty(cell,_farm.Reservations,out _))removed++;_manager?.UpdateDebugHud($"감자밭 {removed}칸 제거");return;}if(_farm!.Plots.TryCreate(_manager!.LocalCompanyId,CropCatalogV3.PotatoCropId,valid,FarmSessionV3.MaxFarmCellsPerCompany,out var plot,out string reason))_manager.UpdateDebugHud($"감자밭 {plot!.CellCount}칸 지정");else _manager.UpdateDebugHud(reason);}
}

public partial class FarmGrowthRuntimeV3:Node
{
    private FarmSessionV3? _farm;private float _accumulator;public void Initialize(FarmSessionV3 farm)=>_farm=farm;public override void _PhysicsProcess(double delta){if(_farm==null)return;_accumulator+=Math.Max(0,(float)delta);int steps=0;while(_accumulator>=1&&steps<4){_accumulator-=1;TickOneSecond();steps++;}}
    public void AdvanceForTest(float seconds){int whole=(int)MathF.Floor(Math.Max(0,seconds));for(int i=0;i<whole;i++)TickOneSecond();}
    private void TickOneSecond(){if(_farm==null)return;bool changed=false;foreach(var crop in _farm.Plots.GetGrowingCrops())if(_farm.Crops.TryGet(crop.CropDefinitionId,out var definition)&&definition!=null)changed|=crop.AdvanceGrowth(1,definition.GrowthDurationSeconds);_farm.Diagnostics.GrowthTickCount++;_farm.Diagnostics.LastGrowthTickDuration=1;if(changed)_farm.Plots.NotifyCropChanged();}
}

public sealed class FarmingWorkCoordinatorV3
{
    private readonly FarmSessionV3 _farm;private readonly ResourceSessionV3 _resources;private readonly MercenaryWorkSessionV3 _work;private readonly MercenaryControlSessionV3 _control;private readonly MercenarySessionV3 _mercenaries;private readonly IMercenaryNavigationWorldQueryV3 _query;private readonly string _player,_company;private Func<string,float>? _needsMultiplier;private long _revision;public event Action? Changed;public event Action? ResourcesChanged;
    public FarmingWorkCoordinatorV3(FarmSessionV3 farm,ResourceSessionV3 resources,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,string player,string company){_farm=farm;_resources=resources;_work=work;_control=control;_mercenaries=mercenaries;_query=query;_player=player;_company=company;}public void AttachNeedsMultiplier(Func<string,float> value)=>_needsMultiplier=value;public int ActiveCount=>_farm.Works.Count;
    public bool TryIssue(GlobalCellCoord cell,IReadOnlyList<string> selected,out string reason){if(!_farm.Plots.TryGetCrop(cell,out var crop)||crop==null||crop.CompanyId!=_company){reason="FarmCellMissing";return false;}FarmingActionV3 action=crop.Stage switch{CropStageV3.Empty=>FarmingActionV3.Sowing,CropStageV3.Mature=>FarmingActionV3.Harvesting,_=>(FarmingActionV3)(-1)};if((int)action<0){reason="CropNotMature";return false;}if(action==FarmingActionV3.Sowing&&_resources.GroundStacks.GetStacksAtCell(cell).Count>0){reason="GroundStackBlocksSowing";return false;}if(_farm.Reservations.IsReserved(cell)){reason="FarmCellBusy";return false;}if(!SelectWorker(selected,cell,action,out string worker,out var profile,out reason))return false;if(!_work.CanStartFor(worker,action==FarmingActionV3.Sowing?WorkTypeV3.Sowing:WorkTypeV3.Harvesting,out reason))return false;if(!_farm.Crops.TryGet(crop.CropDefinitionId,out var definition)||definition==null){reason="CropMissing";return false;}float factor=.75f+profile!.WorkSkills.Farming*.025f;float rate=MercenaryDerivedStatsCalculatorV3.Calculate(profile).WorkSpeedMultiplier*factor;float required=(action==FarmingActionV3.Sowing?definition.BaseSowingDurationSeconds:definition.BaseHarvestDurationSeconds)/rate;string id=WorkRequestIdFactoryV3.Create();long revision=++_revision;FarmingWorkStateV3 state=new(){WorkRequestId=id,MercenaryId=worker,FarmPlotId=crop.FarmPlotId,TargetCell=cell,CropDefinitionId=crop.CropDefinitionId,Action=action,RequiredDurationSeconds=required,CropRevisionAtStart=crop.Revision,Revision=revision,FarmingSkill=profile.WorkSkills.Farming,BaseExecutionRate=rate};_work.NotifyExternalWorkSupersede(worker);_work.CancelForDirectMove(worker);_control.SupersedeDirectMovementForWork(worker);if(!_farm.Reservations.TryReserve(new(cell,crop.FarmPlotId,worker,id,action,DateTime.UtcNow,revision),out reason)||!_farm.Works.TryAdd(state,out reason)){_farm.Reservations.ReleaseByWorkRequest(id);return false;}if(!_mercenaries.Registry.TryGetState(worker,out var workerState)||workerState==null){Fail(state,"WorkerRemoved");reason="WorkerRemoved";return false;}if(workerState.CurrentCell.Value==cell.Value){BeginWork(state,workerState);reason=string.Empty;return true;}if(!_control.ExternalMovements.TryRequest(worker,workerState.CurrentCell,cell,MovementRequestSourceTypeV3.Work,id,_control.SessionRevision,revision,_control.Movements,out var movement,out reason)||movement==null){Fail(state,reason);return false;}state.MovementRequestId=movement.MovementRequestId;Changed?.Invoke();reason=string.Empty;return true;}
    public bool TryHandleMovementResult(MercenaryMovementResultV3 result){if(!_farm.Works.TryGet(result.Request.MercenaryId,out var work)||work==null||work.WorkRequestId!=result.Request.SourceId||work.Revision!=result.Request.SourceRevision)return false;if(work.MovementRequestId!=result.Request.MovementRequestId||!result.Succeeded||!_mercenaries.Registry.TryGetState(work.MercenaryId,out var worker)||worker==null||worker.CurrentCell.Value!=work.TargetCell.Value||result.Request.DestinationCell.Value!=work.TargetCell.Value){Fail(work,result.FailureReason.Length>0?result.FailureReason:"FarmingArrivalMismatch");return true;}if(!ValidateAtArrival(work,out string reason)){Fail(work,reason);return true;}BeginWork(work,worker);return true;}
    public void Tick(float delta){foreach(var work in _farm.Works.GetAll().ToList()){if(work.Phase is not (FarmingWorkPhaseV3.Sowing or FarmingWorkPhaseV3.Harvesting))continue;if(!ValidateWorking(work,out string reason)){Fail(work,reason);continue;}work.ProgressSeconds+=Math.Max(0,delta)*Math.Clamp(_needsMultiplier?.Invoke(work.MercenaryId)??1f,.1f,2f);if(work.ProgressSeconds<work.RequiredDurationSeconds){Changed?.Invoke();continue;}if(work.Action==FarmingActionV3.Sowing)CompleteSowing(work);else CompleteHarvest(work);}}
    public bool Cancel(string mercenary,string reason){if(!_farm.Works.TryGet(mercenary,out var work)||work==null)return false;Fail(work,reason,FarmingWorkPhaseV3.Cancelled);return true;}public bool TryGet(string mercenary,out FarmingWorkStateV3? state)=>_farm.Works.TryGet(mercenary,out state);
    private bool SelectWorker(IReadOnlyList<string> selected,GlobalCellCoord target,FarmingActionV3 action,out string worker,out MercenaryProfileV3? profile,out string reason){worker="";profile=null;var candidates=new List<(string Id,MercenaryProfileV3 Profile,float Rate,float Distance)>();foreach(string id in selected)if(_mercenaries.CanPlayerControlMercenary(_player,id)&&_mercenaries.Registry.TryGetMercenary(id,out var p,out var s)&&p!=null&&s!=null&&s.CompanyId==_company){float rate=MercenaryDerivedStatsCalculatorV3.Calculate(p).WorkSpeedMultiplier*(.75f+p.WorkSkills.Farming*.025f);candidates.Add((id,p,rate,MercenaryMovementCostPolicyV3.Octile(s.CurrentCell.Value,target.Value)));}var best=candidates.OrderByDescending(x=>x.Rate).ThenBy(x=>x.Distance).ThenBy(x=>x.Id,StringComparer.Ordinal).FirstOrDefault();if(best.Profile==null){reason="NoEligibleWorker";return false;}worker=best.Id;profile=best.Profile;reason=string.Empty;return true;}
    private bool ValidateAtArrival(FarmingWorkStateV3 work,out string reason){if(!_farm.Plots.TryGetCrop(work.TargetCell,out var crop)||crop==null||crop.FarmPlotId!=work.FarmPlotId){reason="FarmCellMissing";return false;}if(!_farm.Reservations.IsReservedBy(work.TargetCell,work.WorkRequestId)){reason="FarmReservationLost";return false;}if(work.Action==FarmingActionV3.Sowing){if(crop.Stage!=CropStageV3.Empty){reason="CropCellNotEmpty";return false;}if(_resources.GroundStacks.GetStacksAtCell(work.TargetCell).Count>0){reason="GroundStackBlocksSowing";return false;}}else if(crop.Stage!=CropStageV3.Mature||crop.Revision!=work.CropRevisionAtStart){reason="CropRevisionChanged";return false;}reason=string.Empty;return true;}
    private bool ValidateWorking(FarmingWorkStateV3 work,out string reason)=>ValidateAtArrival(work,out reason);
    private void BeginWork(FarmingWorkStateV3 work,MercenaryStateV3 worker){work.Phase=work.Action==FarmingActionV3.Sowing?FarmingWorkPhaseV3.Sowing:FarmingWorkPhaseV3.Harvesting;work.ProgressSeconds=0;worker.TrySetActivityState(MercenaryActivityStateV3.Working,out _);Changed?.Invoke();}
    private void CompleteSowing(FarmingWorkStateV3 work){if(!_farm.Plots.TryGetCrop(work.TargetCell,out var crop)||crop==null||!crop.BeginGrowing()){Fail(work,"CropCellNotEmpty");return;}_farm.Plots.NotifyCropChanged();_farm.Diagnostics.CompletedSowingCount++;Finish(work);}
    private void CompleteHarvest(FarmingWorkStateV3 work){if(!_farm.Plots.TryGetCrop(work.TargetCell,out var crop)||crop==null||crop.Stage!=CropStageV3.Mature||!_farm.Crops.TryGet(work.CropDefinitionId,out var definition)||definition==null){Fail(work,"CropNotMature");return;}if(!_resources.GroundStacks.TryAddOrMerge(definition.HarvestResourceType,definition.HarvestYieldAmount,work.TargetCell,out var stack,out _,out string reason)||stack==null){Fail(work,"HarvestOutputFailed");return;}if(!_resources.GenerationLedger.TryRecord(definition.HarvestResourceType,definition.HarvestYieldAmount,"Harvest",work.MercenaryId,work.WorkRequestId,work.FarmPlotId,work.TargetCell)){_resources.GroundStacks.TryTakeAmount(stack.ResourceStackId,definition.HarvestYieldAmount,out _,out _,out _,out _);Fail(work,"GenerationLedgerFailed");return;}if(!crop.ResetAfterHarvest()){Fail(work,"CropRevisionChanged");return;}_farm.Plots.NotifyCropChanged();_farm.Diagnostics.CompletedHarvestCount++;ResourcesChanged?.Invoke();Finish(work);}
    private void Finish(FarmingWorkStateV3 work){work.Phase=FarmingWorkPhaseV3.Completed;_farm.Reservations.ReleaseByWorkRequest(work.WorkRequestId);_farm.Works.Remove(work.MercenaryId);if(_mercenaries.Registry.TryGetState(work.MercenaryId,out var state)&&state!=null)state.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);Changed?.Invoke();}
    private void Fail(FarmingWorkStateV3 work,string reason,FarmingWorkPhaseV3 phase=FarmingWorkPhaseV3.Failed){work.Phase=phase;work.FailureReason=reason;_farm.Diagnostics.LastFailureReason=reason;_farm.Reservations.ReleaseByWorkRequest(work.WorkRequestId);_control.ExternalMovements.Cancel(work.MercenaryId,reason,_control.Movements);_farm.Works.Remove(work.MercenaryId);if(_mercenaries.Registry.TryGetState(work.MercenaryId,out var state)&&state!=null&&!_control.Movements.TryGet(work.MercenaryId,out _))state.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);Changed?.Invoke();}
}
