using System;
using System.Collections.Generic;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Mercenary.Runtime;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Resources.Runtime;
using GameplayV3.Session;
using GameplayV3.Stockpile;
using Godot;
using WorldV2;

namespace GameplayV3.Work.Runtime;

public partial class MercenaryWorkRuntimeV3 : Node
{
    private MercenaryWorkSessionV3? _work;private MercenaryControlSessionV3? _control;private ResourceSessionV3? _resources;private MercenarySessionV3? _mercenaries;private IMercenaryNavigationWorldQueryV3? _query;private ResourceNodeViewRegistryV3? _nodeViews;private GroundResourceStackViewRegistryV3? _stackViews;private MercenaryViewRegistryV3? _mercenaryViews;private Node2D? _stackContainer;private WorldV2GridRenderer? _grid;private WorldManagerV2? _manager;private readonly GatheringWorkSettingsV3 _settings=new();
    private readonly Dictionary<string,(string Node,string Mercenary)> _trackedExecutions=new(StringComparer.Ordinal);private readonly Dictionary<string,string> _trackedHauling=new(StringComparer.Ordinal);
    public void Initialize(MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,ResourceSessionV3 resources,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,ResourceNodeViewRegistryV3 nodeViews,GroundResourceStackViewRegistryV3 stackViews,MercenaryViewRegistryV3 mercenaryViews,Node2D stackContainer,WorldV2GridRenderer grid,WorldManagerV2 manager)
    {_work=work;_control=control;_resources=resources;_mercenaries=mercenaries;_query=query;_nodeViews=nodeViews;_stackViews=stackViews;_mercenaryViews=mercenaryViews;_stackContainer=stackContainer;_grid=grid;_manager=manager;RestoreVisuals();}
    public override void _PhysicsProcess(double delta)
    {if(_work==null||_control==null||_resources==null||_mercenaries==null||_query==null||!GameplaySessionV3.IsCurrentWorkSession(_work))return;DrainMovementResults();foreach(MercenaryWorkExecutionStateV3 execution in _work.GetActiveExecutions()){_trackedExecutions[execution.WorkRequestId]=(execution.ResourceNodeId,execution.MercenaryId);TickExecution(execution,(float)delta);}foreach(HaulingWorkExecutionStateV3 execution in _work.GetActiveHaulingExecutions()){_trackedHauling[execution.WorkRequestId]=execution.MercenaryId;TickHauling(execution,(float)delta);}CleanupTerminalVisuals();}
    private void DrainMovementResults(){while(_control!.ExternalMovements.TryDequeueResult(out MercenaryMovementResultV3? result)){if(result==null||result.Request.SourceType!=MovementRequestSourceTypeV3.Work)continue;if(_work!.TryGetHaulingExecution(result.Request.SourceId,out HaulingWorkExecutionStateV3? hauling)&&hauling!=null&&hauling.Revision==result.Request.SourceRevision){ApplyHaulingMovementResult(hauling,result);continue;}if(!_work.IsCurrentExecution(result.Request.SourceId,result.Request.SourceRevision)||!_work.TryGetExecution(result.Request.SourceId,out MercenaryWorkExecutionStateV3? execution)||execution==null)continue;if(result.Succeeded){if(!_mercenaries!.Registry.TryGetState(execution.MercenaryId,out MercenaryStateV3? state)||state==null||execution.SelectedApproachCell==null||state.CurrentCell.Value!=execution.SelectedApproachCell.Value.Value){_work.Fail(execution.WorkRequestId,"MovementFailed");continue;}execution.Phase=WorkExecutionPhaseV3.Working;if(_work.TryGetRequest(execution.WorkRequestId,out WorkRequestV3? request)&&request!=null)request.Status=WorkRequestStatusV3.Working;state.TrySetActivityState(MercenaryActivityStateV3.Working,out _);SetWorkerFeedback(execution);GD.Print($"[WorkCoreV3] Working started request={execution.WorkRequestId} mercenary={execution.MercenaryId}");}else{execution.CurrentCandidateIndex++;execution.SelectedApproachCell=null;execution.MovementRequestId=string.Empty;execution.Phase=WorkExecutionPhaseV3.SelectingApproach;}}}
    private void TickExecution(MercenaryWorkExecutionStateV3 execution,float delta)
    {if(!_work!.TryGetRequest(execution.WorkRequestId,out WorkRequestV3? request)||request==null)return;if(!_resources!.Nodes.TryGet(execution.ResourceNodeId,out ResourceNodeStateV3? node)||node==null){_work.Fail(execution.WorkRequestId,"TargetRemoved");return;}if(!_work.Reservations.IsReservedBy(node.ResourceNodeId,execution.WorkRequestId)){_work.Fail(execution.WorkRequestId,"ReservationLost");return;}if(execution.Phase==WorkExecutionPhaseV3.SelectingApproach){StartNextApproach(execution,request);return;}if(execution.Phase==WorkExecutionPhaseV3.WaitingForPath&&_control!.ExternalMovements.TryGetActive(execution.MercenaryId,out MercenaryMovementRequestV3? movement)&&movement!=null&&movement.Status==MercenaryMovementRequestStatusV3.Moving){execution.Phase=WorkExecutionPhaseV3.MovingToApproach;request.Status=WorkRequestStatusV3.MovingToTarget;}if(execution.Phase!=WorkExecutionPhaseV3.Working)return;TickWorking(execution,request,node,delta);}
    private void StartNextApproach(MercenaryWorkExecutionStateV3 execution,WorkRequestV3 request)
    {if(execution.CurrentCandidateIndex>=execution.CandidateApproachCells.Count){_work!.Fail(execution.WorkRequestId,"NoReachableApproachCell");return;}if(!_mercenaries!.Registry.TryGetState(execution.MercenaryId,out MercenaryStateV3? state)||state==null){_work!.Fail(execution.WorkRequestId,"WorkerRemoved");return;}GlobalCellCoord candidate=execution.CandidateApproachCells[execution.CurrentCandidateIndex];GlobalCellCoord start=_control!.Movements.TryGet(execution.MercenaryId,out MercenaryMovementStateV3? active)&&active!=null?active.ToCell:state.CurrentCell;if(!_control.ExternalMovements.TryRequest(execution.MercenaryId,start,candidate,MovementRequestSourceTypeV3.Work,execution.WorkRequestId,_work!.SessionRevision,execution.Revision,_control.Movements,out MercenaryMovementRequestV3? movement,out string reason)||movement==null){_work.Fail(execution.WorkRequestId,reason);return;}execution.SelectedApproachCell=candidate;execution.MovementRequestId=movement.MovementRequestId;execution.Phase=WorkExecutionPhaseV3.WaitingForPath;request.Status=WorkRequestStatusV3.MovingToTarget;if(_nodeViews!.TryGet(execution.ResourceNodeId,out ResourceNodeEntityV3? view)&&view!=null)view.SetReserved(true);GD.Print($"[WorkCoreV3] Approach movement request={execution.WorkRequestId} candidate={candidate} index={execution.CurrentCandidateIndex}");}
    private void TickWorking(MercenaryWorkExecutionStateV3 execution,WorkRequestV3 request,ResourceNodeStateV3 node,float delta)
    {if(!_mercenaries!.Registry.TryGetState(execution.MercenaryId,out MercenaryStateV3? state)||state==null||execution.SelectedApproachCell==null||state.CurrentCell.Value!=execution.SelectedApproachCell.Value.Value||Math.Max(Math.Abs(state.CurrentCell.Value.X-node.Cell.Value.X),Math.Abs(state.CurrentCell.Value.Y-node.Cell.Value.Y))!=1){_work!.Fail(execution.WorkRequestId,"InvalidWorkState");return;}execution.WorkProgressSeconds+=Math.Max(0,delta);SetWorkerFeedback(execution);int cycles=0;while(execution.WorkProgressSeconds>=execution.RequiredWorkSeconds&&cycles<_settings.MaxCyclesPerTick){execution.WorkProgressSeconds-=execution.RequiredWorkSeconds;cycles++;if(!node.TryHarvest(out int amount,out string reason)){_work!.Fail(execution.WorkRequestId,reason);return;}execution.CompletedCycleCount++;_work!.Diagnostics.CompletedCycleCount++;if(!_resources!.GroundStacks.TryAddStack(node.ProducedResourceType,amount,state.CurrentCell,out GroundResourceStackV3? stack,out bool merged,out reason)||stack==null){_work.Fail(execution.WorkRequestId,reason);return;}ResourceMaterializationCoordinatorV3.MaterializeOrRefreshStack(stack,_resources,_stackContainer!,_grid!,_stackViews!);ResourceMaterializationCoordinatorV3.RefreshNode(node.ResourceNodeId,_resources,_nodeViews!);_manager?.SetResourceRuntimeDiagnostics(_nodeViews!.GetIds(),_stackViews!.GetIds());SetWorkerFeedback(execution);GD.Print($"[WorkCoreV3] Gathering cycle request={request.WorkRequestId} yield={amount} remaining={node.RemainingAmount} stack={stack.Amount} merged={merged}");if(node.IsDepleted){_nodeViews!.TryRemove(node.ResourceNodeId);_manager?.SetResourceRuntimeDiagnostics(_nodeViews!.GetIds(),_stackViews!.GetIds());_work.Complete(execution.WorkRequestId);ClearWorkerFeedback(execution.MercenaryId);GD.Print($"[WorkCoreV3] Resource depleted node={node.ResourceNodeId} work={request.WorkRequestId}");_manager?.UpdateDebugHud("Gathering completed.");return;}}}
    private void TickHauling(HaulingWorkExecutionStateV3 execution,float delta)
    {
        if(!_work!.TryGetRequest(execution.WorkRequestId,out WorkRequestV3? request)||request==null||!_mercenaries!.Registry.TryGetState(execution.MercenaryId,out MercenaryStateV3? state)||state==null){_work.Fail(execution.WorkRequestId,"WorkerRemoved");return;}
        HaulingWorkPayloadV3 payload=execution.Payload;
        if(_stackViews!.TryGet(payload.SourceStackId,out GroundResourceStackEntityV3? sourceView)&&sourceView!=null)sourceView.SetReserved(true);
        if(!_work.SourceStackReservations.IsReservedBy(payload.SourceStackId,execution.WorkRequestId)){_work.Fail(execution.WorkRequestId,"SourceReservationLost");return;}
        if(execution.Phase==HaulingExecutionPhaseV3.PlanningTrip){PlanHaulingTrip(execution,state);return;}
        if(execution.Phase==HaulingExecutionPhaseV3.WaitingForSourcePath&&_control!.ExternalMovements.TryGetActive(execution.MercenaryId,out MercenaryMovementRequestV3? sourceMove)&&sourceMove?.Status==MercenaryMovementRequestStatusV3.Moving){execution.Phase=HaulingExecutionPhaseV3.MovingToSource;request.Status=WorkRequestStatusV3.MovingToTarget;}
        if(execution.Phase==HaulingExecutionPhaseV3.WaitingForDestinationPath&&_control!.ExternalMovements.TryGetActive(execution.MercenaryId,out MercenaryMovementRequestV3? destinationMove)&&destinationMove?.Status==MercenaryMovementRequestStatusV3.Moving){execution.Phase=HaulingExecutionPhaseV3.MovingToDestination;request.Status=WorkRequestStatusV3.MovingToTarget;}
        if(execution.Phase is not (HaulingExecutionPhaseV3.PickingUp or HaulingExecutionPhaseV3.DroppingOff))return;
        execution.HandlingProgressSeconds+=Math.Max(0,delta);SetHaulingFeedback(execution);if(execution.HandlingProgressSeconds<execution.RequiredHandlingSeconds)return;
        execution.HandlingProgressSeconds=execution.RequiredHandlingSeconds;if(execution.Phase==HaulingExecutionPhaseV3.PickingUp)CommitPickup(execution,state);else CommitDrop(execution,state);
    }
    private void PlanHaulingTrip(HaulingWorkExecutionStateV3 execution,MercenaryStateV3 state)
    {
        HaulingWorkPayloadV3 payload=execution.Payload;if(payload.RemainingRequestedAmount<=0){_work!.Complete(execution.WorkRequestId);ClearWorkerFeedback(execution.MercenaryId);return;}if(!_resources!.GroundStacks.TryGet(payload.SourceStackId,out GroundResourceStackV3? source)||source==null||source.Amount<1){_work!.Fail(execution.WorkRequestId,"InvalidSourceStack");return;}execution.PlannedPickupAmount=Math.Min(Math.Min(source.Amount,payload.RemainingRequestedAmount),execution.Calculation.MaxCarryUnits);if(execution.PlannedPickupAmount<1){_work!.Fail(execution.WorkRequestId,"SourceStackEmpty");return;}
        if(payload.DestinationCell==null||!_work!.Stockpiles.CellReservations.IsReservedBy(payload.DestinationCell.Value,execution.WorkRequestId)){if(!TryReserveNextDestination(execution,state.CurrentCell)){_work!.Fail(execution.WorkRequestId,"NoStockpileDestination");return;}}
        if(state.CurrentCell.Value==payload.SourceCell.Value){BeginHandling(execution,state,true);return;}RequestHaulingMovement(execution,state.CurrentCell,payload.SourceCell,true);
    }
    private void ApplyHaulingMovementResult(HaulingWorkExecutionStateV3 execution,MercenaryMovementResultV3 result)
    {
        if(!_mercenaries!.Registry.TryGetState(execution.MercenaryId,out MercenaryStateV3? state)||state==null){_work!.Fail(execution.WorkRequestId,"WorkerRemoved");return;}bool toSource=execution.Phase is HaulingExecutionPhaseV3.WaitingForSourcePath or HaulingExecutionPhaseV3.MovingToSource;if(!result.Succeeded){if(toSource){_work!.Fail(execution.WorkRequestId,"SourceMovementFailed");return;}if(TryReserveNextDestination(execution,state.CurrentCell)){RequestHaulingMovement(execution,state.CurrentCell,execution.Payload.DestinationCell!.Value,false);return;}_work!.Fail(execution.WorkRequestId,"DestinationMovementFailed");return;}
        GlobalCellCoord expected=toSource?execution.Payload.SourceCell:execution.Payload.DestinationCell??state.CurrentCell;if(state.CurrentCell.Value!=expected.Value){_work!.Fail(execution.WorkRequestId,toSource?"SourceMovementFailed":"DestinationMovementFailed");return;}BeginHandling(execution,state,toSource);
    }
    private void RequestHaulingMovement(HaulingWorkExecutionStateV3 execution,GlobalCellCoord start,GlobalCellCoord destination,bool toSource)
    {if(!_control!.ExternalMovements.TryRequest(execution.MercenaryId,start,destination,MovementRequestSourceTypeV3.Work,execution.WorkRequestId,_work!.SessionRevision,execution.Revision,_control.Movements,out MercenaryMovementRequestV3? movement,out string reason)||movement==null){_work.Fail(execution.WorkRequestId,reason);return;}execution.MovementRequestId=movement.MovementRequestId;execution.Phase=toSource?HaulingExecutionPhaseV3.WaitingForSourcePath:HaulingExecutionPhaseV3.WaitingForDestinationPath;}
    private void BeginHandling(HaulingWorkExecutionStateV3 execution,MercenaryStateV3 state,bool pickup)
    {execution.Phase=pickup?HaulingExecutionPhaseV3.PickingUp:HaulingExecutionPhaseV3.DroppingOff;execution.HandlingProgressSeconds=0;execution.RequiredHandlingSeconds=pickup?execution.Calculation.PickupDurationSeconds:execution.Calculation.DropDurationSeconds;state.TrySetActivityState(MercenaryActivityStateV3.Working,out _);if(_work!.TryGetRequest(execution.WorkRequestId,out WorkRequestV3? request)&&request!=null)request.Status=WorkRequestStatusV3.Working;SetHaulingFeedback(execution);}
    private void CommitPickup(HaulingWorkExecutionStateV3 execution,MercenaryStateV3 state)
    {
        HaulingWorkPayloadV3 payload=execution.Payload;if(state.CurrentCell.Value!=payload.SourceCell.Value||!_work!.SourceStackReservations.IsReservedBy(payload.SourceStackId,execution.WorkRequestId)||!_resources!.GroundStacks.TryGet(payload.SourceStackId,out GroundResourceStackV3? source)||source==null||source.ResourceType!=payload.ResourceType||_work!.Carries.ContainsCarry(execution.MercenaryId)){_work!.Fail(execution.WorkRequestId,"PickupFailed");return;}
        int planned=Math.Min(execution.PlannedPickupAmount,Math.Min(source.Amount,payload.RemainingRequestedAmount));if(!_work.Carries.CanBegin(execution.MercenaryId,planned,execution.Calculation.MaxCarryUnits,out string reason)||!_resources.GroundStacks.TryTakeAmount(payload.SourceStackId,planned,out int taken,out GroundResourceStackV3? changed,out bool removed,out reason)){_work.Fail(execution.WorkRequestId,"PickupFailed");return;}
        if(!_work.Carries.TryBeginCarry(execution.MercenaryId,execution.WorkRequestId,payload.ResourceType,taken,payload.SourceStackId,execution.Revision,execution.Calculation.MaxCarryUnits,out _,out reason)){_resources.GroundStacks.TryAddOrMerge(payload.ResourceType,taken,payload.SourceCell,out _,out _,out _);_work.Fail(execution.WorkRequestId,"CarryStateConflict");return;}
        payload.TotalPickedUp+=taken;if(removed)_stackViews!.TryRemove(payload.SourceStackId);else if(changed!=null)ResourceMaterializationCoordinatorV3.MaterializeOrRefreshStack(changed,_resources,_stackContainer!,_grid!,_stackViews!);SetHaulingFeedback(execution);GD.Print($"[HaulingV3] pickup request={execution.WorkRequestId} amount={taken} remaining={payload.RemainingRequestedAmount}");if(payload.DestinationCell==null){_work.Fail(execution.WorkRequestId,"NoStockpileDestination");return;}RequestHaulingMovement(execution,state.CurrentCell,payload.DestinationCell.Value,false);
    }
    private void CommitDrop(HaulingWorkExecutionStateV3 execution,MercenaryStateV3 state)
    {
        HaulingWorkPayloadV3 payload=execution.Payload;if(payload.DestinationCell==null||state.CurrentCell.Value!=payload.DestinationCell.Value.Value||!_work!.Stockpiles.CellReservations.IsReservedBy(payload.DestinationCell.Value,execution.WorkRequestId)||!_work!.Stockpiles.Zones.TryGetZoneAtCell(payload.DestinationCell.Value,out StockpileZoneStateV3? zone)||zone==null||zone.CompanyId!=_manager!.LocalCompanyId||!zone.Allows(payload.ResourceType)||!_work!.Carries.TryGetCarry(execution.MercenaryId,out MercenaryCarryStateV3? carry)||carry==null||carry.WorkRequestId!=execution.WorkRequestId){_work!.Fail(execution.WorkRequestId,"DropFailed");return;}
        foreach(GroundResourceStackV3 existing in _resources!.GroundStacks.GetStacksAtCell(payload.DestinationCell.Value))if(existing.ResourceType!=payload.ResourceType){_work.Fail(execution.WorkRequestId,"DestinationTypeConflict");return;}int dropped=carry.Amount;if(!_work.Carries.TryDropCarryAtCell(execution.MercenaryId,execution.WorkRequestId,payload.DestinationCell.Value,_resources.GroundStacks,out GroundResourceStackV3? stack,out string reason)||stack==null){_work.Fail(execution.WorkRequestId,"DropFailed");return;}ResourceMaterializationCoordinatorV3.MaterializeOrRefreshStack(stack,_resources,_stackContainer!,_grid!,_stackViews!);payload.RemainingRequestedAmount=Math.Max(0,payload.RemainingRequestedAmount-dropped);payload.TotalDroppedOff+=dropped;payload.CompletedTripCount++;_work.Stockpiles.CellReservations.TryRelease(payload.DestinationCell.Value,execution.WorkRequestId);GD.Print($"[HaulingV3] drop request={execution.WorkRequestId} amount={dropped} trip={payload.CompletedTripCount} remaining={payload.RemainingRequestedAmount}");ClearWorkerFeedback(execution.MercenaryId);if(payload.RemainingRequestedAmount==0){_work.Complete(execution.WorkRequestId);_manager.UpdateDebugHud("Hauling completed.");return;}payload.DestinationCell=null;payload.StockpileZoneId=null;execution.DestinationCandidateIndex=0;execution.Phase=HaulingExecutionPhaseV3.PlanningTrip;state.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);
    }
    private bool TryReserveNextDestination(HaulingWorkExecutionStateV3 execution,GlobalCellCoord origin)
    {
        HaulingWorkPayloadV3 payload=execution.Payload;if(payload.DestinationCell!=null)_work!.Stockpiles.CellReservations.TryRelease(payload.DestinationCell.Value,execution.WorkRequestId);for(int i=execution.DestinationCandidateIndex;i<execution.DestinationCandidates.Count;i++){execution.DestinationCandidateIndex=i+1;var candidate=execution.DestinationCandidates[i];if(!candidate.Zone.Allows(payload.ResourceType)||!_query!.IsWalkable(candidate.Cell.Value))continue;bool conflict=false;foreach(GroundResourceStackV3 stack in _resources!.GroundStacks.GetStacksAtCell(candidate.Cell))if(stack.ResourceType!=payload.ResourceType){conflict=true;break;}if(conflict)continue;StockpileCellReservationV3 reservation=new(candidate.Zone.StockpileZoneId,candidate.Cell,execution.WorkRequestId,execution.MercenaryId,payload.ResourceType,execution.Revision,DateTime.UtcNow);if(!_work!.Stockpiles.CellReservations.TryReserve(reservation,out _))continue;payload.StockpileZoneId=candidate.Zone.StockpileZoneId;payload.DestinationCell=candidate.Cell;return true;}return false;
    }
    private void SetHaulingFeedback(HaulingWorkExecutionStateV3 execution){if(_mercenaryViews!.TryGetView(execution.MercenaryId,out MercenaryEntityV3? view)&&view!=null){bool handling=execution.Phase is HaulingExecutionPhaseV3.PickingUp or HaulingExecutionPhaseV3.DroppingOff;view.SetWorkFeedback(handling,execution.RequiredHandlingSeconds<=0?0:execution.HandlingProgressSeconds/execution.RequiredHandlingSeconds);if(_work!.Carries.TryGetCarry(execution.MercenaryId,out MercenaryCarryStateV3? carry)&&carry!=null)view.SetCarryFeedback(carry.ResourceType,carry.Amount);else view.ClearCarryFeedback();}}
    public void RestoreVisuals(){if(_resources==null||_work==null)return;foreach(MercenaryWorkExecutionStateV3 execution in _work.GetActiveExecutions()){if(_nodeViews!.TryGet(execution.ResourceNodeId,out ResourceNodeEntityV3? node)&&node!=null)node.SetReserved(true);SetWorkerFeedback(execution);}foreach(HaulingWorkExecutionStateV3 execution in _work.GetActiveHaulingExecutions())SetHaulingFeedback(execution);RefreshAllStacks();}
    private void SetWorkerFeedback(MercenaryWorkExecutionStateV3 execution){if(_mercenaryViews!.TryGetView(execution.MercenaryId,out MercenaryEntityV3? view)&&view!=null)view.SetWorkFeedback(execution.Phase==WorkExecutionPhaseV3.Working,execution.RequiredWorkSeconds<=0?0:execution.WorkProgressSeconds/execution.RequiredWorkSeconds);}
    private void ClearWorkerFeedback(string id){if(_mercenaryViews!.TryGetView(id,out MercenaryEntityV3? view)&&view!=null){view.SetWorkFeedback(false,0);view.ClearCarryFeedback();}}
    private void CleanupTerminalVisuals(){List<string> removed=new();foreach(var pair in _trackedExecutions)if(!_work!.TryGetExecution(pair.Key,out _)){if(_nodeViews!.TryGet(pair.Value.Node,out ResourceNodeEntityV3? node)&&node!=null)node.SetReserved(false);ClearWorkerFeedback(pair.Value.Mercenary);removed.Add(pair.Key);}foreach(string id in removed)_trackedExecutions.Remove(id);removed.Clear();foreach(var pair in _trackedHauling)if(!_work!.TryGetHaulingExecution(pair.Key,out _)){ClearWorkerFeedback(pair.Value);removed.Add(pair.Key);}if(removed.Count>0)RefreshAllStacks();foreach(string id in removed)_trackedHauling.Remove(id);}
    private void RefreshAllStacks(){if(_resources==null||_stackViews==null||_stackContainer==null||_grid==null||_work==null)return;HashSet<string> live=new(_resources.GroundStacks.GetAllStackIds(),StringComparer.Ordinal);foreach(string id in _stackViews.GetIds())if(!live.Contains(id))_stackViews.TryRemove(id);foreach(string id in live)if(_resources.GroundStacks.TryGet(id,out GroundResourceStackV3? stack)&&stack!=null){GroundResourceStackEntityV3? view=ResourceMaterializationCoordinatorV3.MaterializeOrRefreshStack(stack,_resources,_stackContainer,_grid,_stackViews);view?.SetReserved(_work.SourceStackReservations.IsReserved(id));view?.SetStored(_work.Stockpiles.Zones.IsOwnedStockpileCell(_manager?.LocalCompanyId??string.Empty,stack.Cell));}_manager?.SetResourceRuntimeDiagnostics(_nodeViews!.GetIds(),_stackViews.GetIds());}
}
