using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using GameplayV3.Resources;
using GameplayV3.Time;

namespace GameplayV3.Objectives;

public enum FrontierSurvivalMilestoneIdV3{GatherWood,GatherStone,CreateStockpile,BuildBeds,EstablishFarm,CreateRoom,EstablishHeadquarters,SurviveThreeDays}
public sealed record FrontierSurvivalSettingsV3(int WoodTarget=30,int StoneTarget=15,int StockpileCellTarget=4,int BedTarget=3,int FarmCellTarget=9,int RoomTarget=1,int HeadquartersTarget=1,int SurvivalHoursTarget=72)
{public static FrontierSurvivalSettingsV3 Default{get;}=new();}
public sealed record FrontierSurvivalMilestoneSnapshotV3(FrontierSurvivalMilestoneIdV3 MilestoneId,string DisplayName,string Description,int CurrentValue,int TargetValue,bool CurrentConditionMet,bool CompletedOnce,double? CompletedAtWorldSeconds,long Revision,string LastChangedReason);
public sealed record FrontierSurvivalSnapshotV3(string CompanyId,double StartedAtWorldSeconds,double ElapsedWorldSeconds,int SurvivedHours,IReadOnlyList<FrontierSurvivalMilestoneSnapshotV3> Milestones,int CompletedMilestoneCount,int TotalMilestoneCount,bool IsCompleted,double? CompletedAtWorldSeconds,long Revision);
public sealed record FrontierSurvivalEventV3(string CompanyId,FrontierSurvivalMilestoneIdV3? MilestoneId,int PreviousValue,int CurrentValue,int TargetValue,bool CompletedOnce,long Revision,string Reason);
public sealed class FrontierSurvivalDiagnosticsV3{public long ObjectiveEventCount{get;internal set;}public int ObjectiveDirtyCount{get;internal set;}public long ObjectiveFullWorldScanCount{get;internal set;}public long DuplicateSubscriptionCount{get;internal set;}public long DuplicateCompletionEventCount{get;internal set;}public long EventCoalescedCount{get;internal set;}}

public sealed class FrontierSurvivalSessionV3:IDisposable
{
    private const int RecentLimit=16;
    private sealed class State{public State(int target){Target=target;}public int Current;public readonly int Target;public bool Completed;public double? CompletedAt;public long Revision;public string Reason="Initial";}
    private readonly SimulationClockSessionV3 _clock;private readonly Dictionary<FrontierSurvivalMilestoneIdV3,State> _states=new();private readonly Queue<FrontierSurvivalEventV3> _recent=new();private long _revision;private bool _disposed;private int _completionEvents;
    public FrontierSurvivalSessionV3(long sessionRevision,string companyId,SimulationClockSessionV3 clock,FrontierSurvivalSettingsV3? settings=null)
    {SessionRevision=sessionRevision;CompanyId=companyId;_clock=clock;Settings=settings??FrontierSurvivalSettingsV3.Default;StartedAtWorldSeconds=clock.ElapsedSimulationSeconds;_states[FrontierSurvivalMilestoneIdV3.GatherWood]=new(Settings.WoodTarget);_states[FrontierSurvivalMilestoneIdV3.GatherStone]=new(Settings.StoneTarget);_states[FrontierSurvivalMilestoneIdV3.CreateStockpile]=new(1);_states[FrontierSurvivalMilestoneIdV3.BuildBeds]=new(Settings.BedTarget);_states[FrontierSurvivalMilestoneIdV3.EstablishFarm]=new(Settings.FarmCellTarget);_states[FrontierSurvivalMilestoneIdV3.CreateRoom]=new(Settings.RoomTarget);_states[FrontierSurvivalMilestoneIdV3.EstablishHeadquarters]=new(Settings.HeadquartersTarget);_states[FrontierSurvivalMilestoneIdV3.SurviveThreeDays]=new(Settings.SurvivalHoursTarget);_clock.HourChanged+=OnHourChanged;ClockSubscriptionCount=1;}
    public long SessionRevision{get;}public string CompanyId{get;}public FrontierSurvivalSettingsV3 Settings{get;}public double StartedAtWorldSeconds{get;}public bool IsCompleted{get;private set;}public double? CompletedAtWorldSeconds{get;private set;}public bool IsDisposed=>_disposed;public int ClockSubscriptionCount{get;private set;}public int MilestoneCount=>_states.Count;public long Revision=>_revision;public FrontierSurvivalDiagnosticsV3 Diagnostics{get;}=new();
    public event Action<FrontierSurvivalEventV3>? MilestoneProgressChanged;public event Action<FrontierSurvivalEventV3>? MilestoneCompleted;public event Action<FrontierSurvivalEventV3>? FrontierSurvivalCompleted;
    public FrontierSurvivalSnapshotV3 GetSnapshot(){List<FrontierSurvivalMilestoneSnapshotV3> values=new(8);foreach(FrontierSurvivalMilestoneIdV3 id in Enum.GetValues<FrontierSurvivalMilestoneIdV3>())values.Add(ToSnapshot(id,_states[id]));return new(CompanyId,StartedAtWorldSeconds,Math.Max(0,_clock.ElapsedSimulationSeconds-StartedAtWorldSeconds),GetSurvivedHours(),new ReadOnlyCollection<FrontierSurvivalMilestoneSnapshotV3>(values),GetCompletedCount(),8,IsCompleted,CompletedAtWorldSeconds,_revision);}
    public bool TryGetMilestone(FrontierSurvivalMilestoneIdV3 id,out FrontierSurvivalMilestoneSnapshotV3? value){if(!_states.TryGetValue(id,out State? state)){value=null;return false;}value=ToSnapshot(id,state);return true;}public int GetCompletedCount(){int count=0;foreach(State state in _states.Values)if(state.Completed)count++;return count;}public int GetSurvivedHours()=>(int)Math.Floor(Math.Max(0,_clock.ElapsedSimulationSeconds-StartedAtWorldSeconds)/3600.0+1e-9);public IReadOnlyList<FrontierSurvivalEventV3> GetRecentEvents()=>Array.AsReadOnly(_recent.ToArray());
    internal void RecordGathered(string companyId,ResourceTypeV3 type,int amount,string reason){if(_disposed||companyId!=CompanyId||reason!="Gathering"||amount<=0)return;if(type==ResourceTypeV3.Wood)Increment(FrontierSurvivalMilestoneIdV3.GatherWood,amount,"GatheringWood");else if(type==ResourceTypeV3.Stone)Increment(FrontierSurvivalMilestoneIdV3.GatherStone,amount,"GatheringStone");}
    internal void UpdateStockpile(int qualifyingZoneCount)=>Set(FrontierSurvivalMilestoneIdV3.CreateStockpile,qualifyingZoneCount,"StockpileChanged");internal void UpdateBeds(int count)=>Set(FrontierSurvivalMilestoneIdV3.BuildBeds,count,"StructureChanged");internal void UpdateFarmCells(int count)=>Set(FrontierSurvivalMilestoneIdV3.EstablishFarm,count,"FarmChanged");internal void UpdateRooms(int count)=>Set(FrontierSurvivalMilestoneIdV3.CreateRoom,count,"RoomChanged");internal void UpdateHeadquarters(bool exists)=>Set(FrontierSurvivalMilestoneIdV3.EstablishHeadquarters,exists?1:0,"HeadquartersChanged");internal void UpdateSurvival()=>Set(FrontierSurvivalMilestoneIdV3.SurviveThreeDays,GetSurvivedHours(),"HourChanged");
    private void Increment(FrontierSurvivalMilestoneIdV3 id,int amount,string reason)=>Set(id,checked(_states[id].Current+amount),reason);
    private void Set(FrontierSurvivalMilestoneIdV3 id,int value,string reason)
    {State state=_states[id];value=Math.Max(0,value);if(state.Current==value)return;int previous=state.Current;state.Current=value;state.Revision++;state.Reason=reason;_revision++;bool newlyCompleted=!state.Completed&&value>=state.Target;if(newlyCompleted){state.Completed=true;state.CompletedAt=_clock.ElapsedSimulationSeconds;}FrontierSurvivalEventV3 evt=NewEvent(id,previous,state);Record(evt);MilestoneProgressChanged?.Invoke(evt);if(newlyCompleted)MilestoneCompleted?.Invoke(evt);TryComplete();}
    private void TryComplete(){if(IsCompleted||GetCompletedCount()!=_states.Count)return;IsCompleted=true;CompletedAtWorldSeconds=_clock.ElapsedSimulationSeconds;_revision++;_completionEvents++;FrontierSurvivalEventV3 evt=new(CompanyId,null,7,8,8,true,_revision,"FrontierSurvivalCompleted");Record(evt);FrontierSurvivalCompleted?.Invoke(evt);}
    private void OnHourChanged(SimulationClockEventV3 _)=>UpdateSurvival();private FrontierSurvivalEventV3 NewEvent(FrontierSurvivalMilestoneIdV3 id,int previous,State state)=>new(CompanyId,id,previous,state.Current,state.Target,state.Completed,_revision,state.Reason);private void Record(FrontierSurvivalEventV3 value){_recent.Enqueue(value);while(_recent.Count>RecentLimit)_recent.Dequeue();Diagnostics.ObjectiveEventCount++;}
    private static FrontierSurvivalMilestoneSnapshotV3 ToSnapshot(FrontierSurvivalMilestoneIdV3 id,State state)=>new(id,DisplayName(id),Description(id),state.Current,state.Target,state.Current>=state.Target,state.Completed,state.CompletedAt,state.Revision,state.Reason);
    public static string DisplayName(FrontierSurvivalMilestoneIdV3 id)=>id switch{FrontierSurvivalMilestoneIdV3.GatherWood=>"나무 확보",FrontierSurvivalMilestoneIdV3.GatherStone=>"돌 확보",FrontierSurvivalMilestoneIdV3.CreateStockpile=>"저장 구역 만들기",FrontierSurvivalMilestoneIdV3.BuildBeds=>"침대 준비",FrontierSurvivalMilestoneIdV3.EstablishFarm=>"감자밭 조성",FrontierSurvivalMilestoneIdV3.CreateRoom=>"폐쇄된 방 만들기",FrontierSurvivalMilestoneIdV3.EstablishHeadquarters=>"본부 수립",_=>"3일 생존"};
    public static string Description(FrontierSurvivalMilestoneIdV3 id)=>id switch{FrontierSurvivalMilestoneIdV3.GatherWood=>"채집으로 나무 30 확보",FrontierSurvivalMilestoneIdV3.GatherStone=>"채집으로 돌 15 확보",FrontierSurvivalMilestoneIdV3.CreateStockpile=>"4칸 이상 저장 구역",FrontierSurvivalMilestoneIdV3.BuildBeds=>"완성된 간이 침대 3개",FrontierSurvivalMilestoneIdV3.EstablishFarm=>"감자밭 9칸",FrontierSurvivalMilestoneIdV3.CreateRoom=>"유효한 폐쇄 공간",FrontierSurvivalMilestoneIdV3.EstablishHeadquarters=>"첫 본부 수립",_=>"게임 세계 시간 72시간 생존"};
    public void Dispose(){if(_disposed)return;_disposed=true;_clock.HourChanged-=OnHourChanged;ClockSubscriptionCount=0;MilestoneProgressChanged=null;MilestoneCompleted=null;FrontierSurvivalCompleted=null;}
}
