using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Construction;
using GameplayV3.Control;
using GameplayV3.Jobs;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Stockpile;
using GameplayV3.Work;
using WorldV2;
using Godot;

namespace GameplayV3.Production.Runtime;

internal enum ProductionWorkPhaseV3 { MoveToSource, MoveToFacility, MoveToWork, Working }
internal sealed class ProductionWorkStateV3
{public required string WorkId;public required string FacilityId;public required string MercenaryId;public required long Revision;public ProductionWorkPhaseV3 Phase;public JobCommandSourceV3 CommandSource;public string SourceStackId="";public GlobalCellCoord SourceCell;public ResourceTypeV3 ResourceType;public int Amount;public int MaxCarry;public float Speed=1;}
public readonly record struct ProductionWorkHudSnapshotV3(string WorkRequestId,string FacilityId,string Phase,string MercenaryId,JobCommandSourceV3 CommandSource);

public sealed class ProductionWorkCoordinatorV3
{
    private readonly ProductionSessionV3 _production;private readonly ConstructionSessionV3 _construction;private readonly ResourceSessionV3 _resources;private readonly StockpileSessionV3 _stockpiles;private readonly MercenaryWorkSessionV3 _work;private readonly MercenaryControlSessionV3 _control;private readonly MercenarySessionV3 _mercenaries;private readonly IMercenaryNavigationWorldQueryV3 _query;private readonly string _player,_company;private readonly Dictionary<string,ProductionWorkStateV3> _jobs=new(StringComparer.Ordinal);private readonly HashSet<string> _reservedFacilities=new(StringComparer.Ordinal);private Func<string,float>? _needsMultiplier;private long _revision;
    public ProductionWorkCoordinatorV3(ProductionSessionV3 production,ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,string player,string company){_production=production;_construction=construction;_resources=resources;_stockpiles=stockpiles;_work=work;_control=control;_mercenaries=mercenaries;_query=query;_player=player;_company=company;production.FacilityRemoved+=OnFacilityRemoved;}
    public event Action? ResourcesChanged;public int ActiveJobCount=>_jobs.Count;public int DirectJobCount=>_jobs.Values.Count(x=>x.CommandSource==JobCommandSourceV3.DirectOrder);public bool IsFacilityReserved(string facilityId)=>_reservedFacilities.Contains(facilityId);public void AttachWorkMultiplier(Func<string,float> value)=>_needsMultiplier=value;
    public bool HasApproach(string mercenaryId,string facilityId){if(!_production.TryGetFacility(facilityId,out var facility)||facility==null||!_construction.Structures.TryGet(facility.StructureId,out var structure)||structure==null||!_mercenaries.Registry.TryGetState(mercenaryId,out var state)||state==null)return false;return ConstructionApproachCellServiceV3.GetCandidates(structure.OccupiedCells,state.CurrentCell,_query).Count>0;}
    public bool TryIssue(string facilityId,IReadOnlyList<string> selected,out string reason)
    =>TryIssueCore(facilityId,selected,JobCommandSourceV3.Automatic,_production.SessionRevision,false,out _,out reason);
    public bool TryIssueDirect(string facilityId,IReadOnlyList<string> selected,long sessionRevision,out ProductionWorkHudSnapshotV3 snapshot,out string reason)
    =>TryIssueCore(facilityId,selected,JobCommandSourceV3.DirectOrder,sessionRevision,true,out snapshot,out reason);
    private bool TryIssueCore(string facilityId,IReadOnlyList<string> selected,JobCommandSourceV3 commandSource,long sessionRevision,bool readyOnly,out ProductionWorkHudSnapshotV3 snapshot,out string reason)
    {snapshot=default;if(sessionRevision!=_production.SessionRevision||sessionRevision!=_control.SessionRevision||sessionRevision!=_work.SessionRevision){reason="InvalidSession";return false;}if(_reservedFacilities.Contains(facilityId)){reason="FacilityReserved";return false;}if(!_production.TryGetFacility(facilityId,out var facility)||facility==null){reason="InvalidFacility";return false;}if(facility.CompanyId!=_company){reason="OwnershipDenied";return false;}if(facility.Queue.Count==0){reason="NoOrder";return false;}var order=facility.Queue[0];bool started;if(order.State==ProductionOrderStateV3.WaitingMaterials){if(readyOnly){reason="WaitingMaterials";return false;}started=TrySupply(facility,order,selected,commandSource,out reason);}else if(order.State==ProductionOrderStateV3.Ready)started=TryProduce(facility,order,selected,commandSource,out reason);else{reason=order.State==ProductionOrderStateV3.OutputBlocked?"OutputBlocked":"ProductionNotDispatchable";return false;}if(!started)return false;string worker=selected.FirstOrDefault(id=>TryGetHudSnapshot(id,out var value)&&value.FacilityId==facilityId)??string.Empty;return worker.Length>0&&TryGetHudSnapshot(worker,out snapshot);}
    public bool TryGetHudSnapshot(string mercenary,out ProductionWorkHudSnapshotV3 snapshot){foreach(var job in _jobs.Values)if(job.MercenaryId==mercenary){snapshot=new(job.WorkId,job.FacilityId,job.Phase.ToString(),job.MercenaryId,job.CommandSource);return true;}snapshot=default;return false;}
    public bool CancelForDirectMove(string mercenary){bool changed=false;foreach(var job in _jobs.Values.Where(x=>x.MercenaryId==mercenary).ToList()){Fail(job,"CancelledByDirectMove");changed=true;}return changed;}
    private bool TrySupply(ProductionFacilitySnapshotV3 facility,ProductionOrderSnapshotV3 order,IReadOnlyList<string> selected,JobCommandSourceV3 commandSource,out string reason)
    {reason="MissingRecipe";if(!_production.TryGetRecipe(order.RecipeId,out var recipe)||recipe==null)return false;Dictionary<ResourceTypeV3,int> delivered=facility.MaterialBuffer.ToDictionary(x=>x.ResourceType,x=>x.RequiredAmount);StructureMaterialRequirementV3 missing=recipe.Inputs.FirstOrDefault(x=>delivered.GetValueOrDefault(x.ResourceType)<x.RequiredAmount);int amountMissing=missing.RequiredAmount-delivered.GetValueOrDefault(missing.ResourceType);if(amountMissing<1){reason="MaterialsReady";return false;}GroundResourceStackV3? source=null;foreach(string id in _resources.GroundStacks.GetStackIdsByType(missing.ResourceType))if(_resources.GroundStacks.TryGet(id,out var s)&&s!=null&&_stockpiles.Zones.IsOwnedStockpileCell(_company,s.Cell)&&_resources.AmountReservations.GetAvailableAmount(id)>0&&!_work.SourceStackReservations.IsReserved(id)){source=s;break;}if(source==null){reason="NoStoredMaterials";return false;}if(!Select(selected,source.Cell,true,out string worker,out var profile,out reason))return false;string workId=WorkRequestIdFactoryV3.Create();long revision=++_revision;int max=HaulingWorkCalculatorV3.GetMaxCarryUnits(profile!),amount=Math.Min(amountMissing,Math.Min(max,_resources.AmountReservations.GetAvailableAmount(source.ResourceStackId)));if(!_work.SourceStackReservations.TryReserve(new GroundStackReservationV3(source.ResourceStackId,workId,worker,_company,amount,revision,DateTime.UtcNow),out reason))return false;ProductionWorkStateV3 job=new(){WorkId=workId,FacilityId=facility.FacilityId,MercenaryId=worker,Revision=revision,Phase=ProductionWorkPhaseV3.MoveToSource,CommandSource=commandSource,SourceStackId=source.ResourceStackId,SourceCell=source.Cell,ResourceType=missing.ResourceType,Amount=amount,MaxCarry=max};return Start(job,source.Cell,out reason);}
    private bool TryProduce(ProductionFacilitySnapshotV3 facility,ProductionOrderSnapshotV3 order,IReadOnlyList<string> selected,JobCommandSourceV3 commandSource,out string reason)
    {if(!_production.TryGetRecipe(order.RecipeId,out var recipe)||recipe==null){reason="MissingRecipe";return false;}if(!Select(selected,facility.AnchorCell,false,out string worker,out var profile,out reason))return false;if(!_construction.Structures.TryGet(facility.StructureId,out var structure)||structure==null){reason="InvalidStructure";return false;}var approaches=ConstructionApproachCellServiceV3.GetCandidates(structure.OccupiedCells,_mercenaries.Registry.TryGetState(worker,out var state)&&state!=null?state.CurrentCell:facility.AnchorCell,_query);if(approaches.Count==0){reason="NoPath";return false;}float score=MercenaryDerivedStatsCalculatorV3.GetWorkScore(profile!,MercenaryWorkSkillTypeV3.Production),speed=Math.Clamp(MercenaryDerivedStatsCalculatorV3.Calculate(profile!).WorkSpeedMultiplier*(.75f+score*.025f),.25f,3f);ProductionWorkStateV3 job=new(){WorkId=WorkRequestIdFactoryV3.Create(),FacilityId=facility.FacilityId,MercenaryId=worker,Revision=++_revision,Phase=ProductionWorkPhaseV3.MoveToWork,CommandSource=commandSource,Speed=speed};return Start(job,approaches[0],out reason);}
    private bool Start(ProductionWorkStateV3 job,GlobalCellCoord destination,out string reason){_work.NotifyExternalWorkSupersede(job.MercenaryId);_reservedFacilities.Add(job.FacilityId);_jobs.Add(job.WorkId,job);if(!_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)||state==null){reason="WorkerRemoved";Fail(job,reason);return false;}_control.SupersedeDirectMovementForWork(job.MercenaryId);if(!_control.ExternalMovements.TryRequest(job.MercenaryId,state.CurrentCell,destination,MovementRequestSourceTypeV3.Work,job.WorkId,_control.SessionRevision,job.Revision,_control.Movements,out _,out reason)){Fail(job,reason);return false;}return true;}
    public bool TryHandleMovementResult(MercenaryMovementResultV3 result)
    {if(!_jobs.TryGetValue(result.Request.SourceId,out var job)||job.Revision!=result.Request.SourceRevision)return false;if(!result.Succeeded){Fail(job,"MovementFailed");return true;}if(job.Phase==ProductionWorkPhaseV3.MoveToSource){Pickup(job);return true;}if(job.Phase==ProductionWorkPhaseV3.MoveToFacility){Deliver(job);return true;}if(job.Phase==ProductionWorkPhaseV3.MoveToWork){if(!_mercenaries.Registry.TryGetMercenary(job.MercenaryId,out var profile,out _)||profile==null){Fail(job,"InvalidCompletionWorker");return true;}if(!_production.TryBeginWork(job.FacilityId,job.MercenaryId,profile.WorkSkills.GetValue(MercenaryWorkSkillTypeV3.Production),out _,out string reason)){Fail(job,reason);return true;}job.Phase=ProductionWorkPhaseV3.Working;_mercenaries.Registry.TryGetState(job.MercenaryId,out var state);state?.TrySetActivityState(MercenaryActivityStateV3.Working,out _);return true;}return true;}
    private void Pickup(ProductionWorkStateV3 job){if(!_resources.GroundStacks.TryTakeAmount(job.SourceStackId,job.Amount,out int taken,out _,out _,out _)||!_work.Carries.TryBeginCarry(job.MercenaryId,job.WorkId,job.ResourceType,taken,job.SourceStackId,job.Revision,job.MaxCarry,out _,out _)){Fail(job,"PickupFailed");return;}_work.SourceStackReservations.TryRelease(job.SourceStackId,job.WorkId);if(!_production.TryGetFacility(job.FacilityId,out var f)||f==null){Fail(job,"FacilityRemoved");return;}job.Phase=ProductionWorkPhaseV3.MoveToFacility;Request(job,f.AnchorCell);ResourcesChanged?.Invoke();}
    private void Deliver(ProductionWorkStateV3 job){if(!_work.Carries.TryGetCarry(job.MercenaryId,out var carry)||carry==null||!_production.TryDeliverMaterial(job.FacilityId,carry.ResourceType,carry.Amount,out _)||!_work.Carries.TryClearCarry(job.MercenaryId,job.WorkId,out _)){Fail(job,"DeliveryFailed");return;}Finish(job);ResourcesChanged?.Invoke();}
    public void Tick(float delta){foreach(var job in _jobs.Values.Where(x=>x.Phase==ProductionWorkPhaseV3.Working).ToList()){if(!_mercenaries.Registry.TryGetMercenary(job.MercenaryId,out var profile,out var state)||profile==null||state==null||state.CompanyId!=_company){Fail(job,"InvalidCompletionWorker");continue;}float progress=delta*job.Speed*Math.Clamp(_needsMultiplier?.Invoke(job.MercenaryId)??1,.1f,2f);ProductionCompletionWorkerV3 worker=new(job.MercenaryId,state.CompanyId,profile.WorkSkills.GetValue(MercenaryWorkSkillTypeV3.Production),_production.SessionRevision,job.WorkId);if(!_production.TryAdvanceWork(job.FacilityId,progress,()=>FindOutput(job.FacilityId),worker,out bool complete,out string reason)){Fail(job,reason);continue;}if(complete){_production.TryEjectNextEquipmentOutput(job.FacilityId,()=>FindOutput(job.FacilityId),out _);Finish(job);}else if(reason is "OutputBlocked" or "EquipmentOutputBufferFull")Finish(job);}foreach(var f in _production.GetFacilities(_company).Where(x=>x.OutputBuffer.Count>0||x.EquipmentOutputInstanceIds.Count>0).Take(8)){if(f.OutputBuffer.Count>0)_production.TryFlushOutput(f.FacilityId,()=>FindOutput(f.FacilityId));if(f.EquipmentOutputInstanceIds.Count>0)_production.TryEjectNextEquipmentOutput(f.FacilityId,()=>FindOutput(f.FacilityId),out _);}}
    private GlobalCellCoord? FindOutput(string facility){if(!_production.TryGetFacility(facility,out var f)||f==null)return null;Vector2I[] offsets={Vector2I.Down,Vector2I.Right,Vector2I.Up,Vector2I.Left,new(1,1),new(-1,1),new(1,-1),new(-1,-1)};foreach(var offset in offsets){Vector2I cell=f.AnchorCell.Value+offset;if(_query.IsInsideWorld(cell)&&_query.IsWalkable(cell))return new(cell);}return null;}
    private bool Select(IReadOnlyList<string> selected,GlobalCellCoord target,bool hauling,out string worker,out MercenaryProfileV3? profile,out string reason){worker="";profile=null;foreach(string id in selected)if(_mercenaries.CanPlayerControlMercenary(_player,id)&&_mercenaries.Registry.TryGetMercenary(id,out var p,out var s)&&p!=null&&s!=null&&_work.CanStartFor(id,hauling?WorkTypeV3.Hauling:WorkTypeV3.Production,out _)){worker=id;profile=p;reason="";return true;}reason="NoEligibleWorker";return false;}
    private void Request(ProductionWorkStateV3 job,GlobalCellCoord destination){if(!_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)||state==null){Fail(job,"WorkerRemoved");return;}if(!_control.ExternalMovements.TryRequest(job.MercenaryId,state.CurrentCell,destination,MovementRequestSourceTypeV3.Work,job.WorkId,_control.SessionRevision,job.Revision,_control.Movements,out _,out string reason))Fail(job,reason);}
    private void Finish(ProductionWorkStateV3 job){_work.SourceStackReservations.ReleaseByWorkRequest(job.WorkId);_reservedFacilities.Remove(job.FacilityId);_jobs.Remove(job.WorkId);_mercenaries.Registry.TryGetState(job.MercenaryId,out var state);state?.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);}
    private void Fail(ProductionWorkStateV3 job,string reason){if(_work.Carries.TryGetCarry(job.MercenaryId,out var carry)&&carry?.WorkRequestId==job.WorkId&&_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)&&state!=null)_work.Carries.TryDropCarryAtCell(job.MercenaryId,job.WorkId,state.CurrentCell,_resources.GroundStacks,out _,out _);_control.ExternalMovements.Cancel(job.MercenaryId,reason,_control.Movements);Finish(job);ResourcesChanged?.Invoke();}
    private void OnFacilityRemoved(ProductionEventV3 e){foreach(var job in _jobs.Values.Where(x=>x.FacilityId==e.FacilityId).ToList())Fail(job,"FacilityRemoved");}
}
