using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Resources.Runtime;
using GameplayV3.Stockpile;
using GameplayV3.Work;
using Godot;
using WorldV2;

namespace GameplayV3.Construction.Runtime;

public partial class ConstructionWorldOverlayV3:Node2D
{
    private ConstructionSessionV3? _session;private WorldV2GridRenderer? _grid;private IReadOnlyList<GlobalCellCoord> _preview=Array.Empty<GlobalCellCoord>();private bool _previewValid;
    public void Initialize(ConstructionSessionV3 session,WorldV2GridRenderer grid){_session=session;_grid=grid;ZIndex=1;QueueRedraw();}
    public void SetPreview(IReadOnlyList<GlobalCellCoord> cells,bool valid){_preview=cells;_previewValid=valid;QueueRedraw();}public void ClearPreview(){_preview=Array.Empty<GlobalCellCoord>();QueueRedraw();}public void Refresh()=>QueueRedraw();
    public override void _Draw(){if(_session==null||_grid==null)return;float tile=_grid.TileSize;foreach(string id in _session.Blueprints.GetAllBlueprintIds())if(_session.Blueprints.TryGet(id,out var bp)&&bp!=null)DrawBlueprint(bp,tile);foreach(string id in _session.Structures.GetAllStructureIds())if(_session.Structures.TryGet(id,out var structure)&&structure!=null)foreach(var c in structure.OccupiedCells){Rect2 r=Rect(c,tile);DrawRect(r,new Color("5b3825"),true);DrawRect(r,new Color("a5744f"),false,2);DrawLine(r.Position+new Vector2(3,4),r.End-new Vector2(3,4),new Color("d0a375"),2);}foreach(var c in _preview){Rect2 r=Rect(c,tile);Color color=_previewValid?new Color(0.25f,0.9f,0.65f,.32f):new Color(1f,.25f,.3f,.35f);DrawRect(r,color,true);DrawRect(r,new Color(color.R,color.G,color.B,.9f),false,2);}}
    private void DrawBlueprint(ConstructionBlueprintStateV3 bp,float tile){Color fill=bp.Status switch{ConstructionBlueprintStatusV3.ReadyToBuild=>new Color(.25f,.85f,1f,.30f),ConstructionBlueprintStatusV3.UnderConstruction=>new Color(.35f,.65f,1f,.38f),ConstructionBlueprintStatusV3.WaitingForFootprintClear=>new Color(1f,.45f,.25f,.38f),_=>new Color(.2f,.72f,.95f,.22f)};HashSet<Vector2I> cells=new(bp.OccupiedCells.Select(x=>x.Value));foreach(var c in bp.OccupiedCells){Rect2 r=Rect(c,tile);DrawRect(r,fill,true);foreach((Vector2I d,Vector2 a,Vector2 b) e in Edges(tile))if(!cells.Contains(c.Value+e.d))DrawLine(r.Position+e.a,r.Position+e.b,new Color(.55f,.9f,1f,.9f),1.5f);}var first=bp.OccupiedCells[0];int delivered=bp.MaterialBuffer.GetDeliveredAmount(ResourceTypeV3.Wood),required=bp.MaterialBuffer.GetRequiredAmount(ResourceTypeV3.Wood);DrawString(ThemeDB.FallbackFont,_grid!.CellToWorldCenter(first.Value)+new Vector2(-10,-8),bp.Status==ConstructionBlueprintStatusV3.ReadyToBuild?"READY":$"{delivered}/{required}",HorizontalAlignment.Left,40,9,new Color(.85f,.96f,1f));}
    private static IEnumerable<(Vector2I d,Vector2 a,Vector2 b)> Edges(float t){yield return(Vector2I.Up,Vector2.Zero,new(t,0));yield return(Vector2I.Right,new(t,0),new(t,t));yield return(Vector2I.Down,new(t,t),new(0,t));yield return(Vector2I.Left,new(0,t),Vector2.Zero);}private static Rect2 Rect(GlobalCellCoord c,float t)=>new(new Vector2(c.Value.X*t,c.Value.Y*t),new(t,t));
}

public sealed class ConstructionPlacementServiceV3
{
    public const int MaxBatch=64;
    public static IReadOnlyList<GlobalCellCoord> BuildLine(GlobalCellCoord a,GlobalCellCoord b){List<GlobalCellCoord> r=new();int dx=b.Value.X-a.Value.X,dy=b.Value.Y-a.Value.Y;if(Math.Abs(dx)>=Math.Abs(dy)){int step=Math.Sign(dx);for(int x=a.Value.X;;x+=step){r.Add(new(new Vector2I(x,a.Value.Y)));if(x==b.Value.X||r.Count==MaxBatch)break;}}else{int step=Math.Sign(dy);for(int y=a.Value.Y;;y+=step){r.Add(new(new Vector2I(a.Value.X,y)));if(y==b.Value.Y||r.Count==MaxBatch)break;}}return r.AsReadOnly();}
    public static bool ValidateCell(GlobalCellCoord cell,string company,ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,out string reason){if(!query.IsInsideWorld(cell.Value)||!query.GetCellInfo(cell.Value).IsWalkable){reason="InvalidTerrain";return false;}if(construction.Blueprints.IsBlueprintCell(cell)||construction.Structures.IsStructureCell(cell)){reason="ConstructionOverlap";return false;}if(resources.Nodes.ContainsCell(cell.Value)||resources.GroundStacks.GetStacksAtCell(cell).Count>0){reason="ResourceOverlap";return false;}if(stockpiles.Zones.IsStockpileCell(cell)){reason="StockpileOverlap";return false;}foreach(string id in mercenaries.Registry.GetAllMercenaryIds())if(mercenaries.Registry.TryGetState(id,out var state)&&state?.CurrentCell.Value==cell.Value){reason="MercenaryOverlap";return false;}reason=string.Empty;return true;}
}

public partial class ConstructionPlacementControllerV3:Node
{
    private ConstructionSessionV3? _construction;private ResourceSessionV3? _resources;private StockpileSessionV3? _stockpiles;private MercenarySessionV3? _mercenaries;private IMercenaryNavigationWorldQueryV3? _query;private WorldV2GridRenderer? _grid;private WorldManagerV2? _manager;private ConstructionWorldOverlayV3? _overlay;private bool _active,_dragging;private Vector2 _press;private StructureOrientationV3 _orientation;
    public bool IsActive=>_active;public StructureOrientationV3 Orientation=>_orientation;
    public event Action<bool>? ActiveChanged;
    public void Initialize(ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,WorldV2GridRenderer grid,WorldManagerV2 manager,ConstructionWorldOverlayV3 overlay){_construction=construction;_resources=resources;_stockpiles=stockpiles;_mercenaries=mercenaries;_query=query;_grid=grid;_manager=manager;_overlay=overlay;}
    public void SetActive(bool active){if(_active==active)return;_active=active;if(!active){_dragging=false;_overlay?.ClearPreview();}ActiveChanged?.Invoke(active);}
    public bool TryHandleInput(InputEvent e){if(!_active)return false;if(e is InputEventKey key&&key.Pressed&&!key.Echo){if(key.Keycode==Key.R){_orientation=(StructureOrientationV3)(((int)_orientation+1)%4);UpdatePreview(_press,_press);return true;}if(key.Keycode==Key.Escape){SetActive(false);return true;}}if(e is InputEventMouseButton mb&&mb.ButtonIndex==MouseButton.Right&&mb.Pressed){SetActive(false);return true;}if(e is InputEventMouseButton left&&left.ButtonIndex==MouseButton.Left){if(left.Pressed){_dragging=true;_press=left.Position;UpdatePreview(_press,_press);}else if(_dragging){_dragging=false;Commit(_press,left.Position);}return true;}if(e is InputEventMouseMotion motion&&_dragging){UpdatePreview(_press,motion.Position);return true;}return false;}
    public bool TryHandleBlueprintAction(InputEvent e,ConstructionWorkCoordinatorV3 work,IReadOnlyList<string> selected){if(_active||e is not InputEventMouseButton mb||!mb.Pressed||mb.ButtonIndex!=MouseButton.Right)return false;GlobalCellCoord cell=ScreenCell(mb.Position);if(!_construction!.Blueprints.TryGetBlueprintAtCell(cell,out var bp)||bp==null)return false;string reason;if(mb.ShiftPressed){if(!work.TryCancelBlueprint(bp.BlueprintId,out reason))_manager!.UpdateDebugHud(reason);else _manager!.UpdateDebugHud("Blueprint cancelled and materials refunded.");}else{if(selected.Count==0){_manager!.UpdateDebugHud("Select a mercenary first.");return true;}if(!work.TryIssue(bp.BlueprintId,selected,out reason))_manager!.UpdateDebugHud(reason);else _manager!.UpdateDebugHud(bp.MaterialBuffer.IsComplete?"Construction assigned.":"Material supply assigned.");}return true;}
    private GlobalCellCoord ScreenCell(Vector2 p)=>new(_grid!.WorldToCell(GetViewport().GetCanvasTransform().AffineInverse()*p));private IReadOnlyList<GlobalCellCoord> Cells(Vector2 a,Vector2 b)=>ConstructionPlacementServiceV3.BuildLine(ScreenCell(a),ScreenCell(b));
    private bool Validate(IReadOnlyList<GlobalCellCoord> cells,out string reason){HashSet<Vector2I> seen=new();foreach(var anchor in cells){if(!seen.Add(anchor.Value)){reason="BatchOverlap";return false;}if(!ConstructionPlacementServiceV3.ValidateCell(anchor,_manager!.LocalCompanyId,_construction!,_resources!,_stockpiles!,_mercenaries!,_query!,out reason))return false;}reason=string.Empty;return true;}
    private void UpdatePreview(Vector2 a,Vector2 b){var cells=Cells(a,b);_overlay!.SetPreview(cells,Validate(cells,out _));}
    private void Commit(Vector2 a,Vector2 b){var anchors=Cells(a,b);string reason="InvalidDefinition";if(!_construction!.Definitions.TryGetDefinition(StructureDefinitionCatalogV3.WoodenWallId,out var definition)||definition==null||!Validate(anchors,out reason)){_manager!.UpdateDebugHud(reason);UpdatePreview(a,b);return;}List<ConstructionBlueprintStateV3> states=new();foreach(var anchor in anchors){var footprint=StructureFootprintResolverV3.Resolve(definition,anchor,_orientation);states.Add(new(ConstructionBlueprintIdFactoryV3.Create(),_manager!.LocalCompanyId,definition.DefinitionId,anchor,_orientation,footprint.Cells,new(definition.RequiredMaterials),DateTime.UtcNow));}if(!_construction.Blueprints.TryRegisterBatch(states,_construction.Structures,_manager!.WorldBounds,out reason)){_manager.UpdateDebugHud(reason);return;}_construction.Diagnostics.PlacedBlueprintCount+=states.Count;_overlay!.ClearPreview();_overlay.Refresh();GD.Print($"[ConstructionV3] Blueprint batch placed count={states.Count} orientation={_orientation}");_manager.UpdateDebugHud($"Placed {states.Count} wooden wall blueprint(s).");}
}

internal enum ConstructionJobPhaseV3{MoveToSource,PickUp,MoveToBlueprint,Deliver,MoveToBuild,Build,WaitingClear}
internal sealed class ConstructionJobV3
{public required string Id;public required string BlueprintId;public required string MercenaryId;public required bool Supply;public required long Revision;public ConstructionJobPhaseV3 Phase;public string SourceStackId="";public GlobalCellCoord SourceCell;public GlobalCellCoord ApproachCell;public ResourceTypeV3 MaterialType;public int Amount;public int MaxCarryUnits;public int CompletedTrips;public float RequiredSeconds;}

public sealed class ConstructionWorkCoordinatorV3
{
    private readonly ConstructionSessionV3 _construction;private readonly ResourceSessionV3 _resources;private readonly StockpileSessionV3 _stockpiles;private readonly MercenaryWorkSessionV3 _work;private readonly MercenaryControlSessionV3 _control;private readonly MercenarySessionV3 _mercenaries;private readonly IMercenaryNavigationWorldQueryV3 _query;private readonly string _localPlayerId;private readonly string _localCompanyId;private readonly Rect2I _worldBounds;private readonly bool _emitLogs;private readonly Dictionary<string,ConstructionJobV3> _jobs=new(StringComparer.Ordinal);private long _revision;
    public event Action? Changed;public event Action? ResourcesChanged;public int ActiveJobCount=>_jobs.Count;public int LastSupplyTripCount{get;private set;}public string LastSupplyWorkerId{get;private set;}="";public string LastConstructionWorkerId{get;private set;}="";
    public ConstructionWorkCoordinatorV3(ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,WorldManagerV2 manager):this(construction,resources,stockpiles,work,control,mercenaries,query,manager.LocalPlayerId,manager.LocalCompanyId,manager.WorldBounds,true){}
    public ConstructionWorkCoordinatorV3(ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,string localPlayerId,string localCompanyId,Rect2I worldBounds,bool emitLogs=false){_construction=construction;_resources=resources;_stockpiles=stockpiles;_work=work;_control=control;_mercenaries=mercenaries;_query=query;_localPlayerId=localPlayerId;_localCompanyId=localCompanyId;_worldBounds=worldBounds;_emitLogs=emitLogs;}
    public bool TryIssue(string blueprintId,IReadOnlyList<string> selected,out string reason){if(!_construction.Blueprints.TryGet(blueprintId,out var bp)||bp==null||bp.CompanyId!=_localCompanyId){reason="InvalidBlueprint";return false;}if(_construction.Reservations.IsReserved(blueprintId)){reason="BlueprintReserved";return false;}return bp.MaterialBuffer.IsComplete?TryBuild(bp,selected,out reason):TrySupply(bp,selected,out reason);}
    public void CancelForDirectMove(string mercenaryId){foreach(var job in _jobs.Values.Where(x=>x.MercenaryId==mercenaryId).ToList())Fail(job,"CancelledByDirectMove");}
    private bool TrySupply(ConstructionBlueprintStateV3 bp,IReadOnlyList<string> selected,out string reason){ResourceTypeV3 type=bp.MaterialBuffer.GetMissingAmount(ResourceTypeV3.Wood)>0?ResourceTypeV3.Wood:ResourceTypeV3.Stone;int missing=bp.MaterialBuffer.GetMissingAmount(type);List<GroundResourceStackV3> sources=GetAvailableSources(bp.CompanyId,type);if(sources.Sum(x=>x.Amount)<missing){reason="InsufficientStoredMaterials";return false;}GroundResourceStackV3 source=sources[0];if(!SelectWorker(selected,source.Cell,true,out string worker,out var profile,out reason))return false;string id=WorkRequestIdFactoryV3.Create();long rev=++_revision;var job=new ConstructionJobV3{Id=id,BlueprintId=bp.BlueprintId,MercenaryId=worker,Supply=true,Revision=rev,Phase=ConstructionJobPhaseV3.MoveToSource,MaterialType=type,MaxCarryUnits=HaulingWorkCalculatorV3.GetMaxCarryUnits(profile!)};if(!_construction.Reservations.TryReserve(new(bp.BlueprintId,id,worker,bp.CompanyId,ConstructionReservationPurposeV3.MaterialDelivery,DateTime.UtcNow,rev),out reason))return false;_jobs.Add(id,job);LastSupplyWorkerId=worker;if(!PlanNextSource(job,bp,out reason)){Fail(job,reason);return false;}if(_emitLogs)GD.Print($"[ConstructionV3] Supply started blueprint={bp.BlueprintId} worker={worker} amount={missing}");reason=string.Empty;return true;}
    private bool TryBuild(ConstructionBlueprintStateV3 bp,IReadOnlyList<string> selected,out string reason){if(!SelectWorker(selected,bp.AnchorCell,false,out string worker,out var profile,out reason))return false;var approaches=ConstructionApproachCellServiceV3.GetCandidates(bp.OccupiedCells,_mercenaries.Registry.TryGetState(worker,out var st)&&st!=null?st.CurrentCell:bp.AnchorCell,_query);if(approaches.Count==0){reason="NoApproachCells";return false;}string id=WorkRequestIdFactoryV3.Create();long rev=++_revision;var definition=_construction.Definitions.TryGetDefinition(bp.DefinitionId,out var d)?d:null;if(definition==null){reason="InvalidDefinition";return false;}var calc=ConstructionWorkCalculatorV3.Calculate(profile!,definition.BaseConstructionDurationSeconds);var job=new ConstructionJobV3{Id=id,BlueprintId=bp.BlueprintId,MercenaryId=worker,Supply=false,Revision=rev,Phase=ConstructionJobPhaseV3.MoveToBuild,ApproachCell=approaches[0],RequiredSeconds=calc.RequiredConstructionSeconds};if(!_construction.Reservations.TryReserve(new(bp.BlueprintId,id,worker,bp.CompanyId,ConstructionReservationPurposeV3.Construction,DateTime.UtcNow,rev),out reason))return false;_jobs.Add(id,job);LastConstructionWorkerId=worker;RequestMove(job,job.ApproachCell);if(_emitLogs)GD.Print($"[ConstructionV3] Construction started blueprint={bp.BlueprintId} worker={worker} seconds={job.RequiredSeconds:0.00}");reason=string.Empty;return true;}
    private List<GroundResourceStackV3> GetAvailableSources(string company,ResourceTypeV3 type)=>_resources.GroundStacks.GetAllStackIds().Select(id=>(_resources.GroundStacks.TryGet(id,out var s),s)).Where(x=>x.Item1&&x.s!=null&&x.s.ResourceType==type&&x.s.Amount>0&&_stockpiles.Zones.IsOwnedStockpileCell(company,x.s.Cell)&&!_work.SourceStackReservations.IsReserved(x.s.ResourceStackId)).Select(x=>x.s!).OrderByDescending(x=>x.Amount).ThenBy(x=>x.ResourceStackId,StringComparer.Ordinal).ToList();
    private bool PlanNextSource(ConstructionJobV3 job,ConstructionBlueprintStateV3 bp,out string reason){List<GroundResourceStackV3> sources=GetAvailableSources(bp.CompanyId,job.MaterialType);if(sources.Count==0){reason="NoStoredMaterials";return false;}GroundResourceStackV3 source=sources[0];job.SourceStackId=source.ResourceStackId;job.SourceCell=source.Cell;job.Amount=Math.Min(Math.Min(source.Amount,bp.MaterialBuffer.GetMissingAmount(job.MaterialType)),job.MaxCarryUnits);if(job.Amount<1){reason="InvalidSupplyAmount";return false;}if(!_work.SourceStackReservations.TryReserve(new(source.ResourceStackId,job.Id,job.MercenaryId,bp.CompanyId,job.Amount,job.Revision,DateTime.UtcNow),out reason))return false;job.Phase=ConstructionJobPhaseV3.MoveToSource;RequestMove(job,source.Cell);return _jobs.ContainsKey(job.Id);}
    private bool SelectWorker(IReadOnlyList<string> selected,GlobalCellCoord target,bool hauling,out string worker,out MercenaryProfileV3? profile,out string reason){worker="";profile=null;var list=new List<(string Id,MercenaryProfileV3 P,float Score,float Dist,int Index)>();for(int i=0;i<selected.Count;i++)if(_mercenaries.CanPlayerControlMercenary(_localPlayerId,selected[i])&&_mercenaries.Registry.TryGetMercenary(selected[i],out var p,out var s)&&p!=null&&s!=null){float score=hauling?HaulingWorkCalculatorV3.Calculate(p).HaulingScore:ConstructionWorkCalculatorV3.Calculate(p,6).ConstructionScore;list.Add((selected[i],p,score,MercenaryMovementCostPolicyV3.Octile(s.CurrentCell.Value,target.Value),i));}var best=list.OrderByDescending(x=>x.Score).ThenBy(x=>x.Dist).ThenBy(x=>x.Index).ThenBy(x=>x.Id,StringComparer.Ordinal).FirstOrDefault();if(best.P==null){reason="NoEligibleWorker";return false;}worker=best.Id;profile=best.P;reason="";return true;}
    private void RequestMove(ConstructionJobV3 job,GlobalCellCoord destination){if(!_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)||state==null){Fail(job,"WorkerRemoved");return;}_work.CancelForDirectMove(job.MercenaryId);_control.SupersedeDirectMovementForWork(job.MercenaryId);if(!_control.ExternalMovements.TryRequest(job.MercenaryId,state.CurrentCell,destination,MovementRequestSourceTypeV3.Work,job.Id,_control.SessionRevision,job.Revision,_control.Movements,out _,out string reason))Fail(job,reason);}
    public bool TryHandleMovementResult(MercenaryMovementResultV3 result){if(!_jobs.TryGetValue(result.Request.SourceId,out var job)||job.Revision!=result.Request.SourceRevision)return false;if(!result.Succeeded){Fail(job,"MovementFailed");return true;}if(job.Phase==ConstructionJobPhaseV3.MoveToSource){CommitPickup(job);return true;}if(job.Phase==ConstructionJobPhaseV3.MoveToBlueprint){job.Phase=ConstructionJobPhaseV3.Deliver;CommitDelivery(job);return true;}if(job.Phase==ConstructionJobPhaseV3.MoveToBuild){if(_construction.Blueprints.TryGet(job.BlueprintId,out var bp)&&bp!=null&&bp.TryBeginConstruction(out _)){job.Phase=ConstructionJobPhaseV3.Build;_mercenaries.Registry.TryGetState(job.MercenaryId,out var s);s?.TrySetActivityState(MercenaryActivityStateV3.Working,out _);Changed?.Invoke();}else Fail(job,"InvalidConstructionState");return true;}return true;}
    private void CommitPickup(ConstructionJobV3 job){if(!_resources.GroundStacks.TryTakeAmount(job.SourceStackId,job.Amount,out int taken,out _,out _,out string reason)){Fail(job,"PickupFailed");return;}if(!_work.Carries.TryBeginCarry(job.MercenaryId,job.Id,job.MaterialType,taken,job.SourceStackId,job.Revision,job.MaxCarryUnits,out _,out reason)){_resources.GroundStacks.TryAddOrMerge(job.MaterialType,taken,job.SourceCell,out _,out _,out _);Fail(job,"PickupFailed");return;}_work.SourceStackReservations.TryRelease(job.SourceStackId,job.Id);ResourcesChanged?.Invoke();if(!_construction.Blueprints.TryGet(job.BlueprintId,out var bp)||bp==null||!_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)||state==null){Fail(job,"InvalidBlueprint");return;}var approaches=ConstructionApproachCellServiceV3.GetCandidates(bp.OccupiedCells,state.CurrentCell,_query);if(approaches.Count==0){Fail(job,"NoApproachCells");return;}job.ApproachCell=approaches[0];job.Phase=ConstructionJobPhaseV3.MoveToBlueprint;RequestMove(job,job.ApproachCell);Changed?.Invoke();}
    private void CommitDelivery(ConstructionJobV3 job){if(!_construction.Blueprints.TryGet(job.BlueprintId,out var bp)||bp==null||!_work.Carries.TryGetCarry(job.MercenaryId,out var carry)||carry==null||!bp.MaterialBuffer.CanAccept(carry.ResourceType,carry.Amount)){Fail(job,"DropFailed");return;}if(!bp.MaterialBuffer.TryDeliver(carry.ResourceType,carry.Amount,out _)||!_work.Carries.TryClearCarry(job.MercenaryId,job.Id,out _)){Fail(job,"DropFailed");return;}job.CompletedTrips++;bp.RefreshMaterialStatus();Changed?.Invoke();if(!bp.MaterialBuffer.IsComplete){if(!PlanNextSource(job,bp,out string reason))Fail(job,reason);return;}LastSupplyTripCount=job.CompletedTrips;Finish(job);if(_emitLogs)GD.Print($"[ConstructionV3] Supply completed blueprint={bp.BlueprintId} trips={job.CompletedTrips} ready=true");}
    public void Tick(float delta){foreach(var job in _jobs.Values.ToList()){if(job.Phase is not (ConstructionJobPhaseV3.Build or ConstructionJobPhaseV3.WaitingClear))continue;if(!_construction.Blueprints.TryGet(job.BlueprintId,out var bp)||bp==null){Fail(job,"InvalidBlueprint");continue;}if(job.Phase==ConstructionJobPhaseV3.Build)bp.AddProgress(delta);if(bp.ConstructionProgressSeconds<job.RequiredSeconds){Changed?.Invoke();continue;}if(!FootprintClear(bp,job.MercenaryId)){bp.SetWaitingForClear();job.Phase=ConstructionJobPhaseV3.WaitingClear;Changed?.Invoke();continue;}Complete(job,bp);}}
    private bool FootprintClear(ConstructionBlueprintStateV3 bp,string builder){HashSet<Vector2I> cells=new(bp.OccupiedCells.Select(x=>x.Value));foreach(string id in _mercenaries.Registry.GetAllMercenaryIds())if(_mercenaries.Registry.TryGetState(id,out var s)&&s!=null&&cells.Contains(s.CurrentCell.Value))return false;foreach(string id in _control.Movements.GetActiveIds())if(_control.Movements.TryGet(id,out var m)&&m!=null&&cells.Contains(m.ToCell.Value))return false;return true;}
    private void Complete(ConstructionJobV3 job,ConstructionBlueprintStateV3 bp){if(!_construction.Definitions.TryGetDefinition(bp.DefinitionId,out var d)||d==null){Fail(job,"InvalidDefinition");return;}var structure=new StructureStateV3(StructureIdFactoryV3.Create(),bp.CompanyId,bp.DefinitionId,bp.AnchorCell,bp.Orientation,bp.OccupiedCells,bp.MaterialBuffer.GetDeliveredMaterialsSnapshot(),d.BlocksMovement,DateTime.UtcNow);if(!_construction.Structures.TryRegister(structure,_construction.Blueprints,_worldBounds,out string reason,bp.BlueprintId)){Fail(job,reason);return;}if(!_construction.Blueprints.TryRemove(bp.BlueprintId,out _)){_construction.Structures.TryRemove(structure.StructureId,out _);Fail(job,"CompletionFailed");return;}bp.MarkCompleted();_construction.Diagnostics.CompletedStructureCount++;Finish(job);if(_emitLogs)GD.Print($"[ConstructionV3] Structure completed id={structure.StructureId} definition={structure.DefinitionId}");}
    public bool TryCancelBlueprint(string id,out string reason){if(!_construction.Blueprints.TryGet(id,out var bp)||bp==null||bp.CompanyId!=_localCompanyId){reason="InvalidBlueprint";return false;}foreach(var job in _jobs.Values.Where(x=>x.BlueprintId==id).ToList())Fail(job,"CancelledByBlueprintRemoval");var materials=bp.MaterialBuffer.GetDeliveredMaterialsSnapshot();if(!_construction.Blueprints.TryRemove(id,out _)){reason="BlueprintRemovalFailed";return false;}foreach(var m in materials)_resources.GroundStacks.TryAddOrMerge(m.ResourceType,m.RequiredAmount,bp.AnchorCell,out _,out _,out _);bp.MarkCancelled();_construction.Diagnostics.CancelledBlueprintCount++;ResourcesChanged?.Invoke();Changed?.Invoke();reason="";return true;}
    private void Finish(ConstructionJobV3 job){_construction.Reservations.ReleaseByWorkRequest(job.Id);_work.SourceStackReservations.ReleaseByWorkRequest(job.Id);_jobs.Remove(job.Id);_mercenaries.Registry.TryGetState(job.MercenaryId,out var state);state?.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);Changed?.Invoke();}
    private void Fail(ConstructionJobV3 job,string reason){if(_work.Carries.TryGetCarry(job.MercenaryId,out var carry)&&carry?.WorkRequestId==job.Id&&_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)&&state!=null){_work.Carries.TryDropCarryAtCell(job.MercenaryId,job.Id,state.CurrentCell,_resources.GroundStacks,out _,out _);ResourcesChanged?.Invoke();}_control.ExternalMovements.Cancel(job.MercenaryId,reason,_control.Movements);_construction.Diagnostics.LastFailureReason=reason;Finish(job);}
}
