using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Resources.Runtime;
using GameplayV3.Stockpile;
using GameplayV3.Work;
using GameplayV3.Needs;
using Godot;
using WorldV2;

namespace GameplayV3.Construction.Runtime;

public partial class ConstructionWorldOverlayV3:Node2D
{
    private ConstructionSessionV3? _session;private WorldV2GridRenderer? _grid;private IReadOnlyList<GlobalCellCoord> _preview=Array.Empty<GlobalCellCoord>();private string? _previewDefinitionId;private GlobalCellCoord _previewAnchor;private StructureOrientationV3 _previewOrientation;private bool _previewValid,_hasPreviewAnchor;
    public void Initialize(ConstructionSessionV3 session,WorldV2GridRenderer grid){_session=session;_grid=grid;ZIndex=1;QueueRedraw();}
    public void SetPreview(string definitionId,GlobalCellCoord anchor,StructureOrientationV3 orientation,IReadOnlyList<GlobalCellCoord> cells,bool valid){bool changed=_previewDefinitionId!=definitionId||!_hasPreviewAnchor||_previewAnchor.Value!=anchor.Value||_previewOrientation!=orientation||_previewValid!=valid||!_preview.SequenceEqual(cells);_previewDefinitionId=definitionId;_previewAnchor=anchor;_previewOrientation=orientation;_previewValid=valid;_hasPreviewAnchor=true;_preview=cells;if(changed)QueueRedraw();}public void ClearPreview(){if(!_hasPreviewAnchor&&_preview.Count==0)return;_preview=Array.Empty<GlobalCellCoord>();_previewDefinitionId=null;_hasPreviewAnchor=false;_previewValid=false;QueueRedraw();}public void Refresh()=>QueueRedraw();
    public override void _Draw(){if(_session==null||_grid==null)return;float tile=_grid.TileSize;foreach(string id in _session.Blueprints.GetAllBlueprintIds())if(_session.Blueprints.TryGet(id,out var bp)&&bp!=null)DrawBlueprint(bp,tile);foreach(string id in _session.Structures.GetAllStructureIds())if(_session.Structures.TryGet(id,out var structure)&&structure!=null)DrawStructure(structure,tile);DrawDemolitions(tile);foreach(var c in _preview){Rect2 r=Rect(c,tile);Color color=_previewValid?new Color(0.25f,0.9f,0.65f,.32f):new Color(1f,.25f,.3f,.35f);DrawRect(r,color,true);DrawRect(r,new Color(color.R,color.G,color.B,.9f),false,2);}DrawPlacementPreview(tile);}
    private void DrawStructure(StructureStateV3 structure,float tile){if(structure.DefinitionId!=StructureDefinitionCatalogV3.BasicBedId){foreach(var c in structure.OccupiedCells){Rect2 r=Rect(c,tile);DrawRect(r,new Color("5b3825"),true);DrawRect(r,new Color("a5744f"),false,2);DrawLine(r.Position+new Vector2(3,4),r.End-new Vector2(3,4),new Color("d0a375"),2);}return;}HashSet<Vector2I> cells=new(structure.OccupiedCells.Select(x=>x.Value));foreach(var cell in structure.OccupiedCells){Rect2 r=Rect(cell,tile);DrawRect(r,new Color(.28f,.20f,.16f,.96f),true);foreach((Vector2I d,Vector2 a,Vector2 b) edge in Edges(tile))if(!cells.Contains(cell.Value+edge.d))DrawLine(r.Position+edge.a,r.Position+edge.b,new Color(.72f,.55f,.39f,.96f),2);}if(_session!.Definitions.TryGetDefinition(structure.DefinitionId,out var definition)&&definition!=null){RestFacilitySlotV3 slot=RestFacilitySlotResolverV3.Resolve(structure,definition)[0];Rect2 use=Rect(slot.UseCell,tile);Vector2 pillowSize=structure.Orientation is StructureOrientationV3.Deg0 or StructureOrientationV3.Deg180?new Vector2(tile-8,7):new Vector2(7,tile-8);Vector2 pillowPos=use.Position+(new Vector2(tile,tile)-pillowSize)/2;DrawRect(new Rect2(pillowPos,pillowSize),new Color(.82f,.72f,.56f,.95f),true);DrawRect(new Rect2(pillowPos,pillowSize),new Color(.95f,.85f,.68f,.9f),false,1);}}
    private void DrawDemolitions(float tile){foreach(string id in _session!.Demolitions.GetAllStructureIds())if(_session.Structures.TryGet(id,out var structure)&&structure!=null&&_session.Demolitions.TryGet(id,out var demolition)&&demolition!=null){HashSet<Vector2I> cells=new(structure.OccupiedCells.Select(x=>x.Value));Color fill=demolition.Status==StructureDemolitionStatusV3.UnderDemolition?new Color(.95f,.18f,.18f,.34f):new Color(.75f,.08f,.12f,.25f);foreach(var cell in structure.OccupiedCells){Rect2 r=Rect(cell,tile);DrawRect(r,fill,true);foreach((Vector2I d,Vector2 a,Vector2 b) edge in Edges(tile))if(!cells.Contains(cell.Value+edge.d))DrawLine(r.Position+edge.a,r.Position+edge.b,new Color(1f,.28f,.28f,.92f),2);DrawLine(r.Position+new Vector2(4,4),r.End-new Vector2(4,4),new Color(1f,.25f,.25f,.8f),1.5f);DrawLine(new Vector2(r.End.X-4,r.Position.Y+4),new Vector2(r.Position.X+4,r.End.Y-4),new Color(1f,.25f,.25f,.8f),1.5f);}if(_session.Definitions.TryGetDefinition(structure.DefinitionId,out var definition)&&definition!=null){float ratio=Mathf.Clamp(demolition.ProgressSeconds/definition.BaseDemolitionDurationSeconds,0,1);Vector2 p=Rect(structure.AnchorCell,tile).Position+new Vector2(2,tile-4);DrawRect(new Rect2(p,new Vector2(tile-4,3)),new Color(.12f,.03f,.03f,.9f),true);DrawRect(new Rect2(p,new Vector2((tile-4)*ratio,3)),new Color(1f,.3f,.25f,.95f),true);}}}
    private void DrawBlueprint(ConstructionBlueprintStateV3 bp,float tile){Color fill=bp.Status switch{ConstructionBlueprintStatusV3.ReadyToBuild=>new Color(.25f,.85f,1f,.30f),ConstructionBlueprintStatusV3.UnderConstruction=>new Color(.35f,.65f,1f,.38f),ConstructionBlueprintStatusV3.WaitingForFootprintClear=>new Color(1f,.45f,.25f,.38f),_=>new Color(.2f,.72f,.95f,.22f)};HashSet<Vector2I> cells=new(bp.OccupiedCells.Select(x=>x.Value));foreach(var c in bp.OccupiedCells){Rect2 r=Rect(c,tile);DrawRect(r,fill,true);foreach((Vector2I d,Vector2 a,Vector2 b) e in Edges(tile))if(!cells.Contains(c.Value+e.d))DrawLine(r.Position+e.a,r.Position+e.b,new Color(.55f,.9f,1f,.9f),1.5f);}var first=bp.OccupiedCells[0];int delivered=bp.MaterialBuffer.GetDeliveredAmount(ResourceTypeV3.Wood),required=bp.MaterialBuffer.GetRequiredAmount(ResourceTypeV3.Wood);DrawString(ThemeDB.FallbackFont,_grid!.CellToWorldCenter(first.Value)+new Vector2(-10,-8),bp.Status==ConstructionBlueprintStatusV3.ReadyToBuild?"READY":$"{delivered}/{required}",HorizontalAlignment.Left,40,9,new Color(.85f,.96f,1f));}
    private static IEnumerable<(Vector2I d,Vector2 a,Vector2 b)> Edges(float t){yield return(Vector2I.Up,Vector2.Zero,new(t,0));yield return(Vector2I.Right,new(t,0),new(t,t));yield return(Vector2I.Down,new(t,t),new(0,t));yield return(Vector2I.Left,new(0,t),Vector2.Zero);}private static Rect2 Rect(GlobalCellCoord c,float t)=>new(new Vector2(c.Value.X*t,c.Value.Y*t),new(t,t));
    private void DrawPlacementPreview(float tile){if(!_hasPreviewAnchor||_previewDefinitionId!=StructureDefinitionCatalogV3.BasicBedId||_session==null||!_session.Definitions.TryGetDefinition(_previewDefinitionId,out var definition)||definition==null)return;var rest=definition.RestFacility;if(rest==null||rest.Slots.Count==0)return;GlobalCellCoord use=StructureFootprintResolverV3.ResolveLocalCell(definition,_previewAnchor,_previewOrientation,rest.Slots[0].LocalCell);Rect2 cell=Rect(use,tile);Vector2 size=_previewOrientation is StructureOrientationV3.Deg0 or StructureOrientationV3.Deg180?new Vector2(tile-8,7):new Vector2(7,tile-8);Rect2 pillow=new(cell.Position+(new Vector2(tile,tile)-size)/2,size);DrawRect(pillow,new Color(.98f,.9f,.5f,.95f),true);DrawRect(pillow,new Color(1f,.98f,.75f,.98f),false,1.5f);}
}

public sealed class ConstructionPlacementServiceV3
{
    public const int MaxBatch=64;
    public static IReadOnlyList<GlobalCellCoord> BuildLine(GlobalCellCoord a,GlobalCellCoord b){List<GlobalCellCoord> r=new();int dx=b.Value.X-a.Value.X,dy=b.Value.Y-a.Value.Y;if(Math.Abs(dx)>=Math.Abs(dy)){int step=Math.Sign(dx);for(int x=a.Value.X;;x+=step){r.Add(new(new Vector2I(x,a.Value.Y)));if(x==b.Value.X||r.Count==MaxBatch)break;}}else{int step=Math.Sign(dy);for(int y=a.Value.Y;;y+=step){r.Add(new(new Vector2I(a.Value.X,y)));if(y==b.Value.Y||r.Count==MaxBatch)break;}}return r.AsReadOnly();}
    public static bool ValidateCell(GlobalCellCoord cell,string company,ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,out string reason){if(!query.IsInsideWorld(cell.Value)||!query.GetCellInfo(cell.Value).IsWalkable){reason="InvalidTerrain";return false;}if(construction.Blueprints.IsBlueprintCell(cell)||construction.Structures.IsStructureCell(cell)){reason="ConstructionOverlap";return false;}if(resources.Nodes.ContainsCell(cell.Value)||resources.GroundStacks.GetStacksAtCell(cell).Count>0){reason="ResourceOverlap";return false;}if(stockpiles.Zones.IsStockpileCell(cell)){reason="StockpileOverlap";return false;}foreach(string id in mercenaries.Registry.GetAllMercenaryIds())if(mercenaries.Registry.TryGetState(id,out var state)&&state?.CurrentCell.Value==cell.Value){reason="MercenaryOverlap";return false;}reason=string.Empty;return true;}
    public static bool TryValidatePlacementBatch(StructureDefinitionV3 definition,IReadOnlyList<ResolvedStructureFootprintV3> footprints,string company,ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,out string reason){if(footprints.Count==0){reason="EmptyPlacement";return false;}if(footprints.Count>MaxBatch){reason="BatchMaxExceeded";return false;}if(definition.PlacementMode==StructurePlacementModeV3.Single&&footprints.Count!=1){reason="SinglePlacementOnly";return false;}HashSet<Vector2I> seen=new();foreach(var footprint in footprints){if(footprint.Cells.Count!=definition.BaseFootprintOffsets.Count){reason="FootprintMismatch";return false;}foreach(var cell in footprint.Cells){if(!seen.Add(cell.Value)){reason="BatchOverlap";return false;}if(!ValidateCell(cell,company,construction,resources,stockpiles,mercenaries,query,out reason))return false;}}reason=string.Empty;return true;}
}

public partial class ConstructionPlacementControllerV3:Node
{
    private ConstructionSessionV3? _construction;private ResourceSessionV3? _resources;private StockpileSessionV3? _stockpiles;private MercenarySessionV3? _mercenaries;private IMercenaryNavigationWorldQueryV3? _query;private WorldV2GridRenderer? _grid;private WorldManagerV2? _manager;private ConstructionWorldOverlayV3? _overlay;private bool _placementActive,_dragging,_hasDragStartCell,_hasCurrentMouseCell,_hasPreviewAnchor,_cursorOverUi;private GlobalCellCoord _dragStartCell,_currentMouseCell,_previewAnchorCell;private Vector2 _lastMouseScreen;private StructureOrientationV3 _activeOrientation;private ConstructionPlacementToolKindV3 _activeToolKind;private string? _activeStructureDefinitionId;private IReadOnlyList<GlobalCellCoord> _previewOccupiedCells=Array.Empty<GlobalCellCoord>();private bool _previewIsValid;private string _previewFailureReason=string.Empty;
    public bool IsActive=>_placementActive;public bool IsPlacementActive=>_placementActive;public ConstructionPlacementToolKindV3 ActiveToolKind=>_activeToolKind;public string? ActiveStructureDefinitionId=>_activeStructureDefinitionId;public StructureOrientationV3 ActiveOrientation=>_activeOrientation;public StructureOrientationV3 Orientation=>_activeOrientation;public GlobalCellCoord PreviewAnchorCell=>_previewAnchorCell;public bool HasPreviewAnchor=>_hasPreviewAnchor;public IReadOnlyList<GlobalCellCoord> PreviewOccupiedCells=>_previewOccupiedCells;public bool PreviewIsValid=>_previewIsValid;public string PreviewFailureReason=>_previewFailureReason;public bool IsDragging=>_dragging;public GlobalCellCoord DragStartCell=>_dragStartCell;public bool HasDragStartCell=>_hasDragStartCell;
    public event Action<bool>? ActiveChanged;
    public void Initialize(ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,WorldV2GridRenderer grid,WorldManagerV2 manager,ConstructionWorldOverlayV3 overlay){_construction=construction;_resources=resources;_stockpiles=stockpiles;_mercenaries=mercenaries;_query=query;_grid=grid;_manager=manager;_overlay=overlay;ClearActivePlacementTool(false);}
    public void SetActivePlacementTool(ConstructionPlacementToolKindV3 toolKind,string? structureDefinitionId){ResetPlacementInteraction();bool wasActive=_placementActive;if(toolKind==ConstructionPlacementToolKindV3.None){_placementActive=false;_activeToolKind=ConstructionPlacementToolKindV3.None;_activeStructureDefinitionId=null;_activeOrientation=StructureOrientationV3.Deg0;if(wasActive)ActiveChanged?.Invoke(false);return;}if(!IsToolDefinitionPair(toolKind,structureDefinitionId)){_placementActive=false;_activeToolKind=ConstructionPlacementToolKindV3.None;_activeStructureDefinitionId=null;_activeOrientation=StructureOrientationV3.Deg0;_previewFailureReason="InvalidPlacementToolDefinition";_manager?.UpdateDebugHud(_previewFailureReason);if(wasActive)ActiveChanged?.Invoke(false);return;}_placementActive=true;_activeToolKind=toolKind;_activeStructureDefinitionId=structureDefinitionId;_activeOrientation=StructureOrientationV3.Deg0;_lastMouseScreen=GetViewport().GetMousePosition();UpdatePreview(_lastMouseScreen);if(!wasActive)ActiveChanged?.Invoke(true);}
    public void ClearActivePlacementTool()=>ClearActivePlacementTool(true);
    private void ClearActivePlacementTool(bool emitEvent){bool wasActive=_placementActive;ResetPlacementInteraction();_placementActive=false;_activeToolKind=ConstructionPlacementToolKindV3.None;_activeStructureDefinitionId=null;_activeOrientation=StructureOrientationV3.Deg0;_hasCurrentMouseCell=false;_previewFailureReason=string.Empty;if(emitEvent&&wasActive)ActiveChanged?.Invoke(false);}
    public void RefreshPreview(){if(_placementActive)UpdatePreview(GetViewport().GetMousePosition());}
    public bool TryHandleInput(InputEvent e){if(!_placementActive)return false;if(e is InputEventKey key&&key.Pressed&&!key.Echo){if(key.Keycode==Key.R){RotateActiveOrientation();UpdatePreview(_lastMouseScreen);return true;}if(key.Keycode==Key.Escape){ClearActivePlacementTool();return true;}}if(e is InputEventMouseButton mb&&mb.ButtonIndex==MouseButton.Right&&mb.Pressed){ClearActivePlacementTool();return true;}if(e is InputEventMouseMotion motion){_lastMouseScreen=motion.Position;UpdatePreview(motion.Position);return true;}if(e is InputEventMouseButton left&&left.ButtonIndex==MouseButton.Left){_lastMouseScreen=left.Position;if(left.Pressed){if(IsCursorOverUi(left.Position)){HidePreview("CursorOverUi");return true;}_dragging=true;_dragStartCell=ScreenCell(left.Position);_hasDragStartCell=true;UpdatePreview(left.Position);return true;}if(!_dragging)return true;if(IsCursorOverUi(left.Position)){_dragging=false;_hasDragStartCell=false;HidePreview("CursorOverUi");return true;}Commit(left.Position);_dragging=false;_hasDragStartCell=false;UpdatePreview(left.Position);return true;}return false;}
    public bool TryHandleBlueprintAction(InputEvent e,ConstructionWorkCoordinatorV3 work,IReadOnlyList<string> selected){if(_placementActive||e is not InputEventMouseButton mb||!mb.Pressed||mb.ButtonIndex!=MouseButton.Right)return false;GlobalCellCoord cell=ScreenCell(mb.Position);if(!_construction!.Blueprints.TryGetBlueprintAtCell(cell,out var bp)||bp==null)return false;string reason;if(mb.ShiftPressed){if(!work.TryCancelBlueprint(bp.BlueprintId,out reason))_manager!.UpdateDebugHud(reason);else _manager!.UpdateDebugHud("Blueprint cancelled and materials refunded.");}else{if(selected.Count==0){_manager!.UpdateDebugHud("Select a mercenary first.");return true;}if(!work.TryIssue(bp.BlueprintId,selected,out reason))_manager!.UpdateDebugHud(reason);else _manager!.UpdateDebugHud(bp.MaterialBuffer.IsComplete?"Construction assigned.":"Material supply assigned.");}return true;}
    private GlobalCellCoord ScreenCell(Vector2 p)=>new(_grid!.WorldToCell(GetViewport().GetCanvasTransform().AffineInverse()*p));
    private bool IsCursorOverUi(Vector2 screen)=>_manager?.ConstructionTrayOpen==true&&_manager.ConstructionUiGlobalRect.HasPoint(screen);
    private bool IsToolDefinitionPair(ConstructionPlacementToolKindV3 kind,string? definitionId)=>kind switch{ConstructionPlacementToolKindV3.WoodenWall=>definitionId==StructureDefinitionCatalogV3.WoodenWallId,ConstructionPlacementToolKindV3.BasicBed=>definitionId==StructureDefinitionCatalogV3.BasicBedId,_=>false};
    private void ResetPlacementInteraction(){_dragging=false;_hasDragStartCell=false;_overlay?.ClearPreview();_hasPreviewAnchor=false;_previewOccupiedCells=Array.Empty<GlobalCellCoord>();_previewIsValid=false;_cursorOverUi=false;}
    private void HidePreview(string reason){_cursorOverUi=reason=="CursorOverUi";_overlay?.ClearPreview();_previewOccupiedCells=Array.Empty<GlobalCellCoord>();_hasPreviewAnchor=false;_previewIsValid=false;_previewFailureReason=reason;}
    private bool TryBuildPlacement(Vector2 screen,out StructureDefinitionV3? definition,out IReadOnlyList<GlobalCellCoord> anchors,out IReadOnlyList<ResolvedStructureFootprintV3> footprints,out string reason){definition=null;anchors=Array.Empty<GlobalCellCoord>();footprints=Array.Empty<ResolvedStructureFootprintV3>();if(!_placementActive||_construction==null||_grid==null){reason="PlacementInactive";return false;}if(IsCursorOverUi(screen)){reason="CursorOverUi";return false;}if(string.IsNullOrEmpty(_activeStructureDefinitionId)||!_construction.Definitions.TryGetDefinition(_activeStructureDefinitionId,out definition)||definition==null){reason="InvalidPlacementToolDefinition";return false;}StructureDefinitionV3 activeDefinition=definition;GlobalCellCoord current=ScreenCell(screen);_currentMouseCell=current;_hasCurrentMouseCell=true;anchors=activeDefinition.PlacementMode==StructurePlacementModeV3.Single||!_dragging||!_hasDragStartCell?new[]{current}:ConstructionPlacementServiceV3.BuildLine(_dragStartCell,current);footprints=anchors.Select(anchor=>StructureFootprintResolverV3.Resolve(activeDefinition,anchor,_activeOrientation)).ToList().AsReadOnly();reason=string.Empty;return true;}
    private void UpdatePreview(Vector2 screen){_lastMouseScreen=screen;if(IsCursorOverUi(screen)){HidePreview("CursorOverUi");return;}if(!TryBuildPlacement(screen,out StructureDefinitionV3? definition,out IReadOnlyList<GlobalCellCoord> anchors,out IReadOnlyList<ResolvedStructureFootprintV3> footprints,out string buildReason)){HidePreview(buildReason);return;}StructureDefinitionV3 activeDefinition=definition!;List<GlobalCellCoord> cells=footprints.SelectMany(x=>x.Cells).Distinct().OrderBy(x=>x.Value.Y).ThenBy(x=>x.Value.X).ToList();bool valid=ConstructionPlacementServiceV3.TryValidatePlacementBatch(activeDefinition,footprints,_manager!.LocalCompanyId,_construction!,_resources!,_stockpiles!,_mercenaries!,_query!,out string reason);GlobalCellCoord anchor=anchors[0];if(_hasPreviewAnchor&&_previewAnchorCell.Value==anchor.Value&&_previewOccupiedCells.SequenceEqual(cells)&&_previewIsValid==valid&&_previewFailureReason==reason&&!_cursorOverUi)return;_cursorOverUi=false;_previewAnchorCell=anchor;_hasPreviewAnchor=true;_previewOccupiedCells=cells.AsReadOnly();_previewIsValid=valid;_previewFailureReason=valid?string.Empty:reason;_overlay!.SetPreview(activeDefinition.DefinitionId,anchor,_activeOrientation,_previewOccupiedCells,valid);}
    private void Commit(Vector2 screen){if(!TryBuildPlacement(screen,out StructureDefinitionV3? definition,out IReadOnlyList<GlobalCellCoord> anchors,out IReadOnlyList<ResolvedStructureFootprintV3> footprints,out string buildReason)){_previewFailureReason=buildReason;_manager?.UpdateDebugHud(buildReason);return;}StructureDefinitionV3 activeDefinition=definition!;if(!ConstructionPlacementServiceV3.TryValidatePlacementBatch(activeDefinition,footprints,_manager!.LocalCompanyId,_construction!,_resources!,_stockpiles!,_mercenaries!,_query!,out string reason)){_previewFailureReason=reason;_manager.UpdateDebugHud(reason);return;}List<ConstructionBlueprintStateV3> states=new();for(int i=0;i<anchors.Count;i++){var footprint=footprints[i];states.Add(new(ConstructionBlueprintIdFactoryV3.Create(),_manager.LocalCompanyId,activeDefinition.DefinitionId,anchors[i],_activeOrientation,footprint.Cells,new(activeDefinition.RequiredMaterials),DateTime.UtcNow));}if(!_construction!.Blueprints.TryRegisterBatch(states,_construction.Structures,_manager.WorldBounds,out reason)){_previewFailureReason=reason;_manager.UpdateDebugHud(reason);return;}_construction.Diagnostics.PlacedBlueprintCount+=states.Count;_overlay!.Refresh();GD.Print($"[ConstructionV3] Blueprint batch placed definition={activeDefinition.DefinitionId} count={states.Count} orientation={_activeOrientation}");_manager.UpdateDebugHud($"Placed {states.Count} {activeDefinition.DisplayName} blueprint(s).");}
    private void RotateActiveOrientation(){if(!_placementActive||_construction==null||string.IsNullOrEmpty(_activeStructureDefinitionId)||!_construction.Definitions.TryGetDefinition(_activeStructureDefinitionId,out var definition)||definition==null)return;List<StructureOrientationV3> orientations=definition.AllowedOrientations.ToList();int index=orientations.IndexOf(_activeOrientation);_activeOrientation=orientations[(index+1)%orientations.Count];}
    public void PrintDebugDiagnostics(){GD.Print($"[ConstructionPlacementV3] ActiveConstructionTool={_activeToolKind} ActiveStructureDefinitionId={_activeStructureDefinitionId??"-"} ActiveOrientation={_activeOrientation} PreviewAnchorCell={(_hasPreviewAnchor?_previewAnchorCell.ToString():"-")} PreviewOccupiedCells={string.Join(',',_previewOccupiedCells.Select(x=>x.ToString()))} PreviewIsValid={_previewIsValid} PreviewFailureReason={_previewFailureReason} IsDragging={_dragging} DragStartCell={(_hasDragStartCell?_dragStartCell.ToString():"-")}");}
}

internal enum ConstructionJobPhaseV3{MoveToSource,PickUp,MoveToBlueprint,Deliver,MoveToBuild,Build,WaitingClear}
internal sealed class ConstructionJobV3
{public required string Id;public required string BlueprintId;public required string MercenaryId;public required bool Supply;public required long Revision;public ConstructionJobPhaseV3 Phase;public string SourceStackId="";public GlobalCellCoord SourceCell;public GlobalCellCoord ApproachCell;public ResourceTypeV3 MaterialType;public int Amount;public int MaxCarryUnits;public int CompletedTrips;public float RequiredSeconds;}

public readonly record struct ConstructionWorkHudSnapshotV3(string WorkRequestId,string BlueprintId,bool IsSupply,string Phase,GlobalCellCoord TargetCell,float ProgressSeconds,float RequiredSeconds,int CompletedTrips);

public sealed class ConstructionWorkCoordinatorV3
{
    private readonly ConstructionSessionV3 _construction;private readonly ResourceSessionV3 _resources;private readonly StockpileSessionV3 _stockpiles;private readonly MercenaryWorkSessionV3 _work;private readonly MercenaryControlSessionV3 _control;private readonly MercenarySessionV3 _mercenaries;private readonly IMercenaryNavigationWorldQueryV3 _query;private readonly string _localPlayerId;private readonly string _localCompanyId;private readonly Rect2I _worldBounds;private readonly bool _emitLogs;private readonly Dictionary<string,ConstructionJobV3> _jobs=new(StringComparer.Ordinal);private Func<string,float>? _workMultiplier;private long _revision;
    public event Action? Changed;public event Action? ResourcesChanged;public int ActiveJobCount=>_jobs.Count;public int LastSupplyTripCount{get;private set;}public string LastSupplyWorkerId{get;private set;}="";public string LastConstructionWorkerId{get;private set;}="";
    public ConstructionWorkCoordinatorV3(ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,WorldManagerV2 manager):this(construction,resources,stockpiles,work,control,mercenaries,query,manager.LocalPlayerId,manager.LocalCompanyId,manager.WorldBounds,true){}
    public ConstructionWorkCoordinatorV3(ConstructionSessionV3 construction,ResourceSessionV3 resources,StockpileSessionV3 stockpiles,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,string localPlayerId,string localCompanyId,Rect2I worldBounds,bool emitLogs=false){_construction=construction;_resources=resources;_stockpiles=stockpiles;_work=work;_control=control;_mercenaries=mercenaries;_query=query;_localPlayerId=localPlayerId;_localCompanyId=localCompanyId;_worldBounds=worldBounds;_emitLogs=emitLogs;}
    public void AttachWorkMultiplier(Func<string,float> resolver)=>_workMultiplier=resolver;
    public bool TryIssue(string blueprintId,IReadOnlyList<string> selected,out string reason){if(!_construction.Blueprints.TryGet(blueprintId,out var bp)||bp==null||bp.CompanyId!=_localCompanyId){reason="InvalidBlueprint";return false;}if(_construction.Reservations.IsReserved(blueprintId)){reason="BlueprintReserved";return false;}return bp.MaterialBuffer.IsComplete?TryBuild(bp,selected,out reason):TrySupply(bp,selected,out reason);}
    public bool CancelForDirectMove(string mercenaryId){bool cancelled=false;foreach(var job in _jobs.Values.Where(x=>x.MercenaryId==mercenaryId).ToList()){Fail(job,"CancelledByDirectMove");cancelled=true;}return cancelled;}
    public bool TryGetHudSnapshot(string mercenaryId,out ConstructionWorkHudSnapshotV3 snapshot)
    {foreach(var job in _jobs.Values)if(job.MercenaryId==mercenaryId&&_construction.Blueprints.TryGet(job.BlueprintId,out var bp)&&bp!=null){snapshot=new(job.Id,job.BlueprintId,job.Supply,job.Phase.ToString(),bp.AnchorCell,bp.ConstructionProgressSeconds,job.RequiredSeconds,job.CompletedTrips);return true;}snapshot=default;return false;}
    private bool TrySupply(ConstructionBlueprintStateV3 bp,IReadOnlyList<string> selected,out string reason){ResourceTypeV3 type=bp.MaterialBuffer.GetMissingAmount(ResourceTypeV3.Wood)>0?ResourceTypeV3.Wood:ResourceTypeV3.Stone;int missing=bp.MaterialBuffer.GetMissingAmount(type);List<GroundResourceStackV3> sources=GetAvailableSources(bp.CompanyId,type);if(sources.Sum(x=>x.Amount)<missing){reason="InsufficientStoredMaterials";return false;}GroundResourceStackV3 source=sources[0];if(!SelectWorker(selected,source.Cell,true,out string worker,out var profile,out reason))return false;_work.NotifyExternalWorkSupersede(worker);string id=WorkRequestIdFactoryV3.Create();long rev=++_revision;var job=new ConstructionJobV3{Id=id,BlueprintId=bp.BlueprintId,MercenaryId=worker,Supply=true,Revision=rev,Phase=ConstructionJobPhaseV3.MoveToSource,MaterialType=type,MaxCarryUnits=HaulingWorkCalculatorV3.GetMaxCarryUnits(profile!)};if(!_construction.Reservations.TryReserve(new(bp.BlueprintId,id,worker,bp.CompanyId,ConstructionReservationPurposeV3.MaterialDelivery,DateTime.UtcNow,rev),out reason))return false;_jobs.Add(id,job);LastSupplyWorkerId=worker;if(!PlanNextSource(job,bp,out reason)){Fail(job,reason);return false;}if(_emitLogs)GD.Print($"[ConstructionV3] Supply started blueprint={bp.BlueprintId} worker={worker} amount={missing}");reason=string.Empty;return true;}
    private bool TryBuild(ConstructionBlueprintStateV3 bp,IReadOnlyList<string> selected,out string reason){if(!SelectWorker(selected,bp.AnchorCell,false,out string worker,out var profile,out reason))return false;var approaches=ConstructionApproachCellServiceV3.GetCandidates(bp.OccupiedCells,_mercenaries.Registry.TryGetState(worker,out var st)&&st!=null?st.CurrentCell:bp.AnchorCell,_query);if(approaches.Count==0){reason="NoApproachCells";return false;}_work.NotifyExternalWorkSupersede(worker);string id=WorkRequestIdFactoryV3.Create();long rev=++_revision;var definition=_construction.Definitions.TryGetDefinition(bp.DefinitionId,out var d)?d:null;if(definition==null){reason="InvalidDefinition";return false;}var calc=ConstructionWorkCalculatorV3.Calculate(profile!,definition.BaseConstructionDurationSeconds);var job=new ConstructionJobV3{Id=id,BlueprintId=bp.BlueprintId,MercenaryId=worker,Supply=false,Revision=rev,Phase=ConstructionJobPhaseV3.MoveToBuild,ApproachCell=approaches[0],RequiredSeconds=calc.RequiredConstructionSeconds};if(!_construction.Reservations.TryReserve(new(bp.BlueprintId,id,worker,bp.CompanyId,ConstructionReservationPurposeV3.Construction,DateTime.UtcNow,rev),out reason))return false;_jobs.Add(id,job);LastConstructionWorkerId=worker;RequestMove(job,job.ApproachCell);if(_emitLogs)GD.Print($"[ConstructionV3] Construction started blueprint={bp.BlueprintId} worker={worker} seconds={job.RequiredSeconds:0.00}");reason=string.Empty;return true;}
    private List<GroundResourceStackV3> GetAvailableSources(string company,ResourceTypeV3 type)=>_resources.GroundStacks.GetAllStackIds().Select(id=>(_resources.GroundStacks.TryGet(id,out var s),s)).Where(x=>x.Item1&&x.s!=null&&x.s.ResourceType==type&&_resources.AmountReservations.GetAvailableAmount(x.s.ResourceStackId)>0&&_stockpiles.Zones.IsOwnedStockpileCell(company,x.s.Cell)&&!_work.SourceStackReservations.IsReserved(x.s.ResourceStackId)).Select(x=>x.s!).OrderByDescending(x=>_resources.AmountReservations.GetAvailableAmount(x.ResourceStackId)).ThenBy(x=>x.ResourceStackId,StringComparer.Ordinal).ToList();
    private bool PlanNextSource(ConstructionJobV3 job,ConstructionBlueprintStateV3 bp,out string reason){List<GroundResourceStackV3> sources=GetAvailableSources(bp.CompanyId,job.MaterialType);if(sources.Count==0){reason="NoStoredMaterials";return false;}GroundResourceStackV3 source=sources[0];job.SourceStackId=source.ResourceStackId;job.SourceCell=source.Cell;job.Amount=Math.Min(Math.Min(_resources.AmountReservations.GetAvailableAmount(source.ResourceStackId),bp.MaterialBuffer.GetMissingAmount(job.MaterialType)),job.MaxCarryUnits);if(job.Amount<1){reason="InvalidSupplyAmount";return false;}if(!_work.SourceStackReservations.TryReserve(new(source.ResourceStackId,job.Id,job.MercenaryId,bp.CompanyId,job.Amount,job.Revision,DateTime.UtcNow),out reason))return false;job.Phase=ConstructionJobPhaseV3.MoveToSource;RequestMove(job,source.Cell);return _jobs.ContainsKey(job.Id);}
    private bool SelectWorker(IReadOnlyList<string> selected,GlobalCellCoord target,bool hauling,out string worker,out MercenaryProfileV3? profile,out string reason){worker="";profile=null;var list=new List<(string Id,MercenaryProfileV3 P,float Score,float Dist,int Index)>();bool exhausted=false;for(int i=0;i<selected.Count;i++){if(!_work.CanStartFor(selected[i],WorkTypeV3.Construction,out _)){exhausted=true;continue;}if(_mercenaries.CanPlayerControlMercenary(_localPlayerId,selected[i])&&_mercenaries.Registry.TryGetMercenary(selected[i],out var p,out var s)&&p!=null&&s!=null){float score=hauling?HaulingWorkCalculatorV3.Calculate(p).HaulingScore:ConstructionWorkCalculatorV3.Calculate(p,6).ConstructionScore;list.Add((selected[i],p,score,MercenaryMovementCostPolicyV3.Octile(s.CurrentCell.Value,target.Value),i));}}var best=list.OrderByDescending(x=>x.Score).ThenBy(x=>x.Dist).ThenBy(x=>x.Index).ThenBy(x=>x.Id,StringComparer.Ordinal).FirstOrDefault();if(best.P==null){reason=exhausted?"TooExhausted":"NoEligibleWorker";return false;}worker=best.Id;profile=best.P;reason="";return true;}
    private void RequestMove(ConstructionJobV3 job,GlobalCellCoord destination){if(!_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)||state==null){Fail(job,"WorkerRemoved");return;}_work.CancelForDirectMove(job.MercenaryId);_control.SupersedeDirectMovementForWork(job.MercenaryId);if(!_control.ExternalMovements.TryRequest(job.MercenaryId,state.CurrentCell,destination,MovementRequestSourceTypeV3.Work,job.Id,_control.SessionRevision,job.Revision,_control.Movements,out _,out string reason))Fail(job,reason);}
    public bool TryHandleMovementResult(MercenaryMovementResultV3 result){if(!_jobs.TryGetValue(result.Request.SourceId,out var job)||job.Revision!=result.Request.SourceRevision)return false;if(!result.Succeeded){Fail(job,"MovementFailed");return true;}if(job.Phase==ConstructionJobPhaseV3.MoveToSource){CommitPickup(job);return true;}if(job.Phase==ConstructionJobPhaseV3.MoveToBlueprint){job.Phase=ConstructionJobPhaseV3.Deliver;CommitDelivery(job);return true;}if(job.Phase==ConstructionJobPhaseV3.MoveToBuild){if(_construction.Blueprints.TryGet(job.BlueprintId,out var bp)&&bp!=null&&bp.TryBeginConstruction(out _)){job.Phase=ConstructionJobPhaseV3.Build;_mercenaries.Registry.TryGetState(job.MercenaryId,out var s);s?.TrySetActivityState(MercenaryActivityStateV3.Working,out _);Changed?.Invoke();}else Fail(job,"InvalidConstructionState");return true;}return true;}
    private void CommitPickup(ConstructionJobV3 job){if(!_resources.GroundStacks.TryTakeAmount(job.SourceStackId,job.Amount,out int taken,out _,out _,out string reason)){Fail(job,"PickupFailed");return;}if(!_work.Carries.TryBeginCarry(job.MercenaryId,job.Id,job.MaterialType,taken,job.SourceStackId,job.Revision,job.MaxCarryUnits,out _,out reason)){_resources.GroundStacks.TryAddOrMerge(job.MaterialType,taken,job.SourceCell,out _,out _,out _);Fail(job,"PickupFailed");return;}_work.SourceStackReservations.TryRelease(job.SourceStackId,job.Id);ResourcesChanged?.Invoke();if(!_construction.Blueprints.TryGet(job.BlueprintId,out var bp)||bp==null||!_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)||state==null){Fail(job,"InvalidBlueprint");return;}var approaches=ConstructionApproachCellServiceV3.GetCandidates(bp.OccupiedCells,state.CurrentCell,_query);if(approaches.Count==0){Fail(job,"NoApproachCells");return;}job.ApproachCell=approaches[0];job.Phase=ConstructionJobPhaseV3.MoveToBlueprint;RequestMove(job,job.ApproachCell);Changed?.Invoke();}
    private void CommitDelivery(ConstructionJobV3 job){if(!_construction.Blueprints.TryGet(job.BlueprintId,out var bp)||bp==null||!_work.Carries.TryGetCarry(job.MercenaryId,out var carry)||carry==null||!bp.MaterialBuffer.CanAccept(carry.ResourceType,carry.Amount)){Fail(job,"DropFailed");return;}if(!bp.MaterialBuffer.TryDeliver(carry.ResourceType,carry.Amount,out _)||!_work.Carries.TryClearCarry(job.MercenaryId,job.Id,out _)){Fail(job,"DropFailed");return;}job.CompletedTrips++;bp.RefreshMaterialStatus();Changed?.Invoke();if(!bp.MaterialBuffer.IsComplete){if(!PlanNextSource(job,bp,out string reason))Fail(job,reason);return;}LastSupplyTripCount=job.CompletedTrips;Finish(job);if(_emitLogs)GD.Print($"[ConstructionV3] Supply completed blueprint={bp.BlueprintId} trips={job.CompletedTrips} ready=true");}
    public void Tick(float delta){foreach(var job in _jobs.Values.ToList()){if(job.Phase is not (ConstructionJobPhaseV3.Build or ConstructionJobPhaseV3.WaitingClear))continue;if(!_construction.Blueprints.TryGet(job.BlueprintId,out var bp)||bp==null){Fail(job,"InvalidBlueprint");continue;}if(job.Phase==ConstructionJobPhaseV3.Build)bp.AddProgress(delta*Math.Clamp(_workMultiplier?.Invoke(job.MercenaryId)??1f,.1f,2f));if(bp.ConstructionProgressSeconds<job.RequiredSeconds){Changed?.Invoke();continue;}if(!FootprintClear(bp,job.MercenaryId)){bp.SetWaitingForClear();job.Phase=ConstructionJobPhaseV3.WaitingClear;Changed?.Invoke();continue;}Complete(job,bp);}}
    private bool FootprintClear(ConstructionBlueprintStateV3 bp,string builder){HashSet<Vector2I> cells=new(bp.OccupiedCells.Select(x=>x.Value));foreach(string id in _mercenaries.Registry.GetAllMercenaryIds())if(_mercenaries.Registry.TryGetState(id,out var s)&&s!=null&&cells.Contains(s.CurrentCell.Value))return false;foreach(string id in _control.Movements.GetActiveIds())if(_control.Movements.TryGet(id,out var m)&&m!=null&&cells.Contains(m.ToCell.Value))return false;return true;}
    private void Complete(ConstructionJobV3 job,ConstructionBlueprintStateV3 bp){if(!_construction.Definitions.TryGetDefinition(bp.DefinitionId,out var d)||d==null){Fail(job,"InvalidDefinition");return;}var structure=new StructureStateV3(StructureIdFactoryV3.Create(),bp.CompanyId,bp.DefinitionId,bp.AnchorCell,bp.Orientation,bp.OccupiedCells,bp.MaterialBuffer.GetDeliveredMaterialsSnapshot(),d.BlocksMovement,DateTime.UtcNow);if(!_construction.Structures.TryRegister(structure,_construction.Blueprints,_worldBounds,out string reason,bp.BlueprintId)){Fail(job,reason);return;}if(!_construction.Blueprints.TryRemove(bp.BlueprintId,out _)){_construction.Structures.TryRemove(structure.StructureId,out _);Fail(job,"CompletionFailed");return;}bp.MarkCompleted();_construction.Diagnostics.CompletedStructureCount++;Finish(job);if(_emitLogs)GD.Print($"[ConstructionV3] Structure completed id={structure.StructureId} definition={structure.DefinitionId}");}
    public bool TryCancelBlueprint(string id,out string reason){if(!_construction.Blueprints.TryGet(id,out var bp)||bp==null||bp.CompanyId!=_localCompanyId){reason="InvalidBlueprint";return false;}foreach(var job in _jobs.Values.Where(x=>x.BlueprintId==id).ToList())Fail(job,"CancelledByBlueprintRemoval");var materials=bp.MaterialBuffer.GetDeliveredMaterialsSnapshot();if(!_construction.Blueprints.TryRemove(id,out _)){reason="BlueprintRemovalFailed";return false;}foreach(var m in materials)_resources.GroundStacks.TryAddOrMerge(m.ResourceType,m.RequiredAmount,bp.AnchorCell,out _,out _,out _);bp.MarkCancelled();_construction.Diagnostics.CancelledBlueprintCount++;ResourcesChanged?.Invoke();Changed?.Invoke();reason="";return true;}
    private void Finish(ConstructionJobV3 job){_construction.Reservations.ReleaseByWorkRequest(job.Id);_work.SourceStackReservations.ReleaseByWorkRequest(job.Id);_jobs.Remove(job.Id);_mercenaries.Registry.TryGetState(job.MercenaryId,out var state);state?.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);Changed?.Invoke();}
    private void Fail(ConstructionJobV3 job,string reason){if(_work.Carries.TryGetCarry(job.MercenaryId,out var carry)&&carry?.WorkRequestId==job.Id&&_mercenaries.Registry.TryGetState(job.MercenaryId,out var state)&&state!=null){_work.Carries.TryDropCarryAtCell(job.MercenaryId,job.Id,state.CurrentCell,_resources.GroundStacks,out _,out _);ResourcesChanged?.Invoke();}_control.ExternalMovements.Cancel(job.MercenaryId,reason,_control.Movements);_construction.Diagnostics.LastFailureReason=reason;Finish(job);}
}
