using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Work;
using GameplayV3.Jobs;
using GameplayV3.Session;
using Godot;
using WorldV2;

namespace GameplayV3.Construction.Runtime;

internal sealed class DemolitionJobV3
{
    public required WorkRequestV3 Request;public required DemolitionWorkPayloadV3 Payload;public required IReadOnlyList<GlobalCellCoord> ApproachCandidates;public bool Floor;public int CandidateIndex;public bool Working;
}

public readonly record struct DemolitionWorkHudSnapshotV3(string WorkRequestId,string StructureId,string Phase,GlobalCellCoord TargetCell,float ProgressSeconds,float RequiredSeconds);

public sealed class DemolitionWorkCoordinatorV3
{
    private readonly ConstructionSessionV3 _construction;private readonly ResourceSessionV3 _resources;private readonly MercenaryWorkSessionV3 _work;private readonly MercenaryControlSessionV3 _control;private readonly MercenarySessionV3 _mercenaries;private readonly IMercenaryNavigationWorldQueryV3 _query;private readonly string _playerId,_companyId;private readonly Rect2I _bounds;private readonly Dictionary<string,DemolitionJobV3> _jobsByWorker=new(StringComparer.Ordinal);private readonly Dictionary<string,string> _workerByStructure=new(StringComparer.Ordinal);private readonly Action<string>? _cancelConstruction;private readonly bool _emitLogs;private Func<string,float>? _workMultiplier;private Func<string,bool>? _hasEquipmentOutput;private Action<string>? _restDemolitionStarted;private Action<string>? _restDemolitionEnded;private long _revision;
    public event Action? Changed;public event Action? ResourcesChanged;public int ActiveJobCount=>_jobsByWorker.Count;
    public DemolitionWorkCoordinatorV3(ConstructionSessionV3 construction,ResourceSessionV3 resources,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,string playerId,string companyId,Rect2I bounds,Action<string>? cancelConstruction=null,bool emitLogs=false){_construction=construction;_resources=resources;_work=work;_control=control;_mercenaries=mercenaries;_query=query;_playerId=playerId;_companyId=companyId;_bounds=bounds;_cancelConstruction=cancelConstruction;_emitLogs=emitLogs;}
    public void AttachWorkMultiplier(Func<string,float> resolver)=>_workMultiplier=resolver;
    public void AttachEquipmentOutputBlocker(Func<string,bool> resolver)=>_hasEquipmentOutput=resolver;
    public void AttachRestLifecycle(Action<string> started,Action<string> ended){_restDemolitionStarted=started;_restDemolitionEnded=ended;}
    public bool TryIssue(string structureId,IReadOnlyList<string> selected,out string reason)
    {
        if(!_construction.Structures.TryGet(structureId,out var structure)||structure==null)return TryIssueFloor(structureId,selected,out reason);if(structure.CompanyId!=_companyId){reason="OwnershipDenied";return false;}if(_hasEquipmentOutput?.Invoke(structureId)==true){reason="EquipmentOutputNotEmpty";return false;}if(!_construction.Definitions.TryGetDefinition(structure.DefinitionId,out var definition)||definition==null){reason="InvalidDefinition";return false;}if(!definition.CanBeDemolished){reason="DemolitionNotAllowed";return false;}if(!_construction.Demolitions.TryGet(structureId,out var demolition)||demolition==null){reason="NotDesignated";return false;}if(_construction.DemolitionReservations.IsReserved(structureId)){reason="AlreadyReserved";return false;}if(selected.Count==0){reason="NoSelectedWorkers";return false;}
        bool exhausted=false;List<(string Id,MercenaryProfileV3 Profile,MercenaryStateV3 State,DemolitionWorkCalculationV3 Calc,IReadOnlyList<GlobalCellCoord> Approaches,int Selection)> candidates=new();for(int i=0;i<selected.Count;i++){string id=selected[i];if(!_work.CanStartFor(id,WorkTypeV3.Demolition,out _)){exhausted=true;continue;}if(!_mercenaries.CanPlayerControlMercenary(_playerId,id)||!_mercenaries.Registry.TryGetMercenary(id,out var profile,out var state)||profile==null||state==null||state.CompanyId!=_companyId)continue;var approaches=ConstructionApproachCellServiceV3.GetCandidates(structure.OccupiedCells,state.CurrentCell,_query);if(approaches.Count==0)continue;var calc=DemolitionWorkCalculatorV3.Calculate(profile,definition.BaseDemolitionDurationSeconds);candidates.Add((id,profile,state,calc,approaches,i));}
        var best=candidates.OrderByDescending(x=>x.Calc.DemolitionScore).ThenBy(x=>MercenaryMovementCostPolicyV3.Octile(x.State.CurrentCell.Value,x.Approaches[0].Value)).ThenByDescending(x=>MercenaryDerivedStatsCalculatorV3.Calculate(x.Profile).WorkSpeedMultiplier).ThenBy(x=>x.Selection).ThenBy(x=>x.Id,StringComparer.Ordinal).FirstOrDefault();if(best.Profile==null){reason=exhausted?"TooExhausted":"NoApproachCells";return false;}
        CancelForNewWork(best.Id,"SupersededByNewWork");_work.CancelForDirectMove(best.Id);_cancelConstruction?.Invoke(best.Id);_control.SupersedeDirectMovementForWork(best.Id);long revision=++_revision;DateTime now=DateTime.UtcNow;string workId=WorkRequestIdFactoryV3.Create();WorkRequestV3 request=new(workId,WorkTypeV3.Demolition,WorkTargetKindV3.Structure,_companyId,structureId,structure.AnchorCell,best.Id,revision,now);var payload=new DemolitionWorkPayloadV3(structureId,structure.OccupiedCells,structure.EmbeddedMaterials,best.Calc.RequiredSeconds,demolition.ProgressSeconds,_construction.Structures.OccupancyRevision,_construction.Structures.OccupancyRevision,revision);if(!_construction.DemolitionReservations.TryReserve(new(structureId,workId,best.Id,_companyId,now,revision),out reason))return false;request.Status=WorkRequestStatusV3.Assigned;var job=new DemolitionJobV3{Request=request,Payload=payload,ApproachCandidates=best.Approaches};_jobsByWorker.Add(best.Id,job);_workerByStructure.Add(structureId,best.Id);_construction.DemolitionDiagnostics.LastWorkerId=best.Id;_construction.DemolitionDiagnostics.LastDuration=best.Calc.RequiredSeconds;RequestNextApproach(job);if(_emitLogs)GD.Print($"[DemolitionV3] started structure={structureId} worker={best.Id} required={best.Calc.RequiredSeconds:0.00} progress={demolition.ProgressSeconds:0.00}");reason=string.Empty;Changed?.Invoke();return true;
    }
    private bool TryIssueFloor(string markId,IReadOnlyList<string> selected,out string reason){if(!_construction.Floors.TryGetMark(markId,out var mark)||mark==null||!_construction.Floors.TryGetFloor(mark.Cell,out var floor)||floor==null){reason="InvalidFloorDemolition";return false;}if(mark.CompanyId!=_companyId||floor.CompanyId!=_companyId){reason="OwnershipDenied";return false;}if(_construction.DemolitionReservations.IsReserved(markId)){reason="AlreadyReserved";return false;}if(selected.Count==0){reason="NoSelectedWorkers";return false;}bool exhausted=false;List<(string Id,MercenaryProfileV3 Profile,MercenaryStateV3 State,DemolitionWorkCalculationV3 Calc,IReadOnlyList<GlobalCellCoord> Approaches,int Selection)> candidates=new();for(int i=0;i<selected.Count;i++){string id=selected[i];if(!_work.CanStartFor(id,WorkTypeV3.Demolition,out _)){exhausted=true;continue;}if(!_mercenaries.CanPlayerControlMercenary(_playerId,id)||!_mercenaries.Registry.TryGetMercenary(id,out var profile,out var state)||profile==null||state==null)continue;IReadOnlyList<GlobalCellCoord> approaches=_query.IsWalkable(mark.Cell.Value)?new[]{mark.Cell}:ConstructionApproachCellServiceV3.GetCandidates(new[]{mark.Cell},state.CurrentCell,_query);if(approaches.Count==0)continue;var calc=DemolitionWorkCalculatorV3.Calculate(profile,1.5f);candidates.Add((id,profile,state,calc,approaches,i));}var best=candidates.OrderByDescending(x=>x.Calc.DemolitionScore).ThenBy(x=>MercenaryMovementCostPolicyV3.Octile(x.State.CurrentCell.Value,x.Approaches[0].Value)).ThenBy(x=>x.Selection).ThenBy(x=>x.Id,StringComparer.Ordinal).FirstOrDefault();if(best.Profile==null){reason=exhausted?"TooExhausted":"NoApproachCells";return false;}CancelForNewWork(best.Id,"SupersededByNewWork");_work.CancelForDirectMove(best.Id);_cancelConstruction?.Invoke(best.Id);_control.SupersedeDirectMovementForWork(best.Id);long revision=++_revision;DateTime now=DateTime.UtcNow;string workId=WorkRequestIdFactoryV3.Create();WorkRequestV3 request=new(workId,WorkTypeV3.Demolition,WorkTargetKindV3.FloorCell,_companyId,markId,mark.Cell,best.Id,revision,now);var payload=new DemolitionWorkPayloadV3(markId,new[]{mark.Cell},new[]{new StructureMaterialRequirementV3(ResourceTypeV3.Wood,1)},best.Calc.RequiredSeconds,mark.ProgressSeconds,mark.FloorRevision,_construction.Structures.OccupancyRevision,revision);if(!_construction.DemolitionReservations.TryReserve(new(markId,workId,best.Id,_companyId,now,revision),out reason))return false;request.Status=WorkRequestStatusV3.Assigned;var job=new DemolitionJobV3{Request=request,Payload=payload,ApproachCandidates=best.Approaches,Floor=true};_jobsByWorker.Add(best.Id,job);_workerByStructure.Add(markId,best.Id);RequestNextApproach(job);reason="";Changed?.Invoke();return true;}
    public bool TryHandleMovementResult(MercenaryMovementResultV3 result){if(!_jobsByWorker.TryGetValue(result.Request.MercenaryId,out var job)||job.Request.WorkRequestId!=result.Request.SourceId||job.Request.Revision!=result.Request.SourceRevision)return false;if(!result.Succeeded){job.CandidateIndex++;if(job.CandidateIndex>=job.ApproachCandidates.Count)CancelJob(job,"NoReachableApproachCell",false);else RequestNextApproach(job);return true;}if(!_mercenaries.Registry.TryGetState(job.Request.AssignedMercenaryId,out var state)||state==null||job.Payload.SelectedApproachCell==null||state.CurrentCell.Value!=job.Payload.SelectedApproachCell.Value.Value){CancelJob(job,"MovementFailed",false);return true;}bool began=job.Floor?_construction.Floors.TryBeginDemolition(job.Payload.StructureId):_construction.Demolitions.TryBeginDemolition(job.Payload.StructureId,out _);if(!began){CancelJob(job,"InvalidDemolitionState",false);return true;}if(!job.Floor)_restDemolitionStarted?.Invoke(job.Payload.StructureId);job.Working=true;job.Request.Status=WorkRequestStatusV3.Working;state.TrySetActivityState(MercenaryActivityStateV3.Working,out _);Changed?.Invoke();return true;}
    public void Tick(float delta){foreach(var job in _jobsByWorker.Values.ToList()){if(!job.Working)continue;if(job.Floor){TickFloor(job,delta);continue;}if(!_construction.Structures.TryGet(job.Payload.StructureId,out var structure)||structure==null){CancelJob(job,"StructureRemoved",true);continue;}if(!_construction.DemolitionReservations.IsReservedBy(structure.StructureId,job.Request.WorkRequestId)){CancelJob(job,"ReservationLost",false);continue;}float effectiveDelta=Math.Max(0,delta)*Math.Clamp(_workMultiplier?.Invoke(job.Request.AssignedMercenaryId)??1f,.1f,2f);if(!_construction.Demolitions.TryAddProgress(structure.StructureId,effectiveDelta,out string reason)){CancelJob(job,reason,false);continue;}_construction.Demolitions.TryGet(structure.StructureId,out var state);job.Payload.CurrentProgressSeconds=state?.ProgressSeconds??job.Payload.CurrentProgressSeconds;Changed?.Invoke();if(job.Payload.CurrentProgressSeconds<job.Payload.RequiredDemolitionSeconds)continue;DemolitionCompletionResultV3 result=DemolitionCompletionServiceV3.TryComplete(_construction,_resources,structure.StructureId,job.Request.WorkRequestId,_bounds,job.Payload.RequiredDemolitionSeconds,_hasEquipmentOutput);if(!result.Succeeded){CancelJob(job,result.FailureReason,false);continue;}_construction.DemolitionDiagnostics.CompletedCount++;_construction.DemolitionDiagnostics.LastDemolishedStructureId=structure.StructureId;_construction.DemolitionDiagnostics.LastSalvageTotalAmount=result.SalvageAmount;_construction.DemolitionDiagnostics.LastSalvageResourceTypes=string.Join(",",structure.EmbeddedMaterials.Select(x=>x.ResourceType).Distinct());_construction.DemolitionDiagnostics.LastOccupancyRevisionBefore=result.OccupancyRevisionBefore;_construction.DemolitionDiagnostics.LastOccupancyRevisionAfter=result.OccupancyRevisionAfter;FinishJob(job);ResourcesChanged?.Invoke();Changed?.Invoke();if(_emitLogs)GD.Print($"[DemolitionV3] completed structure={structure.StructureId} salvage={result.SalvageAmount} occupancy={result.OccupancyRevisionBefore}->{result.OccupancyRevisionAfter}");}}
    private void TickFloor(DemolitionJobV3 job,float delta){if(!_construction.Floors.TryGetMark(job.Payload.StructureId,out var mark)||mark==null||!_construction.DemolitionReservations.IsReservedBy(mark.MarkId,job.Request.WorkRequestId)){CancelJob(job,"ReservationLost",false);return;}float effective=Math.Max(0,delta)*Math.Clamp(_workMultiplier?.Invoke(job.Request.AssignedMercenaryId)??1f,.1f,2f);if(!_construction.Floors.TryAddDemolitionProgress(mark.MarkId,effective)){CancelJob(job,"InvalidDemolitionState",false);return;}job.Payload.CurrentProgressSeconds=mark.ProgressSeconds;if(mark.ProgressSeconds<job.Payload.RequiredDemolitionSeconds){Changed?.Invoke();return;}long occupancy=_construction.Structures.OccupancyRevision;if(!_construction.Floors.TryCompleteDemolition(mark.MarkId,out var floor,out string reason)||floor==null){CancelJob(job,reason,false);return;}if(!_resources.GroundStacks.TryAddOrMerge(ResourceTypeV3.Wood,1,floor.Cell,out _,out _,out _)){CancelJob(job,"SalvageCommitFailed",false);return;}_construction.DemolitionReservations.ReleaseByWorkRequest(job.Request.WorkRequestId);_construction.DemolitionDiagnostics.CompletedCount++;_construction.DemolitionDiagnostics.LastDemolishedStructureId=mark.MarkId;_construction.DemolitionDiagnostics.LastSalvageTotalAmount=1;_construction.DemolitionDiagnostics.LastOccupancyRevisionBefore=occupancy;_construction.DemolitionDiagnostics.LastOccupancyRevisionAfter=_construction.Structures.OccupancyRevision;FinishJob(job);ResourcesChanged?.Invoke();Changed?.Invoke();}
    public bool CancelForDirectMove(string worker)=>CancelForNewWork(worker,"CancelledByDirectMove");public bool CancelForNewWork(string worker,string reason="SupersededByNewWork"){if(!_jobsByWorker.TryGetValue(worker,out var job))return false;CancelJob(job,reason,false);return true;}
    public bool TryGetHudSnapshot(string mercenaryId,out DemolitionWorkHudSnapshotV3 snapshot)
    {if(_jobsByWorker.TryGetValue(mercenaryId,out var job)){snapshot=new(job.Request.WorkRequestId,job.Payload.StructureId,job.Working?"Working":"MovingToApproach",job.Request.TargetCell,job.Payload.CurrentProgressSeconds,job.Payload.RequiredDemolitionSeconds);return true;}snapshot=default;return false;}
    public bool TryRemoveDesignation(string structureId,out string reason){if(_workerByStructure.TryGetValue(structureId,out string? worker)&&_jobsByWorker.TryGetValue(worker,out var job))CancelJob(job,"CancelledByDesignationRemoval",false);if(!_construction.Demolitions.TryRemoveDesignation(structureId,out _)){reason="NotDesignated";return false;}_construction.DemolitionReservations.ReleaseByStructure(structureId);reason=string.Empty;Changed?.Invoke();return true;}
    public bool TryRemoveFloorDesignation(string markId,out string reason){if(_workerByStructure.TryGetValue(markId,out string? worker)&&_jobsByWorker.TryGetValue(worker,out var job))CancelJob(job,"CancelledByDesignationRemoval",false);if(!_construction.Floors.TryRemoveMark(markId,out _)){reason="NotDesignated";return false;}_construction.DemolitionReservations.ReleaseByStructure(markId);reason="";Changed?.Invoke();return true;}
    private void RequestNextApproach(DemolitionJobV3 job){GlobalCellCoord destination=job.ApproachCandidates[job.CandidateIndex];job.Payload.SelectedApproachCell=destination;if(!_mercenaries.Registry.TryGetState(job.Request.AssignedMercenaryId,out var state)||state==null){CancelJob(job,"WorkerRemoved",false);return;}if(!_control.ExternalMovements.TryRequest(job.Request.AssignedMercenaryId,state.CurrentCell,destination,MovementRequestSourceTypeV3.Work,job.Request.WorkRequestId,_control.SessionRevision,job.Request.Revision,_control.Movements,out _,out string reason))CancelJob(job,reason.Length==0?"MovementFailed":reason,false);else job.Request.Status=WorkRequestStatusV3.MovingToTarget;}
    private void CancelJob(DemolitionJobV3 job,string reason,bool removeDesignation){job.Request.Status=reason=="SupersededByNewWork"?WorkRequestStatusV3.Superseded:WorkRequestStatusV3.Cancelled;job.Request.FailureReason=reason;job.Payload.FailureReason=reason;_construction.DemolitionReservations.ReleaseByWorkRequest(job.Request.WorkRequestId);_control.ExternalMovements.Cancel(job.Request.AssignedMercenaryId,reason,_control.Movements);if(job.Floor){if(removeDesignation)_construction.Floors.TryRemoveMark(job.Payload.StructureId,out _);else _construction.Floors.TryResetDemolition(job.Payload.StructureId);}else{if(removeDesignation)_construction.Demolitions.TryRemove(job.Payload.StructureId,out _);else _construction.Demolitions.TrySetDesignated(job.Payload.StructureId);}_construction.DemolitionDiagnostics.FailedCount++;_construction.DemolitionDiagnostics.LastFailureReason=reason;FinishJob(job);Changed?.Invoke();}
    private void FinishJob(DemolitionJobV3 job){_jobsByWorker.Remove(job.Request.AssignedMercenaryId);_workerByStructure.Remove(job.Payload.StructureId);if(!job.Floor)_restDemolitionEnded?.Invoke(job.Payload.StructureId);_construction.DemolitionReservations.ReleaseByWorkRequest(job.Request.WorkRequestId);if(_mercenaries.Registry.TryGetState(job.Request.AssignedMercenaryId,out var state)&&state!=null&&!_control.Movements.TryGet(job.Request.AssignedMercenaryId,out _))state.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);}
}

public partial class DemolitionDesignationControllerV3:Node
{
    public const int MaxStructuresPerGesture=64;private const int MaxCellsPerGesture=4096;private ConstructionSessionV3? _construction;private WorldV2GridRenderer? _grid;private WorldManagerV2? _manager;private ConstructionWorldOverlayV3? _overlay;private DemolitionWorkCoordinatorV3? _work;private bool _active,_dragging;private Vector2 _press;
    public bool IsActive=>_active;public event Action<bool>? ActiveChanged;
    public void Initialize(ConstructionSessionV3 construction,WorldV2GridRenderer grid,WorldManagerV2 manager,ConstructionWorldOverlayV3 overlay,DemolitionWorkCoordinatorV3 work){_construction=construction;_grid=grid;_manager=manager;_overlay=overlay;_work=work;}
    public void SetActive(bool active){if(_active==active)return;_active=active;_dragging=false;ActiveChanged?.Invoke(active);}
    public bool TryHandleInput(InputEvent e){if(!_active)return false;if(e is InputEventKey key&&key.Pressed&&!key.Echo&&key.Keycode==Key.Escape){SetActive(false);return true;}if(e is InputEventMouseButton right&&right.Pressed&&right.ButtonIndex==MouseButton.Right){SetActive(false);return true;}if(e is InputEventMouseButton left&&left.ButtonIndex==MouseButton.Left){if(left.Pressed){_dragging=true;_press=left.Position;}else if(_dragging){_dragging=false;Commit(_press,left.Position,left.ShiftPressed);}return true;}return e is InputEventMouseMotion&&_dragging;}
    public bool TryHandleStructureAction(InputEvent e,IReadOnlyList<string> selected){if(_active||e is not InputEventMouseButton mb||!mb.Pressed||mb.ButtonIndex!=MouseButton.Right)return false;GlobalCellCoord cell=ScreenCell(mb.Position);if(!_construction!.Structures.TryGetStructureAtCell(cell,out var structure)||structure==null)return false;if(mb.ShiftPressed){_manager!.UpdateDebugHud("완성 구조물은 철거 지정 후 RMB로 철거합니다.");return true;}if(!_construction.Demolitions.IsDesignated(structure.StructureId)){_manager!.UpdateDebugHud("철거 지정 필요");return true;}if(selected.Count>0&&GameplaySessionV3.TryGetJobActivityRangePolicy(out JobActivityRangePolicyV3? policy)&&policy!=null)policy.Evaluate(structure.CompanyId,JobTypeV3.Demolition,JobSourceKindV3.Structure,structure.StructureId,structure.AnchorCell,selected[0],JobCommandSourceV3.DirectOrder);if(!_work!.TryIssue(structure.StructureId,selected,out string reason))_manager!.UpdateDebugHud(reason);else _manager!.UpdateDebugHud("철거 작업을 시작했습니다.");return true;}
    private void Commit(Vector2 a,Vector2 b,bool remove){Vector2I ca=ScreenCell(a).Value,cb=ScreenCell(b).Value;int minX=Math.Min(ca.X,cb.X),maxX=Math.Max(ca.X,cb.X),minY=Math.Min(ca.Y,cb.Y),maxY=Math.Max(ca.Y,cb.Y);HashSet<string> ids=new(StringComparer.Ordinal);int checkedCells=0;for(int y=minY;y<=maxY&&ids.Count<MaxStructuresPerGesture&&checkedCells<MaxCellsPerGesture;y++)for(int x=minX;x<=maxX&&ids.Count<MaxStructuresPerGesture&&checkedCells<MaxCellsPerGesture;x++){checkedCells++;if(_construction!.Structures.TryGetStructureAtCell(new(new Vector2I(x,y)),out var structure)&&structure!=null)ids.Add(structure.StructureId);}int changed=0;foreach(string id in ids){if(remove){if(_work!.TryRemoveDesignation(id,out _))changed++;continue;}if(!_construction!.Structures.TryGet(id,out var structure)||structure==null||structure.CompanyId!=_manager!.LocalCompanyId||!_construction.Definitions.TryGetDefinition(structure.DefinitionId,out var definition)||definition==null)continue;if(_construction.Demolitions.TryDesignate(structure,definition,_manager.LocalCompanyId,out _,out bool reused,out _)&&!reused)changed++;}_overlay!.Refresh();_manager!.UpdateDebugHud(remove?$"철거 지정 {changed}개 해제":$"철거 지정 {changed}개 추가");}
    private GlobalCellCoord ScreenCell(Vector2 p)=>new(_grid!.WorldToCell(GetViewport().GetCanvasTransform().AffineInverse()*p));
}
