using System;
using System.Collections.Generic;
using System.Linq;
using GameplayV3.Control;
using GameplayV3.Mercenary;
using GameplayV3.Movement;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Work;
using Godot;
using WorldV2;

namespace GameplayV3.Construction.Runtime;

internal sealed class DemolitionJobV3
{
    public required WorkRequestV3 Request;public required DemolitionWorkPayloadV3 Payload;public required IReadOnlyList<GlobalCellCoord> ApproachCandidates;public int CandidateIndex;public bool Working;
}

public sealed class DemolitionWorkCoordinatorV3
{
    private readonly ConstructionSessionV3 _construction;private readonly ResourceSessionV3 _resources;private readonly MercenaryWorkSessionV3 _work;private readonly MercenaryControlSessionV3 _control;private readonly MercenarySessionV3 _mercenaries;private readonly IMercenaryNavigationWorldQueryV3 _query;private readonly string _playerId,_companyId;private readonly Rect2I _bounds;private readonly Dictionary<string,DemolitionJobV3> _jobsByWorker=new(StringComparer.Ordinal);private readonly Dictionary<string,string> _workerByStructure=new(StringComparer.Ordinal);private readonly Action<string>? _cancelConstruction;private readonly bool _emitLogs;private long _revision;
    public event Action? Changed;public event Action? ResourcesChanged;public int ActiveJobCount=>_jobsByWorker.Count;
    public DemolitionWorkCoordinatorV3(ConstructionSessionV3 construction,ResourceSessionV3 resources,MercenaryWorkSessionV3 work,MercenaryControlSessionV3 control,MercenarySessionV3 mercenaries,IMercenaryNavigationWorldQueryV3 query,string playerId,string companyId,Rect2I bounds,Action<string>? cancelConstruction=null,bool emitLogs=false){_construction=construction;_resources=resources;_work=work;_control=control;_mercenaries=mercenaries;_query=query;_playerId=playerId;_companyId=companyId;_bounds=bounds;_cancelConstruction=cancelConstruction;_emitLogs=emitLogs;}
    public bool TryIssue(string structureId,IReadOnlyList<string> selected,out string reason)
    {
        if(!_construction.Structures.TryGet(structureId,out var structure)||structure==null){reason="InvalidStructure";return false;}if(structure.CompanyId!=_companyId){reason="OwnershipDenied";return false;}if(!_construction.Definitions.TryGetDefinition(structure.DefinitionId,out var definition)||definition==null){reason="InvalidDefinition";return false;}if(!definition.CanBeDemolished){reason="DemolitionNotAllowed";return false;}if(!_construction.Demolitions.TryGet(structureId,out var demolition)||demolition==null){reason="NotDesignated";return false;}if(_construction.DemolitionReservations.IsReserved(structureId)){reason="AlreadyReserved";return false;}if(selected.Count==0){reason="NoSelectedWorkers";return false;}
        List<(string Id,MercenaryProfileV3 Profile,MercenaryStateV3 State,DemolitionWorkCalculationV3 Calc,IReadOnlyList<GlobalCellCoord> Approaches,int Selection)> candidates=new();for(int i=0;i<selected.Count;i++){string id=selected[i];if(!_mercenaries.CanPlayerControlMercenary(_playerId,id)||!_mercenaries.Registry.TryGetMercenary(id,out var profile,out var state)||profile==null||state==null||state.CompanyId!=_companyId)continue;var approaches=ConstructionApproachCellServiceV3.GetCandidates(structure.OccupiedCells,state.CurrentCell,_query);if(approaches.Count==0)continue;var calc=DemolitionWorkCalculatorV3.Calculate(profile,definition.BaseDemolitionDurationSeconds);candidates.Add((id,profile,state,calc,approaches,i));}
        var best=candidates.OrderByDescending(x=>x.Calc.DemolitionScore).ThenBy(x=>MercenaryMovementCostPolicyV3.Octile(x.State.CurrentCell.Value,x.Approaches[0].Value)).ThenByDescending(x=>MercenaryDerivedStatsCalculatorV3.Calculate(x.Profile).WorkSpeedMultiplier).ThenBy(x=>x.Selection).ThenBy(x=>x.Id,StringComparer.Ordinal).FirstOrDefault();if(best.Profile==null){reason="NoApproachCells";return false;}
        CancelForNewWork(best.Id,"SupersededByNewWork");_work.CancelForDirectMove(best.Id);_cancelConstruction?.Invoke(best.Id);_control.SupersedeDirectMovementForWork(best.Id);long revision=++_revision;DateTime now=DateTime.UtcNow;string workId=WorkRequestIdFactoryV3.Create();WorkRequestV3 request=new(workId,WorkTypeV3.Demolition,WorkTargetKindV3.Structure,_companyId,structureId,structure.AnchorCell,best.Id,revision,now);var payload=new DemolitionWorkPayloadV3(structureId,structure.OccupiedCells,structure.EmbeddedMaterials,best.Calc.RequiredSeconds,demolition.ProgressSeconds,_construction.Structures.OccupancyRevision,_construction.Structures.OccupancyRevision,revision);if(!_construction.DemolitionReservations.TryReserve(new(structureId,workId,best.Id,_companyId,now,revision),out reason))return false;request.Status=WorkRequestStatusV3.Assigned;var job=new DemolitionJobV3{Request=request,Payload=payload,ApproachCandidates=best.Approaches};_jobsByWorker.Add(best.Id,job);_workerByStructure.Add(structureId,best.Id);_construction.DemolitionDiagnostics.LastWorkerId=best.Id;_construction.DemolitionDiagnostics.LastDuration=best.Calc.RequiredSeconds;RequestNextApproach(job);if(_emitLogs)GD.Print($"[DemolitionV3] started structure={structureId} worker={best.Id} required={best.Calc.RequiredSeconds:0.00} progress={demolition.ProgressSeconds:0.00}");reason=string.Empty;Changed?.Invoke();return true;
    }
    public bool TryHandleMovementResult(MercenaryMovementResultV3 result){if(!_jobsByWorker.TryGetValue(result.Request.MercenaryId,out var job)||job.Request.WorkRequestId!=result.Request.SourceId||job.Request.Revision!=result.Request.SourceRevision)return false;if(!result.Succeeded){job.CandidateIndex++;if(job.CandidateIndex>=job.ApproachCandidates.Count)CancelJob(job,"NoReachableApproachCell",false);else RequestNextApproach(job);return true;}if(!_mercenaries.Registry.TryGetState(job.Request.AssignedMercenaryId,out var state)||state==null||job.Payload.SelectedApproachCell==null||state.CurrentCell.Value!=job.Payload.SelectedApproachCell.Value.Value){CancelJob(job,"MovementFailed",false);return true;}if(!_construction.Demolitions.TryBeginDemolition(job.Payload.StructureId,out string reason)){CancelJob(job,reason,false);return true;}job.Working=true;job.Request.Status=WorkRequestStatusV3.Working;state.TrySetActivityState(MercenaryActivityStateV3.Working,out _);Changed?.Invoke();return true;}
    public void Tick(float delta){foreach(var job in _jobsByWorker.Values.ToList()){if(!job.Working)continue;if(!_construction.Structures.TryGet(job.Payload.StructureId,out var structure)||structure==null){CancelJob(job,"StructureRemoved",true);continue;}if(!_construction.DemolitionReservations.IsReservedBy(structure.StructureId,job.Request.WorkRequestId)){CancelJob(job,"ReservationLost",false);continue;}if(!_construction.Demolitions.TryAddProgress(structure.StructureId,Math.Max(0,delta),out string reason)){CancelJob(job,reason,false);continue;}_construction.Demolitions.TryGet(structure.StructureId,out var state);job.Payload.CurrentProgressSeconds=state?.ProgressSeconds??job.Payload.CurrentProgressSeconds;Changed?.Invoke();if(job.Payload.CurrentProgressSeconds<job.Payload.RequiredDemolitionSeconds)continue;DemolitionCompletionResultV3 result=DemolitionCompletionServiceV3.TryComplete(_construction,_resources,structure.StructureId,job.Request.WorkRequestId,_bounds,job.Payload.RequiredDemolitionSeconds);if(!result.Succeeded){CancelJob(job,result.FailureReason,false);continue;}_construction.DemolitionDiagnostics.CompletedCount++;_construction.DemolitionDiagnostics.LastDemolishedStructureId=structure.StructureId;_construction.DemolitionDiagnostics.LastSalvageTotalAmount=result.SalvageAmount;_construction.DemolitionDiagnostics.LastSalvageResourceTypes=string.Join(",",structure.EmbeddedMaterials.Select(x=>x.ResourceType).Distinct());_construction.DemolitionDiagnostics.LastOccupancyRevisionBefore=result.OccupancyRevisionBefore;_construction.DemolitionDiagnostics.LastOccupancyRevisionAfter=result.OccupancyRevisionAfter;FinishJob(job);ResourcesChanged?.Invoke();Changed?.Invoke();if(_emitLogs)GD.Print($"[DemolitionV3] completed structure={structure.StructureId} salvage={result.SalvageAmount} occupancy={result.OccupancyRevisionBefore}->{result.OccupancyRevisionAfter}");}}
    public void CancelForDirectMove(string worker)=>CancelForNewWork(worker,"CancelledByDirectMove");public void CancelForNewWork(string worker,string reason="SupersededByNewWork"){if(_jobsByWorker.TryGetValue(worker,out var job))CancelJob(job,reason,false);}
    public bool TryRemoveDesignation(string structureId,out string reason){if(_workerByStructure.TryGetValue(structureId,out string? worker)&&_jobsByWorker.TryGetValue(worker,out var job))CancelJob(job,"CancelledByDesignationRemoval",false);if(!_construction.Demolitions.TryRemoveDesignation(structureId,out _)){reason="NotDesignated";return false;}_construction.DemolitionReservations.ReleaseByStructure(structureId);reason=string.Empty;Changed?.Invoke();return true;}
    private void RequestNextApproach(DemolitionJobV3 job){GlobalCellCoord destination=job.ApproachCandidates[job.CandidateIndex];job.Payload.SelectedApproachCell=destination;if(!_mercenaries.Registry.TryGetState(job.Request.AssignedMercenaryId,out var state)||state==null){CancelJob(job,"WorkerRemoved",false);return;}if(!_control.ExternalMovements.TryRequest(job.Request.AssignedMercenaryId,state.CurrentCell,destination,MovementRequestSourceTypeV3.Work,job.Request.WorkRequestId,_control.SessionRevision,job.Request.Revision,_control.Movements,out _,out string reason))CancelJob(job,reason.Length==0?"MovementFailed":reason,false);else job.Request.Status=WorkRequestStatusV3.MovingToTarget;}
    private void CancelJob(DemolitionJobV3 job,string reason,bool removeDesignation){job.Request.Status=reason=="SupersededByNewWork"?WorkRequestStatusV3.Superseded:WorkRequestStatusV3.Cancelled;job.Request.FailureReason=reason;job.Payload.FailureReason=reason;_construction.DemolitionReservations.ReleaseByWorkRequest(job.Request.WorkRequestId);_control.ExternalMovements.Cancel(job.Request.AssignedMercenaryId,reason,_control.Movements);if(removeDesignation)_construction.Demolitions.TryRemove(job.Payload.StructureId,out _);else _construction.Demolitions.TrySetDesignated(job.Payload.StructureId);_construction.DemolitionDiagnostics.FailedCount++;_construction.DemolitionDiagnostics.LastFailureReason=reason;FinishJob(job);Changed?.Invoke();}
    private void FinishJob(DemolitionJobV3 job){_jobsByWorker.Remove(job.Request.AssignedMercenaryId);_workerByStructure.Remove(job.Payload.StructureId);_construction.DemolitionReservations.ReleaseByWorkRequest(job.Request.WorkRequestId);if(_mercenaries.Registry.TryGetState(job.Request.AssignedMercenaryId,out var state)&&state!=null&&!_control.Movements.TryGet(job.Request.AssignedMercenaryId,out _))state.TrySetActivityState(MercenaryActivityStateV3.Idle,out _);}
}

public partial class DemolitionDesignationControllerV3:Node
{
    public const int MaxStructuresPerGesture=64;private const int MaxCellsPerGesture=4096;private ConstructionSessionV3? _construction;private WorldV2GridRenderer? _grid;private WorldManagerV2? _manager;private ConstructionWorldOverlayV3? _overlay;private DemolitionWorkCoordinatorV3? _work;private bool _active,_dragging;private Vector2 _press;
    public bool IsActive=>_active;public event Action<bool>? ActiveChanged;
    public void Initialize(ConstructionSessionV3 construction,WorldV2GridRenderer grid,WorldManagerV2 manager,ConstructionWorldOverlayV3 overlay,DemolitionWorkCoordinatorV3 work){_construction=construction;_grid=grid;_manager=manager;_overlay=overlay;_work=work;}
    public void SetActive(bool active){if(_active==active)return;_active=active;_dragging=false;ActiveChanged?.Invoke(active);}
    public bool TryHandleInput(InputEvent e){if(!_active)return false;if(e is InputEventKey key&&key.Pressed&&!key.Echo&&key.Keycode==Key.Escape){SetActive(false);return true;}if(e is InputEventMouseButton right&&right.Pressed&&right.ButtonIndex==MouseButton.Right){SetActive(false);return true;}if(e is InputEventMouseButton left&&left.ButtonIndex==MouseButton.Left){if(left.Pressed){_dragging=true;_press=left.Position;}else if(_dragging){_dragging=false;Commit(_press,left.Position,left.ShiftPressed);}return true;}return e is InputEventMouseMotion&&_dragging;}
    public bool TryHandleStructureAction(InputEvent e,IReadOnlyList<string> selected){if(_active||e is not InputEventMouseButton mb||!mb.Pressed||mb.ButtonIndex!=MouseButton.Right)return false;GlobalCellCoord cell=ScreenCell(mb.Position);if(!_construction!.Structures.TryGetStructureAtCell(cell,out var structure)||structure==null)return false;if(mb.ShiftPressed){_manager!.UpdateDebugHud("완성 구조물은 철거 지정 후 RMB로 철거합니다.");return true;}if(!_construction.Demolitions.IsDesignated(structure.StructureId)){_manager!.UpdateDebugHud("철거 지정 필요");return true;}if(!_work!.TryIssue(structure.StructureId,selected,out string reason))_manager!.UpdateDebugHud(reason);else _manager!.UpdateDebugHud("철거 작업을 시작했습니다.");return true;}
    private void Commit(Vector2 a,Vector2 b,bool remove){Vector2I ca=ScreenCell(a).Value,cb=ScreenCell(b).Value;int minX=Math.Min(ca.X,cb.X),maxX=Math.Max(ca.X,cb.X),minY=Math.Min(ca.Y,cb.Y),maxY=Math.Max(ca.Y,cb.Y);HashSet<string> ids=new(StringComparer.Ordinal);int checkedCells=0;for(int y=minY;y<=maxY&&ids.Count<MaxStructuresPerGesture&&checkedCells<MaxCellsPerGesture;y++)for(int x=minX;x<=maxX&&ids.Count<MaxStructuresPerGesture&&checkedCells<MaxCellsPerGesture;x++){checkedCells++;if(_construction!.Structures.TryGetStructureAtCell(new(new Vector2I(x,y)),out var structure)&&structure!=null)ids.Add(structure.StructureId);}int changed=0;foreach(string id in ids){if(remove){if(_work!.TryRemoveDesignation(id,out _))changed++;continue;}if(!_construction!.Structures.TryGet(id,out var structure)||structure==null||structure.CompanyId!=_manager!.LocalCompanyId||!_construction.Definitions.TryGetDefinition(structure.DefinitionId,out var definition)||definition==null)continue;if(_construction.Demolitions.TryDesignate(structure,definition,_manager.LocalCompanyId,out _,out bool reused,out _)&&!reused)changed++;}_overlay!.Refresh();_manager!.UpdateDebugHud(remove?$"철거 지정 {changed}개 해제":$"철거 지정 {changed}개 추가");}
    private GlobalCellCoord ScreenCell(Vector2 p)=>new(_grid!.WorldToCell(GetViewport().GetCanvasTransform().AffineInverse()*p));
}
