using System;
using System.Collections.Generic;
using System.Diagnostics;
using GameplayV3.Farming;
using GameplayV3.Navigation;
using GameplayV3.Resources;
using GameplayV3.Session;
using Godot;
using WorldV2;

namespace GameplayV3.Construction.Runtime;

public enum FloorToolModeV3 { None, Build, Remove }
internal sealed class FloorDesignationBatchV3
{
    public required string BatchId;public required string CompanyId;public required FloorToolModeV3 Mode;public required IReadOnlyList<GlobalCellCoord> Cells;public int NextIndex;public int CreatedCount;public int SkippedCount;
}
public partial class FloorConstructionRuntimeV3:Node2D
{
    public const int MaxFloorDesignationCellsPerCommit=256,MaxBlueprintCreatesPerFrame=32,MaxDesignationBatchesPerFrame=4,MaxFloorVisualChunksPerFrame=4,MaxFloorVisualCellsPerFrame=2048;
    private ConstructionSessionV3? _construction;private ResourceSessionV3? _resources;private FarmSessionV3? _farm;private IMercenaryNavigationWorldQueryV3? _query;private WorldV2GridRenderer? _grid;private WorldManagerV2? _manager;private ConstructionWorkCoordinatorV3? _constructionWork;private DemolitionWorkCoordinatorV3? _demolitionWork;private readonly Queue<FloorDesignationBatchV3> _batches=new();private IReadOnlyList<GlobalCellCoord> _validPreview=Array.Empty<GlobalCellCoord>(),_invalidPreview=Array.Empty<GlobalCellCoord>();private FloorToolModeV3 _mode;private bool _dragging;private GlobalCellCoord _dragStart,_dragEnd;private Vector2I _lastCursorCell=new(int.MinValue,int.MinValue),_lastViewChunk=new(int.MinValue,int.MinValue);private long _batchSequence;private int _pendingCells;private string _lastBatchId="";
    public bool IsActive=>_mode!=FloorToolModeV3.None;public FloorToolModeV3 Mode=>_mode;public int PendingBatchCount=>_batches.Count;public int PendingCellCount=>_pendingCells;public int RequestedPreviewCells{get;private set;}public int ValidPreviewCells=>_validPreview.Count;public int SkippedPreviewCells=>_invalidPreview.Count;public string LastBatchId=>_lastBatchId;public event Action<bool>? ActiveChanged;
    public void Initialize(ConstructionSessionV3 construction,ResourceSessionV3 resources,FarmSessionV3? farm,IMercenaryNavigationWorldQueryV3 query,WorldV2GridRenderer grid,WorldManagerV2 manager){_construction=construction;_resources=resources;_farm=farm;_query=query;_grid=grid;_manager=manager;ZIndex=0;QueueRedraw();}
    public void AttachCoordinators(ConstructionWorkCoordinatorV3 construction,DemolitionWorkCoordinatorV3 demolition){_constructionWork=construction;_demolitionWork=demolition;}
    public void SetTool(FloorToolModeV3 mode){bool old=IsActive;_mode=mode;_dragging=false;_validPreview=Array.Empty<GlobalCellCoord>();_invalidPreview=Array.Empty<GlobalCellCoord>();RequestedPreviewCells=0;QueueRedraw();if(old!=IsActive)ActiveChanged?.Invoke(IsActive);}
    public bool TryHandleInput(InputEvent e){if(!IsActive)return false;if(e is InputEventKey key&&key.Pressed&&!key.Echo&&key.Keycode==Key.Escape){SetTool(FloorToolModeV3.None);return true;}if(e is InputEventMouseButton right&&right.Pressed&&right.ButtonIndex==MouseButton.Right){SetTool(FloorToolModeV3.None);return true;}if(e is InputEventMouseMotion motion){if(_dragging)UpdatePreview(ScreenCell(motion.Position));return _dragging;}if(e is InputEventMouseButton left&&left.ButtonIndex==MouseButton.Left){GlobalCellCoord cell=ScreenCell(left.Position);if(left.Pressed){_dragging=true;_dragStart=cell;UpdatePreview(cell);}else if(_dragging){UpdatePreview(cell);CommitPreview();_dragging=false;}return true;}return false;}
    private GlobalCellCoord ScreenCell(Vector2 screen)=>new(_grid!.WorldToCell(GetViewport().GetCanvasTransform().AffineInverse()*screen));
    private void UpdatePreview(GlobalCellCoord current){if(current.Value==_lastCursorCell)return;_lastCursorCell=current.Value;_dragEnd=current;List<GlobalCellCoord> valid=new(),invalid=new();int minX=Math.Min(_dragStart.Value.X,current.Value.X),maxX=Math.Max(_dragStart.Value.X,current.Value.X),minY=Math.Min(_dragStart.Value.Y,current.Value.Y),maxY=Math.Max(_dragStart.Value.Y,current.Value.Y);long requested=(long)(maxX-minX+1)*(maxY-minY+1);RequestedPreviewCells=requested>int.MaxValue?int.MaxValue:(int)requested;int checkedCells=0;for(int y=minY;y<=maxY&&checkedCells<MaxFloorDesignationCellsPerCommit;y++)for(int x=minX;x<=maxX&&checkedCells<MaxFloorDesignationCellsPerCommit;x++){checkedCells++;GlobalCellCoord cell=new(new Vector2I(x,y));if(IsValid(cell))valid.Add(cell);else invalid.Add(cell);}_validPreview=valid.AsReadOnly();_invalidPreview=invalid.AsReadOnly();_manager?.UpdateDebugHud($"{(_mode==FloorToolModeV3.Build?"나무 바닥":"바닥 제거")} {maxX-minX+1}×{maxY-minY+1} 유효 {valid.Count}칸 Wood {valid.Count} 무효 {Math.Max(0,RequestedPreviewCells-valid.Count)}칸");QueueRedraw();}
    private bool IsValid(GlobalCellCoord cell){if(_construction==null||_query==null||!_query.IsInsideWorld(cell.Value))return false;if(_farm?.Plots.ContainsCell(cell.Value)==true)return false;if(_mode==FloorToolModeV3.Remove)return _construction.Floors.TryGetFloor(cell,out _)||_construction.Floors.TryGetBlueprint(cell,out _);if(_construction.Floors.HasFloor(cell)||_construction.Floors.TryGetBlueprint(cell,out _)||_construction.Floors.TryGetMark(cell,out _))return false;return _query.IsWalkable(cell.Value)||_construction.Structures.IsStructureCell(cell);}
    private void CommitPreview(){if(_validPreview.Count==0)return;List<GlobalCellCoord> cells=new(_validPreview);FloorDesignationBatchV3 batch=new(){BatchId=$"floorbatch_{++_batchSequence}",CompanyId=_manager!.LocalCompanyId,Mode=_mode,Cells=cells.AsReadOnly()};_batches.Enqueue(batch);_pendingCells+=cells.Count;_lastBatchId=batch.BatchId;if(cells.Count<=16)ProcessBatches(MaxBlueprintCreatesPerFrame);_manager.UpdateDebugHud($"Floor batch queued id={batch.BatchId} cells={cells.Count}");}
    public override void _PhysicsProcess(double delta){if(_construction==null||!GameplaySessionV3.IsCurrentConstructionSession(_construction))return;Stopwatch sw=Stopwatch.StartNew();_construction.Floors.ResetTickDiagnostics();ProcessBatches(MaxBlueprintCreatesPerFrame);IReadOnlyList<Vector2I> dirty=_construction.Floors.ConsumeDirtyChunks(MaxFloorVisualChunksPerFrame);_construction.Floors.Diagnostics.VisualChunksUpdatedThisFrame=dirty.Count;if(dirty.Count>0)QueueRedraw();sw.Stop();_construction.Floors.Diagnostics.RuntimeTickMs=sw.Elapsed.TotalMilliseconds;_construction.Floors.Diagnostics.MaxRuntimeTickMs=Math.Max(_construction.Floors.Diagnostics.MaxRuntimeTickMs,sw.Elapsed.TotalMilliseconds);}
    private void ProcessBatches(int cellBudget){int batches=0;while(cellBudget>0&&batches<MaxDesignationBatchesPerFrame&&_batches.Count>0){FloorDesignationBatchV3 batch=_batches.Peek();while(cellBudget>0&&batch.NextIndex<batch.Cells.Count){GlobalCellCoord cell=batch.Cells[batch.NextIndex++];_pendingCells--;cellBudget--;if(batch.Mode==FloorToolModeV3.Build){if(_construction!.FloorDefinitions.TryGet(FloorDefinitionCatalogV3.WoodenFloorId,out var definition)&&definition!=null&&IsValidForBuild(cell)&&_construction.Floors.TryCreateBlueprint(batch.CompanyId,cell,definition,_manager!.WorldBounds,out _,out _))batch.CreatedCount++;else batch.SkippedCount++;}else if(_construction!.Floors.TryGetBlueprint(cell,out var bp)&&bp!=null){if(_constructionWork?.TryCancelFloorBlueprint(bp.BlueprintId,out _)==true)batch.CreatedCount++;else batch.SkippedCount++;}else if(_construction.Floors.TryMarkDemolition(batch.CompanyId,cell,out _,out bool reused,out _)&&!reused)batch.CreatedCount++;else batch.SkippedCount++;}if(batch.NextIndex>=batch.Cells.Count){_batches.Dequeue();batches++;GD.Print($"[FloorV3] batch completed id={batch.BatchId} mode={batch.Mode} created={batch.CreatedCount} skipped={batch.SkippedCount}");}else break;}}
    private bool IsValidForBuild(GlobalCellCoord cell)=>_construction!=null&&_query!=null&&_query.IsInsideWorld(cell.Value)&&_farm?.Plots.ContainsCell(cell.Value)!=true&&!_construction.Floors.HasFloor(cell)&&!_construction.Floors.TryGetBlueprint(cell,out _ )&&!_construction.Floors.TryGetMark(cell,out _)&&(_query.IsWalkable(cell.Value)||_construction.Structures.IsStructureCell(cell));
    public override void _Process(double delta){if(_grid==null)return;Vector2 center=GetViewport().GetCanvasTransform().AffineInverse()*(GetViewportRect().Size*.5f);Vector2I chunk=FloorRegistryV3.ChunkOf(_grid.WorldToCell(center));if(chunk!=_lastViewChunk){_lastViewChunk=chunk;QueueRedraw();}}
    public override void _Draw(){if(_construction==null||_grid==null)return;float tile=_grid.TileSize;Transform2D inv=GetViewport().GetCanvasTransform().AffineInverse();Vector2 a=inv*Vector2.Zero,b=inv*GetViewportRect().Size;Vector2I minCell=_grid.WorldToCell(new(Math.Min(a.X,b.X),Math.Min(a.Y,b.Y))),maxCell=_grid.WorldToCell(new(Math.Max(a.X,b.X),Math.Max(a.Y,b.Y)));Vector2I minChunk=FloorRegistryV3.ChunkOf(minCell),maxChunk=FloorRegistryV3.ChunkOf(maxCell);int drawn=0;for(int cy=minChunk.Y-1;cy<=maxChunk.Y+1&&drawn<MaxFloorVisualCellsPerFrame;cy++)for(int cx=minChunk.X-1;cx<=maxChunk.X+1&&drawn<MaxFloorVisualCellsPerFrame;cx++){Vector2I chunk=new(cx,cy);foreach(var floor in _construction.Floors.EnumerateFloorsInChunk(chunk)){DrawFloor(floor.Cell,tile);drawn++;}foreach(var bp in _construction.Floors.EnumerateBlueprintsInChunk(chunk)){Rect2 r=Rect(bp.Cell,tile);DrawRect(r,new Color(.62f,.45f,.25f,.25f),true);DrawRect(r,new Color(.92f,.73f,.45f,.72f),false,1);drawn++;}foreach(var mark in _construction.Floors.EnumerateMarksInChunk(chunk)){Rect2 r=Rect(mark.Cell,tile);DrawRect(r,new Color(.8f,.1f,.12f,.22f),true);DrawLine(r.Position+new Vector2(4,4),r.End-new Vector2(4,4),new Color(1f,.2f,.2f,.85f),1.5f);DrawLine(new(r.End.X-4,r.Position.Y+4),new(r.Position.X+4,r.End.Y-4),new Color(1f,.2f,.2f,.85f),1.5f);drawn++;}}foreach(var cell in _validPreview)DrawRect(Rect(cell,tile),_mode==FloorToolModeV3.Build?new Color(.35f,.8f,.5f,.28f):new Color(.9f,.2f,.2f,.3f),true);foreach(var cell in _invalidPreview)DrawRect(Rect(cell,tile),new Color(.9f,.1f,.15f,.22f),true);}
    private void DrawFloor(GlobalCellCoord cell,float tile){Rect2 r=Rect(cell,tile);DrawRect(r,new Color(.36f,.24f,.14f,.88f),true);Color line=new(.58f,.40f,.24f,.78f);for(int i=1;i<4;i++)DrawLine(new(r.Position.X,r.Position.Y+tile*i/4),new(r.End.X,r.Position.Y+tile*i/4),line,1);int hash=unchecked(cell.Value.X*73856093^cell.Value.Y*19349663);float seam=3+Math.Abs(hash%Math.Max(1,(int)tile-6));DrawLine(new(r.Position.X+seam,r.Position.Y),new(r.Position.X+seam,r.End.Y),new Color(.24f,.15f,.09f,.6f),1);}
    private static Rect2 Rect(GlobalCellCoord cell,float tile)=>new(new Vector2(cell.Value.X*tile,cell.Value.Y*tile),new(tile,tile));
}
