using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using GameplayV3.Company;
using GameplayV3.Construction;
using GameplayV3.Farming;
using GameplayV3.Jobs;
using GameplayV3.Mercenary;
using GameplayV3.Mercenary.Runtime;
using GameplayV3.Rooms;
using GameplayV3.Session;
using GameplayV3.Stockpile;
using Godot;
using WorldV2;

namespace GameplayV3.Bases.Runtime;

internal readonly record struct BaseSourceEventV3(bool Remove,string SourceId,BaseSpatialSourceV3? Source);

public partial class BaseAreaRuntimeV3:Node
{
    private readonly Queue<string> _eventOrder=new();private readonly Dictionary<string,BaseSourceEventV3> _pendingEvents=new(StringComparer.Ordinal);private readonly Dictionary<Vector2I,HashSet<string>> _knownFloorsByChunk=new();private readonly HashSet<string> _knownStockpiles=new(StringComparer.Ordinal),_knownFarms=new(StringComparer.Ordinal);private BaseAreaSessionV3? _session;private CompanySessionV3? _companies;private ConstructionSessionV3? _construction;private StockpileSessionV3? _stockpiles;private FarmSessionV3? _farms;private RoomSessionV3? _rooms;private bool _initialized;
    public int PendingEventCount=>_pendingEvents.Count;
    public void Initialize(BaseAreaSessionV3 session,CompanySessionV3 companies,ConstructionSessionV3 construction,StockpileSessionV3 stockpiles,FarmSessionV3 farms,RoomSessionV3 rooms,Rect2I worldBounds)
    {
        if(_initialized)return;_initialized=true;_session=session;_companies=companies;_construction=construction;_stockpiles=stockpiles;_farms=farms;_rooms=rooms;session.SetWorldBounds(worldBounds);construction.Structures.StructureRegistered+=OnStructureRegistered;construction.Structures.StructureRemoved+=OnStructureRemoved;construction.Floors.ChunkChanged+=OnFloorChunkChanged;stockpiles.Zones.CellsChanged+=OnStockpileCellsChanged;farms.Plots.Changed+=OnFarmChanged;rooms.Registry.Remapped+=OnRoomsRemapped;session.Changed+=OnBaseChanged;QueueInitialSync();SetPhysicsProcess(true);
    }
    public override void _PhysicsProcess(double delta){if(!_initialized||_session==null||!GameplaySessionV3.IsCurrentBaseAreaSession(_session)){SetPhysicsProcess(false);return;}Stopwatch watch=Stopwatch.StartNew();_session.Diagnostics.ResetTick();ProcessEvents(BaseAreaSettingsV3.MaxDirtySourcesProcessedPerTick);_session.RebuildDirtyCompanies(BaseAreaSettingsV3.MaxBaseRebuildsPerTick);if(GameplaySessionV3.TryGetFacilityAffiliationSession(out FacilityAffiliationSessionV3? facilities)&&facilities!=null)facilities.ProcessDirty();if(GameplaySessionV3.TryGetMercenaryBaseAffiliationSession(out MercenaryBaseAffiliationSessionV3? mercenaryBases)&&mercenaryBases!=null)mercenaryBases.ProcessDirty();watch.Stop();_session.Diagnostics.RuntimeTickMs=watch.Elapsed.TotalMilliseconds;_session.Diagnostics.MaxRuntimeMs=Math.Max(_session.Diagnostics.MaxRuntimeMs,watch.Elapsed.TotalMilliseconds);}
    public void ProcessUntilIdleForFixture(int maxTicks=10000){for(int i=0;i<maxTicks&&(_pendingEvents.Count>0||_session?.DirtyCompanyCount>0);i++)_PhysicsProcess(1d/60d);}
    public override void _ExitTree(){if(_construction!=null){_construction.Structures.StructureRegistered-=OnStructureRegistered;_construction.Structures.StructureRemoved-=OnStructureRemoved;_construction.Floors.ChunkChanged-=OnFloorChunkChanged;}if(_stockpiles!=null)_stockpiles.Zones.CellsChanged-=OnStockpileCellsChanged;if(_farms!=null)_farms.Plots.Changed-=OnFarmChanged;if(_rooms!=null)_rooms.Registry.Remapped-=OnRoomsRemapped;if(_session!=null)_session.Changed-=OnBaseChanged;_initialized=false;}
    private void QueueInitialSync(){if(_session==null||_construction==null||_stockpiles==null||_farms==null||_rooms==null||_companies==null)return;foreach(string id in _construction.Structures.GetAllStructureIds())if(_construction.Structures.TryGet(id,out var state)&&state!=null)Enqueue(StructureSource(state));foreach(Vector2I chunk in _construction.Floors.GetChunkCoords().ToList())QueueFloorChunk(chunk);foreach(string id in _stockpiles.Zones.GetAllZoneIds())if(_stockpiles.Zones.TryGetZone(id,out var zone)&&zone!=null){_knownStockpiles.Add(id);Enqueue(StockpileSource(zone));}foreach(var company in _companies.CompanyRegistry.GetAllCompanies())foreach(var plot in _farms.Plots.GetPlotsByCompany(company.CompanyId)){_knownFarms.Add(plot.FarmPlotId);Enqueue(FarmSource(plot));}_session.UpdateRoomSnapshot(_rooms.Registry.GetAllRooms());_session.Diagnostics.InitialSyncRemaining=_pendingEvents.Count;}
    private void ProcessEvents(int budget){if(_session==null)return;int processed=0;while(processed<budget&&_eventOrder.Count>0){string id=_eventOrder.Dequeue();if(!_pendingEvents.Remove(id,out BaseSourceEventV3 value))continue;if(value.Remove)_session.RemoveSource(value.SourceId);else if(value.Source!=null)_session.UpsertSource(value.Source);processed++;}_session.Diagnostics.SourceEventsProcessedThisTick=processed;_session.Diagnostics.InitialSyncProcessed+=processed;_session.Diagnostics.InitialSyncRemaining=_pendingEvents.Count;}
    private void Enqueue(BaseSpatialSourceV3 source){if(!_pendingEvents.ContainsKey(source.SourceId))_eventOrder.Enqueue(source.SourceId);_pendingEvents[source.SourceId]=new(false,source.SourceId,source);}
    private void EnqueueRemove(string id){if(!_pendingEvents.ContainsKey(id))_eventOrder.Enqueue(id);_pendingEvents[id]=new(true,id,null);}
    private BaseSpatialSourceV3 StructureSource(StructureStateV3 state){var classification=BaseSpatialSourceCatalogV3.ClassifyStructure(state.DefinitionId);long order=state.CompletedUtc.Ticks;return new(state.StructureId,state.CompanyId,classification.Kind,classification.Role,state.OccupiedCells,classification.Weight,order,order,true,true,state.DefinitionId);}
    private BaseSpatialSourceV3 FloorSource(FloorCellStateV3 floor){string id=FloorId(floor.Cell.Value);return new(id,floor.CompanyId,BaseSpatialSourceKindV3.Floor,BaseSpatialSourceRoleV3.Connector,new[]{floor.Cell},0,floor.CompletedSequence,floor.Revision,true,true,floor.FloorTypeId);}
    private BaseSpatialSourceV3 StockpileSource(StockpileZoneStateV3 zone){var role=BaseSpatialSourceCatalogV3.ClassifyStockpile(zone.Cells);return new(zone.StockpileZoneId,zone.CompanyId,BaseSpatialSourceKindV3.StockpileZone,role,zone.Cells,role==BaseSpatialSourceRoleV3.Anchor?3:0,zone.CreatedUtc.Ticks,_stockpiles?.Zones.Revision??0,true,zone.IsEnabled);}
    private BaseSpatialSourceV3 FarmSource(FarmPlotV3 plot){var role=BaseSpatialSourceCatalogV3.ClassifyFarm(plot.Cells.Select(c=>new GlobalCellCoord(c)).ToList());return new(plot.FarmPlotId,plot.CompanyId,BaseSpatialSourceKindV3.FarmPlot,role,plot.Cells.Select(c=>new GlobalCellCoord(c)),role==BaseSpatialSourceRoleV3.Anchor?2:0,plot.CreatedUtc.Ticks,plot.Revision,true,true,plot.CropDefinitionId);}
    private static string FloorId(Vector2I cell)=>$"basefloor:{cell.X}:{cell.Y}";
    private void OnStructureRegistered(StructureStateV3 state)=>Enqueue(StructureSource(state));private void OnStructureRemoved(StructureStateV3 state)=>EnqueueRemove(state.StructureId);
    private void OnFloorChunkChanged(Vector2I chunk,int count,long revision)=>QueueFloorChunk(chunk);
    private void QueueFloorChunk(Vector2I chunk){if(_construction==null)return;HashSet<string> current=new(StringComparer.Ordinal);foreach(var floor in _construction.Floors.EnumerateFloorsInChunk(chunk)){string id=FloorId(floor.Cell.Value);current.Add(id);Enqueue(FloorSource(floor));}if(_knownFloorsByChunk.TryGetValue(chunk,out var old))foreach(string id in old)if(!current.Contains(id))EnqueueRemove(id);if(current.Count==0)_knownFloorsByChunk.Remove(chunk);else _knownFloorsByChunk[chunk]=current;}
    private void OnStockpileCellsChanged(IReadOnlyList<GlobalCellCoord> cells){if(_stockpiles==null)return;HashSet<string> current=new(_stockpiles.Zones.GetAllZoneIds(),StringComparer.Ordinal);foreach(string id in _knownStockpiles)if(!current.Contains(id))EnqueueRemove(id);foreach(string id in current)if(_stockpiles.Zones.TryGetZone(id,out var zone)&&zone!=null)Enqueue(StockpileSource(zone));_knownStockpiles.Clear();_knownStockpiles.UnionWith(current);}
    private void OnFarmChanged(){if(_farms==null||_companies==null)return;HashSet<string> current=new(StringComparer.Ordinal);foreach(var company in _companies.CompanyRegistry.GetAllCompanies())foreach(var plot in _farms.Plots.GetPlotsByCompany(company.CompanyId)){current.Add(plot.FarmPlotId);Enqueue(FarmSource(plot));}foreach(string id in _knownFarms)if(!current.Contains(id))EnqueueRemove(id);_knownFarms.Clear();_knownFarms.UnionWith(current);}
    private void OnRoomsRemapped(RoomTopologyRemapV3 remap){if(_session!=null&&_rooms!=null)_session.UpdateRoomSnapshot(_rooms.Registry.GetAllRooms());}
    private void OnBaseChanged(BaseAreaChangeEventV3 value){}
}

public partial class BaseAreaOverlayV3:Node2D
{
    private BaseAreaSessionV3? _session;private BaseRoleSessionV3? _roles;private FacilityAffiliationSessionV3? _facilities;private MercenaryBaseAffiliationSessionV3? _mercenaryBases;private MercenarySessionV3? _mercenaries;private MercenaryViewRegistryV3? _views;private JobManagerV3? _jobs;private JobActivityRangePolicyV3? _policy;private WorldV2GridRenderer? _grid;private string _company=string.Empty;public bool OverlayEnabled{get;private set;}public int DrawnBaseCount{get;private set;}public int DrawnCellCount{get;private set;}public int DrawnActivityRangeCount{get;private set;}public int DrawnFacilityCount{get;private set;}public int DrawnMercenaryCount{get;private set;}public int DrawnPolicyMarkerCount{get;private set;}public int PerObjectNodeCount=>0;
    public void Initialize(BaseAreaSessionV3 session,WorldV2GridRenderer grid){_session=session;_grid=grid;ZIndex=1;session.Changed+=OnChanged;if(GameplaySessionV3.TryGetBaseRoleSession(out BaseRoleSessionV3? roles)&&roles!=null){_roles=roles;roles.BaseRoleChanged+=OnRoleChanged;roles.HeadquartersChanged+=OnHeadquartersChanged;roles.BaseRoleRemoved+=OnRoleRemoved;}Visible=false;}
    public void BindActivityDebug(FacilityAffiliationSessionV3 facilities,MercenaryBaseAffiliationSessionV3 mercenaryBases,MercenarySessionV3 mercenaries,MercenaryViewRegistryV3 views,JobManagerV3 jobs,JobActivityRangePolicyV3 policy,string company){UnbindActivityDebug();_facilities=facilities;_mercenaryBases=mercenaryBases;_mercenaries=mercenaries;_views=views;_jobs=jobs;_policy=policy;_company=company;facilities.FacilityAffiliationChanged+=OnFacilityChanged;facilities.BaseActivityRangeChanged+=OnRangeChanged;mercenaryBases.MercenaryBaseAffiliationChanged+=OnMercenaryChanged;policy.DiagnosticEventRecorded+=OnPolicyEvent;if(OverlayEnabled)QueueRedraw();}
    public void Toggle(){OverlayEnabled=!OverlayEnabled;Visible=OverlayEnabled;if(OverlayEnabled)QueueRedraw();}
    public void SetSuppressed(bool suppressed){Visible=OverlayEnabled&&!suppressed;if(Visible)QueueRedraw();}
    public override void _ExitTree(){if(_session!=null)_session.Changed-=OnChanged;if(_roles!=null){_roles.BaseRoleChanged-=OnRoleChanged;_roles.HeadquartersChanged-=OnHeadquartersChanged;_roles.BaseRoleRemoved-=OnRoleRemoved;}UnbindActivityDebug();}
    private void UnbindActivityDebug(){if(_facilities!=null){_facilities.FacilityAffiliationChanged-=OnFacilityChanged;_facilities.BaseActivityRangeChanged-=OnRangeChanged;}if(_mercenaryBases!=null)_mercenaryBases.MercenaryBaseAffiliationChanged-=OnMercenaryChanged;if(_policy!=null)_policy.DiagnosticEventRecorded-=OnPolicyEvent;_facilities=null;_mercenaryBases=null;_policy=null;}
    private void OnChanged(BaseAreaChangeEventV3 value){if(OverlayEnabled)QueueRedraw();}
    private void OnRoleChanged(BaseRoleChangedV3 value){if(OverlayEnabled)QueueRedraw();}private void OnHeadquartersChanged(HeadquartersChangedV3 value){if(OverlayEnabled)QueueRedraw();}private void OnRoleRemoved(BaseRoleRemovedV3 value){if(OverlayEnabled)QueueRedraw();}
    private void OnFacilityChanged(FacilityAffiliationChangedV3 value){if(OverlayEnabled)QueueRedraw();}private void OnRangeChanged(BaseActivityRangeChangedV3 value){if(OverlayEnabled)QueueRedraw();}private void OnMercenaryChanged(MercenaryBaseAffiliationChangedV3 value){if(OverlayEnabled)QueueRedraw();}private void OnPolicyEvent(JobActivityRangeEventV3 value){if(OverlayEnabled)QueueRedraw();}
    public override void _Draw(){DrawnBaseCount=DrawnCellCount=DrawnActivityRangeCount=DrawnFacilityCount=DrawnMercenaryCount=DrawnPolicyMarkerCount=0;if(!OverlayEnabled||_session==null||_grid==null||!GameplaySessionV3.IsCurrentBaseAreaSession(_session))return;Transform2D inverse=GetViewport().GetCanvasTransform().AffineInverse();Vector2 size=GetViewportRect().Size;Vector2I minCell=_grid.WorldToCell(inverse*Vector2.Zero)-Vector2I.One,maxCell=_grid.WorldToCell(inverse*size)+Vector2I.One;Vector2I minChunk=BaseSpatialSourceV3.ChunkOf(minCell),maxChunk=BaseSpatialSourceV3.ChunkOf(maxCell);HashSet<string> ids=new(StringComparer.Ordinal),rangeIds=new(StringComparer.Ordinal),facilityIds=new(StringComparer.Ordinal);for(int y=minChunk.Y;y<=maxChunk.Y;y++)for(int x=minChunk.X;x<=maxChunk.X;x++){Vector2I chunk=new(x,y);foreach(string id in _session.Areas.GetIdsInChunk(chunk))ids.Add(id);if(_facilities!=null){foreach(string id in _facilities.GetActivityRangeChunkCandidates(_company,chunk))rangeIds.Add(id);foreach(var facility in _facilities.GetFacilitiesInChunk(chunk))if(facilityIds.Add(facility.FacilityKey))DrawFacility(facility,minCell,maxCell);}}foreach(string id in rangeIds.OrderBy(x=>x,StringComparer.Ordinal))if(_facilities?.TryGetActivityRange(id,out var range)==true&&range!=null){Color color=ColorFor(id);DrawRect(WorldRect(range.ExpandedBounds),new(color,.72f),false,2f);DrawnActivityRangeCount++;}foreach(string id in ids.OrderBy(x=>x,StringComparer.Ordinal))if(_session.Areas.TryGet(id,out var area)&&area!=null){Color color=ColorFor(id);Rect2I visible=area.Bounds.Intersection(new(minCell,maxCell-minCell+Vector2I.One));for(int y=visible.Position.Y;y<visible.End.Y;y++)for(int x=visible.Position.X;x<visible.End.X;x++)if(area.Contains(new(x,y))){DrawRect(new Rect2(x*_grid.TileSize,y*_grid.TileSize,_grid.TileSize,_grid.TileSize),new(color,.12f),true);DrawnCellCount++;}DrawRect(WorldRect(area.Bounds),new(color,.9f),false,1.5f);Vector2 center=_grid.CellToWorldCenter(area.CenterCell.Value);DrawCircle(center,4,color);string roleLabel=_roles?.TryGetRole(id,out BaseRoleStateV3? role)==true&&role!=null?role.Role switch{BaseRoleV3.Headquarters=>"HQ",BaseRoleV3.Base=>"BASE",_=>"OUTPOST"}:"-";DrawString(ThemeDB.FallbackFont,center+new Vector2(6,-4),$"[{roleLabel}] {Short(id)} {Short(area.CompanyId)} A{area.AnchorCount} M{area.MemberSourceCount}",HorizontalAlignment.Left,-1,11,color);DrawnBaseCount++;}DrawMercenaries(minCell,maxCell);DrawPolicyMarkers(minCell,maxCell);}
    private void DrawFacility(FacilityAffiliationSnapshotV3 facility,Vector2I min,Vector2I max){if(facility.Bounds.End.X<=min.X||facility.Bounds.End.Y<=min.Y||facility.Bounds.Position.X>max.X||facility.Bounds.Position.Y>max.Y)return;Color color=facility.AffiliationState switch{FacilityAffiliationStateV3.Affiliated=>new Color(.35f,.9f,.65f,.85f),FacilityAffiliationStateV3.Unaffiliated=>new Color(1f,.72f,.2f,.95f),FacilityAffiliationStateV3.Ambiguous=>new Color(1f,.25f,.35f,.95f),FacilityAffiliationStateV3.PendingBaseRebuild=>new Color(.75f,.55f,1f,.9f),_=>new Color(.5f,.5f,.5f,.7f)};DrawRect(WorldRect(facility.Bounds),color,false,2f);DrawnFacilityCount++;}
    private void DrawMercenaries(Vector2I min,Vector2I max){if(_views==null||_mercenaryBases==null||_mercenaries==null||_grid==null)return;foreach(string id in _views.GetAllViewIds())if(_mercenaries.Registry.TryGetState(id,out var state)&&state!=null&&state.CurrentCell.Value.X>=min.X&&state.CurrentCell.Value.X<=max.X&&state.CurrentCell.Value.Y>=min.Y&&state.CurrentCell.Value.Y<=max.Y&&_mercenaryBases.TryGetMercenaryBase(id,out var affiliation)&&affiliation!=null){Vector2 p=_grid.CellToWorldCenter(state.CurrentCell.Value);Color c=affiliation.BaseAreaId==null?Colors.Gray:ColorFor(affiliation.BaseAreaId);DrawLine(p+new Vector2(-7,-11),p+new Vector2(7,-11),c,2f);DrawString(ThemeDB.FallbackFont,p+new Vector2(9,-7),$"{Short(id)} -> {(affiliation.BaseAreaId==null?"-":Short(affiliation.BaseAreaId))}",HorizontalAlignment.Left,-1,10,c);DrawnMercenaryCount++;}}
    private void DrawPolicyMarkers(Vector2I min,Vector2I max){if(_policy==null||_grid==null)return;foreach(JobActivityRangeEventV3 evt in _policy.GetRecentEvents()){Vector2I cell=evt.TargetCell.Value;if(cell.X<min.X||cell.X>max.X||cell.Y<min.Y||cell.Y>max.Y)continue;Color c=evt.Reason==JobActivityRangeReasonV3.DirectOrderOverride?Colors.Cyan:evt.Allowed?Colors.LightGreen:Colors.OrangeRed;Vector2 p=_grid.CellToWorldCenter(cell);DrawCircle(p,6,c,false,2f);DrawString(ThemeDB.FallbackFont,p+new Vector2(8,3),evt.Reason.ToString(),HorizontalAlignment.Left,-1,10,c);DrawnPolicyMarkerCount++;}}
    private Rect2 WorldRect(Rect2I cells)=>new(cells.Position.X*_grid!.TileSize,cells.Position.Y*_grid.TileSize,cells.Size.X*_grid.TileSize,cells.Size.Y*_grid.TileSize);
    private static string Short(string id)=>id.Length<=12?id:id[..12];private static Color ColorFor(string id){uint hash=2166136261;foreach(char c in id){hash^=c;hash*=16777619;}return Color.FromHsv((hash%360)/360f,.55f,.95f);}
}
